### ISSUE TITLE
[heapster scalability] Port OpenTSDB

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/heapster#1001]
cc: @piosz @fgrzadkowski

**Comment by mwielgus** [comment]
I will port the code but someone should test if it really works.

**Comment by mwielgus** [comment]
#1000 needs porting.

**Comment by mwielgus** [comment]
#1007 - #1000 ported.

**Comment by mwielgus** [comment]
Ok, so we have a basic support for metrics in opentsdb. Events are pending/TBD.

**Comment by piosz** [comment]
Fixed by @mwielgus
