### ISSUE TITLE
Grafana pre-baked queries reference invalid influxdb datasets

### ISSUE THREAD

**Issue by justinsb** [kubernetes/heapster#1003]
I believe the queries in grafana are wrong:

These are the measurements shown by "SHOW MEASUREMENTS" against influxdb:

```
name
cpu/node_reservation
cpu/node_utilization
cpu/usage
cpu/usage_rate
filesystem/limit
filesystem/usage
log/events
memory/major_page_faults
memory/node_reservation
memory/node_utilization
memory/page_faults
memory/usage
memory/working_set
network/rx
network/rx_errors
network/tx
network/tx_errors
uptime
```

Did we change the names of the statistics that were collected? All the grafana queries are things like `select hostname, mean(value) from "memory/limit_bytes_gauge" where $timeFilter and container_name = 'machine' group by time($interval), hostname order asc` but `memory/limit_bytes_gauge` is not defined

cf https://github.com/kubernetes/kubernetes/issues/21692#issuecomment-188471149

**Comment by innovia** [comment]
cf [kubernetes/kubernetes#487](https://github.com/kubernetes/contrib/issues/487) same issue...

**Comment by fgrzadkowski** [comment]
Fixed

**Comment by innovia** [comment]
Thank you!

**Comment by innovia** [comment]
@fgrzadkowski  how do I build only heapster to test on my deployed  alpha 1.2 cluster?

**Comment by fgrzadkowski** [comment]
We have release new version that should include this fix `v0.20.0-alpha9`.

**Comment by innovia** [comment]
great thank you so much

**Comment by innovia** [comment]
@fgrzadkowski sorry but I don't see that in the releases for kubernetes 

you mean a release on heapster ? 

if so how do I add it to the alpha8 deployed cluster / or how do i redeploy with the new release?

**Comment by fgrzadkowski** [comment]
I meant heapster release. If you want to update this manually you should update RC definition for heapster on master in `/etc/kubernetes/addons/cluster-monitoring` or you can update 'cluster/addons/cluster-monitoring/...` and redeploy your cluster.

**Comment by innovia** [comment]
thanks for the explanation - i really appreciate your help

**Comment by mwielgus** [comment]
@innovia @fgrzadkowski 
A tiny correction - grafana + influxdb is in a separate docker image. New version is here gcr.io/google_containers/heapster_grafana:v2.6.0-2.

**Comment by dmcnaught** [comment]
I updated our 1.2alpha8 cluster to use heapster v0.20.0-alpha9 and heapster_grafana:v2.6.0-2.
It's looking great now - thanks!

**Comment by dmcnaught** [comment]
It looks like there is a similar issue in 1.1.7 and 1.1.8. Is there is a patch for that release?

**Comment by mwielgus** [comment]
You will have to port the config files manually. Heapster and grafana should work on the older cluster as well. BTW, please pay attention to new mini-releases of Heapster - 0.20.0 (a big rewrite/refactoring) is still in alpha stage and we are pushing new version with bugfixes every other day. Today we pushed alpha10.

**Comment by innovia** [comment]
@fgrzadkowski  i've deleted my running rc's for garafana and heapster and re-ran  the create on them and it's working great! thank you so much for the fix
