### ISSUE TITLE
Working set seem to be shared between containers

### ISSUE THREAD

**Issue by Vanuan** [kubernetes/heapster#1005]
I use heapster to get info from cadvisor to influxdb. What I've noticed is that memory/working_set_bytes_gauge is approximately the same, no matter which container I choose. But memory/usage_bytes_gauge does seem to represent what cadvisor shows as a "hot" memory. I.e. working set is greater than usage bytes for some containers.

Is there some misunderstanding?

**Comment by mwielgus** [comment]
Please check if the problem persists in the new Heapster version candidate gcr.io/google_containers/heapster:v0.20.0-alpha10 and reopen if needed.
