### ISSUE TITLE
Heapster very unstable in local cluster

### ISSUE THREAD

**Issue by cheld** [kubernetes/heapster#1028]
I run version 0.20.0-alpha1 along a local cluster (or hypercube). It is very unstable and crashes every couple of minutes.

Command:

docker run --net=host  gcr.io/google_containers/heapster:v0.20.0-alpha1 -port 8082 \
    --source=kubernetes:http://127.0.0.1:8080?inClusterConfig=false&auth=""

Stack-Trace:

I0301 16:11:05.000151       1 manager.go:76] Scraping metrics start: 2016-03-01 16:10:30 +0000 UTC, end: 2016-03-01 16:11:00 +0000 UTC
I0301 16:11:05.000269       1 manager.go:85] Querying source: kubelet:127.0.0.1:10255
I0301 16:11:05.123297       1 kubelet.go:229] successfully obtained stats for 16 containers
E0301 16:11:05.123342       1 kubelet.go:132] Missing metadata for container stupefied_bardeen. Got: map[]
E0301 16:11:05.123355       1 kubelet.go:132] Missing metadata for container condescending_euler. Got: map[]
E0301 16:11:05.123364       1 kubelet.go:132] Missing metadata for container serene_joliot. Got: map[]
E0301 16:11:05.123388       1 kubelet.go:132] Missing metadata for container /user. Got: map[]
E0301 16:11:05.123399       1 kubelet.go:132] Missing metadata for container /user/1000.user/c2.session. Got: map[]
E0301 16:11:05.123409       1 kubelet.go:132] Missing metadata for container /docker. Got: map[]
E0301 16:11:05.123430       1 kubelet.go:132] Missing metadata for container /docker/bab50b010b66f33494a463a9c3e63d59fc8deacf9bf0c574e1b6fb565fe3586b/kube-proxy. Got: map[]
E0301 16:11:05.123466       1 kubelet.go:132] Missing metadata for container compassionate_pare. Got: map[]
E0301 16:11:05.123485       1 kubelet.go:132] Missing metadata for container /user/1000.user. Got: map[]
I0301 16:11:05.123512       1 manager.go:139] ScrapeMetrics: time: 123.26777ms size: 7
I0301 16:11:05.123522       1 manager.go:141]    scrape  bucket 0: 1
I0301 16:11:05.123534       1 manager.go:141]    scrape  bucket 1: 0
I0301 16:11:05.123547       1 manager.go:141]    scrape  bucket 2: 0
I0301 16:11:05.123551       1 manager.go:141]    scrape  bucket 3: 0
I0301 16:11:05.123555       1 manager.go:141]    scrape  bucket 4: 0
I0301 16:11:05.123561       1 manager.go:141]    scrape  bucket 5: 0
I0301 16:11:05.123565       1 manager.go:141]    scrape  bucket 6: 0
I0301 16:11:05.123570       1 manager.go:141]    scrape  bucket 7: 0
I0301 16:11:05.123576       1 manager.go:141]    scrape  bucket 8: 0
I0301 16:11:05.123581       1 manager.go:141]    scrape  bucket 9: 0
I0301 16:11:05.123585       1 manager.go:141]    scrape  bucket 10: 0
I0301 16:11:35.000191       1 manager.go:76] Scraping metrics start: 2016-03-01 16:11:00 +0000 UTC, end: 2016-03-01 16:11:30 +0000 UTC
I0301 16:11:35.000327       1 manager.go:85] Querying source: kubelet:127.0.0.1:10255
I0301 16:11:35.129251       1 kubelet.go:229] successfully obtained stats for 22 containers
E0301 16:11:35.129305       1 kubelet.go:132] Missing metadata for container stupefied_bardeen. Got: map[]
E0301 16:11:35.129322       1 kubelet.go:132] Missing metadata for container compassionate_pare. Got: map[]
E0301 16:11:35.129340       1 kubelet.go:132] Missing metadata for container /docker/bab50b010b66f33494a463a9c3e63d59fc8deacf9bf0c574e1b6fb565fe3586b/kube-proxy. Got: map[]
E0301 16:11:35.129390       1 kubelet.go:132] Missing metadata for container /user. Got: map[]
E0301 16:11:35.129421       1 kubelet.go:132] Missing metadata for container condescending_euler. Got: map[]
E0301 16:11:35.129469       1 kubelet.go:132] Missing metadata for container /user/1000.user. Got: map[]
panic: runtime error: index out of range

goroutine 210 [running]:
k8s.io/heapster/metrics/sources/kubelet.(*kubeletMetricsSource).decodeMetrics(0xc8201e8460, 0xc820091500, 0x0, 0x0, 0xc8203dee10)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/kubelet/kubelet.go:154 +0x18cf
k8s.io/heapster/metrics/sources/kubelet.(*kubeletMetricsSource).ScrapeMetrics(0xc8201e8460, 0xece67b614, 0xc800000000, 0x1983580, 0xece67b632, 0xc800000000, 0x1983580, 0xc820212000)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/kubelet/kubelet.go:237 +0x4c8
k8s.io/heapster/metrics/sources.scrape(0x7f7585cf7218, 0xc8201e8460, 0xece67b614, 0x0, 0x1983580, 0xece67b632, 0x0, 0x1983580, 0x0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/manager.go:156 +0x328
k8s.io/heapster/metrics/sources.(*sourceManager).ScrapeMetrics.func1(0x7f7585cf7218, 0xc8201e8460, 0xc82012d860, 0xece67b614, 0x0, 0x1983580, 0xece67b632, 0x0, 0x1983580, 0xece67b64b, ...)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/manager.go:86 +0x15f
created by k8s.io/heapster/metrics/sources.(*sourceManager).ScrapeMetrics
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/manager.go:102 +0x47a

goroutine 1 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7f7585db8058, 0x72, 0xc820010170)
	/usr/lib/google-golang/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203fb560, 0x72, 0x0, 0x0)
	/usr/lib/google-golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203fb560, 0x0, 0x0)
	/usr/lib/google-golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc8203fb500, 0x0, 0x7f7585db8118, 0xc8204e7fe0)
	/usr/lib/google-golang/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc82032e250, 0xc82040b908, 0x0, 0x0)
	/usr/lib/google-golang/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc82032e250, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc8201afb00, 0x7f7585e0a6f0, 0xc82032e250, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc8201afb00, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0xc820336b00, 0x5, 0x7f7585e0a690, 0xc8201914d0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/server.go:1967 +0x8f
main.main()
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/heapster.go:169 +0x1c84

goroutine 8 [chan receive]:
github.com/golang/glog.(*loggingT).flushDaemon(0x19839e0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/github.com/golang/glog/glog.go:879 +0x67
created by github.com/golang/glog.init.1
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/github.com/golang/glog/glog.go:410 +0x297

goroutine 14 [syscall, 2 minutes]:
os/signal.loop()
	/usr/lib/google-golang/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/lib/google-golang/src/os/signal/signal_unix.go:28 +0x37

goroutine 36 [select]:
k8s.io/kubernetes/pkg/client/cache.(*Reflector).watchHandler(0xc82007b710, 0x7f7585d37338, 0xc820612c60, 0xc82075bc88, 0xc8203162a0, 0xc820015320, 0x0, 0x0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:312 +0x13df
k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc82007b710, 0xc820015320, 0x0, 0x0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:279 +0x1215
k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run.func1()
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:158 +0x2c
k8s.io/kubernetes/pkg/util.Until.func1(0xc8201ebec0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:126 +0x4b
k8s.io/kubernetes/pkg/util.Until(0xc8201ebec0, 0x3b9aca00, 0xc820015320)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:127 +0x68
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:158 +0x84

goroutine 37 [select]:
k8s.io/heapster/metrics/sinks.NewDataSinkManager.func1(0x7f7585e02270, 0xc8201af380, 0xc8201af3e0, 0xc8201af440)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sinks/manager.go:86 +0x2b0
created by k8s.io/heapster/metrics/sinks.NewDataSinkManager
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sinks/manager.go:97 +0x238

goroutine 38 [select]:
k8s.io/kubernetes/pkg/client/cache.(*Reflector).watchHandler(0xc82007b8c0, 0x7f7585d37338, 0xc820612b40, 0xc820827c88, 0xc82024e000, 0xc820015320, 0x0, 0x0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:312 +0x13df
k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc82007b8c0, 0xc820015320, 0x0, 0x0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:279 +0x1215
k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run.func1()
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:158 +0x2c
k8s.io/kubernetes/pkg/util.Until.func1(0xc82021c0c0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:126 +0x4b
k8s.io/kubernetes/pkg/util.Until(0xc82021c0c0, 0x3b9aca00, 0xc820015320)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:127 +0x68
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:158 +0x84

goroutine 39 [select, 2 minutes]:
k8s.io/kubernetes/pkg/client/cache.(*Reflector).watchHandler(0xc82007b950, 0x7f7585d37338, 0xc820732870, 0xc820759c88, 0xc82012c060, 0xc820015320, 0x0, 0x0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:312 +0x13df
k8s.io/kubernetes/pkg/client/cache.(*Reflector).ListAndWatch(0xc82007b950, 0xc820015320, 0x0, 0x0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:279 +0x1215
k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run.func1()
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:158 +0x2c
k8s.io/kubernetes/pkg/util.Until.func1(0xc82021c2b0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:126 +0x4b
k8s.io/kubernetes/pkg/util.Until(0xc82021c2b0, 0x3b9aca00, 0xc820015320)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/util/util.go:127 +0x68
created by k8s.io/kubernetes/pkg/client/cache.(*Reflector).Run
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/client/cache/reflector.go:158 +0x84

goroutine 40 [select]:
k8s.io/heapster/metrics/manager.(*realManager).Housekeep(0xc8201af560)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/manager/manager.go:100 +0x399
created by k8s.io/heapster/metrics/manager.(*realManager).Start
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/manager/manager.go:85 +0x35

goroutine 53 [IO wait, 2 minutes]:
net.runtime_pollWait(0x7f7585db7f98, 0x72, 0xc820010170)
	/usr/lib/google-golang/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc820168220, 0x72, 0x0, 0x0)
	/usr/lib/google-golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc820168220, 0x0, 0x0)
	/usr/lib/google-golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201681c0, 0xc82075e000, 0x1000, 0x1000, 0x0, 0x7f7585df7168, 0xc820010170)
	/usr/lib/google-golang/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820734008, 0xc82075e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f7585cf7000, 0xc820734008, 0xc82074c058, 0xc82075e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8202e4100, 0xc82075e000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82024e420)
	/usr/lib/google-golang/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc82024e420, 0xa, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/bufio/bufio.go:328 +0x21a
net/http/internal.readLine(0xc82024e420, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/internal/chunked.go:110 +0x4b
net/http/internal.(*chunkedReader).beginChunk(0xc820732810)
	/usr/lib/google-golang/src/net/http/internal/chunked.go:47 +0x39
net/http/internal.(*chunkedReader).Read(0xc820732810, 0xc82076c200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/internal/chunked.go:77 +0xb7
net/http.(*body).readLocked(0xc82025a840, 0xc82076c200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transfer.go:632 +0x98
net/http.(*body).Read(0xc82025a840, 0xc82076c200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transfer.go:624 +0x110
net/http.(*bodyEOFSignal).Read(0xc82025a880, 0xc82076c200, 0x200, 0x200, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transport.go:1296 +0x26a
encoding/json.(*Decoder).refill(0xc82005c000, 0x0, 0x0)
	/usr/lib/google-golang/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc82005c000, 0x1, 0x0, 0x0)
	/usr/lib/google-golang/src/encoding/json/stream.go:128 +0x41b
encoding/json.(*Decoder).Decode(0xc82005c000, 0xeae040, 0xc8207328a0, 0x0, 0x0)
	/usr/lib/google-golang/src/encoding/json/stream.go:57 +0x159
k8s.io/kubernetes/pkg/watch/json.(*Decoder).Decode(0xc820732840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/json/decoder.go:50 +0xa5
k8s.io/kubernetes/pkg/watch.(*StreamWatcher).receive(0xc820732870)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/iowatcher.go:92 +0xf0
created by k8s.io/kubernetes/pkg/watch.NewStreamWatcher
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/iowatcher.go:59 +0xbf

goroutine 135 [select, 2 minutes]:
net/http.(*persistConn).readLoop(0xc820752210)
	/usr/lib/google-golang/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
	/usr/lib/google-golang/src/net/http/transport.go:685 +0xc78

goroutine 181 [IO wait]:
net.runtime_pollWait(0x7f7585db7ed8, 0x72, 0xc820010170)
	/usr/lib/google-golang/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8201e9100, 0x72, 0x0, 0x0)
	/usr/lib/google-golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8201e9100, 0x0, 0x0)
	/usr/lib/google-golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8201e90a0, 0xc8207a4000, 0x1000, 0x1000, 0x0, 0x7f7585df7168, 0xc820010170)
	/usr/lib/google-golang/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820746020, 0xc8207a4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f7585cf7000, 0xc820746020, 0xc820752268, 0xc8207a4000, 0x1000, 0x1000, 0xc820a78b40, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc82012ed80, 0xc8207a4000, 0x1000, 0x1000, 0xc8210697d0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820316cc0)
	/usr/lib/google-golang/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820316cc0, 0xc820cb610a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/bufio/bufio.go:328 +0x21a
net/http/internal.readLine(0xc820316cc0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/internal/chunked.go:110 +0x4b
net/http/internal.(*chunkedReader).beginChunk(0xc820612c00)
	/usr/lib/google-golang/src/net/http/internal/chunked.go:47 +0x39
net/http/internal.(*chunkedReader).Read(0xc820612c00, 0xc8207a6601, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/internal/chunked.go:77 +0xb7
net/http.(*body).readLocked(0xc82026e5c0, 0xc8207a6601, 0x5ff, 0x5ff, 0xc800000000, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transfer.go:632 +0x98
net/http.(*body).Read(0xc82026e5c0, 0xc8207a6601, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transfer.go:624 +0x110
net/http.(*bodyEOFSignal).Read(0xc82026e600, 0xc8207a6601, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transport.go:1296 +0x26a
encoding/json.(*Decoder).refill(0xc8207a01a0, 0x0, 0x0)
	/usr/lib/google-golang/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc8207a01a0, 0x1, 0x0, 0x0)
	/usr/lib/google-golang/src/encoding/json/stream.go:128 +0x41b
encoding/json.(*Decoder).Decode(0xc8207a01a0, 0xeae040, 0xc820cb3380, 0x0, 0x0)
	/usr/lib/google-golang/src/encoding/json/stream.go:57 +0x159
k8s.io/kubernetes/pkg/watch/json.(*Decoder).Decode(0xc820612c30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/json/decoder.go:50 +0xa5
k8s.io/kubernetes/pkg/watch.(*StreamWatcher).receive(0xc820612c60)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/iowatcher.go:92 +0xf0
created by k8s.io/kubernetes/pkg/watch.NewStreamWatcher
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/iowatcher.go:59 +0xbf

goroutine 178 [select, 2 minutes]:
net/http.(*persistConn).readLoop(0xc82074c000)
	/usr/lib/google-golang/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
	/usr/lib/google-golang/src/net/http/transport.go:685 +0xc78

goroutine 179 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc82074c000)
	/usr/lib/google-golang/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/lib/google-golang/src/net/http/transport.go:686 +0xc9d

goroutine 180 [IO wait]:
net.runtime_pollWait(0x7f7585db7e18, 0x72, 0xc820010170)
	/usr/lib/google-golang/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82015c220, 0x72, 0x0, 0x0)
	/usr/lib/google-golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82015c220, 0x0, 0x0)
	/usr/lib/google-golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82015c1c0, 0xc820762000, 0x1000, 0x1000, 0x0, 0x7f7585df7168, 0xc820010170)
	/usr/lib/google-golang/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820746008, 0xc820762000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f7585cf7000, 0xc820746008, 0xc82074a058, 0xc820762000, 0x1000, 0x1000, 0xc820c9f200, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820142300, 0xc820762000, 0x1000, 0x1000, 0xc820c7f7d0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820316540)
	/usr/lib/google-golang/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).ReadSlice(0xc820316540, 0xc820c8340a, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/bufio/bufio.go:328 +0x21a
net/http/internal.readLine(0xc820316540, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/internal/chunked.go:110 +0x4b
net/http/internal.(*chunkedReader).beginChunk(0xc820612ae0)
	/usr/lib/google-golang/src/net/http/internal/chunked.go:47 +0x39
net/http/internal.(*chunkedReader).Read(0xc820612ae0, 0xc8207a8001, 0xdff, 0xdff, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/internal/chunked.go:77 +0xb7
net/http.(*body).readLocked(0xc82026e340, 0xc8207a8001, 0xdff, 0xdff, 0xc800000000, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transfer.go:632 +0x98
net/http.(*body).Read(0xc82026e340, 0xc8207a8001, 0xdff, 0xdff, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transfer.go:624 +0x110
net/http.(*bodyEOFSignal).Read(0xc82026e380, 0xc8207a8001, 0xdff, 0xdff, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transport.go:1296 +0x26a
encoding/json.(*Decoder).refill(0xc8207a0000, 0x0, 0x0)
	/usr/lib/google-golang/src/encoding/json/stream.go:152 +0x287
encoding/json.(*Decoder).readValue(0xc8207a0000, 0x1, 0x0, 0x0)
	/usr/lib/google-golang/src/encoding/json/stream.go:128 +0x41b
encoding/json.(*Decoder).Decode(0xc8207a0000, 0xeae040, 0xc820cabf20, 0x0, 0x0)
	/usr/lib/google-golang/src/encoding/json/stream.go:57 +0x159
k8s.io/kubernetes/pkg/watch/json.(*Decoder).Decode(0xc820612b10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/json/decoder.go:50 +0xa5
k8s.io/kubernetes/pkg/watch.(*StreamWatcher).receive(0xc820612b40)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/iowatcher.go:92 +0xf0
created by k8s.io/kubernetes/pkg/watch.NewStreamWatcher
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/Godeps/_workspace/src/k8s.io/kubernetes/pkg/watch/iowatcher.go:59 +0xbf

goroutine 132 [select, 2 minutes]:
net/http.(*persistConn).readLoop(0xc82074a000)
	/usr/lib/google-golang/src/net/http/transport.go:976 +0xac7
created by net/http.(*Transport).dialConn
	/usr/lib/google-golang/src/net/http/transport.go:685 +0xc78

goroutine 133 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc82074a000)
	/usr/lib/google-golang/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/lib/google-golang/src/net/http/transport.go:686 +0xc9d

goroutine 136 [select, 2 minutes]:
net/http.(*persistConn).writeLoop(0xc820752210)
	/usr/lib/google-golang/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/lib/google-golang/src/net/http/transport.go:686 +0xc9d

goroutine 193 [IO wait]:
net.runtime_pollWait(0x7f7585db7d58, 0x72, 0xc820010170)
	/usr/lib/google-golang/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8203fbb10, 0x72, 0x0, 0x0)
	/usr/lib/google-golang/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203fbb10, 0x0, 0x0)
	/usr/lib/google-golang/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203fbab0, 0xc8207fe000, 0x1000, 0x1000, 0x0, 0x7f7585df7168, 0xc820010170)
	/usr/lib/google-golang/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8207fa000, 0xc8207fe000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/net/net.go:172 +0xe4
net/http.noteEOFReader.Read(0x7f7585cf7000, 0xc8207fa000, 0xc8200ba688, 0xc8207fe000, 0x1000, 0x1000, 0xc82002c400, 0x0, 0x0)
	/usr/lib/google-golang/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8207f6040, 0xc8207fe000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc8207fc000)
	/usr/lib/google-golang/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8207fc000, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/google-golang/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200ba630)
	/usr/lib/google-golang/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/usr/lib/google-golang/src/net/http/transport.go:685 +0xc78

goroutine 194 [select]:
net/http.(*persistConn).writeLoop(0xc8200ba630)
	/usr/lib/google-golang/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/usr/lib/google-golang/src/net/http/transport.go:686 +0xc9d

goroutine 209 [select]:
k8s.io/heapster/metrics/sources.(*sourceManager).ScrapeMetrics(0xc820214380, 0xece67b614, 0xc800000000, 0x1983580, 0xece67b632, 0xe00000000, 0x1983580, 0x1983580)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sources/manager.go:119 +0x10e9
k8s.io/heapster/metrics/manager.(*realManager).housekeep.func1(0xece67b614, 0xc800000000, 0x1983580, 0xece67b632, 0x0, 0x1983580, 0xc8201af560)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/manager/manager.go:128 +0xdc
created by k8s.io/heapster/metrics/manager.(*realManager).housekeep
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/manager/manager.go:144 +0x33d

Any idea?

**Comment by mwielgus** [comment]
Can you please switch to the newest version? gcr.io/google_containers/heapster:v0.20.0-alpha9

Just FYI heapster 0.20.0 is a big refactoring/rewrite and there were numerous bugs in early alpha versions. Issue in kubelet.go:154 was fixed some time ago.

**Comment by cheld** [comment]
ok, thanks. It seems to run stable. 

BTW stupid question: Is there a way to see the available versions of a container in gcr like on Docker Hub?

**Comment by piosz** [comment]
We are not aware of any way. If you will figure it out please let us know:)
