### ISSUE TITLE
Document how to use old heapster + kubedash

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/heapster#1031]
Since kube-dash is not supported in new heapster we need a way for some customer to run the old "bundle".

**Comment by r8k** [comment]
@fgrzadkowski I think the easiest way is to use the older image `docker.io/kubernetes/heapster:canary`

**Comment by vishh** [comment]
the `canary` image is updated everyday. We should use an explicit version.

@fgrzadkowski @mwielgus We should get this resolved soon since Kubernetes v1.2 is already out.

**Comment by fgrzadkowski** [comment]
@vishh +1

@mwielgus Can you please document this? This is really high priority.

**Comment by mwielgus** [comment]
Understood. Will be done today.

**Comment by mwielgus** [comment]
https://github.com/kubernetes/kubedash/pull/57

**Comment by andyxning** [comment]
Hi, guys, any plans for supporting heapster 1.1.0. We need the OpenTSDB sink. :)

**Comment by fgrzadkowski** [comment]
@andyxning Are you saying you'd like new heapster with kube-dash? I don't think it's possible. CC-ing @piosz for more details.

**Comment by andyxning** [comment]
@piosz what is the difficulty for migrating to supporting new heapster. :)

**Comment by piosz** [comment]
@andyxning what do you mean? 

Heapster 1.1.0 is released and available in GCR as `gcr.io/google_containers/heapster:v1.1.0`.

Heapster starting from version 1.0 doesn't support kube-dash, the effort is deprecated and is replaced by [dashboard](https://github.com/kubernetes/dashboard) project.

OpenTSDB sink is supported both in Heapster 1.0 and 1.1, though it's community driven feature and we can't promise it works.

**Comment by andyxning** [comment]
@piosz thanks for your info. If i am not misunderstanding, you mean that from heapster 1.0 we should use dashboard instead of kube-dash. If then, will kube-dash will be deprecated in the future? :)

**Comment by piosz** [comment]
New dashboard was introduced in Kubernetes 1.2 and is by default installed in Kubernetes cluster. In the same Kubernetes version we released stable Heapster version 1.0 which doesn't support kube-dash. We strongly encourage you to use dashboard instead of kube-dash however it's still possible to use also kube-dash (more details [here](https://github.com/kubernetes/kubedash#usage)).

@bryk can provide more details on dashboard.

**Comment by bryk** [comment]
@andyxning Dashboard UI eng here. Some kube-dash functionality is not supported yet in the Dashboard UI. But we are committed to have all monitoring functionalities that kubedash had + more features this quarter. In the meantime, the Dashboard UI still has many nice non-monitoring features that you should try out :)

**Comment by andyxning** [comment]
@Bryk Ok, i will have a try. :)


=======
Ning Xie


2016-06-28 15:52 GMT+08:00 Piotr Bryk <notifications@github.com>:
