### ISSUE TITLE
Create final v1.0 version and bump version in K8S 1.2 release branch

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/heapster#1051]
cc: @piosz @fgrzadkowski

**Comment by piosz** [comment]
our target is v1.0

**Comment by piosz** [comment]
PR in flight https://github.com/kubernetes/kubernetes/pull/22993

**Comment by piosz** [comment]
https://github.com/kubernetes/kubernetes/pull/22993 is merged so closing this
