### ISSUE TITLE
Heapster race conditions with docker image heapster:canary

### ISSUE THREAD

**Issue by ckleban** [kubernetes/heapster#1057]
As in issue #780, I'm still seeing the race condition. Logs from my heapster pod that fail to create a DB in influxdb (and also fail to retry). I'm using the kubenernetes/heapster:canary image. 

I0310 18:40:14.541729       1 heapster.go:61] /heapster --source=kubernetes:https://kubernetes.default --sink=influxdb:http://monitoring-influxdb:8086
I0310 18:40:14.541818       1 heapster.go:62] Heapster version 0.19.1
I0310 18:40:14.543349       1 kube_factory.go:172] Using Kubernetes client with master "https://kubernetes.default" and version "v1"
I0310 18:40:14.543363       1 kube_factory.go:173] Using kubelet port 10255
E0310 18:40:19.678442       1 manager.go:299] encountered following errors while setting up sinks - issues while creating an InfluxDB sink: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp: lookup monitoring-influxdb: no such host, will retry on use
I0310 18:40:19.680930       1 heapster.go:72] Starting heapster on port 8082
E0310 18:42:00.005793       1 kubelet.go:102] failed to get stats from kubelet url: http://10.56.184.130:10255/stats/default/web-zelhp/c539e4e9-e6ef-11e5-8a2d-000c29fb6370/web - request failed - "404 Not Found", response: "no matching container\n"
E0310 18:42:00.010569       1 kube_pods.go:110] failed to get stats for container "web" in pod "default"/"web-zelhp"
E0310 18:42:05.011524       1 kubelet.go:102] failed to get stats from kubelet url: http://10.56.184.130:10255/stats/default/web-zelhp/c539e4e9-e6ef-11e5-8a2d-000c29fb6370/web - request failed - "404 Not Found", response: "no matching container\n"
E0310 18:42:05.011578       1 kube_pods.go:110] failed to get stats for container "web" in pod "default"/"web-zelhp"
E0310 19:19:35.006889       1 kubelet.go:102] failed to get stats from kubelet url: http://10.56.184.127:10255/stats/default/netperf-tester-client-59emk/0526e690-e6f5-11e5-8a2d-000c29fb6370/netperf-tester-client - request failed - "404 Not Found", response: "no matching container\n"
E0310 19:19:35.006983       1 kube_pods.go:110] failed to get stats for container "netperf-tester-client" in pod "default"/"netperf-tester-client-59emk"
E0310 19:19:35.007209       1 kubelet.go:102] failed to get stats from kubelet url: http://10.56.184.130:10255/stats/default/netperf-tester-host-irxrg/04d15616-e6f5-11e5-8a2d-000c29fb6370/netperf-tester-host - request failed - "404 Not Found", response: "no matching container\n"
E0310 19:19:35.007217       1 kube_pods.go:110] failed to get stats for container "netperf-tester-host" in pod "default"/"netperf-tester-host-irxrg"
E0310 19:19:40.024935       1 kubelet.go:102] failed to get stats from kubelet url: http://10.56.184.130:10255/stats/default/netperf-tester-host-irxrg/04d15616-e6f5-11e5-8a2d-000c29fb6370/netperf-tester-host - request failed - "404 Not Found", response: "no matching container\n"
E0310 19:19:40.024967       1 kube_pods.go:110] failed to get stats for container "netperf-tester-host" in pod "default"/"netperf-tester-host-irxrg"
E0310 19:19:40.025626       1 kubelet.go:102] failed to get stats from kubelet url: http://10.56.184.127:10255/stats/default/netperf-tester-client-59emk/0526e690-e6f5-11e5-8a2d-000c29fb6370/netperf-tester-client - request failed - "404 Not Found", response: "no matching container\n"
E0310 19:19:40.025637       1 kube_pods.go:110] failed to get stats for container "netperf-tester-client" in pod "default"/"netperf-tester-client-59emk"
E0310 19:19:45.006950       1 kubelet.go:102] failed to get stats from kubelet url: http://10.56.184.127:10255/stats/default/netperf-tester-client-59emk/0526e690-e6f5-11e5-8a2d-000c29fb6370/netperf-tester-client - request failed - "404 Not Found", response: "no matching container\n"
E0310 19:19:45.006967       1 kube_pods.go:110] failed to get stats for container "netperf-tester-client" in pod "default"/"netperf-tester-client-59emk"
E0310 19:19:45.010303       1 kubelet.go:102] failed to get stats from kubelet url: http://10.56.184.130:10255/stats/default/netperf-tester-host-irxrg/04d15616-e6f5-11e5-8a2d-000c29fb6370/netperf-tester-host - request failed - "404 Not Found", response: "no matching container\n"
E0310 19:19:45.010365       1 kube_pods.go:110] failed to get stats for container "netperf-tester-host" in pod "default"/"netperf-tester-host-irxrg"

If I restart the heapster pod, things seem to work fine:

>>kubectl --namespace=kube-system logs heapster-v10-6t5ju --follow
I0310 19:25:27.242994       1 heapster.go:61] /heapster --source=kubernetes:https://kubernetes.default --sink=influxdb:http://monitoring-influxdb:8086
I0310 19:25:27.243077       1 heapster.go:62] Heapster version 0.19.1
I0310 19:25:27.244369       1 kube_factory.go:172] Using Kubernetes client with master "https://kubernetes.default" and version "v1"
I0310 19:25:27.244383       1 kube_factory.go:173] Using kubelet port 10255
I0310 19:25:27.247568       1 driver.go:351] created influxdb sink with options: {root root monitoring-influxdb:8086 k8s false}
I0310 19:25:27.258551       1 driver.go:272] Created database "k8s" on influxDB server at "monitoring-influxdb:8086"
I0310 19:25:27.265837       1 heapster.go:72] Starting heapster on port 8082

**Comment by mwielgus** [comment]
Please try v0.20.0-alpha12.

**Comment by ckleban** [comment]
Retrying works. Closing request
