### ISSUE TITLE
Add s390x support

### ISSUE THREAD

**Issue by rposts** [kubernetes/heapster#1063]
Please add s390x support to Heapster.

I was able to get this working on s390x by simply pulling this file from Kubernetes master: 

https://github.com/kubernetes/kubernetes/blob/master/Godeps/_workspace/src/github.com/boltdb/bolt/bolt_s390x.go

Thanks.

**Comment by mwielgus** [comment]
Could you please be a bit more specific on what you are exactly trying to do? And what exactly is missing?
I guess that s390x stands for some IBM architecture but I've personally never heard much about it.

**Comment by rposts** [comment]
My apologies.  Yes, s390x is Linux on IBM's System z.  

I am working on validating OpenShift on s390x architecture and as part of that effort I had to use Heapster for OpenShift autoscaling.  I found that I was unable to create Heapster Docker images unless I copied bolt_s390x.go from Kubernetes master.  Here is Dockerfile reference: https://github.com/openshift/origin-metrics/blob/master/heapster-base/Dockerfile

Let me know if it makes sense.

Thanks.

**Comment by rposts** [comment]
So what is missing is bolt_s390x.go in https://github.com/kubernetes/heapster/tree/master/Godeps/_workspace/src/github.com/boltdb/bolt

**Comment by mwielgus** [comment]
Well, it is not entirely missing - most likely we are just using Influxdb client/db that is about half a year old that doesn't depend on the newest boltdb that has the mentioned file. We can definitely think about upgrading the deps a bit to have this file on-board but this is not a matter of putting an extra file there.

**Comment by rposts** [comment]
Sure - I understand. Perhaps we can prioritize this issue accordingly.  In the meantime I will continue with mentioned workaround on s390x. Thanks.
