### ISSUE TITLE
[Azure k8s cluster] Heapster / InfluxDB / Grafana are not working anymore.

### ISSUE THREAD

**Issue by theobolo** [kubernetes/heapster#1067]
Hello,

Today i've started a cluster from scratch with azure kubernetes guide and few modifications in the cloud-configs.

I modified the source:kubernetes of the heapster replication controller with that source=kubernetes:http://172.18.0.12:8080 witch is the Kube API master endpoint in that cluster.

I installed the InfluxDB heapster on my cluster.

The logs from heapster : 

![sans titre](https://cloud.githubusercontent.com/assets/7281773/13782550/e8977f02-eac7-11e5-871f-794fdea03efb.png)

And from InfluxDB (link) : 

http://kube-8fa666f98c72d5.cloudapp.net:8080/api/v1/proxy/namespaces/kube-system/services/dashboard-canary/#/logs/kube-system/influxdb-grafana/influxdb-grafana-gv8dk/influxdb

And can also see the grafana log with the link above.

By the way everything seems to be ok but i have no infos on the Grafana http client :

![sans titre](https://cloud.githubusercontent.com/assets/7281773/13782719/92a078aa-eac8-11e5-853b-c7c2cbde5a5d.png)

any ideas ? everything was ok on my previous cluster.
BTW Kubedash is not working :/

**Comment by remoe** [comment]
Same here and the current kubedash does also not work (stats 404)

**Comment by theobolo** [comment]
Ohhhh at least i think i've figured out why : 

As it was said in an other issue they changed the folder architecture inside the InfluxDB.

The problem is just that the container and kubernetes metrics templates are not requesting the correct paths ...

#https://github.com/kubernetes/heapster/issues/970

**Comment by remoe** [comment]
@theobolo , right thanks! It works when you use this:

kubernetes/cluster/addons/cluster-monitoring/influxdb/influxdb-grafana-controller.yaml

But it doesn't get the pod names:

![grafana](https://cloud.githubusercontent.com/assets/804941/13786788/858ec552-ead9-11e5-8809-7c381bafce08.png)

**Comment by theobolo** [comment]
Was working good with the kubernetes/cluster/addons/cluster-monitoring/influxdb****

But with all the folder even heapster.

It's working from that folder.

**Comment by Calpicow** [comment]
Updated to `heapster_grafana:v2.6.0-2`. Cluster view works fine, but pod view is completely broken.

**Comment by remoe** [comment]
@Calpicow, I've deleted the whole influxdb and garfana-data before I installed the new container.

**Comment by Calpicow** [comment]
Ok, it works when I select the podname directly, but the namespace filter is broken.

**Comment by fonk** [comment]
I fixed the dashboards for heapster_grafana:v2.6.0 (and possibly earlier versions with new influxdb scheme) as far as I could - only the two Cluster Network Graphs are missing right now:
[dashboards.zip](https://github.com/kubernetes/heapster/files/185239/dashboards.zip)
Maybe someone with more influxdb knowledge can fix the last two...
