### ISSUE TITLE
Grafana container cannot connect to InfluxDB via service IP

### ISSUE THREAD

**Issue by zihaoyu** [kubernetes/heapster#1079]
Heapster container can connect to InfluxDB sink via service IP, but not Grafana container.

```
root@heapster-3c83g:/go# curl --connect-timeout 10 http://monitoring-influxdb:8086
404 page not found
```

```
root@influxdb-grafana-7cmy4:/# curl --connect-timeout 10 http://monitoring-grafana:8086
curl: (28) Connection timed out after 10001 milliseconds
```

For now we are using `localhost` since Grafana and InfluxDB containers are in the same pod.

**Comment by binarybana** [comment]
This is related to the kubelet's hairpin mode or promiscuous mode: https://github.com/kubernetes/kubernetes/issues/20475

**Comment by antoineco** [comment]
@zihaoyu did you set the `--hairpin-mode=hairpin-veth` kubelet flag? After that just kill your pod and it should work.

You can check on your hosts whether the hairpin mode is enabled or not on each virtual interface of your docker bridge:

```
for intf in /sys/devices/virtual/net/docker0/brif/*; do
  cat $intf/hairpin_mode
done
```

**Comment by zihaoyu** [comment]
@antoineco No I did not set that flag. kubelet runs with default values for `--configure-cbr0` and `--hairpin-mode` options.

**Comment by binarybana** [comment]
Though there is a bug with the `--hairpin-mode` flag not taking effect in
certain cases that is fixed for inclusion into 1.2.1. (don't have time to
look up the issue number atm)

**Comment by antoineco** [comment]
It doesn't fallback properly to `hairpin-veth` in case `--configure-cbr0` is false, however @zihaoyu said it was set to `true` in his cluster, so this might be yet a different case.

**Comment by zihaoyu** [comment]
Not an issue any more.
