### ISSUE TITLE
Namespace filter is broken

### ISSUE THREAD

**Issue by Calpicow** [kubernetes/heapster#1080]
The namespace filter doesn't show all the namespaces in the cluster and doesn't filter pod names.

Below screenshot shows `jsearch-elk-kibana` namespace typed manually with metrics showing, but is not in the dropdown.

![screen shot 2016-03-17 at 15 49 14](https://cloud.githubusercontent.com/assets/8184583/13863588/0ac01cec-ec58-11e5-84aa-3b13b45b4b00.png)

**Comment by mwielgus** [comment]
Grafana seems to have issues with updating templates. If you go to manage dashboard, click on templates, edit namespace templates and click on update the new namespace will pop in. I will take a look on how to workaround this problem. 

As of pods not being filtered - there is no `show tag values` filtering possible in influxdb. But we can create an additional tag for time serieses that will contain namespace and pod name concatenated together.

**Comment by innovia** [comment]
+1 for pod filtering

**Comment by sekka1** [comment]
Is this related to this issue?  https://github.com/kubernetes/heapster/issues/1120

**Comment by fragtom** [comment]
Having same issue - just default and kube-system displayed. @mwielgus - where to find "templates" - could find out location of namespace templates.

By adding query-parameter var-namespace e.g. 

`?var-namespace=dev`

we are able to drill in the namespace.

**Comment by Calpicow** [comment]
This issue appears to be resolved now.
