### ISSUE TITLE
The numbers seem incorrect from heapster v1.0.0 

### ISSUE THREAD

**Issue by perhapszzy** [kubernetes/heapster#1083]
I'm running heapster v1.0.0 with grafana v2.6.0-2, but the numbers I got seems incorrect:

![image](https://cloud.githubusercontent.com/assets/7953637/13920210/db13506a-efac-11e5-90d7-c9e0688c9441.png)

The memory should be 2G for the machine, but the limit is only 600M and the usage is over 600M as well.

It seems that there are problems about monitoring the containers' filesystem:
This container runs an algorithm that writes to disk, however, the grafana shows 0 fs usage for that container: 
![image](https://cloud.githubusercontent.com/assets/7953637/13920401/bcd17996-efad-11e5-9eea-f23fd57bdfe4.png)

But the number on the node is correct:
![image](https://cloud.githubusercontent.com/assets/7953637/13920529/792d388c-efae-11e5-98bc-492b3cb5ad5e.png)

Any idea/suggestion about this problem? Could that be caused by the version of k8s? I'm running k8s v1.1

**Comment by mwielgus** [comment]
Limit is the sum of memory explicitly asked by your pods in the Limit section of container resources.
In the same way Request is the sum of memory explicitely asked by you pods in Request section. If you don't specify limit but only request then request sum can be higher than limit.

Adding @vishh to handle filesystem metric question.

**Comment by vishh** [comment]
Is this data for a pod or a container? `Limits` and `Requests` are per container. 
As for filesystem metrics, what is your node configuration? We don't support device mapper docker storage driver as of now.

**Comment by perhapszzy** [comment]
@mwielgus  Thanks, that makes much more sense. 
@vishh  It should be the problem that device  mapper is not counted now. The code writes the disk in the container but the pod is not mounted on any hostpath. Is there any plan to support the device mapper storage in near future?

**Comment by vishh** [comment]
https://github.com/google/cadvisor/issues/959

**Comment by perhapszzy** [comment]
Thanks for the pointer.it seems that heapster v0.19.0 worked correctly on getting those numbers, I'm curious is there anything dramatically changed for v1.0.0?

**Comment by vishh** [comment]
For what numbers?

**Comment by perhapszzy** [comment]
The disk usage for containers

**Comment by vishh** [comment]
We haven't changed disk usage semantics since the last release.
