### ISSUE TITLE
namespace_based_enricher.go:64] Failed to get namespace: exist: %!s(bool=false) error: <nil>

### ISSUE THREAD

**Issue by saiwl** [kubernetes/heapster#1085]
i use kubernetes v1.1.3。the config file to run heapster is below:
apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-heapster-v6
  #namespace: kube-system
  namespace: default
  labels:
    k8s-app: heapster
  #  version: v6
spec:
  replicas: 1
  selector:
    k8s-app: heapster
  #  version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
  #      version: v6
    spec:
      nodeName: 10.143.24.31
      containers:
        #- image: gcr.io/google_containers/heapster:v0.16.1
        #- image: kubernetes/heapster:v0.19.0
        #- image: gcr.io/google_containers/heapster:v1.0.0
        - image: kubernetes/heapster:canary
          name: heapster
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
          command:
            - /heapster
            - --source=kubernetes:http://10.143.24.29:8080?inClusterConfig=false&auth=
            - --sink=kafka:?brokers=10.143.24.31:9092&timeseriestopic=testseries&eventstopic=testtopic

kubectl get namespace shows:
NAME      LABELS    STATUS    AGE
default   <none>    Active    55d

see the logs by heapster pod:

I0322 10:51:33.555695       1 heapster.go:61] Heapster version 1.0.0
I0322 10:51:33.555743       1 configs.go:60] Using Kubernetes client with master "http://10.143.24.29:8080" and version "v1"
I0322 10:51:33.555754       1 configs.go:61] Using kubelet port 10255
I0322 10:51:33.559001       1 heapster.go:87] Starting with Apache Kafka Sink
I0322 10:51:33.559095       1 heapster.go:87] Starting with Metric Sink
I0322 10:51:33.587133       1 heapster.go:166] Starting heapster on port 8082
I0322 10:52:05.000267       1 manager.go:79] Scraping metrics start: 2016-03-22 10:51:30 +0000 UTC, end: 2016-03-22 10:52:00 +0000 UTC
I0322 10:52:05.446183       1 manager.go:152] ScrapeMetrics: time: 445.758866ms size: 55
W0322 10:52:05.446554       1 namespace_based_enricher.go:64] Failed to get namespace: exist: %!s(bool=false) error: <nil>
W0322 10:52:05.446577       1 namespace_based_enricher.go:64] Failed to get namespace: exist: %!s(bool=false) error: <nil>

why show these errors?
hope some one can help...

**Comment by mwielgus** [comment]
Are these warnings repeatable?

**Comment by mwielgus** [comment]
Heapster gets a list all namespaces from the API server and adds some namespace information to the pods and containers. If the pod's namespace is not on the namespace's list then the warning is printed (although it is badly formatted - i will fix it right now). 

I don't have a clear answer why this was possible given that it had 30 sec to get the namespaces.

**Comment by saiwl** [comment]
thank you very much for you reply!
According to you explanation, I think I find the reason. There are two pods running in kube-system namespace, but kubectl get namespaces command only shows the default namespace. I will test is later, thanks for your help!

**Comment by mwielgus** [comment]
Log fixed with #1086
