### ISSUE TITLE
The limit didn't seem to respect physical resources and quotas

### ISSUE THREAD

**Issue by perhapszzy** [kubernetes/heapster#1089]
The limits for namespaces and nodes seem just to be the sum of limits of pods running under them. 
However, the sums may be larger than the physical resources of a node or quotas set for a namespace. Is this intended or there are some planned works around this?

**Comment by mwielgus** [comment]
This is more-or-less working as intended. Request are used for scheduling. So the total requested value should not exceed node capacity. Limits on the other hand are used to keep containers/pods in some boundaries. 

Please take a look https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/resource-qos.md for more details.

**Comment by perhapszzy** [comment]
Yes, I'm aware of the limits and quotas that could be set to every pod/namespace; actually my biggest concern is that heapster should respect the quotas set on namespace. For example, if a namespace is set to have a limit of 1G memory, it's totally valid under the current model that 2 pods have (512M request and 1G limit). However, in this case, heaspter will show the memory limit for the namespace as 2G (the sum of the two pods) instead of 1G.

**Comment by mwielgus** [comment]
The documentation isn't clear:
http://kubernetes.io/docs/admin/resourcequota/
`In term of resources, Kubernetes checks the total resource requests, not resource limits of all containers/pods in the namespace.`

So IIUC your namespace is set to accept pods with combined sum of requests up to 1gb. So the sum of pod limits is 2gb which is ok.

**Comment by perhapszzy** [comment]
Yeah, I understand that this is totally valid in k8s. What I concerned is the limit number in heapster (or on grafana UI). User had explicitly set the limit of memory for a namespace to be 1G, but the number shows up on grafana would be 2G. This might cause little confusion for users

**Comment by perhapszzy** [comment]
@mwielgus  If you also think that the limit for namespace should respect the quota set, we can make the adjustment for heapster.
