### ISSUE TITLE
OpenTSDB sink does not support float32 MetricValue

### ISSUE THREAD

**Issue by simonklb** [kubernetes/heapster#1103]
The MetricValue struct stores float values as type float32:
https://github.com/kubernetes/heapster/blob/master/metrics/core/types.go#L89

While the OpenTSDB sink client only validates float64:
https://github.com/kubernetes/heapster/blob/master/Godeps/_workspace/src/github.com/bluebreezecf/opentsdb-goclient/client/put.go#L260

One easy fix for this would be to allow for both float types in the OpenTSDB client. But I thought it could  be good to inform you guys about this issue as well.

Would the correct way of going about this be to create a pull request in the original author's repository?

**Comment by barkbay** [comment]
I have opened a PR here https://github.com/bluebreezecf/opentsdb-goclient/pull/1

**Comment by piosz** [comment]
fixed in #1169
