### ISSUE TITLE
No api/v1/model/namespaces/<namespace>/pods/<pod>/containers API handler

### ISSUE THREAD

**Issue by resouer** [kubernetes/heapster#1107]
There is no handler registered to process `api/v1/model/namespaces/<namespace>/pods/<pod>/containers` in [model_handlers.go](https://github.com/kubernetes/heapster/blob/master/metrics/api/v1/model_handlers.go#L149)

Thus, when you `curl localhost:8082/api/v1/model/namespaces/kube-system/pods/influxdb-grafana-rcd5n/containers` , you will get:

```
404: Page Not Found
```

But this api is still in: https://github.com/kubernetes/heapster/blob/master/docs/model.md

Is it deprecated, or I made mistake here?

**Comment by euprogramador** [comment]
I'm having the same problem

**Comment by tspeth** [comment]
Hi guys,

is there any update on this issue? I have the same problem as well.

Thanks!

**Comment by piosz** [comment]
@mwielgus could you please take a look? Thanks!

**Comment by sputnick** [comment]
Same here using the deployment files example for InfluxDB from the Heapster github repo.  The code in Master seems to still have the route but it doesn't work. I have Kube-cluster.app with kubernetes 1.4 - everything but the container metrics work.
https://github.com/kubernetes/heapster/blob/master/metrics/api/v1/model_handlers.go#L178

**Comment by DirectXMan12** [comment]
Yeah, there's currently no route to list the containers in a pod, but if you know the container name, the route to view a metric for a container is still there.  It doesn't actually break HPA or anything like that, it just makes it slightly more annoying to debug metrics issues.

**Comment by sputnick** [comment]
@DirectXMan12 what I meant was that even the direct path does not work - returns nothing.

**Comment by DirectXMan12** [comment]
this is quite old at this point, and the model API is not really supported.  closing
