### ISSUE TITLE
heapster v0.20.0-alpha9 couldn't run successfully in k8s 1.1.8 

### ISSUE THREAD

**Issue by zjx-immersion** [kubernetes/heapster#1110]
k8s:1.1.8
docker:1.10.2
coreos:4.4.6-coreos

this cluster is in AWS.

I ran below yaml file in my coreos k8s cluster follow the fixed issue #1003 ：
> apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster-v12
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v12
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v12
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v12
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v0.20.0-alpha9
          name: heapster
          resources:
            limits:
              cpu: 100m
              memory: 300Mi
          command:
            - /heapster
            - --source=kubernetes:http://10.0.0.50:8080?inClusterConfig=false&kubeletHttps=true&useServiceCAccount=trye&auth=
            - --sink=influxdb:http://monitoring-influxdb:8086
            - --stats_resolution=30s
            - --sink_frequency=1m

however the pod status will be "CrashLoopBackOff"

when i describe the pod info it show :  

> Name:		heapster-v12-fiq1w
Namespace:	kube-system
Node:		ip-10-0-0-188.ap-southeast-1.compute.internal/10.0.0.188
Start Time:	Fri, 01 Apr 2016 16:19:41 +0800
Labels:		k8s-app=heapster,kubernetes.io/cluster-service=true,version=v12
Status:		Running
IP:		10.2.5.2
Controllers:	ReplicationController/heapster-v12
Containers:
  heapster:
    Container ID:	docker://4e36359896805b070e650379cff1da1054bd2f2dfa7d3d575952c0d373768d0b
    Image:		gcr.io/google_containers/heapster:v0.20.0-alpha9
    Image ID:		docker://sha256:d362b18004669e931345a7084c2168ee6d5c78127a2f07c45fcccc3750322635
    Port:
    Command:
      /heapster
      --source=kubernetes:''
      --sink=influxdb:http://monitoring-influxdb:8086
      --stats_resolution=30s
      --sink_frequency=1m
    QoS Tier:
      cpu:	Guaranteed
      memory:	Guaranteed
    Limits:
      cpu:	100m
      memory:	300Mi
    Requests:
      cpu:		100m
      memory:		300Mi
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	2
      Started:		Fri, 01 Apr 2016 16:22:53 +0800
      Finished:		Fri, 01 Apr 2016 16:22:53 +0800
    Ready:		False
    Restart Count:	6
    Environment Variables:
Conditions:
  Type		Status
  Ready 	False
Volumes:
  default-token-nctph:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-nctph
Events:
  FirstSeen	LastSeen	Count	From							SubobjectPath				Type		Reason		Message
  ---------	--------	-----	----							-------------				--------	------		-------
  3m		3m		1	{scheduler }													Scheduled	Successfully assigned heapster-v12-fiq1w to ip-10-0-0-188.ap-southeast-1.compute.internal
  3m		3m		1	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	implicitly required container POD			Started		Started with docker id c5205df46bcc
  3m		3m		1	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	implicitly required container POD			Pulled		Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
  3m		3m		1	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	spec.containers{heapster}				Created		Created with docker id e94471494a1a
  3m		3m		1	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	spec.containers{heapster}				Started		Started with docker id e94471494a1a
  3m		3m		1	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	implicitly required container POD			Created		Created with docker id c5205df46bcc
  3m		3m		1	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	spec.containers{heapster}				Started		Started with docker id 15eb1d441d00
  3m		3m		1	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	spec.containers{heapster}				Created		Created with docker id 15eb1d441d00
  3m		3m		1	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	spec.containers{heapster}				Started		Started with docker id 0e1d747c9033
  3m		3m		1	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	spec.containers{heapster}				Created		Created with docker id 0e1d747c9033
  3m		3m		1	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	spec.containers{heapster}				Started		Started with docker id 38093aa772f1
  3m		3m		1	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	spec.containers{heapster}				Created		Created with docker id 38093aa772f1
  2m		2m		1	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	spec.containers{heapster}				Created		Created with docker id 8982781be1ae
  2m		2m		1	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	spec.containers{heapster}				Started		Started with docker id 8982781be1ae
  43s		43s		1	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	spec.containers{heapster}				Started		Started with docker id 4e3635989680
  3m		43s		6	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	spec.containers{heapster}				Pulled		Container image "gcr.io/google_containers/heapster:v0.20.0-alpha9" already present on machine
  43s		43s		1	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	spec.containers{heapster}				Created		Created with docker id 4e3635989680
  3m		3s		19	{kubelet ip-10-0-0-188.ap-southeast-1.compute.internal}	spec.containers{heapster}				Backoff		Back-off restarting failed docker container

i saw the #1003 , it show me the running version of heapster and heapster_grafana. i
Does heapster v0.20.0-alpha9 can't run in 1.1.8?

**Comment by piosz** [comment]
Thanks for reporting.

`v0.20.0-alpha9` is an experimental version. Could you please try to use a stable one like v1.0.2? In the meantime I'm closing the issue. Please re-open in case of troubles.
