### ISSUE TITLE
Source cadvisor without Kubernetes? 

### ISSUE THREAD

**Issue by goettl79** [kubernetes/heapster#1114]
Hi, is there a chance to get the old source behavior back. The one using etcd and cadvisor directly?

**Comment by ezeev** [comment]
Looking for guidance on this as well - especially for testing a local heapster build. It would be useful to be able to test against a running cAdvisor.

**Comment by piosz** [comment]
Unfortunately this is out of the scope of the Heapster.

cc @mwielgus
