### ISSUE TITLE
Using nodeName/node.spec.externalID instead of node.IP for scraping metrics from kubelet ?

### ISSUE THREAD

**Issue by ravilr** [kubernetes/heapster#1117]
@vishh @piosz 

I'm trying to not expose kubelet on nodes on read-only unsecure port 10255(default). heapster pod is started with :
/usr/bin/heapster --source=kubernetes:https://kubernetes.default?kubeletPort=10250&kubeletHttps=true

but this is not working in our setup, as the kubelet https tls certs are issued for hostname/wildcard SANs only, without the ip (same cert/key pair for all the nodes in the cluster).

heapster error log:
"failed to get stats from kubelet url: https://x.x.x.x:10250/stats/kube-system/heapster-hf1r6/6c239dc7-fa38-11e5-beb3-fa163e85c82f/heapster - Get https://x.x.x.x:10250/stats/kube-system/heapster-hf1r6/6c239dc7-fa38-11e5-beb3-fa163e85c82f/heapster: x509: certificate is valid for 127.0.0.1, not x.x.x.x"

i'm able to gather the stats with in the heapster container by curl'ing the same url with ip replaced with node.spec.externalId(hostname)

So, the question here is, can heapster kubelet source use node hostname instead of node IP for getting kubelet metrics ? this will help setups using wildcard tls sans cert for kubelet server.

**Comment by piosz** [comment]
cc @mwielgus

**Comment by ravilr** [comment]
xref https://github.com/kubernetes/kubernetes/issues/12968

**Comment by jimmidyson** [comment]
Looks like `ExternalID` is deprecated (see https://github.com/kubernetes/kubernetes/blob/master/pkg/api/v1/types.go#L2312-L2314) so I don't think heapster should support this. Going to close this, but we can reopen it if we need more discussion on it.

**Comment by piosz** [comment]
I agree with @jimmidyson.
