### ISSUE TITLE
Data retention in influxDB for 5 days

### ISSUE THREAD

**Issue by Malmee** [kubernetes/heapster#1122]
I want to find the idle containers in a Kubernetes cluster and I have used Heapster for this purpose. I want to examine the resource details of the containers for a number of days and detect the idle containers. 
But heapster model gives history only up to 15 minutes and I want to know whether influxDB deletes history before 15 minutes and is there anyway to get history upto 5 days. Is using 'retention policy in influxDB' support in storing data up to 5 days and is that policy implemented by now? 

I have tried adding the flag "-model_resolution" and making it more than 30s, but the flag can not be set in yaml file as it gives errors when installing the replication controller of heapster. 

Then I have tried adding "start=X&end=Y" to the end of the API endpoint, but it gives the same response that gives without adding that part. 

I want to get 5 days old history of the containers.

**Comment by Malmee** [comment]
The data retention Policy can be updated by moving to the influxDB-grafana pod and altering the retention policy.

**Comment by RobbieXie** [comment]
@Malmee Hi , I am using the heapster API to get performance data of my K8S. I find it only stores 15mins data and i want to know how can i get more data through api, like 1d 's data or 7 days' data.
