### ISSUE TITLE
Having trouble configuring heapster with TLS API

### ISSUE THREAD

**Issue by mogthesprog** [kubernetes/heapster#1125]
Hi Guys,

I'm having trouble authenticating heapster/grafana/influx with my kubernetes API which is running securely. 

Any guidance or docs for doing this would be great, could someone point me in the right direction?

Cheers,

Morgan

**Comment by DirectXMan12** [comment]
as in "Kube system components can't talk to Heapster" or "Heapster can't talk to Kubelet"?

**Comment by mogthesprog** [comment]
Hey, we can close this.

I think there was an issue with the secrets/serviceaccounts in my kubernetes instance. I recreated both of the above and it seemed to work fine. I have a different error now (configuring LDAP Auth). If i have no further joy with it tomorrow i'll raise another ticket.

Cheers
