### ISSUE TITLE
cpu/usage_rate calculator was confused  when container exited and restarted

### ISSUE THREAD

**Issue by lxb31** [kubernetes/heapster#1126]
heapster version: v1.0.2
kubernetes version: v1.1.7
docker version: 1.8.3
os: centos 7.1

When the container of pod exited and restarted, this container was actually replaced by another container, so the cumulative cpu usage **would be reset**. 

see the source code below, from `metrics/processors/rate_calculator.go`

```
 newVal := 1000 * (metricValNew.IntValue - metricValOld.IntValue) /
     (newMs.ScrapeTime.UnixNano() - oldMs.ScrapeTime.UnixNano())
```

in this case, the `metricValNew`  may be less than `metricValOld`, then the result `newVal`  will be negative value.

what's worse,  the kubernetes `Horizontal Pod Autoscaler` will gain a **big value** for cpu usage rate  from heapster API, e.g.   

```
 {
    "timestamp": "2016-04-12T09:56:30Z",
    "value": 18446744073709526456
  },
```

and thus it will scale to exhaust the max number of pods.

Maybe some tricks will make sense here, e.g.

```
if newVal < 0 {
 newVal = 1000 * (metricValNew.IntValue - 0) /
     (newMs.ScrapeTime.UnixNano() - oldMs.ScrapeTime.UnixNano())
}
```

**Comment by fuliangliu** [comment]
No reply !?

**Comment by mwielgus** [comment]
Sorry, I was on vacation. Will take a look soon.

**Comment by DirectXMan12** [comment]
We've fixed this a couple times.  This particular issue should be fixed.
