### ISSUE TITLE
Make Heapster work with CoreOS

### ISSUE THREAD

**Issue by davidopp** [kubernetes/heapster#1132]
@vishh said support was dropped when it was refactored/improved

**Comment by mwielgus** [comment]
Yes, we dropped support for non-Kubernetes deployments.

**Comment by davidopp** [comment]
What do you mean "non-Kubernetes"? Kubernetes runs on CoreOS.

**Comment by davidopp** [comment]
Sorry, I was confused. I thought Heapster now doesn't work with Kubernetes on CoreOS. But actually, what doesn't work is Heapster without Kubernetes (on CoreOS). I never knew that ever worked. I was not suggesting we should revive that functionality. Sorry for the confusion.

**Comment by davidopp** [comment]
(Thanks to @mwielgus for setting me straight.)
