### ISSUE TITLE
node metrics do not include node labels

### ISSUE THREAD

**Issue by moserke** [kubernetes/heapster#1133]
I have poked around looking for where this happens but haven't found it yet.  Seems like metrics with type node don't have the custom labels on a node object don't get set.  For pods/containers the labels get shown.

This may be a duplicate, but couldn't find one.

**Comment by andyxning** [comment]
+1, any details about this?

**Comment by raliste** [comment]
+1

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
