### ISSUE TITLE
Run Heapster tests on Kubernetes 1.2

### ISSUE THREAD

**Issue by piosz** [kubernetes/heapster#1134]
Currently we do it only for Kubernetes 1.0.7

**Comment by euprogramador** [comment]
i am running heapster in kubernetes 1.3.0.Alpha.2 is working

**Comment by piosz** [comment]
Which version of Heapster do you run @euprogramador? Released one like `v1.1.0-beta1`, `v1.0.2` or from HEAD?

**Comment by euprogramador** [comment]
heapster:canary image it is?
