### ISSUE TITLE
failed to start the heapster

### ISSUE THREAD

**Issue by anzhsoft** [kubernetes/heapster#1140]
I tried to enable the cluster addons these days, but i failed to start the heapster. Anyone can help?
`
![image](https://cloud.githubusercontent.com/assets/6193857/14777866/6254e06e-0b02-11e6-8509-b1de4aa1bd24.png)
`

**Comment by anzhsoft** [comment]
I just got the error message from kube desribe pods"
	Warning	FailedSync	Error syncing pod, skipping: [failed to "StartContainer" for "heapster" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=heapster pod=heapster-v1.1.0.beta1-3608176707-edbv4_kube-system(9efc4773-054b-11e6-9624-6c92bf139d06)"
, failed to "StartContainer" for "eventer" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=eventer pod=heapster-v1.1.0.beta1-3608176707-edbv4_kube-system(9efc4773-054b-11e6-9624-6c92bf139d06)"
, failed to "StartContainer" for "heapster-nanny" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=heapster-nanny pod=heapster-v1.1.0.beta1-3608176707-edbv4_kube-system(9efc4773-054b-11e6-9624-6c92bf139d06)"
, failed to "StartContainer" for "eventer-nanny" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=eventer-nanny pod=heapster-v1.1.0.beta1-3608176707-edbv4_kube-system(9efc4773-054b-11e6-9624-6c92bf139d06)"

So are there any other detailed information to debug this issue , and the kubelet log appears same as the kubectl describe pods' output.
@zhouhaibing089

**Comment by dangzhiqiang** [comment]
How to fix it?
