### ISSUE TITLE
Heapster does not store the kubernetes data

### ISSUE THREAD

**Issue by Alpanakabra** [kubernetes/heapster#1149]
Hi

I have heapster canary version
heapster           heapster       kubernetes/heapster:canary                           k8s-app=heapster,version=v6   1          1d
influxdb-grafana   influxdb       kubernetes/heapster_influxdb:v0.5                    name=influxGrafana            1          1d
                   grafana        kubernetes/heapster_grafana:v2.1.0

i am able to get the kubernetes dat to be store in influx DB.

it does not return anything back

Query: 
SHOW TAG VALUES FROM "measurement_name" WITH KEY = "tag_key"
Query Templates 
Success! (no results to display)

Also when i run the 
 https://10.31.226.96:6443/api/v1/proxy/namespaces/kube-system/services/heapster

it gives me page not found 404 error

kindly help.. Thanks in advance

**Comment by piosz** [comment]
Could you please try to do what @mwielgus wrote in https://github.com/kubernetes/heapster/issues/1154#issuecomment-226475676. Also please use a stable version of Heapster.

**Comment by DirectXMan12** [comment]
closing due to no response
