### ISSUE TITLE
Need support for DiskIO stats 

### ISSUE THREAD

**Issue by shilpamayanna** [kubernetes/heapster#1155]
Currently there is no support for DiskIO stats in heapster.

**Comment by piosz** [comment]
This is not tracked by Kubelet/cadvisor so we can't do it easily in Heapster.

@dchen1107 @timstclair @vishh is there any plan to track such metrics on Kubelet side?

**Comment by timstclair** [comment]
These actually are collected by cAdvisor (https://github.com/google/cadvisor/blob/b4f1d7b82f87459070b58052b71ac4524a4344c3/info/v1/container.go#L301), but not surfaced in the summary API since heapster wasn't using them. If we want to include them in heapster, we could add them to the summary.

**Comment by vishh** [comment]
+1 for adding it to the summary API. We need to expose it in a more user
friendly fashion than what cAdvisor does though.

**Comment by piosz** [comment]
Ups, sorry @timstclair for the confusion.

**Comment by DirectXMan12** [comment]
diskio work is partially completed and being tracked elsewhere.  closing
