### ISSUE TITLE
Network stats is not reported for all interfaces.

### ISSUE THREAD

**Issue by shilpamayanna** [kubernetes/heapster#1156]
There is no support to get network stats for all interfaces in a container
though Kubelet reports stats for all interfaces.

GET http://localhost:10255/stats/container
"network": {
      "name": "enp0s3",
      "rx_bytes": 80665997,
      "rx_packets": 104916,
      "rx_errors": 0,
      "rx_dropped": 0,
      "tx_bytes": 3159664,
      "tx_packets": 48017,
      "tx_errors": 0,
      "tx_dropped": 0,
      "interfaces": [
       {
        "name": "enp0s3",
        "rx_bytes": 80665997,
        "rx_packets": 104916,
        "rx_errors": 0,
        "rx_dropped": 0,
        "tx_bytes": 3159664,
        "tx_packets": 48017,
        "tx_errors": 0,
        "tx_dropped": 0
       },
       {
        "name": "enp0s8",
        "rx_bytes": 964194215,
        "rx_packets": 7042748,
        "rx_errors": 0,
        "rx_dropped": 0,
        "tx_bytes": 835608927,
        "tx_packets": 6579475,
        "tx_errors": 0,
        "tx_dropped": 0
       },
       {
        "name": "mgmt0",
        "rx_bytes": 844010537,
        "rx_packets": 6845397,
        "rx_errors": 0,
        "rx_dropped": 0,
        "tx_bytes": 797713219,
        "tx_packets": 6554539,
        "tx_errors": 0,
        "tx_dropped": 0
       }

**Comment by piosz** [comment]
We'd be more than happy to accept the contribution. Please contact me or @mwielgus before starting the work.

**Comment by shilpamayanna** [comment]
@piosz I would like to contribute for this issue.

**Comment by CBR09** [comment]
Hi, any workaround for that?. It will useful to me.

**Comment by DirectXMan12** [comment]
Fixed by #1788
