### ISSUE TITLE
Heapster send metrics for zabbix

### ISSUE THREAD

**Issue by euprogramador** [kubernetes/heapster#1162]
grafana and influxdb is very good but lack a notification system in case of failures in the cluster, zabbix have reporting/alert mechanisms in case of failure, and a very powerful system monitoring therefore suggest its use as heapster data backend

**Comment by piosz** [comment]
contribution is welcome

**Comment by xiaoping378** [comment]
@euprogramador 
maybe Prometheus is right for you.

**Comment by GrigorievNick** [comment]
https://github.com/indigo-dc/Monitoring/blob/master/doc/heapster.md
i use this tools for such purposes. But i install it separately on every k8s node with zabix agent. is some one can help me with DaemonSet it will be perfect. I just do not have enough time.

**Comment by GrigorievNick** [comment]
https://github.com/indigo-dc/Monitoring/blob/master/doc/heapster.md
I use this tools for such purposes, but i'am install it separately(outside) from k8s service.
On every k8s node with zabix agent. If some one have time build daemon set over it, it will be great.
