### ISSUE TITLE
Odd behavior for CPU usage numbers

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/heapster#1168]
I noticed some odd behavior with the CPU usage metric (it may apply to other metrics, but CPU usage is where I noticed and reproduced it).  With the help of some logging, I've noticed that for pods/containers, two different CPU usage numbers seem to come in from the kubelet (both in the "normal" kubelet source and the "summary" source).  Which number is recorded seems to depend mainly on what ordering the two different numbers arrive in from the kubelet (whichever number is listed second is used).

For instance, running a resource consumer pod set to 300 millicores, if I query Heapster for the `cpu/usage` for the "resource-consumer" container in the appropriate resource consumer pod, I get something that looks like this:

```json
{
  "metrics": [
   {
    "timestamp": "2016-05-17T18:47:00Z",
    "value": 1558277775682
   },
   {
    "timestamp": "2016-05-17T18:47:30Z",
    "value": 1565197346187
   },
   {
    "timestamp": "2016-05-17T18:48:00Z",
    "value": 1575614382048
   },
   {
    "timestamp": "2016-05-17T18:48:30Z",
    "value": 1582561234362
   },
   {
    "timestamp": "2016-05-17T18:49:00Z",
    "value": 268925
   }
  ],
  "latestTimestamp": "2016-05-17T18:49:00Z"
 }
```

You can see most of the numbers here are the cumulative CPU usage as normal, but there's that one value which seems out of place.  The small value never seems to change for a given pod (although it's different across different pods).

If you get multiple of those in a row at the right time, you'll get 0 values in `cpu/usage_rate`, even though the cAdvisor UI shows the appropriate 300 millicore usage value.  Additionally, depending on where those results show up, this can cause overflow in the `cpu/usage_rate` field, since it might show a negative usage (causing *really* large numbers to appear in `cpu/usage_rate`).

Any ideas as to what might be causing this?

**Comment by DirectXMan12** [comment]
kubernetes: kubernetes/kubernetes@3f2fe8b5b87e233a161830ce67b9d9d012e6b288
heapster: kubernetes/heapster@a543cfde8d9ff7abb413ba97627d0ef30c1ac53b

**Comment by DirectXMan12** [comment]
cc @onorua

**Comment by DirectXMan12** [comment]
cc @piosz @mwielgus

At the moment, I'm not entirely sure if this is a Heapster issue or a node issue, although I didn't notice it with the older version of Heapster, which seems to suggest it's at least partially a Heapster issue.

**Comment by piosz** [comment]
Thanks for reporting!

Which data source do you use: cadvisor or summary? Currently exactly one of the sources should be used in Heapster. Also could you please share some logs from Heapster? Did you see there:
```
Summary not found, using fallback
```

Anyway if you can see different values in cadvisor and summary Kubelet endpoints it seems to be a huge problem. Did you have a chance to query kubelet directly for both endpoint and see that the responses differ?

cc @timstclair @dchen1107 @fgrzadkowski

**Comment by DirectXMan12** [comment]
IIRC, I saw it using both the summary and the normal one.  I'll double check this afternoon.  I recall that when I added in extra logging, I saw heapster thinking it had received two different entries, and was just using the first of the two (which sometimes happened to be the correct values, sometimes the weird value described above).  I'll do a bit of digging this afternoon.

**Comment by piosz** [comment]
closing in favor of https://github.com/kubernetes/kubernetes/issues/27194

**Comment by ichekrygin** [comment]
Hi guys, this appears to be still happening in `v1.3.5`

**Comment by ichekrygin** [comment]
per comments in https://github.com/kubernetes/kubernetes/issues/27194#issuecomment-240874347 this could be an issue on the heapster side

**Comment by dchen1107** [comment]
I opened https://github.com/kubernetes/kubernetes/issues/30939 with more debugging detail from @ichekrygin. We need to address the issue. Thanks!

**Comment by piosz** [comment]
It turned out to be an issue on OS level. Closing in favor of https://github.com/kubernetes/kubernetes/issues/30939
