### ISSUE TITLE
Add Kubernetes object metrics

### ISSUE THREAD

**Issue by titilambert** [kubernetes/heapster#1174]
Hello,

I would like to get metrics from Kubernetes objects: Deployment, ReplicatSet, ReplicationController, DaemonSet, ...
For example, with ReplicatSets, we have 3 possibles metrics:
 * Desired pod number
 * Current pod number
 * Object Age (maybe this one is useless)
```
NAMESPACE     NAME                              DESIRED   CURRENT   AGE
kube-system   heapster-1041324418               1         1         10d
kube-system   influxdb-grafana-4280995660       1         1         10d
kube-system   kube-dns-3506884991               1         1         10d
kube-system   kubernetes-dashboard-650110457    0         0         8d
kube-system   kubernetes-dashboard-740746746    0         0         7d
kube-system   kubernetes-dashboard-922019324    6         6         6d
```

The use case is to keep an history (in influxdb) of scaling for each object and graph it in Grafana.
We can also create alarm (with Kapacitor or other) if `Desired` and `Current` values stay unequal too long.

What do you think to add a new subsource to Kubernetes  (like `summary_api`) to grab these metrics ?
Do you see other metrics which could be grabbed ?

**Comment by vishh** [comment]
Have you looked at [kube-state-metrics](https://github.com/kubernetes/kube-state-metrics) project?

**Comment by djsly** [comment]
Thanks @vishh for the pointer! and @ghodss great work on https://github.com/kubernetes/kube-state-metrics. 

I was wondering if there were any reasons to keep those projects separated ? Would it make sense to have the state metrics also handled by heapster ?

**Comment by ghodss** [comment]
@djsly Great question. So great, in fact, I created a PR against the kube-state-metrics README to help explain the difference. Please take a look and let me know if that makes sense. https://github.com/kubernetes/kube-state-metrics/pull/2

I'm planning to add DaemonSet support shortly, but ReplicaSet and ReplicationController support is a good idea as well.

**Comment by djsly** [comment]
@ghodss  Thanks for the explanation! While this all make sense, I  am still trying to see if it wouldn't be beneficial for Hipster to also gather the metrics from the API Server (it already connects to it to gather the node list) and allow the state data to be kept inside influxDB out of the box. 

@titilambert has already create the necessary code change and the associated dashboards in grafana. A PR should come in early next week. It comes with supports for deployment / replicaSet / DaemonSet / and other

@vishh @ghodss Are you ok for a review once it is available ?

**Comment by vishh** [comment]
cc @mwielgus

**Comment by piosz** [comment]
cc @fgrzadkowski @jszczepkowski

**Comment by titilambert** [comment]
The PR is ready ! (tests OK)

**Comment by piosz** [comment]
cc @davidopp

**Comment by piosz** [comment]
@titilambert thanks for the contribution. We do have code freeze for 1.3 right now, so the PR has to be suspend for a week or two. Apologies for that. We will back to it as soon as we release Heapster for Kubernetes 1.3 (hopefully early next week).

**Comment by titilambert** [comment]
@piosz Hello, I just rebased the PR #1176. Waiting for feedback

**Comment by piosz** [comment]
@titilambert thanks for the idea. Sorry for the delay, we need to think a bit about the scope of Heapster project. I'll keep you updated soon.

@davidopp @fgrzadkowski

**Comment by titilambert** [comment]
@piosz Any news about the Heapster scope ?

**Comment by titilambert** [comment]
@davidopp @fgrzadkowski Any news about the issue ?

**Comment by djsly** [comment]
@vishh @piosz @ghodss 
Would anyone be ok to give an update on this topic ?
We would like to not diverge to far from the official hipster releases and with the following PR thats unmerged, its making it a bit hard to handle those local build and merge .

https://github.com/kubernetes/heapster/issues/1176

Thanks and sorry for the trouble.

**Comment by piosz** [comment]
@titilambert @djsly I'm really sorry about the delay. I was on vacation and then on business trip.

We definitely want to support collecting Kubernetes objects related metrics. We'd like to have MVP for 1.5. Unfortunately the scope of the project and especially the design hasn't been discussed yet, so it's not clear whether Heapster should or should not be involved into the pipeline. Because of that there is no much sense to accept the PR right now, because we'd like to avoid situation when we will have to roll it back in the next Heapster release or support legacy functionality.

The discussions on the mentioned project should occur in September, I'm happy to include you guys into it, especially taking into account the fact that you have already some experience with it.

Once again apologies for the delay.

**Comment by djsly** [comment]
sure no problem. Please include us in the discussions that would be greatly appreciated. Could you pinpoint me to the meaning of MPV ? is that a new project ?

In the mean time we will keep collecting what we beleive are important metrics from the kubernetes apiserver. 

Regards,

**Comment by ghodss** [comment]
@piosz I'd love to be in the discussions as well so I can know whether to continue development on kube-state-metrics.

**Comment by ghodss** [comment]
@piosz I haven't heard any further discussion about this topic - is there a SIG managing it?

**Comment by bgrant0607** [comment]
@ghodss 

https://github.com/kubernetes/community/blob/master/sig-instrumentation/README.md
