### ISSUE TITLE
Switch to GCM v3 API

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#1175]
Heapster currently uses [`v2beta2`](https://github.com/kubernetes/heapster/blob/master/metrics/sinks/gcm/gcm.go#L30) API of GCM. This API has been officially deprecated. We need to switch to `v3`.

**Comment by vishh** [comment]
https://cloud.google.com/monitoring/api/ref_v3/rest/

**Comment by activars** [comment]
@vishh Will this enable Heapter writing custom metrics from a kube cluster running outside GCE?

**Comment by vishh** [comment]
That will require some changes to how auth is handled.

**Comment by piosz** [comment]
@activars we don't plan to do it soon, but feel free to contribute or at least create an issue, so maybe someone else will do it.

cc @mwielgus

**Comment by piosz** [comment]
This is fixed.
