### ISSUE TITLE
Heapster API not returning correct number of values at higher resolution

### ISSUE THREAD

**Issue by hasbro17** [kubernetes/heapster#1177]
### Environment
I am running a 5 node(each m3.medium) k8s cluster on AWS with a 1 replica nginx server deployment as my test case.
My custom Heapster replication controller just has a 1 container pod replica with the `image: kubernetes/heapster:canary` and the resolution set to 10s via `-metric_resolution=10s`
I am querying the Heapster API from outside the cluster via the kubectl proxy for this experiment.
I have attached my custom-heapster's replication controller and service yaml files for reference.
[heapster-controller.yaml.txt](https://github.com/kubernetes/heapster/files/291979/heapster-controller.yaml.txt)
[heapster-service.yaml.txt](https://github.com/kubernetes/heapster/files/291978/heapster-service.yaml.txt)

Also attached is my cluster.yaml file generated from setting up the cluster via [kube-aws](https://coreos.com/kubernetes/docs/latest/kubernetes-on-aws.html)
[AWS-cluster.yaml.txt](https://github.com/kubernetes/heapster/files/291982/AWS-cluster.yaml.txt)

```
NAMESPACE       NAME                                                              READY     STATUS    RESTARTS   AGE       NODE
calico-system   calico-policy-agent-ip-10-0-0-50.us-west-1.compute.internal       2/2       Running   0          6d        ip-10-0-0-50.us-west-1.compute.internal
default         my-nginx-3800858182-cgh9i                                         1/1       Running   0          12h       ip-10-0-0-98.us-west-1.compute.internal
kube-system     heapster-custom-z4kdm                                             1/1       Running   0          3d        ip-10-0-0-98.us-west-1.compute.internal
kube-system     heapster-v1.0.2-743892168-57uf2                                   2/2       Running   0          6d        ip-10-0-0-96.us-west-1.compute.internal
kube-system     kube-apiserver-ip-10-0-0-50.us-west-1.compute.internal            1/1       Running   0          6d        ip-10-0-0-50.us-west-1.compute.internal
kube-system     kube-controller-manager-ip-10-0-0-50.us-west-1.compute.internal   1/1       Running   1          6d        ip-10-0-0-50.us-west-1.compute.internal
kube-system     kube-dns-v11-e82ff                                                4/4       Running   0          6d        ip-10-0-0-99.us-west-1.compute.internal
kube-system     kube-proxy-ip-10-0-0-50.us-west-1.compute.internal                1/1       Running   0          6d        ip-10-0-0-50.us-west-1.compute.internal
kube-system     kube-proxy-ip-10-0-0-96.us-west-1.compute.internal                1/1       Running   0          6d        ip-10-0-0-96.us-west-1.compute.internal
kube-system     kube-proxy-ip-10-0-0-97.us-west-1.compute.internal                1/1       Running   0          6d        ip-10-0-0-97.us-west-1.compute.internal
kube-system     kube-proxy-ip-10-0-0-98.us-west-1.compute.internal                1/1       Running   0          6d        ip-10-0-0-98.us-west-1.compute.internal
kube-system     kube-proxy-ip-10-0-0-99.us-west-1.compute.internal                1/1       Running   0          6d        ip-10-0-0-99.us-west-1.compute.internal
kube-system     kube-scheduler-ip-10-0-0-50.us-west-1.compute.internal            1/1       Running   0          6d        ip-10-0-0-50.us-west-1.compute.internal
kube-system     kubedash-3370066188-bowsi                                         2/2       Running   0          2d        ip-10-0-0-97.us-west-1.compute.internal
```

### Problem
On querying the Heapster API I am not getting the correct number and value of data point (Timestamp, Value) pairs for some specific metrics.

Querying any metric for an interval of 5 minutes over a resolution of 10 seconds should return 29 or 30 data point pairs. For the cluster wide metrics such as `cpu/usage_rate` or `memory/usage` this is working fine. I have not posted the raw response to keep it brief but you can see that there are 29 values and I've verified that their timestamps are also fine according to the 10s resolution:
```
Request: http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/heapster-custom/api/v1/model/metrics/cpu/usage_rate?start=2016-05-31T11:14:21-07:00&end=2016-05-31T11:19:21-07:00

Response:
cpu/usage_rate: [115 255 362 156 134 87 197 372 136 187 313 258 166 179 124 219 338 142 248 318 103 192 429 90 75 362 267 196 275]
```
Now doing the same for any node specific metric gives me a problem. So for `cpu/node_utilization` I get only 9-10 data points at max, even for an interval duration of 15 minutes. I’ve posted the raw and formatted response so you can see the timestamps as well

```
Request: http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/heapster-custom/api/v1/model/nodes/ip-10-0-0-96.us-west-1.compute.internal/metrics/cpu/node_utilization?start=2016-05-31T11:14:21-07:00&end=2016-05-31T11:19:21-07:00

Response:
 {
  "metrics": [
   {
    "timestamp": "2016-05-31T18:17:00Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:17:10Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:17:20Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:17:40Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:18:00Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:18:10Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:18:30Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:18:40Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:18:50Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:19:10Z",
    "value": 0
   }
  ],
  "latestTimestamp": "2016-05-31T18:19:10Z"
 }

ip-10-0-0-96.us-west-1.compute.internal: [0 0 0 0 0 0 0 0 0 0]
```
As you can see there are only 9 data points returned. Moreover all of them are 0. This happens for all the nodes and also for `memory/node_utilization`. This cannot be the case since the cluster wide cpu and node utilization are clearly not zero.

I am also seeing some erratic behavior for the pod metrics as the values returned are right but they are fewer than the expected amount. So in this case for cpu/usage_rate I get 21 data points instead of 29. The values are correct since my nginx pod has no load on it currently but you can see from the timestamps that some values have been skipped such as the jump from `2016-05-31T18:15:20Z` to `2016-05-31T18:15:50Z`. 
```
Request:
http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/heapster-custom/api/v1/model/namespaces/default/pods/my-nginx-3800858182-cgh9i/metrics/cpu/usage_rate?start=2016-05-31T11:14:21-07:00&end=2016-05-31T11:19:21-07:00

Response:
 {
  "metrics": [
   {
    "timestamp": "2016-05-31T18:14:40Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:14:50Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:15:00Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:15:10Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:15:20Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:15:50Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:16:00Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:16:20Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:16:30Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:16:50Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:17:00Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:17:10Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:17:20Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:17:30Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:17:40Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:18:20Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:18:30Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:18:40Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:18:50Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:19:00Z",
    "value": 0
   },
   {
    "timestamp": "2016-05-31T18:19:10Z",
    "value": 0
   }
  ],
  "latestTimestamp": "2016-05-31T18:19:10Z"
 }

my-nginx-3800858182-cgh9i: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
```

I am not sure if the higher resolution is the problem since it seems to be working fine for cluster wide metrics. Any idea on how I might debug this?

**Comment by piosz** [comment]
By default cadvisor collect metrics every 10s so it's expected that metrics will be missed for pods when Heapster metrics_resolution is set to 10s. On the other hand aggregation across cluster requires at least one collected metric for some pod which is usually true.

In general if you are using default Kubelet setup you shouldn't decrease the the value of metrics_resolution. If you need to do it you should also change flag housekeeping_interval in Kubelet, but there is no guarantee it would work.

**Comment by DreadPirateShawn** [comment]
Also relevant to this topic, for posterity:

https://bugzilla.redhat.com/show_bug.cgi?id=1421834

> In Kubernetes, we specify a cAdvisor housekeeping interval of 10s.  cAdvisor has backoff logic that could move this up to 15s, plus jitter logic that could double that, leaving us with an actual max housekeeping interval of 30s:
> 
> https://github.com/kubernetes/kubernetes/blob/master/vendor/github.com/google/cadvisor/manager/container.go#L382.
> 
> Thus, our Heapster image needs to have a metrics_resolution of at least 30s
> in order to avoid reading the same metrics batch twice from the node, which causes Heapster to skip rate calculation, which causes CPU metrics to not appear.
