### ISSUE TITLE
Heapster pod fails to start

### ISSUE THREAD

**Issue by jesucarr** [kubernetes/heapster#1189]
When creating using the yml at deploy/kube-config/google:

```
kubectl create -f ./heapster/
replicationcontroller "heapster" created
Error from server: error when creating "heapster/heapster-service.yml": services "heapster" already exists
```

The pod in the rc fails to start, with this log message:

```
flag provided but not defined: -poll_duration
Usage of /heapster:
....
```

Also note that I had the service heapster already running. Is that now included by default in GKE?

**Comment by chrislovecnm** [comment]
@jesucarr heapster is deployed in gke if monitoring is enabled.

**Comment by piosz** [comment]
As @chrislovecnm noticed heapster service already exists in GKE. Regarding problem with rc I need to update configuration files. In the meantime try to use [this one](https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/google/heapster-controller.yaml) though you have to get rid off jinja markdowns. Also if you will run another Heapster instance on GKE with the same label set heapster service will redirect queries to both instances in a random way. If you want to play with Heapster on GKE you should create/update a cluster to have monitoring disabled.
