### ISSUE TITLE
Wrong CPU usage_rate and node_utilization, plus no filesystem metrics

### ISSUE THREAD

**Issue by stefanodoni** [kubernetes/heapster#1193]
Hi, 

Heapster is returning wrong values regarding pod CPU usage rate and node_utilization is constantly 0.

This is the cpu usage rate of a pod which contains the stress command consuming 1 CPU:

$ curl 'http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/heapster:/api/v1/model/namespaces/default/pods/stress-3-2693030825-any3s/metrics/cpu/usage_rate'
{
  "metrics": [
   {
    "timestamp": "2016-06-16T09:52:00Z",
    "value": 0
   },
   {
    "timestamp": "2016-06-16T09:53:00Z",
    "value": 2051
   },
   {
    "timestamp": "2016-06-16T09:54:00Z",
    "value": 999
   },
   {
    "timestamp": "2016-06-16T09:55:00Z",
    "value": 18446744073709548330
   },
   {
    "timestamp": "2016-06-16T09:56:00Z",
    "value": 4809
   }

As the pod is burning 1 CPU, Heapster should return a constant 1000 value, but this is far from true. I have verified that the actual container CPU usage is correct by means of docker stats:

CONTAINER           CPU %               MEM USAGE / LIMIT     MEM %               NET I/O             BLOCK I/O
0b148363add2        99.30%              163.8 kB / 4.072 GB   0.00%               0 B / 0 B           0 B / 0 B

As a consequence, Grafana and InfluxDB contains wrong values too. 

Conversely, I noticed that host cpu utilization is correct - in this case the node was running tree stress containers:

$ curl 'http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/heapster:/api/v1/model/nodes/192.168.200.177/metrics/cpu/usage_rate'
{
  "metrics": [
   {
    "timestamp": "2016-06-16T09:54:00Z",
    "value": 3044
   },
   {
    "timestamp": "2016-06-16T09:55:00Z",
    "value": 3043
   },
   {
    "timestamp": "2016-06-16T09:56:00Z",
    "value": 3044
   },
   {
    "timestamp": "2016-06-16T09:57:00Z",
    "value": 3042
   }

However, the metric node_utilization is always 0:

$ curl 'http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/heapster:/api/v1/model/nodes/192.168.200.177/metrics/cpu/node_utilization'
{
  "metrics": [
   {
    "timestamp": "2016-06-16T12:40:00Z",
    "value": 0
   },
   {
    "timestamp": "2016-06-16T12:41:00Z",
    "value": 0
   },
   {
    "timestamp": "2016-06-16T12:42:00Z",
    "value": 0
   }
  ],

Furthermore, I can see filesystem size and usage metrics within InfluxDB database, however they are not being reported by the Heapster API. Is that intended? Is there any plan to export them?

Please let me know if you need any further info.
Thank you!

Cluster info:
k8s cluster created using kube-deploy (docker-multinode) then added heapster using the yaml found in k8s 1.2.4 release tarballs.
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.4", GitCommit:"3eed1e3be6848b877ff80a93da3785d9034d0a4f", GitTreeState:"clean"}

**Comment by piosz** [comment]
known problem: https://github.com/kubernetes/kubernetes/issues/27194

**Comment by stefanodoni** [comment]
Great,
Thanks!

What about the other questions:

1) node_utilization always 0: is that related to the bug?
2) no filesystem metrics available in Heapster API (but available in InfluxDB)?

**Comment by mwielgus** [comment]
1. Node utilization is calculated based on pod cpu metrics. If they are 0 then the utilization will also be 0.
2. Yes, that is correct. We don't support labeled metrics in the api as no client needed it before. Contributions are welcome :).
