### ISSUE TITLE
Expose access to ElasticSearch client options

### ISSUE THREAD

**Issue by jamiehannaford** [kubernetes/heapster#1196]
I'm running Heapster in a Kubernetes pod and using an external ELK cluster for the sink. When the ElasticSearch driver loads, it creates the ElasticSearch client which performs a [startup health check](https://github.com/kubernetes/heapster/blob/master/vendor/github.com/olivere/elastic/client.go#L817). Unfortunately my cluster responds slowly (due to network latency I'm guessing) which is causing the initial check to fail. The client, however, allows you to bump the [timeout](https://github.com/kubernetes/heapster/blob/master/vendor/github.com/olivere/elastic/client.go#L354-L359) and [retry](https://github.com/kubernetes/heapster/blob/master/vendor/github.com/olivere/elastic/client.go#L384-L392) values. You pass these functions in when [creating a client](https://github.com/kubernetes/heapster/blob/master/common/elasticsearch/elasticsearch.go#L109).

When I do this, the initial health check passes and things are fine. My question is: is there any way we can allow users to modify these values? Possibly with environment variables?

**Comment by piosz** [comment]
Not now, but we are open to the contribution. ElasticSearch sink is maintained by community.

cc @huangyuqi @mwielgus @titilambert

**Comment by huangyuqi** [comment]
@jamiehannaford thanks for reporting the issue. ES client has many config items, but in current community version ,we just allow user to config the `endpoints` `secret` `indexname`;   If you want add some other config items for ES client, contributing code for this sink is appreciate.Or contacting me to add this code.
BTW, the interface of Init ES client contains the enable variable of "health check".

**Comment by jamiehannaford** [comment]
@piosz @huangyuqi I'm happy to contribute the code to get this enabled. What would be the best way for the end-user to add ElasticSearch-specific configuration, considering that there are a lot of potential options? 

I could add a few for now to the URL (`?maxRetries=` and `?startupHealthcheckTimeout=`). I notice that [Hawkular](https://github.com/kubernetes/heapster/blob/master/docs/sink-configuration.md#hawkular-metrics) has a lot of configuration values too.

**Comment by piosz** [comment]
@jamiehannaford cool. The URL path is as for now the only possible configuration option. Please agree with @huangyuqi the set of configuration params.

**Comment by huangyuqi** [comment]
@piosz @jamiehannaford  I agree with this way of adding the configuration params. Thanks
