### ISSUE TITLE
Migrate InfluxDB to PetSet

### ISSUE THREAD

**Issue by piosz** [kubernetes/heapster#1197]
cc @fgrzadkowski @jszczepkowski @mwielgus

**Comment by piosz** [comment]
It was done by @jszczepkowski here https://github.com/kubernetes/kubernetes/pull/28109 and then reverted here https://github.com/kubernetes/kubernetes/pull/30080 due to an issue with PetSet implementation.

**Comment by mamoit** [comment]
This would be quite useful.

**Comment by DirectXMan12** [comment]
Heapster is now deprecated.  No new sinks or features will be added.  See https://github.com/kubernetes/heapster/blob/master/docs/deprecation.md#initial-deprecation-kubernetes-111 for more details.
