### ISSUE TITLE
Heapster Container-level Metrics fails to return the list of all available containers under a given pod

### ISSUE THREAD

**Issue by biswars** [kubernetes/heapster#1199]
Ref: [#713](https://github.com/kubernetes/heapster/issues/713#issuecomment-226729033)

This is the is comment from the issue above.

cc: @huangyuqi 

from: @huangyuqi "the version of heapster in the deployment file you use is "1.1.0", it is a refactor version; And the model.md maybe not update.
So, i go to check the code of heapster api, i found the api /api/v1/model/namespaces/{namespace-name}/pods/{pod-name}/containers/ has been removed. Maybe a omission. You can refer the file https://github.com/kubernetes/heapster/blob/master/metrics/api/v1/model_handlers.go#L49-L217
This issue is a bug certainly, in my opinion. Would you bring a new issue to community, copy this comment to there and at me? I am pleasure to fix this."

**Comment by sputnick** [comment]
This seems to be still broken.

**Comment by piosz** [comment]
Closing in favor of #1199. I'm happy to accept a contribution.

**Comment by DirectXMan12** [comment]
@piosz: this is #1199 ;-)

**Comment by piosz** [comment]
Ups! Sorry, I meant #1274
