### ISSUE TITLE
Get Unauthorized Error

### ISSUE THREAD

**Issue by pineking** [kubernetes/heapster#1208]
core@zodiac-04 ~ $ kubectl cluster-info
Kubernetes master is running at https://10.10.10.202
Heapster is running at https://10.10.10.202/api/v1/proxy/namespaces/kube-system/services/heapster
monitoring-grafana is running at https://10.10.10.202/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana

when I acess the link:  https://10.10.10.202/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana from the chrome, chrome shows Unauthorized error.

**Comment by vtuson** [comment]
same issue here

**Comment by vtuson** [comment]
I manage to work around this issue but not accessing grafana via the api proxy, but directly exposing the service. After that I still had to do a few changes.

1) remove env variables influxdb-grafana-controller.yaml
2) expose service as NodePort or LoadBalancer depends of your preference in grafana-service.yaml under spec add:   type: NodePort 
3) Once you do this and deploy the services and replication controller you should be able to access the monitoring-grafana using the ip of your cluster plus the export port. You can see the expose port from kubectl describe service grafana-service
4) login to grafana as admin (admin:admin), select DataSources -> influxdb-datasource and test the connection. The connection is set up as http://monitoring-influxdb:8086, this failed for me. However as influx and grafana are both in the same pod, you can use localhost to access the service. So change the url to http://localhost:8086, save and test the connnection again. This worked for me and a minute later I was getting realtime data from nodes and pods.

**Comment by Parth6288** [comment]
Hi @vtuson , I am also facing the similar issue. Could you please explain in details on how you were able to resolve this. I am new to this and just set up my first Kubernets cluster.
Thanks.

**Comment by DirectXMan12** [comment]
for the API proxy, you would have needed to ensure that system:anonymous had permissions to proxy that service, if you're on a recent version of kube.  Please look at the documentation on the Kubernetes RBAC system.
