### ISSUE TITLE
Source not recognized: cadvisor 

### ISSUE THREAD

**Issue by chbiguereau** [kubernetes/heapster#1215]
Hi All,

I try to run heapster container with cadvisor. I follow [source-configuration](https://github.com/kubernetes/heapster/blob/master/docs/source-configuration.md) documentation. Unfortunately, I get this error:

```
I0715 15:21:47.350183       1 heapster.go:65] /heapster --sink=opentsdb:localhost:4242 --source=cadvisor:external?standalone=localhost
I0715 15:21:47.350242       1 heapster.go:66] Heapster version 1.1.0
F0715 15:21:47.350247       1 heapster.go:78] Failed to create source provide: Source not recognized: cadvisor

```

The [factory.go](https://github.com/kubernetes/heapster/blob/master/events/sources/factory.go) file show only kubernetes source case. Are they any way to run heapster directly on cadvisor ?

**Comment by DirectXMan12** [comment]
the direct cadvisor source hasn't been supported for quite a while.  closing.
