### ISSUE TITLE
pods are empty

### ISSUE THREAD

**Issue by suchisubhra** [kubernetes/heapster#1221]
I do get  machine level metrics..
We have custom namespace and all  pods belong to that namespace.
In namespace drop  down I don't see our namespace.
Only  default  and "kube-system" are there..
Also  there is no  POD which  belongs to kube-system  show up.

Our cadvisor works fine in  port 4194.

~Suchi

**Comment by suchisubhra** [comment]
I also check  
http://master:8080/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/namespaces/

and it is empty....Can somebody help me? where should I start looking

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
