### ISSUE TITLE
Improve integration tests for Metrics API

### ISSUE THREAD

**Issue by piosz** [kubernetes/heapster#1224]
Currently we only test in https://github.com/kubernetes/heapster/blob/master/integration/heapster_api_test.go#L687 querying for metrics from single pod or for single pod. We should add support for:
- all nodes
- all pods
- all pods in a given namespace
- label selector

**Comment by mksalawa** [comment]
#1230 - lacking the test for all pods, which is done in #1231 together with the added handler.
