### ISSUE TITLE
influxdb grafana dashboard query aggregate function error when time range is larger

### ISSUE THREAD

**Issue by andyxning** [kubernetes/heapster#1226]
In our use case, metrics interval is 10s.
When the time range is 3h, everything is right. Time series data is shown in 10s interval. However, when the time range is enlarged to 12h, then according to the [query](https://github.com/kubernetes/heapster/blob/v1.1.0/grafana/dashboards/pods.json#L86):

> "query": "SELECT sum(\"value\") FROM \"cpu/usage_rate\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" =~ /$namespace$/ AND \"pod_name\" =~ /$podname$/ AND $timeFilter GROUP BY time($interval), \"container_name\" fill(null)

The auto decided variable `$interval` will be more than 10s, the least interval we use, then we will sum **all the data between `$interval`**. This may not be what we want. 

What we want is that: we always want the **average** value of metric whatever the time range is. And, also in influxdb 0.13 we can not use some query like this: `avg(sum(cpu/usage_rate))`, so we leverage the [`math` function](https://docs.influxdata.com/influxdb/v0.13/query_language/math_operators/) to calculate the average value like this: `sum(cpu/usage_rate) / count(cpu/usage_rate))`

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
