### ISSUE TITLE
elasticsearch integration heapster basic auth broken

### ISSUE THREAD

**Issue by Thermi** [kubernetes/heapster#1238]
Hello,

It seems like basic auth for elasticsearch is currently broken or does not work as advertised in the description of the PR #733. I'm using heapster v1.1.0.

I'm passing the username and password, together with the node as described in the PR:
`--sink=elasticsearch:?nodes=$THISISMYNODEURL&esUserSecret=$SECRETGOESHERE&esUserName=new-cluster`

Heapster passes the username correctly in the `Authorize` header in the HTTP HEAD request, but not the password. The password field is just left empty. In Wireshark, it looks like this: `Credentials: new-cluster:<nothing>`
The Authorization header looks like this: `Basic bmV3LWNsdXN0ZXI6`.
This causes authentication to fail.

I came to this conclusion by using tcpdump to analyze why heapster could not connect to my proxy and just printed `E0803 04:19:10.629719       1 factory.go:74] Failed to create sink: failed to create ElasticSearch client: no Elasticsearch node available`.

EDIT The problem of lacion in #1211 seems to relate to this malfunction.

**Comment by piosz** [comment]
cc @huangyuqi @AlmogBaku

**Comment by AlmogBaku** [comment]
@Thermi in our config i can see that you are using `EsUserSecret` with capital E....

**Comment by AlmogBaku** [comment]
@Thermi please close this issue, since you were talked about aws
