### ISSUE TITLE
Heapster/monitoring-grafana services removed by kubernetes

### ISSUE THREAD

**Issue by stevedbashton** [kubernetes/heapster#1241]
Hi,
Following the guides on:  https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md

After a ~5 minute period the heapster and monitoring-grafana services are deleted.
Based on the info from: https://github.com/kubernetes/heapster/issues/1185

This is due to having specific  ```kubernetes.io/cluster-service: 'true'```

If i remove this line from grafana-service.yaml and heapster-service.yaml, the heapster dashboard remains available. 

Is this a correct workaround? :)

**Comment by piosz** [comment]
There is [addon updater](https://github.com/kubernetes/kubernetes/tree/master/cluster/saltbase/salt/kube-master-addons), which periodically (every ~5 minutes) checks whether cluster services are up to date. As a side effect it removes all pods with the annotation from kube-system namespace which were not created from manifests.

Removing the annotations is correct workaround. Another option is to run Grafana and Heapster in a different namespace.
