### ISSUE TITLE
Add liveness probe to Heapster

### ISSUE THREAD

**Issue by piosz** [kubernetes/heapster#1251]
http://kubernetes.io/docs/user-guide/liveness/

**Comment by piosz** [comment]
cc @mwielgus @mksalawa

**Comment by mksalawa** [comment]
ref #1271

**Comment by piosz** [comment]
fixed in #1271

**Comment by piosz** [comment]
Liveness probe need to be setup in Kubernetes as well.

**Comment by piosz** [comment]
This is fixed. Thanks @mksalawa
