### ISSUE TITLE
TestFetchAggregations is failing

### ISSUE THREAD

**Issue by piosz** [kubernetes/heapster#1253]
```
--- FAIL: TestFetchAggregations (0.01s)
	Location:	historical_handlers_test.go:1246
	Error:		Not equal: 500 (expected)
			        != 200 (actual)
	Messages:	for test "pod list aggregations with fetch error": status should have been an error status
		
FAIL
FAIL	k8s.io/heapster/metrics/api/v1	0.119s
```
https://k8s-gubernator.appspot.com/build/kubernetes-jenkins/pr-logs/pull/1252/heapster-pull-build-test-e2e/428/

**Comment by piosz** [comment]
cc @mwielgus

**Comment by DirectXMan12** [comment]
I can only repo this with the PR that it comes from, so I think it's actually from there.  I'll take a look, and leave a comment there.

**Comment by piosz** [comment]
You're right. It works on HEAD. Sorry for the confusion!
