### ISSUE TITLE
make build time is too long

### ISSUE THREAD

**Issue by andyxning** [kubernetes/heapster#1256]
Currently, the `build` phase in `Makefile` is 

```
build: clean deps
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go build ./...
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go build -o heapster k8s.io/heapster/metrics
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go build -o eventer k8s.io/heapster/events
```

IMO, 
* the first `go build` command is used to check if the build can be done successfully. However, i think this is useless, as the last two `go build` commands will do this also and when something is wrong, they will exit and stop the build step.
* the first `go build` command can be changed to `go install` which will build all dependencies to `pkg`. Then subsequent `go build` commands will use the pre-compiled dependencies in `pkg`.

So, i am wondering if the first `go build` command can be changed to `go install` which should then make `build` phrase like this:

```
build: clean deps
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go install ./...
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go build -o heapster k8s.io/heapster/metrics
	GOOS=linux GOARCH=amd64 CGO_ENABLED=0 godep go build -o eventer k8s.io/heapster/events
```

At the same time, the `deps` section will always run `go get` even the `godep` is already downloaded. However, `go get` will always run `build and install`. This will utilize more time and will make edit-compile-test consume more time. we can update `deps` phase like this:

```
deps:
      which godep || go get github.com/tools/gode
```

**Comment by piosz** [comment]
fixed in #1257
