### ISSUE TITLE
The config file /etc/kubernetes/kubeconfig/kubeconfig does not exist

### ISSUE THREAD

**Issue by daikaixian** [kubernetes/heapster#1258]
I can't get the heapster pod start.

describe the pod 

`Name:		heapster-yhpir
Namespace:	kube-system
Node:		192.168.0.212/192.168.0.212
Start Time:	Mon, 15 Aug 2016 14:07:54 +0800
Labels:		k8s-app=heapster,version=v6
Status:		Running
IP:		172.17.53.11
Controllers:	ReplicationController/heapster
Containers:
  heapster:
    Container ID:	docker://f830fd3ff867062a9ef6b48356122577887b43e9881a3862f770083da4332438
    Image:		kubernetes/heapster:canary
    Image ID:		docker://sha256:a497588855ad4d47861b1553d6d72a07c8f974d57945db5e9503d35a54372908
    Port:
    Command:
      /heapster
      --source=kubernetes:https://kubernetes.default
      --sink=influxdb:http://monitoring-influxdb:8086
    QoS Tier:
      memory:		BestEffort
      cpu:		BestEffort
    State:		Waiting
      Reason:		CrashLoopBackOff
    Last State:		Terminated
      Reason:		Error
      Exit Code:	1
      Started:		Mon, 15 Aug 2016 14:34:50 +0800
      Finished:		Mon, 15 Aug 2016 14:34:50 +0800
    Ready:		False
    Restart Count:	10
    Environment Variables:
Conditions:
  Type		Status
  Ready 	False
No volumes.
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath			Type		Reason		Message
  ---------	--------	-----	----			-------------			--------	------		-------
  30m		30m		1	{default-scheduler }					Normal		Scheduled	Successfully assigned heapster-yhpir to 192.168.0.212
  29m		29m		1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal		Created		Created container with docker id 0666e23e3c8c
  29m		29m		1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal		Started		Started container with docker id 0666e23e3c8c
  29m		29m		1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal		Created		Created container with docker id e08324e14438
  29m		29m		1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal		Started		Started container with docker id e08324e14438
  29m		29m		2	{kubelet 192.168.0.212}					Warning		FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "heapster" with CrashLoopBackOff: "Back-off 10s restarting failed container=heapster pod=heapster-yhpir_kube-system(9a7d8ce4-62ae-11e6-bba4-448a5b8ccf35)"

  29m	29m	1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Started		Started container with docker id 368bf7d12be9
  29m	29m	1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Created		Created container with docker id 368bf7d12be9
  29m	28m	2	{kubelet 192.168.0.212}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "heapster" with CrashLoopBackOff: "Back-off 20s restarting failed container=heapster pod=heapster-yhpir_kube-system(9a7d8ce4-62ae-11e6-bba4-448a5b8ccf35)"

  28m	28m	1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Created		Created container with docker id ea82eb7e680d
  28m	28m	1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Started		Started container with docker id ea82eb7e680d
  28m	28m	3	{kubelet 192.168.0.212}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "heapster" with CrashLoopBackOff: "Back-off 40s restarting failed container=heapster pod=heapster-yhpir_kube-system(9a7d8ce4-62ae-11e6-bba4-448a5b8ccf35)"

  27m	27m	1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Created		Created container with docker id 7a8e0401bfae
  27m	27m	1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Started		Started container with docker id 7a8e0401bfae
  27m	26m	8	{kubelet 192.168.0.212}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "heapster" with CrashLoopBackOff: "Back-off 1m20s restarting failed container=heapster pod=heapster-yhpir_kube-system(9a7d8ce4-62ae-11e6-bba4-448a5b8ccf35)"

  26m	26m	1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Created		Created container with docker id edf7c0c35a00
  26m	26m	1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Started		Started container with docker id edf7c0c35a00
  26m	23m	15	{kubelet 192.168.0.212}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "heapster" with CrashLoopBackOff: "Back-off 2m40s restarting failed container=heapster pod=heapster-yhpir_kube-system(9a7d8ce4-62ae-11e6-bba4-448a5b8ccf35)"

  23m	23m	1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Created		Created container with docker id eca0acea101c
  23m	23m	1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Started		Started container with docker id eca0acea101c
  18m	18m	1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Started		Started container with docker id 8638da18c05c
  18m	18m	1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Created		Created container with docker id 8638da18c05c
  13m	13m	1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Created		Created container with docker id 79e3b78518ab
  13m	13m	1	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Started		Started container with docker id 79e3b78518ab
  29m	3m	11	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Pulled		Container image "kubernetes/heapster:canary" already present on machine
  8m	3m	2	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Started		(events with common reason combined)
  8m	3m	2	{kubelet 192.168.0.212}	spec.containers{heapster}	Normal	Created		(events with common reason combined)
  23m	11s	109	{kubelet 192.168.0.212}					Warning	FailedSync	Error syncing pod, skipping: failed to "StartContainer" for "heapster" with CrashLoopBackOff: "Back-off 5m0s restarting failed container=heapster pod=heapster-yhpir_kube-system(9a7d8ce4-62ae-11e6-bba4-448a5b8ccf35)"

  29m	11s	139	{kubelet 192.168.0.212}	spec.containers{heapster}	Warning	BackOff	Back-off restarting failed docker container`

kubectl log pod:

`I0815 06:34:50.124080       1 heapster.go:52] /heapster --source=kubernetes:https://kubernetes.default --sink=influxdb:http://monitoring-influxdb:8086
I0815 06:34:50.124115       1 heapster.go:53] Heapster version 0.12.1
E0815 06:34:50.124161       1 heapster.go:59] The config file /etc/kubernetes/kubeconfig/kubeconfig does not exist`

help...

**Comment by 18612116089** [comment]
I had this problem yet. Anyone else can help ?

**Comment by daikaixian** [comment]
@18612116089

it may because you  are using  a older version of heapster.

try to use a newer version.

such as 1.1.0

**Comment by 18612116089** [comment]
@daikaixian 
yes, use v1.1.0 can solve it.
Thanks very much.
