### ISSUE TITLE
Heapster API doesn't work when listing the containers under a pod

### ISSUE THREAD

**Issue by zhuc** [kubernetes/heapster#1274]
When I tried to get the container list of a pod via API, it reports "HTTP 404" error.
The API I tried to access is: 

```
GET http://192.168.1.2:30082/api/v1/model/namespaces/kube-system/pods/heapster-0qiur/containers/
Response:
404: Page Not Found
```

However, when I tried to get the metrics of a container, it works fine.

```
GET http://192.168.1.2:30082/api/v1/model/namespaces/kube-system/pods/heapster-0qiur/containers/heapster/metrics
Response:
[
  "uptime",
  "memory/working_set",
  "memory/limit",
  "cpu/usage",
  "cpu/usage_rate",
  "memory/major_page_faults_rate",
  "cpu/limit",
  "memory/usage",
  "memory/page_faults_rate",
  "memory/page_faults",
  "memory/major_page_faults",
  "cpu/request",
  "memory/request"
 ]
```

```
```

**Comment by zqfan** [comment]
+1, version v1.2.0, k8s v1.4.0

**Comment by hekike** [comment]
Any idea why is it happening? Did you find the solution?

**Comment by zqfan** [comment]
@hekike after read the source code, I think it is limited by k8sclient

**Comment by piosz** [comment]
This is working as intended. Our intend was to not duplicate logic of api server. However if you want add a logic which displays containers from the pod I'm happy to accept the contribution:)

**Comment by piosz** [comment]
@aleksandra-malinowska this is a good initial task in Heapster.
