### ISSUE TITLE
Multi-platform support

### ISSUE THREAD

**Issue by zreigz** [kubernetes/heapster#1280]
Currently there is only amd64 architecture in release repository.  According to this proposal https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/multi-platform.md it would be beneficial to have multi-platform support for heapster. 

Heapster is very important component (used in Dashboard or for Horizontal Pod Autoscaling). Lack of official support for other architectures will limit k8s cluster functionality.

**Comment by zreigz** [comment]
cc @luxas

**Comment by luxas** [comment]
I have scripts already that shows how to cross-compile heapster, grafana and influxdb for all arches here: https://github.com/luxas/kubernetes-on-arm/tree/master/addons/images

ping @kubernetes/heapster-maintainers is this something you'd be willing to merge in v1.2?
I can probably make a PR for that probably, with full backwards compability.
After all, it won't be any functional changes, just release infrastructure changes,

**Comment by piosz** [comment]
This should be done together with building the image in container (in the similar way to how Kubernetes is built now). I'm happy to accept contributions!

**Comment by brendandburns** [comment]
@luxas did this ever happen?  As far as I can tell the latest ARM version of heapster is 0.8.0

Thanks!
--brendan

**Comment by luxas** [comment]
@brendandburns Well, kubernetesonarm/heapster:0.8.0 is v1.2.0-beta.2 of heapster. 0.8.0 is the release of Kubernetes on ARM it was shipped with. Also there are kubernetesonarm/grafana:0.8.0 which is 3.1.1 and kubernetesonarm/influxdb:0.8.0 which is at version v0.13.0.

However, it's of course best if we have official images for them, so here we go: #1387 
I planned to do it earlier, but fully focused on sig-cluster-lifecycle here in between.

Cheers, Lucas
