### ISSUE TITLE
heapster cannot get pod's network rx or tx?

### ISSUE THREAD

**Issue by Max-bazinga** [kubernetes/heapster#1285]
Hi, I use heapster V0.19, docker v1.10.3. But I the table "network/rx_bytes_cumulative" cannot display the /docker containers information. I query the "network/rx_bytes_cumulative" table's result as below:
![image](https://cloud.githubusercontent.com/assets/4305379/18434577/8537c402-7920-11e6-96ac-19c9d4b17a78.png)

I want to get network information of the pods which i create through K8s. But I only found the "machine" measurement in the influxDB.

**Comment by piosz** [comment]
The version 0.19 is no longer supported. Please try to the latest stable release (1.1.0).
