### ISSUE TITLE
network/rx_rate and network/tx_rate alway 0

### ISSUE THREAD

**Issue by Max-bazinga** [kubernetes/heapster#1287]
Hello, I use heapster v1.1.0. But the table "netwokr/rx_rate" always 0. The result I query from InfluxDB as below:
![image](https://cloud.githubusercontent.com/assets/4305379/18446060/1b9eacf8-7953-11e6-978d-eeb880e87deb.png)
However, when I look from the cadvisor's webUI, the eth1 has traffic in it. If the heapster just monitor one ethernet？Which ethernet is the heapter monitor by default?
![image](https://cloud.githubusercontent.com/assets/4305379/18446425/dc0cde46-7954-11e6-9ecf-5b324d3f39cd.png)

**Comment by DirectXMan12** [comment]
Do you see any values on individual containers?

**Comment by Max-bazinga** [comment]
@DirectXMan12 Yes, the individual containers has values. But I want to filter the type equal to  "node" to get the host's value.

**Comment by DirectXMan12** [comment]
This is quite old now.  Please re-open if you're still experiencing the issue

**Comment by DirectXMan12** [comment]
This is quite old now.  Please re-open if you're still experiencing the issue
