### ISSUE TITLE
Docs outdated

### ISSUE THREAD

**Issue by stevezau** [kubernetes/heapster#1288]
Hi,

The docs point to kubernetes/heapster on docker hub but shouldn't they point to gcr.io/google_containers/heapster?

I am happy to open a PR to update the docs but wasn't sure if there was a reason to not include gcr.io/google_containers/heapster yet?

**Comment by piosz** [comment]
Feel free to drop a PR. The docs are definitely outdated.

**Comment by DirectXMan12** [comment]
I believe this has been fixed.
