### ISSUE TITLE
health endpoint for eventer

### ISSUE THREAD

**Issue by AlmogBaku** [kubernetes/heapster#1293]
we should have a /healthz endpoint in eventer like we do in Heapster(#1271) so that Kubernetes can properly health-check it

**Comment by DirectXMan12** [comment]
please add a small description (even if it's just something like "we should have a /healthz endpoint in eventer like we do in Heapster so that Kubernetes can properly health-check it") for future viewers to look back on.

**Comment by AlmogBaku** [comment]
Actually, as I see now- the current eventer implementation doesn't even have an http server..
I'm not sure if we want to create an http server just for this purpose..

@DirectXMan12 what do you think?

**Comment by andyxning** [comment]
@AlmogBaku @DirectXMan12 

I think we should add an http server. As currently we add prometheus metrics to eventer, however we have not enabled an http server to serve `/metric` endpoint which makes adding prometheus metrics useless.

**Comment by DirectXMan12** [comment]
That seems reasonable -- those two together seem sufficient justification.

**Comment by andyxning** [comment]
@AlmogBaku @DirectXMan12 I will make a PR later.

**Comment by andyxning** [comment]
@DirectXMan12 @AlmogBaku PR has been fired. PTAL~
