### ISSUE TITLE
grafana and heapster service error

### ISSUE THREAD

**Issue by Jaware** [kubernetes/heapster#1300]
version:master branch------
\heapster_grafana:v2.6.0-2
kubernetes/heapster:canary
kubernetes/heapster_influxdb:v0.5

grafana service    only showed {{alert.title}}(console showed that js and css files were 404 missing).heapster service   showed "404 page not found".only influxdb service worked normally.
pod logs are   as follows:
GET /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/public/css/**grafana.dark.min.a95b3754.css** HTTP/1.1" **404** Not Found 23 bytes in 730us
2016-09-19T10:09:18.874944104Z 2016/09/19 10:09:18 [I] Completed 172.16.62.0 - "GET /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/public/app/**app.ca0ab6f9.js** HTTP/1.1" **404** Not Found 23 bytes in 1079us

**Comment by Jaware** [comment]
it seems as if it connected the api server using the wrong host url,it should be masterUrl+/api/vi/proxy.....but in my situation,the host url is the grafana service url

**Comment by valentin2105** [comment]
Same problem, unable to use Heapster & Grafana on Kubernetes v1.3.6.

Here is grafana's logs :
`t=2016-09-30T11:35:25+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/public/app/boot.1649cbaa.js status=404 remote_addr=10.240.0.30 time_ns=0 size=19`

Try as a NodePort and as a ClusterIP. 

Any idea?

**Comment by DirectXMan12** [comment]
this appears to be the same as #1316.  Closing in favor of that.
