### ISSUE TITLE
Authorization in Heapster API server

### ISSUE THREAD

**Issue by mksalawa** [kubernetes/heapster#1306]
Follow up of the discussion about authorization in [https://github.com/kubernetes/heapster/pull/1301#issuecomment-248049099](https://github.com/kubernetes/heapster/pull/1301#issuecomment-248049099)

@DirectXMan12 @deads2k

**Comment by DirectXMan12** [comment]
Yeah, so the point there was that you generally don't want *all* of the authorization options available on the Heapster API -- you just want the webhook authorization option (which would get set by the user to the Kube API server hosting the auth APIs).  We (probably) don't want Heapster having separate authn/authz from the rest of the API servers.

**Comment by DirectXMan12** [comment]
closing.  If you want proper auth, use metrics-server.
