### ISSUE TITLE
collect docker events with heapster eventer

### ISSUE THREAD

**Issue by andyxning** [kubernetes/heapster#1308]
As now we can collect Kubernetes events using heapster events, it may be good to also collect Docker events also. As we do in heapster core, calling Kubernetes apiserver to collect the minon nodes running Kubelet with the assumption that Kubelet running on the same port 10255, we can assume that all Docker are also running on the same port and so we can use the Docker remote api to collect all docker events. :)

**Comment by andyxning** [comment]
ping @thockin @piosz @DirectXMan12

**Comment by andyxning** [comment]
I will work on this in the next few days.

**Comment by piosz** [comment]
Sorry, this is out of the scope of Heapster. There is an effort in Kubernetes to support not only Docker as container runtime (see https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/container-runtime-interface-v1.md). I think we should rather add a functionality to CRI to proxy container runtime events to Kubernetes. You can reuse some Heapster code to create your own solution if you need it.
