### ISSUE TITLE
ipv6 is attempted

### ISSUE THREAD

**Issue by moserke** [kubernetes/heapster#1311]
Our coreos hosts by default have ipv6 enabled.  Due to this it has an internalIP for both ipv4 and ipv6 and heapster ends up getting the ipv6 address and attempts to connect to the kubelet on that and fails.

Is there a way to configure kubelet to select only the ipv4 internalIP or must we turn ipv6 off on all of our coreos boxes?

**Comment by DirectXMan12** [comment]
Just to clarify, if you do `kubectl get nodes`, what addresses are listed there?

**Comment by moserke** [comment]
That shows our DNS name for the nodes.  But the kubelet source seems to not be trying to use the hostname but instead using the IP.

At https://github.com/kubernetes/heapster/blob/v1.2.0/metrics/sources/kubelet/kubelet.go#L293 it is looking through the nodes internal IPs and using them.  There are two internal IPs on our nodes, one that is ipv4 and one that is ipv6.   The ipv6 ends up overwriting the ipv4 as it's the second one found.

Then at https://github.com/kubernetes/heapster/blob/v1.2.0/metrics/sources/kubelet/kubelet_client.go#L126 when scraping occurs it is using the IP not the hostname.  So even though the hostname is set to something resolvable, that doesn't get used and IP is used instead.  And since the IP gets set to ipv6 because that is the second one in the node objects IP array for InternalIP that's the one that gets attempted.

This ends up with a log message like: error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://fe80::250:56ff:feb0:553a:10255/stats/container/": Post http://fe80::250:56ff:feb0:553a:10255/stats/container/: dial tcp: too many colons in address fe80::250:56ff:feb0:553a:10255

Since the http client being used is likely an ipv4 client.

So the only option I see at this point is to disable ipv6 or change to use the hostname for the connection to the kubelet instead of the IP

**Comment by kcrawley** [comment]
This is definitely an issue. I ended up having to roll my own image to get this working. I'll put in a PR with a fix that allows for specifying ipv4 || v6, but this project appears to have been almost abandoned.

**Comment by mccormd** [comment]
Any chance of this going in?

**Comment by kcrawley** [comment]
The PR is waiting on me to look at a test failure. I'll look at this today.

**Comment by kcrawley** [comment]
Fixed the test failure, should be good to go now. Thank you for the reminder @mccormd
