### ISSUE TITLE
Move to glide

### ISSUE THREAD

**Issue by AlmogBaku** [kubernetes/heapster#1314]
Kubernetes will eventually migrate to use Glide instead of godep (which is kinda deprecated for vendoring): https://github.com/kubernetes/kubernetes/pull/24202

Can we start and move this project to glide?

@thockin @piosz @DirectXMan12

**Comment by nhlfr** [comment]
Do we want to use glide-vc as well? I don't think we have any libraries whose license would prevent us from using it.

**Comment by AlmogBaku** [comment]
@nhlfr why even committing the vendor dir?

**Comment by nhlfr** [comment]
I can add it to gitignore - it would require ensuring that vendor dir exists during build, but of course that's doable.

**Comment by piosz** [comment]
I'm not familiarized with Glide but I really want to get rid off Godeps, which is big pain point. Anyway I'd like to wait for Kubernetes successful migration.

**Comment by nhlfr** [comment]
Just to clarify - Glide works well with Godep-based dependencies - it even detects conflicts in versions between main project and a dependency (regardless of whether that dep uses Glide or Godep). So I think that there is no need to worry about sequence in which k8s project are going to adopt Glide.

**Comment by DirectXMan12** [comment]
none-the-less, I agree with @piosz: we should probably wait for and/or assist with the Kubernetes migration, and then move ourselves once that happens.  It would be unfortunate if we ended up with a different workflow than Kubernetes, and had to change again to be in line with the main repo.

**Comment by AlmogBaku** [comment]
A success story with heapster can push things forward with the big project of k8s... :D

**Comment by AlmogBaku** [comment]
Also there are other k8s projects that already uses glide, such as `helm`

**Comment by piosz** [comment]
Closing as explained in #1335
