### ISSUE TITLE
summary_api can't enable (KubeletVersion: "v1.2.0-36-g4a3f9c5")

### ISSUE THREAD

**Issue by tacy** [kubernetes/heapster#1317]
(dlv) p info
k8s.io/heapster/metrics/sources/summary.NodeInfo {
        k8s.io/heapster/metrics/sources/kubelet.Host: k8s.io/heapster/metrics/sources/kubelet.Host {
                IP: "172.18.100.7",
                Port: 10250,
                Resource: "",},
        NodeName: "origin-master.tacy.com",
        HostName: "origin-master.tacy.com",
        HostID: "origin-master.tacy.com",
        KubeletVersion: "v1.2.0-36-g4a3f9c5",}

https://github.com/kubernetes/heapster/blob/master/metrics/sources/summary/summary.go#L129 return false

"alpha" > "36"

**Comment by piosz** [comment]
@timstclair when summary api was introduced?

**Comment by timstclair** [comment]
That check is accurate, the summary was introduced in `v1.2.0-alpha.8` (v1.2.0 was the first stable release that included it). I believe semver just does a lexicographical comparison for everything after the `-`. It looks like you're trying to build a custom version of the Kubelet? If so, a simple fix would be to just add a custom tag (e.g. `v1.2.0-patch-foo`), so long as it's ordered after alpha it should work. Alteranatively, you could just rebase on a new release (e.g. 1.2.1).

**Comment by piosz** [comment]
Thanks @timstclair!
@tacy could you please try what @timstclair proposed? I'm closing this, please reopen in case it won't help.
