### ISSUE TITLE
Support persistent storage for InfluxDB backend.

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#132]
As of now InfluxDB pod uses local storage.

**Comment by pires** [comment]
+1

**Comment by vishh** [comment]
Excepting local disk none of the existing Storage solutions in kubernetes works for all the users. I am thinking the best way to address this issue is to provide a cookbook of storage recipes in the repo and make the users choose one based on their deployment. 
We can simplify this by having a deployment binary with simple flags.
Any thoughts @pires ?

**Comment by jimmidyson** [comment]
I think by default we should be using an empty-dir volume, but as we're seeing with lots of things this is deployment/implementation specific. A deployment binary might be a good idea, but we really need this to be in the influxdb manifest at the very least.

**Comment by pires** [comment]
I agree with @jimmidyson. I think it's up to the user to adopt whatever storage strategy he/she is more comfortable with. In the end, I'd really like to see something like [`flocker`](https://github.com/ClusterHQ/flocker) coming into Kubernetes, but right now it's too early to decide on an approach other than empty-dir.

**Comment by piosz** [comment]
closing in favor of #1197
