### ISSUE TITLE
Proposal: Add metrics collector for Ganglia

### ISSUE THREAD

**Issue by TamalSaha** [kubernetes/heapster#1322]
We have [extended Heapster](https://github.com/appscode/heapster/commits/v1.2.0-ac) to collect metrics from Ganglia running as a standalone pod or side car container in a Kubernetes cluster. We would like to see if this feature can be merged into upstream.

**Background**
We would like to collect application specific metrics from custom addons or pre-packaged apps into the cluster monitoring storage (InfluxDB etc.).

**How it Works**
Ganglia has 2 components: `gmond` and `gmetad`. `gmond` exposes an XML file via an http endpoint. Applications can write to that XML file using Ganglia api or their C/Python modules. `gmetad` collects that data and stores in some tsdb.

In our implementation, we expect users to run a standalone or side car `gmond` container with label `monitoring.appscode.com/container:true` label. Functionality of `gmetad` has been replaced with `GangliaBasedEnricher` inside Heapster. We also added a ServiceEnricher to tag the service name of the pod that exported the metrics.

**Benefit**
Heapster is already going all the heavy lifting required to deal with Kubernetes' dynamic environment. The benefit of running inside Heapster is that cluster admins can monitor any metrics they prefer with using very little resource for monitoring data collection.

**Comment by huangyuqi** [comment]
The PR about `Ganglia sink` is appreciate, please push to the upstream. And then someone including me should take a review about this.

**Comment by piosz** [comment]
Please have in mind that we are working on [Kubernetes monitoring architecture](https://docs.google.com/document/d/1z7R44MUz_5gRLwsVH0S9rOy8W5naM9XE5NrbeGIqO2k/edit). It's not clear yet what will be the role of Heapster if the vision will be agreed.

**Comment by TamalSaha** [comment]
@piosz, is the intention to have the new architecture in place for Kube 1.5?

**Comment by piosz** [comment]
It won't be possible to do it due to backward compatibility and pretty short timing. I think some of the stuff would happen for 1.5 and some will be spawned across 1.6 or even 1.7.

**Comment by TamalSaha** [comment]
Closing this as we are pursuing Prometheus.
