### ISSUE TITLE
Add a deployment tool for kubernetes 

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#133]
As of heapster setup and troubleshooting is difficult at times. Having a deployment tool, that verifies that cadvisor is installed on every node, sets up all the heapster components, and ensures that all the components are up and running. This tool could also help configure backends and dynamically generate kube configs.

**Comment by rjnagal** [comment]
+1 there are too many steps in current monitoring setup for user/admin to run through themselves.

The tool should also support cleanly shutting down monitoring for people who don't use it. The subcommands I'd like to see:
- start monitoring
- stop monitoring
- validate (get validate output from heapster and cadvisors, also healthchecks sinks)

**Comment by vishh** [comment]
It could also be extended to add and remove pluggable backends.
For example:
Deploy InfluxDB + Grafana backend if required or setup a GCM backend, etc.

**Comment by piosz** [comment]
Obsolete/Done
