### ISSUE TITLE
Add api sink for Eventer

### ISSUE THREAD

**Issue by andyxning** [kubernetes/heapster#1343]
Currently, we have supported **influxdb**, **ES**, **gcl** and **log**. Now, i want to add one more sink: **api sink**.

The Demand is like this. We can not store events in existing sinks for analyzation and monitoring. We can also use [**Bosun**](http://bosun.org/) to periodically query **influxdb** and **ES** to make alarms when some events such as **system_oom** and **pull_image_error** occur. 

However, this **PULL** strategy is not so timely to report when bad events occurs. I think we can support **api sink** with **POST** support. Under this situation, we can **post** all events to an alarm component which will make an alarm when it receives the **system_oom** or **pull_image_error**. This way the alarm will be in time.

Additionaly, with this **POST** api we can easily add more sinks through it without adding more sinks to the Eventer any more. :)

@piosz @vishh @mwielgus

**Comment by andyxning** [comment]
@huangyuqi @vmarmol @jimmidyson

**Comment by piosz** [comment]
I'm not sure whether I understand this issue. Currently eventer reads events from Kubernetes API server and exports them to a storage backend to archive them. If you need real time events why not just watch api server directly?

**Comment by andyxning** [comment]
@piosz yes, Eventer reads Kubernetes API for events. I want to reuse Eventer for error handling when connecting to Kubernetes API and also the capability for sinking to other destinations at the same time. With Api sink enabled, we can do this job in one program. :)

**Comment by piosz** [comment]
@andyxning sorry, this is out of the scope of eventer, which is supposed to be a simple archiver for events with no logic and no api. Anyway feel free to reuse eventer's code.

**Comment by andyxning** [comment]
@piosz i think may be i express the api sink idea not so good. It will not add any new api to eventer. :)

With api sink, we can config an **external** api server to POST the received events. just like we can store the events to the es.

**Comment by piosz** [comment]
I'm still a little bit confused. Do you want to have a push endpoint which accepts events from other sources than Kubernetes api server?

**Comment by andyxning** [comment]
@piosz yes. the **other sources** is **Eventer**. I just want one program to watch the Kubernetes api server. Then, Eventer can sink the events to multiple sinks at the same time. :)

```
                                     PUSH
               watch(PUSH)         |------ ES
Kubernetes Api    --->  Eventer    ------- Api Server 
                                   |------ InfluxDB 

```

**Comment by piosz** [comment]
What is the responsibility of Api Server on your picture? Is this a sink in eventer which exports some api? If yes this is out of the scope of project, since events are already served by api server.

**Comment by andyxning** [comment]
@piosz I have updated the description map. 

* What api server sink does is when it receives events from Eventer it will call HTTP POST method on **Alarm** with api url http://localhost:2080/api/events. 
* What **Alarm** does is receive events and then judge according to predefined alarm rules. Such as, when an system oom event is received, it will send an alarm message via Slack.

**Comment by piosz** [comment]
I suggest changing Alarm implementation to watch events directly from Kubernetes API server. If this is not an option for you should write a sidecar container which watches events from Kubernetes API server and push them to your alarm path.

**Comment by andyxning** [comment]
Just to mention that i have write [eventarbiter](https://github.com/andyxning/eventarbiter) which utilizes `eventer` to filter event alarm. Have fun with it. :-)
