### ISSUE TITLE
Memory graph shows not the actual memory used

### ISSUE THREAD

**Issue by hitman99** [kubernetes/heapster#1356]
Issue visible in the chart below. Memory usage graph shows a sum of memory used by kubernetes and buffer/cache. Cache should not be included

```
free -m
              total        used        free      shared  buff/cache   available
Mem:          31910         978       25102          98        5830       30485
Swap:         16383           0       16383
```

![image](https://cloud.githubusercontent.com/assets/907201/19760565/faa773e4-9c3a-11e6-9471-8be927e674d0.png)

**Comment by piosz** [comment]
What this chart comes from?

**Comment by hitman99** [comment]
It's in the kubrnetes dashboard, but the data comes from heapster as charts are not available until I deploy heapster add-on.

**Comment by bryk** [comment]
@hitman99 That's a valid observation. I agree with the issue here. 

@piosz How can we make heapster return metrics for a node without cache reservations?

**Comment by bryk** [comment]
cc @rf232

**Comment by DirectXMan12** [comment]
@bryk all the data comes from Kubelet (which it's getting from cAdvisor).

**Comment by Thermi** [comment]
I encountered this issue as well. Please fix. The reported memory metrics are not useful in the current state.

**Comment by piosz** [comment]
Take a look into https://github.com/google/cadvisor/blob/master/info/v1/container.go#L326. Shouldn't you use WorkingSet instead?

**Comment by Thermi** [comment]
WorkingSet doesn't correspond to the actual "used" -+ buffers/cache output of `free`.
For comparison, here's one heapster metric and from free at the same time
```
{
  "_index": "heapster-2016.11.04",
  "_type": "memory",
  "_id": "f3f9d8c2-a2ab-11e6-9941-2aa42b43b130",
  "_score": null,
  "_source": {
    "MemoryMetricsTimestamp": "2016-11-04T16:30:00Z",
    "Metrics": {
      "memory/limit": {
        "value": 1472200704
      },
      "memory/major_page_faults": {
        "value": 151
      },
      "memory/major_page_faults_rate": {
        "value": 0
      },
      "memory/node_allocatable": {
        "value": 3950506000
      },
      "memory/node_capacity": {
        "value": 3950506000
      },
      "memory/node_reservation": {
        "value": 0.31692135
      },
      "memory/node_utilization": {
        "value": 0.81257236
      },
      "memory/page_faults": {
        "value": 37131328
      },
      "memory/page_faults_rate": {
        "value": 10.287301
      },
      "memory/request": {
        "value": 1251999744
      },
      "memory/usage": {
        "value": 3210072064
      },
      "memory/working_set": {
        "value": 2282536960
      }
    },
    "MetricsTags": {
      "host_id": "i-79c274f2",
      "hostname": "ip-10-0-0-67.eu-west-1.compute.internal",
      "labels": "beta.kubernetes.io/arch:amd64,beta.kubernetes.io/instance-type:m3.medium,beta.kubernetes.io/os:linux,failure-domain.beta.kubernetes.io/region:eu-west-1,failure-domain.beta.kubernetes.io/zone:eu-west-1a,kubernetes.io/hostname:ip-10-0-0-67.eu-west-1.compute.internal",
      "nodename": "ip-10-0-0-67.eu-west-1.compute.internal",
      "type": "node"
    }
  },
  "fields": {
    "MemoryMetricsTimestamp": [
      1478277000000
    ]
  },
  "highlight": {
    "MetricsTags.hostname.raw": [
      "@kibana-highlighted-field@ip-10-0-0-67.eu-west-1.compute.internal@/kibana-highlighted-field@"
    ],
    "MetricsTags.type": [
      "@kibana-highlighted-field@node@/kibana-highlighted-field@"
    ],
    "MetricsTags.nodename.raw": [
      "@kibana-highlighted-field@ip-10-0-0-67.eu-west-1.compute.internal@/kibana-highlighted-field@"
    ]
  },
  "sort": [
    1478277000000
  ]
}	
```

```
ip-10-0-0-67 core # free 
             total       used       free     shared    buffers     cached
Mem:       3857916    3751744     106172       1460     237904    1735816
-/+ buffers/cache:    1778024    2079892
Swap:            0          0          0
```

**Comment by piosz** [comment]
cc @timstclair

**Comment by piosz** [comment]
Could you please create an issue in cadvisor repository and then close this one?

**Comment by Thermi** [comment]
I opened an issue here: https://github.com/google/cadvisor/issues/1529
Feel free to weigh in on it.

**Comment by andyxning** [comment]
It seems that memory usage metric for container also contains cache. This should also be fixed as now cadvisor has already contains this info about usage, rss, cache. Aso, with aufs, the page cache may be large. Maybe rss is the really useful metric to determine whether we should make more instances or enlarge memory request

**Comment by eschwartz** [comment]
Any update on this?
I'd really like to be able to collect k8s cache metrics via heapster,
but as it stands, the existing metrics are not useful.

Has anyone else come up with a stop-gap alternative? I'm trying to post metrics to elasticsearch

**Comment by DirectXMan12** [comment]
I think you'd need to weigh in on the cAdvisor bug

**Comment by KristianLyng** [comment]
"kubectl top node" is also inconsistent with memory/node_utilization. "kubectl top node" seems to use working set to calculate its own utilization grade. Similarly, "kubectl top node" differ from typical memory usage in the dashboard (and anything else using "memory/usage") since it reports working set.

The result for me:

"kubectl top":

```
NAME                          CPU(cores)   CPU%      MEMORY(bytes)   MEMORY%   
malxkube01                    277m         2%        4405Mi          6%        
malxkube02                    383m         3%        8746Mi          13%       
malxkube03                    238m         2%        7036Mi          10%       
malxkube04                    273m         2%        6810Mi          10%    
malxkube05                    255m         2%        11680Mi         18%       
drlxkube01                    340m         3%        3055Mi          4%        
drlxkube02                    626m         6%        8095Mi          12%       
drlxkube03                    402m         4%        8705Mi          13%       
drlxkube04                    372m         3%        7773Mi          12%       
drlxkube05                    2139m        21%       8848Mi          13%       
```
Grafana/influx: (cpu/node_utilization)
```
                min     max     avg     current
drlxkube01      12.69%  12.71%  12.70%  12.71%
drlxkube02      32.71%  32.78%  32.75%  32.76%
drlxkube03      35.65%  35.67%  35.66%  35.67%
drlxkube04      28.31%  28.63%  28.44%  28.46%
drlxkube05      26.92%  28.55%  27.63%  28.50%
malxkube01      18.28%  18.35%  18.33%  18.35%
malxkube02      21.50%  21.70%  21.60%  21.68%
malxkube03      16.31%  16.70%  16.46%  16.37%
malxkube04      20.26%  20.42%  20.31%  20.34%
malxkube05      37.67%  37.87%  37.81%  37.67%
```

These should probably be consistent... Not entirely sure if this should be a separate issue or not, as it seems to be more or less the same core problem.

**Comment by DirectXMan12** [comment]
`kubectl top` just uses data from Heapster, so it would have the same problem

**Comment by toddams** [comment]
Any update on this?

**Comment by gacopl** [comment]
really everyone is ok with this ?
