### ISSUE TITLE
Grafana dashboard don't display dashboard for containers kubernetes. I have only pods and cluster dashboards.

### ISSUE THREAD

**Issue by medhedifour** [kubernetes/heapster#1358]
I use grafana/influxdb with heapster in kubernetes. 
Grafana dashboard display pods and nodes in the cluster.
I don't have containers' dashboard.

**Comment by Crassirostris** [comment]
@medhedifour Thanks for the submitting your request.

I will make a new dashboard, same as Pods, but with the ability to select individual containers. Will it solve your problem?

**Comment by luxas** [comment]
Is this fixed?

**Comment by Crassirostris** [comment]
@luxas No, I was swamped with other tasks and wasn't sure it's what the OP wanted

**Comment by Crassirostris** [comment]
@luxas Do you want it?

**Comment by luxas** [comment]
Not specifically, just checked the status.
Maybe the help-wanted label would make sense then?

**Comment by Crassirostris** [comment]
@luxas It's fine, thanks. I think I will be able to address this soon, in a week or so.

**Comment by Crassirostris** [comment]
Unfortunately, different efforts kept me busy and now I'm going out of office for a couple of weeks. Applying help-wanted label
