### ISSUE TITLE
Missing elasticsearch index with date format

### ISSUE THREAD

**Issue by andrejvanderzee** [kubernetes/heapster#1359]
Hi,

As far as I can see, there is no option to specify the date in the elasticsearch index like so:

`--sink=elasticsearch:192.168.1.1:9200?index=heapster-%Y.%m.%d`

Is this anywhere on the roadmap or known workarounds?

Thanks,
Andrej

**Comment by DirectXMan12** [comment]
> Is this anywhere on the roadmap or known workarounds?

Not that I know of.  @AlmogBaku was recently working with the ES sink, so he might know.

**Comment by AlmogBaku** [comment]
Duplicated of #1310 , implemented on #1313 

# ***Would love and appreciate if you can help us and review this PR in order to push it forward...***
This is currently stuck because nobody can review it...

**Comment by andrejvanderzee** [comment]
How can I help? I can acknowledge the created indices in the current version pushes me to write my own UI client for visualization. If this PR enables us to to create proper charts in Kibana, that would be all great.

**Comment by AlmogBaku** [comment]
@andrejvanderzee that's exactly what this PR do.

You can help by:
1. reviewing the code I've committed in the PR and to give a feedback if you have
2. build an image with this PR, deploy it, and test it(basically see if any major issues occurs)

**Comment by andrejvanderzee** [comment]
@AlmogBaku Would be happy to help out. Hopefully I can find the time this week or otherwise will do in the weekend. Would it be possible to export the chart objects from Kibana so that I can quickly import and view them? That would safe me some tedious work.

**Comment by AlmogBaku** [comment]
@thermi can we do that?

**Comment by Thermi** [comment]
@AlmogBaku we can certainly export the complete dashboard and all visualizations.

**Comment by andrejvanderzee** [comment]
@Thermi @AlmogBaku We are running your feature branch now on our DEV cluster and the indices look much, much more useful right now. 

Would it be possible to receive the complete dashboard and all visualizations? It will be useful to others as well so it might be an option to add those to the source base.

In the coming days I will review the code.

**Comment by AlmogBaku** [comment]
@andrejvanderzee would you kindly post your feedback(and continue the discussion) in the PR #1313

**Comment by andrejvanderzee** [comment]
Duplicate of #1313.
