### ISSUE TITLE
Proposal: Add metrics sink for wavefront

### ISSUE THREAD

**Issue by mrcrgl** [kubernetes/heapster#1361]
Hi guys,

in our company we're using wavefront for infrastructure insights. Since we plan to switch to kubernetes+heapster, we would add a sink client for [wavefront](https://www.wavefront.com/). 
Do you think that'd be an interesting feature for other users?

-Marc

**Comment by ezeev** [comment]
Hi @mrcrgl ,

We maintain an image of Heapster that's packaged with a Wavefront sink. We also have a template dashboard you can use:
https://community.wavefront.com/docs/DOC-1204

I would love to sync up with you to help get this running. I'll also submit a PR with the Wavefront sink.

Thanks,
Evan

**Comment by mrcrgl** [comment]
Hi @ezeev,

Sorry for my late response. Please let me know how can I help you. 

- Marc
