### ISSUE TITLE
Occasional negative Metrics.cpu/usage_rate.value

### ISSUE THREAD

**Issue by andrejvanderzee** [kubernetes/heapster#1363]
Occasionally, Heapster seems to report negative values for Metrics.cpu/usage_rate.value as shown below in the Elastic Search log entries. Note that this was spotted on the branch AlmogBaku:feature/elasticsearch_mapping (see #1313).

```
{
  "_index": "heapster-2016.11.02",
  "_type": "cpu",
  "_id": "8719b52c-a0f8-11e6-b156-6692f8478d50",
  "_score": null,
  "_source": {
    "CpuMetricsTimestamp": "2016-11-02T12:33:00Z",
    "Metrics": {
      "cpu/usage": {
        "value": 0
      },
      "cpu/usage_rate": {
        "value": -469
      }
    },
    "MetricsTags": {
      "container_base_image": "abc:v0",
      "container_name": "abc",
      "host_id": "192.168.64.74",
      "hostname": "192.168.64.74",
      "namespace_id": "5ae5cad8-00ad-11e6-a24f-fa163e48ccfb",
      "namespace_name": "default",
      "nodename": "192.168.64.74",
      "pod_id": "a9bff453-a0e6-11e6-ae93-fa163e48ccfb",
      "pod_name": "abc-2147496296-uvry3",
      "pod_namespace": "default",
      "type": "pod_container"
    }
  },
  "fields": {
    "CpuMetricsTimestamp": [
      1478089980000
    ]
  },
  "sort": [
    1478089980000
  ]
}
```

**Comment by AlmogBaku** [comment]
this happened to us also with `Metrics.memory/page_faults_rate.value`

**Comment by jonaz** [comment]
Isn't this related to https://github.com/kubernetes/kubernetes/issues/30939#issuecomment-244454951

I had this in coreos until latest stable (last week) where they stopped using systemd cgroup driver.

**Comment by andrejvanderzee** [comment]
@jonaz We are running CentOS Atomic with systemd v219. The issue you mentioned is caused by newer versions of systemd (>= v226).

**Comment by AlmogBaku** [comment]
@thermi is that the same scenario?, maybe the problem is with Systemd version? maybe the new coreos version solves it also for us?

**Comment by euank** [comment]
The problem in 30939 (linked above) was systemd >=226, docker using the systemd cgroup driver, and an older version of docker.

Using `systemctl cat docker.service` you can verify whether docker is configured to use the ` --exec-opt native.cgroupdriver=systemd` option.

Newer systemd versions don't fix this, but new enough docker versions do.
On CoreOS, we fixed this by moving to `cgroupdriver=cgroupfs`. I don't know what docker versions, if any, include the needed fix.

If this is that same issue, then it's not really a heapster bug but a docker bug.

**Comment by Thermi** [comment]
I looked at our coreos setup and this is what we have:

systemctl cat docker.service

```
[...]
EnvironmentFile=-/run/flannel_docker_opts.env
MountFlags=slave
ExecStart=/usr/lib/coreos/dockerd daemon --host=fd:// $DOCKER_OPTS $DOCKER_CGROUPS $DOCKER_OPT_BIP $DOCKER_OPT_MTU $DOCKER_OPT_IPMASQ
[...]
```

/run/flannel_docker_opts.env:
```
DOCKER_OPT_BIP="--bip=10.2.53.1/24"
DOCKER_OPT_IPMASQ="--ip-masq=false"
DOCKER_OPT_MTU="--mtu=8951"
```

```
$ docker --version
Docker version 1.11.2, build bac3bae
```

@euank Which coreos version or docker version is recent enough and does adding `--exec-opt native.cgroupdriver=systemd` fix or cause the problem?

**Comment by euank** [comment]
1137+ I believe. So long as `DOCKER_CGROUPS` isn't set in your docker.service file, it's defaulting to `cgroupfs`, so the issue in 30939 wouldn't be it.

If you're still seeing a similar problem, then it's a different bug to investigate.

I suspect this could be a different bug than the one in that issue, but since it was referenced as a possible duplicate I wanted to give more information so we could be sure.

**Comment by piosz** [comment]
Which version of Kubernetes and Heapster do you use? Which source: summary api or cadvisor?

It should be rather a bug with system than with Heapster itself because it only appears on CoreOS nodes. 

How often does the problem occur? Could you please do the similar investigation that @Random-Liu did here https://github.com/kubernetes/kubernetes/issues/27194#issuecomment-226318668?

**Comment by Thermi** [comment]
kubernetes 1.3, heapster 1.2 beta. cadvisor, as far as I am aware.

**Comment by piosz** [comment]
@Thermi we haven't tested Heapster 1.2 with Kubernetes 1.3. Do you have the same issue with Heapster 1.1 nad Kubernetes 1.3? Also could you please verify cadvisor output?

**Comment by Thermi** [comment]
We can't test heapster 1.2, because we need to use @AlmogBaku's new mapping. 
heapster is running with "--source=kubernetes:https://kubernetes.default".
