### ISSUE TITLE
[Proposal]: Add a kafka sink for Event

### ISSUE THREAD

**Issue by miaoyq** [kubernetes/heapster#1365]
Kafka is well suited for handling metrics. It might be useful for events as well. So I think it is meaningful to add a kafka sink for event. I have completed the development of kafka sink for event locally. Shall I commit a PR to accept some guys' comments?  Thanks!

**Comment by piosz** [comment]
I'm happy to accept a contribution.

**Comment by miaoyq** [comment]
@piosz  I have opened a PR for this issue, please help to review, thanks!
