### ISSUE TITLE
Issue getting heapster running within Minikube

### ISSUE THREAD

**Issue by aaron-prindle** [kubernetes/heapster#1371]
Has anyone been able to get heapster successfully running within minikube (specifically using influxdb)?  I seem to be having some issues:
https://github.com/kubernetes/minikube/issues/743#issuecomment-259035140

Any help would be appreciated, thanks!

**Comment by aaron-prindle** [comment]
Got it working, closing

**Comment by piosz** [comment]
Could you please describe your problem and the solution? Thanks!

**Comment by aaron-prindle** [comment]
The problem was that I was using type: NodePort for the influxdb and heapster services (as those can be exposed via Minikube) which did not seem to work when attempting to use the services with grafana.   Changing those back to ClusterIP and exposing only grafana via NodePort did the trick.  The link in my original comment shows the logs/configuration I was using.
