### ISSUE TITLE
Allow insecure certificates for HTTPS InfluxDB sinks

### ISSUE THREAD

**Issue by AndyJS** [kubernetes/heapster#1372]
I'm attempting to setup Heapster on k8s to write metrics via HTTPS to an externally hosted InfluxDB server.

Here's my service command:
```
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:https://<redacted>:8086?secure=true&db=k8s-prod
```

Here's the relevant error from my pod logs:
```
2016-11-08T14:55:04.004166113Z E1108 14:55:04.004072       1 influxdb.go:217] issues while creating an InfluxDB sink: failed to ping InfluxDB server at "<redacted>:8086" - Get https://<redacted>:8086/ping: x509: certificate is valid for , not <redacted>, will retry on use
```

From checking the source & docs it appears configuring the Influx client's UnsafeSsl config boolean isn't supported. This would be a nice addition.

**Comment by piosz** [comment]
Thanks for your feedback. I'm happy to accept the contribution.

**Comment by jakon89** [comment]
It was implemented in: https://github.com/kubernetes/heapster/pull/1462
Looks like issue can be closed.
