### ISSUE TITLE
heapster_grafana is out of date

### ISSUE THREAD

**Issue by sjug** [kubernetes/heapster#1373]
I deployed heapster/deploy/kube-config/influxdb/ on my cluster and found that the grafana dashboards are totally obsolete.

All queries are referencing an old storage schema (looking for memory/xxx_bytes_gauge nor cpu/xxx_guage, etc), making it effectively useless as it is now.

The heapster_grafana image should be updated to work with the current storage schema.

**Comment by jeremyd** [comment]
+1

**Comment by keithballdotnet** [comment]
Where can I find the current schema?  I would be happy to do some monkey work and update.

**Comment by keithballdotnet** [comment]
I found an updated container.

gcr.io/google_containers/heapster_grafana:v2.6.0-2

Update the grafana to that.  All good.

**Comment by piosz** [comment]
@Crassirostris could you please take a look?

**Comment by Crassirostris** [comment]
@piosz Sure

@sjug Could you please tell the versions of influxdb and grafana containers?

**Comment by luxas** [comment]
I might have done something already for this, see: https://github.com/kubernetes/heapster/pull/1387

**Comment by Crassirostris** [comment]
@luxas Are you sure we're on the same page? Your PR is about the architecture, and the original question is about grafana version (3.1.1), which you didn't change

Please correct me if I'm wrong

**Comment by Crassirostris** [comment]
@piosz Since the comment

> Update the grafana to that. All good

Can it be closed?

**Comment by DirectXMan12** [comment]
Closing this due to the "All good" comment.
