### ISSUE TITLE
influxdb metrics and events sinks should log errors

### ISSUE THREAD

**Issue by jonaz** [kubernetes/heapster#1376]
If a write fails in influxdb we get nothing in heapster logs and can guess the error using tcpdump and logs in influxdb. 

The problem is this:
```
if _, err := sink.client.Write(bp); err != nil {
		if strings.Contains(err.Error(), dbNotFoundError) {
			sink.resetConnection()
		} else if _, _, err := sink.client.Ping(); err != nil {
			glog.Errorf("InfluxDB ping failed: %v", err)
			sink.resetConnection()
		}
	}

```

The error returned from the Write is never logged :(

I could submit PR if that helps :)

**Comment by piosz** [comment]
@jonaz thanks for reporting. I'm happy to accept your contribution.
