### ISSUE TITLE
heapster1.1.0 Elasticsearch-1.7.5,An error report errors(panic: runtime error: invalid memory address or nil pointer dereference)

### ISSUE THREAD

**Issue by wpengcheng** [kubernetes/heapster#1377]
[root@m8dev-master ccssoft]# docker logs 3615bfec2319
I1111 03:08:33.475312       1 heapster.go:65] /heapster --source=kubernetes:http://172.18.1.219:9326?inClusterConfig=false&kubeletHttps=true&kubeletPort=10250&useServiceAccount=true&auth= --sink=elasticsearch:?nodes=http://172.18.1.231:9200&http://172.18.1.230:9200
I1111 03:08:33.475858       1 heapster.go:66] Heapster version 1.1.0
I1111 03:08:33.475977       1 configs.go:60] Using Kubernetes client with master "http://172.18.1.219:9326" and version "v1"
I1111 03:08:33.475998       1 configs.go:61] Using kubelet port 10250
I1111 03:08:33.493549       1 heapster.go:92] Starting with ElasticSearch Sink
I1111 03:08:33.493578       1 heapster.go:92] Starting with Metric Sink
I1111 03:08:33.511075       1 heapster.go:171] Starting heapster on port 8082
I1111 03:09:05.002654       1 manager.go:79] Scraping metrics start: 2016-11-11 03:08:00 +0000 UTC, end: 2016-11-11 03:09:00 +0000 UTC
I1111 03:09:20.354979       1 manager.go:152] ScrapeMetrics: time: 15.351582017s size: 280
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x1005f78]

goroutine 55 [running]:
panic(0x1786d00, 0xc820012060)
	/usr/lib/google-golang/src/runtime/panic.go:483 +0x3ef
k8s.io/heapster/vendor/github.com/olivere/elastic.(*Client).PerformRequest(0x0, 0x19d59c0, 0x4, 0xc821a5a2c0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/vendor/github.com/olivere/elastic/client.go:904 +0x10d8
k8s.io/heapster/vendor/github.com/olivere/elastic.(*IndexExistsService).Do(0xc8208e97a8, 0x0, 0x0, 0x0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/vendor/github.com/olivere/elastic/index_exists.go:40 +0x193
k8s.io/heapster/common/elasticsearch.SaveDataIntoES(0x0, 0x19fad00, 0x8, 0x19fd370, 0xc, 0x1807440, 0xc820a10280, 0x0, 0x0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/common/elasticsearch/elasticsearch.go:47 +0x107
k8s.io/heapster/metrics/sinks/elasticsearch.(*elasticSearchSink).ExportData(0xc8203c4280, 0xc8208c0120)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sinks/elasticsearch/driver.go:62 +0x483
k8s.io/heapster/metrics/sinks.export(0x7f087f718970, 0xc8203c4280, 0xc8208c0120)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sinks/manager.go:158 +0x2e9
k8s.io/heapster/metrics/sinks.NewDataSinkManager.func1(0x7f087f718970, 0xc8203c4280, 0xc8203ba960, 0xc8203ba9c0)
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sinks/manager.go:88 +0xd9
created by k8s.io/heapster/metrics/sinks.NewDataSinkManager
	/usr/local/google/home/pszczesniak/go/src/k8s.io/heapster/metrics/sinks/manager.go:97 +0x238
[root@m8dev-master ccssoft]#

**Comment by wpengcheng** [comment]
when I use es-2.3.5 and heapsterv1.2.0,it's ok

**Comment by piosz** [comment]
Closing as you were able to resolve the issue.
