### ISSUE TITLE
ES Sink: Support clusterName attribute

### ISSUE THREAD

**Issue by matthughes** [kubernetes/heapster#1383]
I have multiple K8S clusters all logging to the same Elasticsearch cluster.  It would be great if we could add a root-level field `cluster-name` to the sink.

**Comment by piosz** [comment]
cc @AlmogBaku @huangyuqi  @jamiehannaford

**Comment by AlmogBaku** [comment]
#1380

**Comment by piosz** [comment]
@AlmogBaku @andyxning is #1380 fixing this?

**Comment by andyxning** [comment]
I think so. I will try to make it tomorrow. The require is the same

**Comment by andyxning** [comment]
@matthughes Do you mean that you want this behavior for both events(eventer) and metric(heapster)?

**Comment by matthughes** [comment]
Both I would think.  It would be a configuration flag of the ES sink.

**Comment by andyxning** [comment]
This has been implemented in #1380. Please take a look and review it. :)

=======
Ning Xie


2016-12-02 21:49 GMT+08:00 Matt Hughes <notifications@github.com>:
