### ISSUE TITLE
Change images from heapster:canary to gcr.io/heapster:latest

### ISSUE THREAD

**Issue by r2d4** [kubernetes/heapster#1384]
The heapster examples and container makefiles all reference dockerhub's `heapster:canary`.  However, the releases are using gcr.io.  This was confusing for us when we copied some example YAML and tried to pin to a version (the last version pushed to dockerhub is 0.19).

Is there a reason why the "latest" image is pushed to dockerhub and the releases are to gcr.io?
If not, I'd be happy to put together a PR that switches them over to use gcr.io.

I image there are some containers that haven't been pushed to gcr.io yet (such as heapster_influxdb, kubernetes/heapster_riemann), but at least the main heapster image should be moved over.

For reference
https://github.com/kubernetes/heapster/search?p=1&q=canary&utf8=%E2%9C%93

**Comment by andyxning** [comment]
@r2d4 Why not push to both and let the users choose which one they will use. BTW, i agree that we should be consistent. :)
