### ISSUE TITLE
can not show pod metrics in grafana

### ISSUE THREAD

**Issue by perfeyhe** [kubernetes/heapster#1385]
Hi,  I run standalone heapster on kubernetes master,  the metrics I can see in grafana was only:container_name,host_id,hostname. Influxdb was also run on local, here is how I start up heapster:
docker run  -p 8082:8082 kubernetes/heapster:v0.19.0 "--source=kubernetes:http://10.0.0.15:8080?inClusterConfig=false&useServiceAccount=false" "--sink=influxdb:http://172.17.0.1:8086"

And here is the container log:
I1117 07:38:48.590753       1 heapster.go:61] /heapster --source=kubernetes:http://10.0.0.15:8080?inClusterConfig=false&useServiceAccount=false --sink=influxdb:http://172.17.0.1:8086
I1117 07:38:48.590846       1 heapster.go:62] Heapster version 0.19.0
I1117 07:38:48.591264       1 kube_factory.go:172] Using Kubernetes client with master "http://10.0.0.15:8080" and version "v1"
I1117 07:38:48.591281       1 kube_factory.go:173] Using kubelet port 10255
I1117 07:38:48.593613       1 driver.go:316] created influxdb sink with options: {root root 172.17.0.1:8086 k8s false}
I1117 07:38:48.595558       1 driver.go:245] Created database "k8s" on influxDB server at "172.17.0.1:8086"
I1117 07:38:48.603759       1 heapster.go:72] Starting heapster on port 8082

curl 127.0.0.1:8082/metrics
404
curl localhost:8082/api/v1/model/
[
  "metrics/",
  "stats/",
  "namespaces/",
  "nodes/"
 ]
curl localhost:8082/api/v1/model/metrics/
[
  "fs-usage-dev-xvda1",
  "memory-working",
  "cpu-usage",
  "fs-limit-dev-xvdb",
  "fs-limit-dev-xvda1",
  "memory-usage",
  "fs-usage-dev-xvdb",
  "cpu-limit",
  "memory-limit"
 ]

docker version:1.12.1
kubernetes version:v1.2.0

**Comment by perfeyhe** [comment]
I found the reason, There is someting wrong with my cAdvisor,I can't see the subcontainers form cAdvisor panel, so I think this is the reason heapster didn't get pod info and sent it to influxdb. I'm still working on it to find what's wrong whith my cAdvisor.

**Comment by piosz** [comment]
Could you please try to use a new stable release of Heapster v1.2.0?

**Comment by perfeyhe** [comment]
I tried heapster:canary, but pod metric still can't be shown. Then I tried to downgrade docker to lxc-docker 1.9.1, the pod metric came out. It seems cAdvisor can not work well  with kubernetes 1.2.0 and docker-engine 1.2.1, since kube-push.sh is broken, I didn't try to upgrade kubernetes to 1.4.6 to see if there are same problems in this version.
