### ISSUE TITLE
Heapster 1.2.0 redirect error

### ISSUE THREAD

**Issue by thomasfricke** [kubernetes/heapster#1391]
Looks like heapster 1.2.0 does not correctly follow the url if it does end with a  / 
Redirect does not work correctly

**Comment by GreatSUN** [comment]
Hi all,

looks like with Kubernetes 1.4.6 (tested version) the request to the kubelet is broken (at least with TLS/https). Looks like heapster is requesting /stats which is redirected via 503 to /stats/ from kubelet (works verified with curl -L) but heapster does not follow the redirect and fails.

I would need this fixed as we have a dependency to kubernetes 1.4.6 here :-(

Thanks!

**Comment by GreatSUN** [comment]
Just to add it, the parameters we are using:

            - /heapster
            - --source=kubernetes.summary_api:''?kubeletPort=10250&kubeletHttps=true&insecure=true&auth=true
            - --sink=influxdb:http://monitoring-influxdb:8086
            - --tls_cert=/opt/kube/certs/localworker.pem
            - --tls_key=/opt/kube/certs/localworker-key.pem
            - --tls_client_ca=/opt/kube/certs/ca.pem

**Comment by piosz** [comment]
@thomasfricke did it work with Heapster 1.1?

@timstclair has anything changed in Kubelet which may have impact to this?

**Comment by jmastr** [comment]
Checking...

**Comment by timstclair** [comment]
There are some changes to Kubelet TLS auth in 1.5, but I can't think of anything that would have affected 1.4

**Comment by GreatSUN** [comment]
Hi all, as far as I am able to see, it looks working with heapster 1.1.0, but not with 1.2.0.

Any idea?

**Comment by piosz** [comment]
@jimmidyson @mwringe @burmanm @DirectXMan12 any ideas?

**Comment by mwringe** [comment]
We are using 1.2 in OpenShift (based on Kubernetes 1.4), but with kubernetes source and not the kubernetes.summary_api.

You can see our option here: https://github.com/openshift/origin-metrics/blob/master/deployer/templates/heapster.yaml#L85

Where url we use is "https://kubernetes.default.svc:443"

If you use the kubernetes source, does this work for you?
