### ISSUE TITLE
can't collect real metric of memory

### ISSUE THREAD

**Issue by zuomang** [kubernetes/heapster#1403]
Env:
system: coreos
application: kubernetes v1.3.4

when i use heapster collect some metric from my kuberneters cluster, i found some container memory value is 0. So I send request to kubelet api, then response like it, as follows
![image](https://cloud.githubusercontent.com/assets/3816955/20997567/c59e0a28-bd41-11e6-95df-0e3ad039c14d.png)
the "/init.scope/system.slice/docker-...." and "/system.slice/docker-" metric is very similar, then the code will reflect the container info, the metricSetKey is same value
the data result is a map type, if key will use metricSetKey and had same value, the data send to sink will mixed

**Comment by DirectXMan12** [comment]
this is a known issue with CoreOS when using the systemd-cgroups driver with docker.  It is recommended to use the cgroupfs driver instead.
