### ISSUE TITLE
Document Sink Owners

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/heapster#1407]
We have quite a few sinks, and there are several more being proposed in PRs.  The main Heapster maintainers aren't necessarily familiar with all the sinks, so we should have one or two known "maintainers" for each sink.  If we can't find a sink owner, we should probably deprecate the sink unless someone steps up.

**Comment by DirectXMan12** [comment]
These are the current likely candidates based on a quick check of git history.  The ones with `?` next to them I was unsure about, general due to lack of recent activity on the sink.  If you're on this list, please chime in and let us know if you're ok being pinged for reviews on the listed sink.

- ElasticSearch: @AlmogBaku / @andyxning
- GCM: @kubernetes/heapster-maintainers 
- Hawkular: @burmanm / @mwringe 
- InfluxDB: @kubernetes/heapster-maintainers 
- Metric: @kubernetes/heapster-maintainers 
- Kafka: @huangyuqi ?
- Monasca: @taimir / @cheld ?
- OpenTSDB: @petergardfjall ?
- Riemann: @jsoriano ?

**Comment by jsoriano** [comment]
I wouldn't say that I'm actively maintaining the Riemann sink :) But sure, you can ping me if reviews are needed.
And in principle I could also help with Graphite sink if #1341 is merged. Maybe you can also ask to @theairkit after his great work reviewing and testing my PR.

**Comment by DirectXMan12** [comment]
@jsoriano are you still using the Riemann sink?  If nobody is actively using it, we might want to put out the call for interest, and if nobody is interested, simply deprecate it.

**Comment by jsoriano** [comment]
We are using it to forward metrics to Graphite, but in parallel we are also testing the Graphite sink of the PR and we could really promote it in any moment and stop using the Riemann one, so no problem for me to deprecate it.
There is an open PR (#1339) by @shmish111 for the events sink, I don't know if he is using heapster with Riemann.

**Comment by huangyuqi** [comment]
Hi, @DirectXMan12 I can maintain ES and Kafka Sink;

**Comment by ezeev** [comment]
I'll maintain the Wavefront sink (once it is merged)

**Comment by andyxning** [comment]
@DirectXMan12 I may maintain InfluxDB, too. We currently use InfluxDB to store metrics internally.

**Comment by petergardfjall** [comment]
@DirectXMan12: I only submitted a small patch for a piece of code that wasn't working properly. I'm not sure who wrote the majority of the OpenTSDB sink, but I would assume that that person is a more suitable candidate.

**Comment by burmanm** [comment]
@DirectXMan12 Yes, I can take care of the Hawkular sink (and I assume @mwringe will also)

**Comment by theairkit** [comment]
@DirectXMan12 I can take care of Graphite Sink, jointly with @jsoriano of course)
Also, I can do some tests and reviews for others sinks, if needed.

**Comment by cheld** [comment]
I think the Monasca sink could be removed, because support for Kuberentes has been added directly to Monasca.

WDYT?

**Comment by AlmogBaku** [comment]
Thanks for the honor 🗡 

I'll be glad to do that :)

**Comment by DirectXMan12** [comment]
I've updated the list above.  It seems Monasca and Riemann could soon become candidates for deprecation, although I'd like to hear from @shmish111 about the latter.  The original author for the OpenTSDB sink seems to have been @bluebreezecf, so if they're no longer interested, we may wish to consider our options for that one as well.

Ping @piosz @mwielgus any other comments?

**Comment by bluebreezecf** [comment]
@DirectXMan12 I can take care of OpenTSDB sink. Sorry to reply so late.

**Comment by DirectXMan12** [comment]
Thanks, I've updated the list.

**Comment by DirectXMan12** [comment]
@piosz  @fgrzadkowski ok to officially commit this list in the repo?  Thoughts on the deprecation?

**Comment by AlmogBaku** [comment]
@DirectXMan12 is that means we'll get writing privileges ?

**Comment by DirectXMan12** [comment]
It would be nice to get that, or something like the main Kubernetes repo OWNERS functionality.  I'll keep you posted :-)

**Comment by piosz** [comment]
As discussed offline SGTM

**Comment by piosz** [comment]
FYI @fgrzadkowski added all sink maintainers to @kubernetes/heapster-reviewers team.

**Comment by jamtur01** [comment]
I'd be happy to take care of the Riemann sink.

**Comment by mcorbin** [comment]
I can take care of the Riemann sink too (i just need some time to dig into the code).

**Comment by piosz** [comment]
@jamtur01 @mcorbin please send a PR with appriopriate docs update

**Comment by piosz** [comment]
To be clear, one of you can do it. I doesn't have to be two separate PRs.

**Comment by jsoriano** [comment]
@jamtur01 @mcorbin great! If you have any doubt with the code of this sink I can try to help :)
There is currently an open pull-request for the events sink (#1339)

**Comment by mcorbin** [comment]
@jamtur01 @piosz I did a PR.
