### ISSUE TITLE
Cleanup Heapster Docker file

### ISSUE THREAD

**Issue by timstclair** [kubernetes/heapster#1409]
- Heapster is already statically linked, so there there shouldn't be any need for glibc
- Use the scratch base image
- Is the hosts volume still needed? (`VOLUME /var/run/heapster/hosts`)

**Comment by luxas** [comment]
I have cleaned all images up PR https://github.com/kubernetes/heapster/pull/1387 for the other architectures, and it works fine when using those images.

 I think we should be able to just use my updated/alternative images all the time; for amd64 as well.

**Comment by timstclair** [comment]
Yes, those images are much better. Do we need the busybox base though? Can we get away with just using scratch?

**Comment by luxas** [comment]
I've heard @thockin pray earlier that there should always be a base image :)
We need busybox for grafana, but not really for the others.

What are your main arguments for ripping the base image away? Space? Security?
The downside is that it gets harder to debug at least

**Comment by timstclair** [comment]
Security. Debug-ability is definitely a legitimate concern, so we may want to wait for https://github.com/kubernetes/kubernetes/issues/27140 to land before moving to it. Either way, the images in your PR are a big improvement, so moving to scratch is lower priority.

The one other feature I would like to see is running as a non-root user, so we may want to add a user in the docker image to run as.

**Comment by thockin** [comment]
https://github.com/kubernetes/kubernetes/issues/10834

**Comment by luxas** [comment]
This is fixed now in #1387

cc @piosz please close
