### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by AlmogBaku** [kubernetes/heapster#1416]
Kubernetes 1.5 is coming.. and we haven't released recently (although there were some big changes since last release)...

**Comment by chulkilee** [comment]
Please release new docker image as well - I do not want to use canary on non-dev clusters :)

**Comment by AlmogBaku** [comment]
@piosz ?

**Comment by AlmogBaku** [comment]
@DirectXMan12 @piosz ??

**Comment by AlmogBaku** [comment]
what's going on?

**Comment by AlmogBaku** [comment]
Any update?

**Comment by DirectXMan12** [comment]
We should have one soon.  Sorry for the delay.  Going forward, we'll have a better procedure for releases :-)

**Comment by piosz** [comment]
I've published https://github.com/kubernetes/heapster/releases/tag/v1.3.0-beta.0

**Comment by luxas** [comment]
@piosz Can you make a v1.3 milestone so we see what's left to merge into v1.3?
Can you release a beta.1 today as well? And while pushing the beta.1 images, please also push influxdb v1.1.1 and grafana v4.0.2 so we can test the influxdb deployment officially, it should "just work" :)

Lastly we also need to aggregate a changelog between v1.2 and v1.3.

cc @Crassirostris

**Comment by piosz** [comment]
Added milestone. Will draft the new release early next week.

**Comment by luxas** [comment]
Cool, please add issues/PRs that you think should be in the next release to that milestone

**Comment by DirectXMan12** [comment]
I'm working on a rebase right now as well.

**Comment by andyxning** [comment]
@DirectXMan12 This issue should be closed for now.

**Comment by andyxning** [comment]
@AlmogBaku Should we close this?
