### ISSUE TITLE
Riemman client repository AWOL

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/heapster#1419]
I just tried to do a `godep restore`, and was mildly disturbed to find that the repository for the client used for our Riemman sink has disappered: https://github.com/bigdatadev/goryman returns a 404.

I'm not entirely sure if there are any forks hanging around, but if not, we may wish to deprecate and remove the sink, since we can't get updates for the client.

CC @piosz @jsoriano @shmish111

**Comment by jsoriano** [comment]
Hi @DirectXMan12,

I had a local clone with all changesets, I have pushed it to https://github.com/jsoriano/goryman, we could use it while we deprecate the sink.

In any case, @cjgdev, as the last committer to goryman, do you know why the repository is not available anymore?

**Comment by DirectXMan12** [comment]
@jsoriano thanks for the repo save!  @piosz sound fine to substitute @jsoriano's repo in the mean time?

**Comment by piosz** [comment]
@luxas did you have such problem?

**Comment by luxas** [comment]
No actually not, strange that Godeps worked for me. Or it failed on lots of other things that I'm fixing in PR #1454, but not this

**Comment by piosz** [comment]
fixed in #1448
