### ISSUE TITLE
HPA and other metrics on InfluxDB + Grafana

### ISSUE THREAD

**Issue by fwynyk** [kubernetes/heapster#1424]
Hi,

Using InfluxDB + Grafana we only get resource metrics like CPU/Memory/Network/Filesystem. It would be very nice to have metrics like HPA statistics, number of healthy nodes/masters, rollout status, etc. I didn't find any informations in how to get these metrics from heapster to put into InfluxDB/Grafana.

**Comment by piosz** [comment]
Sorry, this is out of the scope of Heapster. There is a plan to build in 2017 infrastore - a repository of data about Kubernetes infrastructure which should have such metrics.
