### ISSUE TITLE
heapster-riemann sink

### ISSUE THREAD

**Issue by sujithnss** [kubernetes/heapster#1425]
Hi

Im pretty novice to this platform. Here I'm facing an issue with the heapster-riemann sink as its throwing an error like image not found. But the similar sink with Influx/Grafana works well. Could you guys please advise.

I was running $ kubectl create -f deploy/kube-config/riemann/

Best Regards
Sujith P V

**Comment by piosz** [comment]
We do not plan to maintain Riemann image. Also according to https://github.com/kubernetes/heapster/blob/master/docs/sink-owners.md we are planning to remove support for Riemann unless we will find owners for it.

cc @DirectXMan12 @jsoriano
