### ISSUE TITLE
labelSelector not working with heapster and hpa

### ISSUE THREAD

**Issue by sjpotter** [kubernetes/heapster#1433]
Following the example here I create a k8s deployment and an hpa

http://kubernetes.io/docs/user-guide/horizontal-pod-autoscaling/walkthrough/

but it never gets metrics i.e. in events I see

Warning   FailedGetMetrics   {horizontal-pod-autoscaler }   unable to get metrics for resource cpu: no metrics returned from heapster

with some instrumenting I see the podautoscaler is calling

http://127.0.0.1:8080/api/v1/proxy/namespaces/kube-system/services/http:heapster:/apis/metrics/v1alpha1/namespaces/default/pods?labelSelector=run%3Dphp-apache

which is the correct label for this deployment and to verify, a describe pod show

```
Labels:		pod-template-hash=2185300881
		run=php-apache
```

Using kubectl proxy to make the same call I see

{
  "metadata": {},
  "items": null
 }

which makes sense with the above warning I see from events

for reference, this is how the container is configured in k8s

```
  heapster:
    Container ID:	docker://611e849048d60153240069a4b48d2c21bf5e862accd8b154105f95428bab425b
    Image:		gcr.io/google_containers/heapster:v1.2.0
    Image ID:		docker://sha256:7cd51f2f6a9741aee93a73dfc48ee22db540a8c8d08147e0ee23ddeef10e9442
    Port:		
    Command:
      /heapster
      --source=kubernetes.summary_api:''
      --sink=influxdb:http://monitoring-influxdb:8086
    Limits:
      cpu:	88m
      memory:	204Mi
    Requests:
      cpu:		88m
      memory:		204Mi
    State:		Running
      Started:		Sat, 24 Dec 2016 23:55:20 -0800
    Ready:		True
    Restart Count:	0
    Liveness:		http-get http://:8082/healthz delay=180s timeout=5s period=10s #success=1 #failure=3
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-vt89s (ro)
    Environment Variables:	<none>
```

In digging into that a little, I don't see a concept of labels being output from kubelet's stat summary api so have no idea how a labelselector could even then work.  At a bit of a loss.  

creating the issue here as encountering it as a heapster api get issue, but perhaps its something else.

**Comment by sjpotter** [comment]
In digging even deeper into heapster, I see that labels are handled by an embedded kubeclient wrapped in a caching layer of sorts, but dont have a good way of debugging it.  Really no clue what could be going wrong here besides the kubeclient not being setup correctly.

**Comment by sjpotter** [comment]
So as a followup, found this code

https://github.com/kubernetes/heapster/blob/master/metrics/apis/metrics/handlers.go#L245-L277

and the answer appears to be: this is due to heapster having a disconnect between its model and metrics api.

the model api will show pod level stats for any "containers" that kubelet's stats/summary api says belong to the pod.  However, the metrics api iterates over the actual containers returned from kubeclient in kube's api pod struct.  If those containers aren't represented in the data stored from stats/summary (say because only total pod data was returned in a single "opaque" container) then heapster will return no data via the metrics api. while it will will show usage in the model api.

This also makes it harder to include overhead related to a pod that is external to a container itself, kubelet's stat summary could include a "container" that captures that, but heapster as is will just ignore.

anyways, this isn't a bug per say, unless one considers the disconnect between model and metric responses to be a bug.

**Comment by piosz** [comment]
@DirectXMan12 can you please take a look?

cc @jszczepkowski

**Comment by DirectXMan12** [comment]
> If those containers aren't represented in the data stored from stats/summary (say because only total pod data was returned in a single "opaque" container) then heapster will return no data via the metrics api. while it will will show usage in the model api.

Yeah, do to current requirements from the consumers of the resource metrics API (the HPA), we need to have per-container usage stats (this is not strictly necessary, but it's how the HPA currently works).

What's the situation in your cluster in which cAdvisor is returning only per-pod usage stats?

**Comment by sjpotter** [comment]
I worked around it, but in a CRI environment, one doesn't necessarily have cadvisor running in a traditional way.  Ex would be in running the pod in its own VM where the hypervisor is running in the pod cgroup so can see its usage at the pod level, but the pod itself is opaque to the host.

**Comment by DirectXMan12** [comment]
Hmm... ok.  Not sure how much we support such a setup where the stats provider doesn't get visibility into the pod.  cc @kubernetes/sig-node-feature-requests what's the current story around setups like that and/or around CRI and stats integration?

**Comment by pramodshaw** [comment]
similar issue, I am facing. How to fix this?
![1](https://cloud.githubusercontent.com/assets/17613381/23743860/39c67c68-04d8-11e7-8772-4c57b678ace7.jpg)

**Comment by DirectXMan12** [comment]
Closing.  This was due to not running a standard metrics setup, which Heapster doesn't really support.
