### ISSUE TITLE
Add nginx ingress controller monitoring sources

### ISSUE THREAD

**Issue by typhoonzero** [kubernetes/heapster#1435]
We are using nginx ingress controller on our production environment. It's sometimes very important to have nginx status handy to find out what's happening on the nginx server, like the nginx connections count or requests per second. Before we moved to kubernetes, we have that metrics collected by `tcollector` and `ganglia`. 

I've looked into the source code and docs, and did not find any instructions for how to add a new source.

**Comment by DirectXMan12** [comment]
We're not adding new sources at the moment.  In the future, such a usecase will be covered as part of the new monitoring vision by the third-party monitoring pipeline components (see https://github.com/kubernetes/community/blob/master/contributors/design-proposals/monitoring_architecture.md)
