### ISSUE TITLE
build heapster images from alpine 3.2 in v0.18.0，glibc show IO ERROR  

### ISSUE THREAD

**Issue by jianzi123** [kubernetes/heapster#1436]
when I build heapster images from alpine 3.2 with heapster v0.18.0, show some errors below
-------------------------------------------------------------------------------------------------------------
[root@centos-minion2 heapster]# docker build -t gcr.io/google_containers/heapster:v0.18.0 ./deploy/docker/
Sending build context to Docker daemon  21.9 MB
Step 1 : FROM alpine:3.2
 ---> 7bed0150ea37
Step 2 : MAINTAINER vishnuk@google.com
 ---> Using cache
 ---> 675a72d9b5f5
Step 3 : RUN apk --update add curl ca-certificates tar &&     curl -Ls https://circle-artifacts.com/gh/andyshinn/alpine-pkg-glibc/8/artifacts/0/home/ubuntu/alpine-pkg-glibc/packages/x86_64/glibc-2.21-r2.apk > /tmp/glibc-2.21-r2.apk &&     apk add --allow-untrusted /tmp/glibc-2.21-r2.apk
 ---> Running in 34476b2497a7
fetch http://dl-cdn.alpinelinux.org/alpine/v3.2/main/x86_64/APKINDEX.tar.gz
(1/11) Installing run-parts (4.4-r0)
(2/11) Installing openssl (1.0.2j-r0)
(3/11) Installing lua5.2-libs (5.2.4-r0)
(4/11) Installing lua5.2 (5.2.4-r0)
(5/11) Installing ncurses-terminfo-base (5.9-r3)
(6/11) Installing ncurses-widec-libs (5.9-r3)
(7/11) Installing lua5.2-posix (33.3.1-r2)
(8/11) Installing ca-certificates (20141019-r2)
(9/11) Installing libssh2 (1.5.0-r1)
(10/11) Installing curl (7.49.1-r4)
(11/11) Installing tar (1.28-r1)
Executing busybox-1.23.2-r0.trigger
Executing ca-certificates-20141019-r2.trigger
OK: 9 MiB in 26 packages
ERROR: /tmp/glibc-2.21-r2.apk: IO ERROR
The command '/bin/sh -c apk --update add curl ca-certificates tar &&     curl -Ls https://circle-artifacts.com/gh/andyshinn/alpine-pkg-glibc/8/artifacts/0/home/ubuntu/alpine-pkg-glibc/packages/x86_64/glibc-2.21-r2.apk > /tmp/glibc-2.21-r2.apk &&     apk add --allow-untrusted /tmp/glibc-2.21-r2.apk' returned a non-zero code: 255
------------------------------------------------------------------------------------------------
i wonder whether the dockfile in heapster need to be updated.

**Comment by piosz** [comment]
Heapster  v0.18.0 is no longer supported. Please use a new stable release.
