### ISSUE TITLE
Why there is only one index in Elasticsearch when Heapster is integrated with Elasticsearch?

### ISSUE THREAD

**Issue by qianzhangxa** [kubernetes/heapster#1440]
Hi,

I am using Heapster 1.2.0 which is integrated with Elasticsearch 2.4.1 with "--sink" option, and I found there will be only one index in Elasticsearch for Heapster, like this:
```
green  open   heapster              1   0     411411            0     62.6mb         62.6mb
```
However the index for Logstash is like this:
```
green  open   logstash-2017.01.03   1   0     622530            0    399.6mb        399.6mb 
green  open   logstash-2017.01.04   1   0      74112            0     46.7mb         46.7mb 
```
So there will be one index for Logstash every day. Can I configure Heapster to have the similar behavior with Logstash, i.e., have one index for each day? In that way, I can easily remove the old performance metrics that Heapster sends to Elasticsearch, e.g., remove the old index regularly.

**Comment by DirectXMan12** [comment]
@AlmogBaku / @huangyuqi / @andyxning

**Comment by AlmogBaku** [comment]
you should use the beta release

**Comment by rikatz** [comment]
@qianzhangxa I think that also that #1439 also 'solves' this, as the docs seems with some kind of problem.

I'm working also to update the library #1443 so ES 5 also works with heapster :)

**Comment by qianzhangxa** [comment]
Thanks @rikatz !

So does that mean the next release (v1.3.0) will support ES 5 and it will create time-based indices in ES?

**Comment by AlmogBaku** [comment]
ES5 is still WIP, but I hope it will support it

**Comment by rikatz** [comment]
@AlmogBaku Thanks! Can you take a look on the PR #1445 as this is stopping the possibility to use ES5 library because of an issue with Godeps? Thanks!!!

**Comment by mihivagyok** [comment]
Hello, do you know when v1.3.0 stable will be released?
Thanks!

**Comment by rikatz** [comment]
@DirectXMan12 @qianzhangxa I think this issue can be closed, as Elasticsearch 5 is supported in Heapster and is using the correct index rotation.

Thanks!
