### ISSUE TITLE
I would like to know if heapster supports average value

### ISSUE THREAD

**Issue by zte-wangning** [kubernetes/heapster#1442]
>   I would like to confirm whether the heapser supports an average value of metrics for a given period of time. For example, in one minute, heapster in 10 seconds, 30 seconds, 50 seconds to collect the data of the three points of memory_usage. Can the heapster calculate the average of the three points for this minute?

**Comment by DirectXMan12** [comment]
No, Heapster does not calculate averages.  You can calculate them yourself.  If your sink supports the Oldtimer interface (currently only InfluxDB), you can also use that to fetch averages.
