### ISSUE TITLE
GPU metrics on kubernetes

### ISSUE THREAD

**Issue by pineking** [kubernetes/heapster#1449]
The GPU task will be supported on kubernetes soon.
I wonder how to add GPU metrics on heapster, so the users can view the usage of GPU information via Grafana+InfluxDB.

**Comment by andyxning** [comment]
I am curious about this, too. IMO, this is mainly related to cAdvisor or libcontainer. Heapster is just collecting time series data from cAdvisor. :)

**Comment by andyxning** [comment]
It seems that @jianzhangbjz has already post an issue about this in [cAdvisor#1436](https://github.com/google/cadvisor/issues/1436).

**Comment by pineking** [comment]
@andyxning thanks for the correction. I will follow the cAdvisor issue.

**Comment by DirectXMan12** [comment]
we can reopen once cAdvisor gets support
