### ISSUE TITLE
Images tags not found

### ISSUE THREAD

**Issue by VAdamec** [kubernetes/heapster#1453]
Trying to start heapster with influxdb, but tags contain in master does not exists:

```
Failed to pull image "gcr.io/google_containers/heapster-grafana:v2.6.0-2" Tag v2.6.0-2 not found
Failed to pull image "gcr.io/google_containers/heapster-influxdb:v0.13.0" Tag v0.13.0 not found 
```

which tags can be used ? Or is Heapster just for Google cloud ?

**Comment by tobad357** [comment]
We are also seeing the same issue, seems like they haven't been built and pushed yet

**Comment by alirezaDavid** [comment]
i have similar issue.

**Comment by VAdamec** [comment]
With heapster-1.3.0-beta it works (https://github.com/kubernetes/heapster/archive/v1.3.0-beta.0.zip), I'm not getting graphs in kubernetes-dashboard, but I can see them via Grafana now. With yaml in master I can see metrics i dashboard, but cannot start grafana. I'll put it together and we will see ;-)

**Comment by piosz** [comment]
@Crassirostris could you please check this and build appropriate images if needed?

**Comment by luxas** [comment]
@piosz @Crassirostris Please wait one second with this until we've got #1454 merged

@VAdamec @alirezaDavid @tobad357 These images were committed to the repo some days ago in #1387, and we will push the images soon. This all will be fixed with and will be a part of v1.3.

**Comment by piosz** [comment]
@luxas this is about old images. Once #1454 is merged we can release a new images.

**Comment by luxas** [comment]
v0.13.0 is new, but will directly be updated to v1.1.1
also v2.6.0-2 is old, we should just push what we have tested with heapster v1.3, and I'm sure these guys are happy with the latest and greatest stuff that works with heapster v1.3 :)

The plan is: heapster v1.3, influxdb: v1.1.1 and grafana v4.0.2, and that will happen soon

**Comment by Crassirostris** [comment]
The problem is that `grafana` image (not even `heapster-grafana`) of version `v2.6.0-2` was pushed to the kubernetes repo on docker hub, not to gcr

I pushed the following images to the gcr

```
gcr.io/google_containers/heapster-grafana:v2.6.0-2
gcr.io/google_containers/heapster-influxdb:v0.13.0
```

Feel free to check and close this issue if no problems occur

**Comment by piosz** [comment]
Thanks @Crassirostris
