### ISSUE TITLE
I would like to know whether the values collected by Heaspter are averages over the sampling interval

### ISSUE THREAD

**Issue by zte-wangning** [kubernetes/heapster#1457]
I would like to know whether the values collected by Heaspter are averages over the sampling interval and  can represent the average of the sampling intervals, or just a single point in the sampling interval. For example, set the heapster sampling interval to 1 minute, can the reported points represent the average of one minute? If the point can't represent the average,how can I get the average value in one minute.

**Comment by andyxning** [comment]
@zte-wangning 

> I would like to know whether the values collected by Heaspter are averages over the sampling interval and can represent the average of the sampling intervals, or just a single point in the sampling interval.

Heapster's metric values are collected from cAdvisor actually. cAdvisor reads and parses values from `cgroups` files at specified interval. So, the answer is values collected by Heapster are not averages over the sampling, they are just single points in the sampling interval.

>  For example, set the heapster sampling interval to 1 minute, can the reported points represent the average of one minute? 

If you want to monitor more precisely, you can adjust following command line arguments. For example, we collects metrics every 10s.
* Heapster: `-metric_resolution 10s`
* Kubelet(cAdvisor): `--global-housekeeping-interval=5s --housekeeping-interval=5s`(**Note: housekeeping interval should be less than `metric_resolution`.**)

This will make Kubelet(cAdvisor) collects metric values from `cgroups` files every 5s, and heapster will query these metrics every 10s. 

> If the point can't represent the average,how can I get the average value in one minute.

You should use one of the sinks heapster supports, such as InfluxDB, to store metric values. After then, you can use the [aggregation functions InfluxDB supports](https://docs.influxdata.com/influxdb/v1.1//query_language/functions) to query average metric values in one minute.

**Comment by piosz** [comment]
@andyxning thanks for the answer
@zte-wangning pelase reopen in case of more questions
