### ISSUE TITLE
Really confused about versions for monitoring

### ISSUE THREAD

**Issue by tonyjchong** [kubernetes/heapster#1461]
Hi, 

I have been reading docs and trying to get heapster, grafana and influxdb running on K8S 1.4.7 for the past few days and I'm guessing the versions of the publically published heapter-* containers on GCR might be outdated. Or, maybe just this one doesn't exist:

gcr.io/google_containers/heapster-grafana:v4.0.2

I'm pretty sure the version of heapster-grafana:v2.6.0-2 that is pubically accessible doesn't work with the latest version of influxdb as none of the metrics show up due to an earlier identified issue.

Can someone provide guidance as to which heapster-grafana, heapster-influxdb and heapster containers work together, that are publically accessible?

Thanks a lot!

**Comment by VAdamec** [comment]
This should be already fixed see #1453 also you can test v1.3.0-beta.0 this works for me, but I'm on version 1.5.1 so need to be verified for older versions. See my small [example](https://github.com/VAdamec/ansible-kubeadm-cluster) how to create small demo cluster to test functionalities.

**Comment by luxas** [comment]
@tonyjchong Thanks for the issue and sorry for the confusion.
We're planning to make this clear with the v1.3 release, see: https://github.com/kubernetes/heapster/issues/1453#issuecomment-272007293
