### ISSUE TITLE
images in grafana-deployment and influxdb-deployment dont exist

### ISSUE THREAD

**Issue by DominicDV** [kubernetes/heapster#1463]
Getting an imagepull error when using them in kubernetes.
https://github.com/kubernetes/heapster/tree/master/deploy/kube-config/influxdb

When looking which images exist in the repository, then only an outdated one
https://console.cloud.google.com/kubernetes/images/tags/heapster-grafana?location=GLOBAL&project=google-containers

**Comment by alirezaDavid** [comment]
#1453 related.

**Comment by piosz** [comment]
Closing as duplicate
