### ISSUE TITLE
error when open localhost:9090/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana

### ISSUE THREAD

**Issue by alirezaDavid** [kubernetes/heapster#1467]
Hi 
i created heapster stack with `kubectl create -f heapster/deploy/kube-config/influxdb` on kubernets deployed on coreos.

LOGS:
`kubectl version`: `GitVersion:v1.5.1`
`kubectl cluster-info`: 
```
Kubernetes master is running at https://178.62.113.66:6443
Heapster is running at https://1.1.1.1:6443/api/v1/proxy/namespaces/kube-system/services/heapster
KubeDNS is running at https://1.1.1.1:6443/api/v1/proxy/namespaces/kube-system/services/kube-dns
monitoring-grafana is running at https://1.1.1.1:6443/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
monitoring-influxdb is running at https://1.1.1.1:6443/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb
```

`kubectl get pods --all-namespaces`:
```
kube-system   monitoring-grafana-3783935480-vp2nh     1/1       Running   0          1m
kube-system   monitoring-influxdb-651061958-tdxj3     1/1       Running   0          1m
```
`gcr.io/google_containers/heapster-grafana:v2.6.0-2`
`gcr.io/google_containers/heapster:v1.3.0-beta.0`
`gcr.io/google_containers/heapster-influxdb:v0.13.0`

when i request to `http://localhost:9090/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/` i got error: `the server could not find the requested resource`

![image](https://cloud.githubusercontent.com/assets/2995061/21974756/f833d7b4-dbdd-11e6-88af-632628c5b639.png)

**Comment by ottoyiu** [comment]
same issue here with those version of images as well.

**Comment by DirectXMan12** [comment]
I don't think the Graphana dashboard is not designed to be accessed through the Kubernetes API server HTTP proxy, and will attempt to load it's resources from the root of wherever the paged is accessed through.  You should access it through its service IP instead (or through an Ingress object).
