### ISSUE TITLE
getsockopt: connection timed out

### ISSUE THREAD

**Issue by stege** [kubernetes/heapster#1477]
Hi,

I used kubeadm to install kubernetes on three nodes. I also installed weave as addon. So far everything works fine including the dashboard. But as soon as I follow the instructions to install heapster with influxdb (I had to use the fix from #1469 to even install it with the curren master version) the dashboard becomes unusable. It seems that almost every requests starts to timeout. 

Accessing 
`http://localhost:8001/api/v1/proxy/namespaces/kube-system/services/heapster/`

results in
```
Error: 'dial tcp 10.42.0.3:8082: getsockopt: connection timed out'
Trying to reach: 'http://10.42.0.3:8082/'
```

I used `kubectl proxy` for it. Pinging the IP works from any of the nodes, but a wget fails with the same error.

I also tried to use release-1.2 but no success. I'm not sure if it's a issue with my setup or heapster, but as I just followed the instructions for kubeadm I don't know what I should change.

Versions:

```
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.1", GitCommit:"82450d03cb057bab0950214ef122b67c83fb11df", GitTreeState:"clean", BuildDate:"2016-12-14T00:57:05Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.2", GitCommit:"08e099554f3c31f6e6f07b448ab3ed78d0520507", GitTreeState:"clean", BuildDate:"2017-01-12T04:52:34Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by judexzhu** [comment]
I have the same issue with you , add the amd64 as #1469 said, either heapter timeout or Grafana time out with the Influxdb , looks like only one can connect to influxdb 8086 in the same time 

2017-01-23T03:58:22.399761000Z I0123 03:58:22.397433       1 influxdb.go:231] created influxdb sink with options: host:monitoring-influxdb:8086 user:root db:k8s
2017-01-23T03:58:22.400195000Z I0123 03:58:22.397518       1 heapster.go:193] Starting with InfluxDB Sink
2017-01-23T03:58:22.400636000Z I0123 03:58:22.397535       1 heapster.go:193] Starting with Metric Sink
2017-01-23T03:58:22.417996000Z I0123 03:58:22.416795       1 heapster.go:105] Starting heapster on port 8082
2017-01-23T04:00:25.285607000Z W0123 04:00:25.281553       1 manager.go:119] Failed to push data to sink: InfluxDB Sink
2017-01-23T04:01:12.512830000Z E0123 04:01:12.507850       1 influxdb.go:150] Failed to create infuxdb: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp 10.101.152.15:8086: getsockopt: connection timed out

but the grafana can connect no issue , but no graphic , for heapster didnt send any data to influxdb 

hope someome can help

**Comment by drinktee** [comment]
similar problem. The network is ok. I started a busybox container and can curl the url and ping other containers, but dashboard print this.
```
[2017-05-09T03:59:53Z] Outcoming response to 172.17.1.1:52422 with 200 status code
Skipping Heapster metrics because of error: an error on the server ("Error: 'dial tcp 172.17.1.7:8082: getsockopt: connection timed out'\nTrying to reach: 'http://172.17.1.7:8082/api/v1/model/namespaces/default/pod-list/curl-3393124085-dcldc,curl2-2854614873-wgzkj/metrics/cpu/usage_rate'") has prevented the request from succeeding (get services heapster)
[2017-05-09T04:00:35Z] Outcoming response to 172.17.1.1:50410 with 200 status code
```
And the heapster seems ok.
```
I0509 03:53:57.371188       1 heapster.go:72] /heapster --source=kubernetes:https://kubernetes.default --sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086
I0509 03:53:57.371233       1 heapster.go:73] Heapster version v1.3.0
I0509 03:53:57.371509       1 configs.go:61] Using Kubernetes client with master "https://kubernetes.default" and version v1
I0509 03:53:57.371528       1 configs.go:62] Using kubelet port 10255
I0509 03:53:57.417024       1 influxdb.go:252] created influxdb sink with options: host:monitoring-influxdb.kube-system.svc:8086 user:root db:k8s
I0509 03:53:57.417058       1 heapster.go:196] Starting with InfluxDB Sink
I0509 03:53:57.417067       1 heapster.go:196] Starting with Metric Sink
I0509 03:53:57.425744       1 heapster.go:106] Starting heapster on port 8082
I0509 03:54:05.025078       1 influxdb.go:215] Created database "k8s" on influxDB server at "monitoring-influxdb.kube-system.svc:8086"
```

**Comment by DirectXMan12** [comment]
So, you can curl the URL that the dashboard fails on from other pods, but not from the dashboard pod?

**Comment by jorgelon** [comment]
In my cases I found the solution some weeks ago, sorry. I simply needed flannel working in my master node to give connectivity to heapster pod

**Comment by taylorshaulis** [comment]
I would like to confirm the solution provided by @jorgelon 

Switching from networking.kope.io to networking.flannel resolved my heapster getsockopt: connection timed out issue.

**Comment by nicolas-g** [comment]
also confirming @jorgelon  , it was fixed by simple running : 
```
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
```
