### ISSUE TITLE
Problem with pushing multi-arch images to gcr.io 

### ISSUE THREAD

**Issue by piosz** [kubernetes/heapster#1478]
When I'm trying to push Heapster images after support for multiple architectures was introduced in #1387 I can see the following issue:
```
./manifest-tool push from-args --platforms linux/amd64,linux/arm,linux/arm64,linux/ppc64le,linux/s390x --template gcr.io/google_containers/heapster-ARCH:v1.3.0-beta.1  --target gcr.io/google_containers/heapster:v1.3.0-beta.1
INFO[0000] Retrieving digests of images...              
INFO[0002] Image "gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1" is digest sha256:<hash>; size: 949 
INFO[0004] Image "gcr.io/google_containers/heapster-arm:v1.3.0-beta.1" is digest sha256:<hash>; size: 950 
INFO[0006] Image "gcr.io/google_containers/heapster-arm64:v1.3.0-beta.1" is digest sha256:<hash>; size: 950 
INFO[0008] Image "gcr.io/google_containers/heapster-ppc64le:v1.3.0-beta.1" is digest sha256:<hash>; size: 950 
INFO[0010] Image "gcr.io/google_containers/heapster-s390x:v1.3.0-beta.1" is digest sha256:<hash>; size: 950 
FATA[0030] Registry push unsuccessful: response 400: 400 Bad Request 
make: *** [push] Error 1
```

It seems that images for specific architectures was pushed but there is no generic image.

**Comment by luxas** [comment]
I've contacted some gcr.io folks, I'm waiting for an answer from them. 
It works fine on docker hub and _should work_ on gcr as well, but doesn't

Meanwhile, heapster-grafana-amd64:v4.0.2 is available

**Comment by whereisaaron** [comment]
Another limitation of gcr.io is it doesn't have any human way to find tags. You can use `docker search` to find images, but then you need to using the API to find tags, e.g. `curl https://gcr.io/v2/google-containers/heapster-influxdb-amd64/tags/list`, these appear to be the current tags.

```
gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1
gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1
```

**Comment by piosz** [comment]
ping @luxas

**Comment by luxas** [comment]
Sent a PR: #1502

**Comment by luxas** [comment]
@piosz This was fixed by inactivating the functionality temporarily, we can now close this

**Comment by vielmetti** [comment]
Can we reopen this? GCR now has multiarch support.

**Comment by luxas** [comment]
@vielmetti please send a PR with the small change to re-enable manifest lists :)
