### ISSUE TITLE
grafanda dashboard error parsing query: found SELECT, expected ; at line 2, char 1

### ISSUE THREAD

**Issue by alirezaDavid** [kubernetes/heapster#1488]
I set kuberentes cluster and  `kubectl create -f deploy/kube-config/influxdb/`
`kubernets version: 1.5.2`

but when open dashboard i got this error:

```
{
  "error": "error parsing query: found SELECT, expected ; at line 2, char 1",
  "message": "error parsing query: found SELECT, expected ; at line 2, char 1"
}
```

my images:

`gcr.io/google_containers/heapster-influxdb:v0.13.0`
`gcr.io/google_containers/heapster-grafana:v2.6.0-2`
`gcr.io/google_containers/heapster:v1.3.0-beta.0`

![screen shot 2017-01-26 at 8 00 42 pm](https://cloud.githubusercontent.com/assets/2995061/22340294/332c09a0-e402-11e6-8533-23ec6e0eae4a.png)

Thanks

**Comment by whereisaaron** [comment]
Hi @alirezaDavid I don't know if either of these are your problem, but two things to check:

1) The image versions you quote is way older that current, maybe you cloned an old version/branch?
[Current versions](kubernetes/heapster/tree/master/deploy/kube-config/influxdb) are:
`gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1`
`gcr.io/google_containers/heapster-grafana-amd64:v4.0.2`
`gcr.io/google_containers/heapster:v1.3.0-beta.0`
Note, due so some image build bug, you need to add the architecture, e.g. `-amd64`.

2) Once you are using influxdb v1.1.1, the image has a bug were it doesn't initialize the correction retention policy. I fix that as follows. (See #1482 and #1474).

```
#!/bin/bash

#
# Applies to heapster influxdb image v1.1.1
# https://github.com/kubernetes/heapster/issues/1482
# https://github.com/kubernetes/heapster/issues/1474
#

kubectl run influxcli --restart=Never --rm -it --image=cburki/influxdb-shell -- \
  --host=monitoring-influxdb.kube-system --port=8086 --database=k8s \
  --execute 'CREATE RETENTION POLICY "default" ON k8s DURATION 0d REPLICATION 1 DEFAULT; SHOW RETENTION POLICIES'
```

**Comment by alirezaDavid** [comment]
@whereisaaron Thanks man, now it's work like a charm.
