### ISSUE TITLE
gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1 is not compatible with grafana-amd64:4.0.2

### ISSUE THREAD

**Issue by jlalouette** [kubernetes/heapster#1503]
gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1 is not compatible with grafana-amd64:4.0.2. You must use the following 0.7 version to get it work :
gcr.io/google_containers/heapster_influxdb:v0.7

**Comment by KarolKraskiewicz** [comment]
Hi @jlalouette 

I understand you tried those images:
`gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1`
`gcr.io/google_containers/heapster-grafana-amd64:v4.0.2`
What is the compatibility issue you encountered? 

I tried the same images together with:
`gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1`
And monitoring was working as expected.

**Comment by jlalouette** [comment]
hello,
grafana was not able to access influxdb database.
but i was using gcr.io/google_containers/heapster-amd64:v1.3.0-beta.0 instead of 1


-------- Message original --------
Objet : Re: [kubernetes/heapster] gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1 is not compatible with grafana-amd64:4.0.2 (#1503)
De : Karol <notifications@github.com>
À : kubernetes/heapster <heapster@noreply.github.com>
Cc : LALOUETTE Johan <Johan.LALOUETTE@canal-plus.com>,Mention <mention@noreply.github.com>


Hi @jlalouette<https://github.com/jlalouette>

I understand you tried those images:
gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1
gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
What is the compatibility issue you encountered?

I tried the same images together with:
gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1
And monitoring was working as expected.

**Comment by KarolKraskiewicz** [comment]
@jlalouette 
Can you verify if the error persist with `gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1` and attach error log?

**Comment by jlalouette** [comment]
Hi Karol,

I confirm that it works fine with gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1

Regards,

Johan

De : Karol [mailto:notifications@github.com]
Envoyé : dimanche 19 février 2017 20:18
À : kubernetes/heapster <heapster@noreply.github.com>
Cc : LALOUETTE Johan <Johan.LALOUETTE@canal-plus.com>; Mention <mention@noreply.github.com>
Objet : Re: [kubernetes/heapster] gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1 is not compatible with grafana-amd64:4.0.2 (#1503)


@jlalouette<https://github.com/jlalouette>
Can you verify if the error persist with gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1 and attach error log?
