### ISSUE TITLE
Make Heapster/InfluxDB/Grafana integration great

### ISSUE THREAD

**Issue by piosz** [kubernetes/heapster#1507]
The is a number of problems with InfluxDB and Grafana. We should make sure that the integration works well out of the box. Any help would be appreciated here.

This is an umbrella issue. Related issues:
#1375
#1376
#1420
#1481
#1482
#1485
#1491
#1494
#1503
#1507

**Comment by piosz** [comment]
@kgrygiel @mwielgus @DirectXMan12
@Demonsthere @jlalouette @jmn @jonaz @judexzhu @karunakar1122v @lilnate22 @mashayev @whereisaaron

**Comment by jlalouette** [comment]
Hi,

It seems that grafana does not support the latest versions of InfluxDB (Earlier than 0.9).
After a lot of test the only way I found to make heapster/grafana/Influxdb works with Kubernetes 1.4 is to use these versions : 
(Be careful with the undescore)

INFLUXDB : `gcr.io/google_containers/heapster_influxdb:v0.7`
GRAFANA : `gcr.io/google_containers/heapster-grafana-amd64:v4.0.2`
HEAPSTER : gcr.io/google_containers/heapster:v1.3.0-beta.0

No specifics configurations required. I can upload the Kubernetes YAML associated to the deployments if you like.


![image](https://cloud.githubusercontent.com/assets/25176246/22737333/f3df0e2c-ee02-11e6-9b49-3889a447197d.png)

![image](https://cloud.githubusercontent.com/assets/25176246/22737352/0f678c78-ee03-11e6-8143-79b82f9dbe17.png)

**Comment by piosz** [comment]
@jlalouette thanks for the update. Do you mean `heapster-grafana-amd64:v4.0.2` does not work with `heapster_influxdb:v1.1.1` or Grafana in general does not support InfluxDB in version 1.1? If the former this issue is about it, to make sure that our images play well together.

**Comment by jlalouette** [comment]
I don't know if grafana 4.0.2 support InfluxDB 1.1 out of the box. The grafana datasource doc ([http://docs.grafana.org/features/datasources/influxdb/]) if refering to InfluxDB 0.8.x and 0.9.x but nothing else. 

What I do know is that `heapster-grafana-amd64:v4.0.2` does not work well with `heapster_influxdb:v1.1.1 `

**Comment by jonaz** [comment]
We are running influxdb v1.1.1 and grafana 4.0.2 in production with heapster 1.1 and its working fine. 
Not using the heapster-grafana-amd64:v4.0.2 but a standalone grafana installation from rpm packages.

**Comment by piosz** [comment]
@bergquist does Grafana support InfluxDB in version 1.0+?

**Comment by piosz** [comment]
Great! Then we need to make sure that our images play well together.

**Comment by lilnate22** [comment]
@piosz  I was able to get it working via modifying deployments:

```
grafana-deployment.yaml:  image: gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
heapster-deploy: image: gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1
influxdb-deploy:  gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1
```

the charts seem to be loading now:
![image](https://cloud.githubusercontent.com/assets/882236/22742374/862ba8d6-ede4-11e6-97ce-04993cca3807.png)


i think we just need to PR to change the yaml files

**Comment by bergquist** [comment]
@piosz Should work fine :) Just poke me if you have any questions regarding grafana

**Comment by jlalouette** [comment]
@piosz Cool, what did you change in addition to the heapster update (1.3.0.beta.0 --> 1.3.0.beta.1) ?

**Comment by DirectXMan12** [comment]
(added another to the list)

**Comment by lilnate22** [comment]
@jlalouette  nothing. just those and it seemed to work.

**Comment by piosz** [comment]
@KarolKraskiewicz any update?
