### ISSUE TITLE
How to use influxdb data when accessing heapster rest api?

### ISSUE THREAD

**Issue by tianshapjq** [kubernetes/heapster#1517]
I found something odd to me, maybe I set wrong configures when starting Heapster?
I configured the Heapster to use Influxdb using --sink="influxdb:http://localhost:8086" and it stored data to db successfully. But when accessing the Heapster rest apis, such as "/api/v1/model/namespaces/default/metrics/", it didn't show data from Influxdb. I looked into the source code, found that it queried data from metricSink which seems to be a memory cache. How can I set Heapster to query data from Influxdb? If not, isn't it unnecessary to set up a backend db?

**Comment by tianshapjq** [comment]
The situation is, I want to query more than 15 collections of data which can up to about 24 hours. Is it possible to obtain such a long time data with just configuring the Heapster start parameters? Maybe querying data from influxdb would work this out?

**Comment by jbehrends** [comment]
Someone can chime in if I'm wrong..  I think heapster was designed to aggregate metrics from all nodes in a kubernetes cluster and expose them via an API, and was not designed to store any data.  The only thing I'm aware of that leverages the API is the kubernetes dashboard. 

Your use case is where a "sink" comes into play.  If you have a sink configured such as influxdb, heapster will poll metrics from all nodes, and then send them off to influxdb, or whatever other backend you have configured.  Then you can query influxdb for metrics from the last X-hrs, days, etc...

**Comment by tianshapjq** [comment]
@jbehrends is there anything I can do to make Heapster querying data from influxdb but not memory cache? So that I can access the rest APIs of Heapster instead of influxdb.

**Comment by jbehrends** [comment]
No.  Heapster only pushes data to external destinations like influx, it can't query data back out.  In my environment I have heapster sending data to graphite, then I have dashboards setup to display the data.  The data is pretty much real-time and I have data as far back as I want.

**Comment by tianshapjq** [comment]
@jbehrends thanks, that really helps a lot :)
