### ISSUE TITLE
gcr.io/google_containers/heapster-amd64:v1.3.0-beta.0 image is missing

### ISSUE THREAD

**Issue by rutsky** [kubernetes/heapster#1518]
Currently specified in [heapster-deployment.yaml](https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/influxdb/heapster-deployment.yaml#L16) image `gcr.io/google_containers/heapster-amd64:v1.3.0-beta.0` is not available.
I changed `beta.0` to `beta.1`, and it worked for me: `gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1`

/cc @luxas

**Comment by xrl** [comment]
Dropping the `-amd64` worked for me.

**Comment by luxas** [comment]
@rutsky That's right. Do you want to send a PR that updates it to v1.3.0-alpha.1?

**Comment by rutsky** [comment]
@luxas `alpha.1`? Why not `beta.1`? It easy to me to send PR, but I'm confused which version is correct?

**Comment by luxas** [comment]
@rutsky Sorry, that was a typo. `v1.3.0-beta.1`, yes please
