### ISSUE TITLE
Support of Environment label

### ISSUE THREAD

**Issue by alexandrst88** [kubernetes/heapster#1521]
We have few kubernetes clusters(dev, prod), and one tsdb cluster. Heapster runs on each cluster and send metrics to TSDB. Also, we deploy pod `example-app` on each cluster
Does Heapster support some tag, label or something which we will understand from which cluster metrics are coming(like env=dev, env=prod)?

**Comment by DirectXMan12** [comment]
some of the sinks do, not sure about OpenTSDB.  Assigning to the sink maintainers: @bluebreezecf

**Comment by jakon89** [comment]
Good point, I am on it. I will send PR today.
