### ISSUE TITLE
Heapster's memory/usage metrics count VIRT + RES

### ISSUE THREAD

**Issue by alexandrst88** [kubernetes/heapster#1522]
Hi, memory/usage metrics counts  **VIRT + RES** memory by docker container(pod).

```11259 root      20   0 18.639g 1.541g   9836 S   2.0  2.5   2:36.79 java```

Which will be good to know only real memory usage of process(`1.541g`).

Does heapster support any metrics **RES** memory usage of process?

Thanks.

**Comment by DirectXMan12** [comment]
Heapster reports the working set, and the total usage.  The summary API also sends us RSS, but we don't expose that currently (it would be a pretty simple patch to do so, though).
