### ISSUE TITLE
deploy/kube-config/influxdb/heapster-deployment.yaml references the incorrect beta version

### ISSUE THREAD

**Issue by pluttrell** [kubernetes/heapster#1526]
This file: `deploy/kube-config/influxdb/heapster-deployment.yaml` on line 16 refers to `image: gcr.io/google_containers/heapster-amd64:v1.3.0-beta.0` which is no longer available. 

Switching to `image: gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1` resolves the problem.

**Comment by piosz** [comment]
Obsolete: currently there is beta.1
