### ISSUE TITLE
lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="x509: failed to load system roots and no roots provided"

### ISSUE THREAD

**Issue by chenjian158978** [kubernetes/heapster#1527]
Following by [Run Heapster in a Kubernetes cluster with an InfluxDB backend and a Grafana UI](https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md)

Using the newest image: 

1. gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
2. gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1
3. gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1

Rebuild the grafana image for adding the configure of alerting to send email:

**run.sh**

      #!/bin/sh

	: "${GF_PATHS_DATA:=/var/lib/grafana}"
	: "${GF_PATHS_LOGS:=/var/log/grafana}"
	: "${GF_SMTP_ENABLED:=true}"
	: "${GF_SMTP_HOST:=smtp.163.com:25}"
	: "${GF_SMTP_USER:=chenjian@163.com}"
	: "${GF_SMTP_PASSWORD:=dfadfadfa}"
	: "${GF_SMTP_FROM_ADDRESS:=chenjian@163.com}"
	
	# Allow access to dashboards without having to log in
	# Export these variables so grafana picks them up
	export GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED:-true}
	export GF_SERVER_HTTP_PORT=${GRAFANA_PORT}
	export GF_SERVER_PROTOCOL=${GF_SERVER_PROTOCOL:-http}
	
	echo "Starting a utility program that will configure Grafana"
	setup_grafana >/dev/stdout 2>/dev/stderr &
	
	echo "Starting Grafana in foreground mode"
	exec /usr/sbin/grafana-server \
	  --homepath=/usr/share/grafana \
	  --config=/etc/grafana/grafana.ini \
	  cfg:default.paths.data="$GF_PATHS_DATA"  \
	  cfg:default.paths.logs="$GF_PATHS_LOGS"   \
	  cfg:default.smtp.enabled="$GF_SMTP_ENABLED"    \
	  cfg:default.smtp.host="$GF_SMTP_HOST"     \
	  cfg:default.smtp.user="$GF_SMTP_USER"     \
	  cfg:default.smtp.password="$GF_SMTP_PASSWORD"    \
	  cfg:default.smtp.from_address="$GF_SMTP_FROM_ADDRESS"
       

**Dockerfile**

	FROM gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
	ADD run.sh /
	RUN chmod 777 run.sh
	
**After Start**

here is the log:

	Starting a utility program that will configure Grafana
	Starting Grafana in foreground mode
	Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp [::1]:3000: getsockopt: connection refused. Retrying after 5 seconds...
	t=2017-02-15T11:17:37+0000 lvl=info msg="Starting Grafana" logger=main version=v4.0.2 commit=unknown-dev compiled=2017-02-15T11:17:37+0000
	t=2017-02-15T11:17:37+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
	t=2017-02-15T11:17:37+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
	t=2017-02-15T11:17:37+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
	t=2017-02-15T11:17:37+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
	t=2017-02-15T11:17:37+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.smtp.enabled=true"
	t=2017-02-15T11:17:37+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.smtp.host=smtp.163.com:25"
	t=2017-02-15T11:17:37+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.smtp.user=chenjian@163.com"
	t=2017-02-15T11:17:37+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.smtp.password=*********"
	t=2017-02-15T11:17:37+0000 lvl=info msg="Config overriden from command line" logger=settings arg="default.smtp.from_address=chenjian@163.com"
	t=2017-02-15T11:17:37+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SERVER_PROTOCOL=http"
	t=2017-02-15T11:17:37+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SERVER_HTTP_PORT=3000"
	t=2017-02-15T11:17:37+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_SERVER_ROOT_URL=/"
	t=2017-02-15T11:17:37+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_AUTH_ANONYMOUS_ENABLED=true"
	t=2017-02-15T11:17:37+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_AUTH_ANONYMOUS_ORG_ROLE=Admin"
	t=2017-02-15T11:17:37+0000 lvl=info msg="Config overriden from Environment variable" logger=settings var="GF_AUTH_BASIC_ENABLED=false"
	t=2017-02-15T11:17:37+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
	t=2017-02-15T11:17:37+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
	t=2017-02-15T11:17:37+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
	t=2017-02-15T11:17:37+0000 lvl=info msg="Path Plugins" logger=settings path=/usr/share/grafana/data/plugins
	t=2017-02-15T11:17:37+0000 lvl=info msg="Initializing DB" logger=sqlstore dbtype=sqlite3
	t=2017-02-15T11:17:37+0000 lvl=info msg="Starting DB migration" logger=migrator
	t=2017-02-15T11:17:37+0000 lvl=info msg="Executing migration" logger=migrator id="create migration_log table"
	t=2017-02-15T11:17:38+0000 lvl=info msg="Executing migration" logger=migrator id="create user table"
	t=2017-02-15T11:17:38+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index user.login"
	t=2017-02-15T11:17:38+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index user.email"
	t=2017-02-15T11:17:38+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_user_login - v1"
	t=2017-02-15T11:17:38+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_user_email - v1"
	t=2017-02-15T11:17:38+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table user to user_v1 - v1"
	t=2017-02-15T11:17:38+0000 lvl=info msg="Executing migration" logger=migrator id="create user table v2"
	t=2017-02-15T11:17:38+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_user_login - v2"
	t=2017-02-15T11:17:38+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_user_email - v2"
	t=2017-02-15T11:17:38+0000 lvl=info msg="Executing migration" logger=migrator id="copy data_source v1 to v2"
	t=2017-02-15T11:17:38+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table user_v1"
	t=2017-02-15T11:17:38+0000 lvl=info msg="Executing migration" logger=migrator id="create temp user table v1-7"
	t=2017-02-15T11:17:38+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_email - v1-7"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_org_id - v1-7"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_code - v1-7"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_temp_user_status - v1-7"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Executing migration" logger=migrator id="create star table"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index star.user_id_dashboard_id"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Executing migration" logger=migrator id="create org table v1"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_org_name - v1"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Executing migration" logger=migrator id="create org_user table v1"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_org_user_org_id - v1"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_org_user_org_id_user_id - v1"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account to org"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account to org"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Executing migration" logger=migrator id="copy data account_user to org_user"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Skipping migration condition not fulfilled" logger=migrator id="copy data account_user to org_user"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table account"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table account_user"
	t=2017-02-15T11:17:39+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard table"
	t=2017-02-15T11:17:40+0000 lvl=info msg="Executing migration" logger=migrator id="add index dashboard.account_id"
	t=2017-02-15T11:17:40+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index dashboard_account_id_slug"
	t=2017-02-15T11:17:40+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard_tag table"
	t=2017-02-15T11:17:40+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index dashboard_tag.dasboard_id_term"
	t=2017-02-15T11:17:40+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_dashboard_tag_dashboard_id_term - v1"
	t=2017-02-15T11:17:40+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table dashboard to dashboard_v1 - v1"
	t=2017-02-15T11:17:40+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard v2"
	t=2017-02-15T11:17:40+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_dashboard_org_id - v2"
	t=2017-02-15T11:17:40+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_dashboard_org_id_slug - v2"
	t=2017-02-15T11:17:40+0000 lvl=info msg="Executing migration" logger=migrator id="copy dashboard v1 to v2"
	t=2017-02-15T11:17:40+0000 lvl=info msg="Executing migration" logger=migrator id="drop table dashboard_v1"
	t=2017-02-15T11:17:40+0000 lvl=info msg="Executing migration" logger=migrator id="alter dashboard.data to mediumtext v1"
	t=2017-02-15T11:17:41+0000 lvl=info msg="Executing migration" logger=migrator id="Add column updated_by in dashboard - v2"
	t=2017-02-15T11:17:41+0000 lvl=info msg="Executing migration" logger=migrator id="Add column created_by in dashboard - v2"
	t=2017-02-15T11:17:41+0000 lvl=info msg="Executing migration" logger=migrator id="Add column gnetId in dashboard"
	t=2017-02-15T11:17:41+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for gnetId in dashboard"
	t=2017-02-15T11:17:41+0000 lvl=info msg="Executing migration" logger=migrator id="Add column plugin_id in dashboard"
	t=2017-02-15T11:17:41+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for plugin_id in dashboard"
	t=2017-02-15T11:17:41+0000 lvl=info msg="Executing migration" logger=migrator id="Add index for dashboard_id in dashboard_tag"
	t=2017-02-15T11:17:41+0000 lvl=info msg="Executing migration" logger=migrator id="create data_source table"
	t=2017-02-15T11:17:41+0000 lvl=info msg="Executing migration" logger=migrator id="add index data_source.account_id"
	t=2017-02-15T11:17:41+0000 lvl=info msg="Executing migration" logger=migrator id="add unique index data_source.account_id_name"
	t=2017-02-15T11:17:41+0000 lvl=info msg="Executing migration" logger=migrator id="drop index IDX_data_source_account_id - v1"
	t=2017-02-15T11:17:41+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_data_source_account_id_name - v1"
	t=2017-02-15T11:17:41+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table data_source to data_source_v1 - v1"
	t=2017-02-15T11:17:41+0000 lvl=info msg="Executing migration" logger=migrator id="create data_source table v2"
	t=2017-02-15T11:17:42+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_data_source_org_id - v2"
	t=2017-02-15T11:17:42+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_data_source_org_id_name - v2"
	t=2017-02-15T11:17:42+0000 lvl=info msg="Executing migration" logger=migrator id="copy data_source v1 to v2"
	t=2017-02-15T11:17:42+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table data_source_v1 #2"
	t=2017-02-15T11:17:42+0000 lvl=info msg="Executing migration" logger=migrator id="Add column with_credentials"
	t=2017-02-15T11:17:42+0000 lvl=info msg="Executing migration" logger=migrator id="Add secure json data column"
	t=2017-02-15T11:17:42+0000 lvl=info msg="Executing migration" logger=migrator id="create api_key table"
	t=2017-02-15T11:17:42+0000 lvl=info msg="Executing migration" logger=migrator id="add index api_key.account_id"
	t=2017-02-15T11:17:42+0000 lvl=info msg="Executing migration" logger=migrator id="add index api_key.key"
	t=2017-02-15T11:17:42+0000 lvl=info msg="Executing migration" logger=migrator id="add index api_key.account_id_name"
	t=2017-02-15T11:17:42+0000 lvl=info msg="Executing migration" logger=migrator id="drop index IDX_api_key_account_id - v1"
	t=2017-02-15T11:17:42+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_api_key_key - v1"
	Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp [::1]:3000: getsockopt: connection refused. Retrying after 5 seconds...
	t=2017-02-15T11:17:42+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_api_key_account_id_name - v1"
	t=2017-02-15T11:17:43+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table api_key to api_key_v1 - v1"
	t=2017-02-15T11:17:43+0000 lvl=info msg="Executing migration" logger=migrator id="create api_key table v2"
	t=2017-02-15T11:17:43+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_api_key_org_id - v2"
	t=2017-02-15T11:17:43+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_api_key_key - v2"
	t=2017-02-15T11:17:43+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_api_key_org_id_name - v2"
	t=2017-02-15T11:17:43+0000 lvl=info msg="Executing migration" logger=migrator id="copy api_key v1 to v2"
	t=2017-02-15T11:17:43+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table api_key_v1"
	t=2017-02-15T11:17:43+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard_snapshot table v4"
	t=2017-02-15T11:17:43+0000 lvl=info msg="Executing migration" logger=migrator id="drop table dashboard_snapshot_v4 #1"
	t=2017-02-15T11:17:43+0000 lvl=info msg="Executing migration" logger=migrator id="create dashboard_snapshot table v5 #2"
	t=2017-02-15T11:17:43+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_dashboard_snapshot_key - v5"
	t=2017-02-15T11:17:43+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_dashboard_snapshot_delete_key - v5"
	t=2017-02-15T11:17:44+0000 lvl=info msg="Executing migration" logger=migrator id="create index IDX_dashboard_snapshot_user_id - v5"
	t=2017-02-15T11:17:44+0000 lvl=info msg="Executing migration" logger=migrator id="alter dashboard_snapshot to mediumtext v2"
	t=2017-02-15T11:17:44+0000 lvl=info msg="Executing migration" logger=migrator id="create quota table v1"
	t=2017-02-15T11:17:44+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_quota_org_id_user_id_target - v1"
	t=2017-02-15T11:17:44+0000 lvl=info msg="Executing migration" logger=migrator id="create plugin_setting table"
	t=2017-02-15T11:17:44+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_plugin_setting_org_id_plugin_id - v1"
	t=2017-02-15T11:17:44+0000 lvl=info msg="Executing migration" logger=migrator id="Add column plugin_version to plugin_settings"
	t=2017-02-15T11:17:44+0000 lvl=info msg="Executing migration" logger=migrator id="create session table"
	t=2017-02-15T11:17:44+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table playlist table"
	t=2017-02-15T11:17:44+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old table playlist_item table"
	t=2017-02-15T11:17:44+0000 lvl=info msg="Executing migration" logger=migrator id="create playlist table v2"
	t=2017-02-15T11:17:44+0000 lvl=info msg="Executing migration" logger=migrator id="create playlist item table v2"
	t=2017-02-15T11:17:45+0000 lvl=info msg="Executing migration" logger=migrator id="drop preferences table v2"
	t=2017-02-15T11:17:45+0000 lvl=info msg="Executing migration" logger=migrator id="drop preferences table v3"
	t=2017-02-15T11:17:45+0000 lvl=info msg="Executing migration" logger=migrator id="create preferences table v3"
	t=2017-02-15T11:17:45+0000 lvl=info msg="Executing migration" logger=migrator id="create alert table v1"
	t=2017-02-15T11:17:45+0000 lvl=info msg="Executing migration" logger=migrator id="add index alert org_id & id "
	t=2017-02-15T11:17:45+0000 lvl=info msg="Executing migration" logger=migrator id="add index alert state"
	t=2017-02-15T11:17:45+0000 lvl=info msg="Executing migration" logger=migrator id="add index alert dashboard_id"
	t=2017-02-15T11:17:45+0000 lvl=info msg="Executing migration" logger=migrator id="create alert_notification table v1"
	t=2017-02-15T11:17:45+0000 lvl=info msg="Executing migration" logger=migrator id="Add column is_default"
	t=2017-02-15T11:17:45+0000 lvl=info msg="Executing migration" logger=migrator id="add index alert_notification org_id & name"
	t=2017-02-15T11:17:45+0000 lvl=info msg="Executing migration" logger=migrator id="Drop old annotation table v4"
	t=2017-02-15T11:17:45+0000 lvl=info msg="Executing migration" logger=migrator id="create annotation table v5"
	t=2017-02-15T11:17:45+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 0 v3"
	t=2017-02-15T11:17:46+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 1 v3"
	t=2017-02-15T11:17:46+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 2 v3"
	t=2017-02-15T11:17:46+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 3 v3"
	t=2017-02-15T11:17:46+0000 lvl=info msg="Executing migration" logger=migrator id="add index annotation 4 v3"
	t=2017-02-15T11:17:46+0000 lvl=info msg="Created default admin user: [admin]"
	t=2017-02-15T11:17:46+0000 lvl=info msg="Starting plugin search" logger=plugins
	t=2017-02-15T11:17:46+0000 lvl=warn msg="Plugin dir does not exist" logger=plugins dir=/usr/share/grafana/data/plugins
	t=2017-02-15T11:17:46+0000 lvl=info msg="Plugin dir created" logger=plugins dir=/usr/share/grafana/data/plugins
	t=2017-02-15T11:17:46+0000 lvl=info msg="Initializing Alerting" logger=alerting.engine
	t=2017-02-15T11:17:46+0000 lvl=info msg="Initializing CleanUpService" logger=cleanup
	t=2017-02-15T11:17:46+0000 lvl=info msg="Initializing HTTP Server" logger=server address=0.0.0.0:3000 protocol=http subUrl=
	Connected to the Grafana dashboard.
	The datasource for the Grafana dashboard is now set.
	t=2017-02-15T11:19:09+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
	t=2017-02-15T11:19:09+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[chenjian@163.com]
	t=2017-02-15T11:19:11+0000 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="x509: failed to load system roots and no roots provided"
	t=2017-02-15T11:20:32+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
	t=2017-02-15T11:20:32+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[chenjian@163.com]
	t=2017-02-15T11:20:32+0000 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="x509: failed to load system roots and no roots provided"
	t=2017-02-15T12:11:33+0000 lvl=info msg="Sending notification" logger=alerting.notifier type=email id=0 isDefault=false
	t=2017-02-15T12:11:33+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[chenjian@163.com]
	t=2017-02-15T12:11:35+0000 lvl=eror msg="Failed to send alert notification email" logger=alerting.notifier.email error="x509: failed to load system roots and no roots provided"

**Comment by DirectXMan12** [comment]
cc #1507

**Comment by chenjian158978** [comment]
Change **smtp.skip_verify** from **false(defaults)** to **true** can fix my problem.

Read some details about adding alert notification:

1. [Alert Notifications](http://docs.grafana.org/alerting/notifications/#alert-notifications)

2. [SMTP settings](http://docs.grafana.org/installation/configuration/#smtp)


Here is the new file of run.sh

	#!/bin/sh
	
	: "${GF_PATHS_DATA:=/var/lib/grafana}"
	: "${GF_PATHS_LOGS:=/var/log/grafana}"
	: "${GF_SMTP_ENABLED:=true}"
	: "${GF_SMTP_HOST:=smtp.163.com:25}"
	: "${GF_SMTP_USER:=chenjian@163.com}"
	: "${GF_SMTP_PASSWORD:=dfdfdfdwer}"
	: "${GF_SMTP_SKIP_VERIFY:=true}"
	: "${GF_SMTP_FROM_ADDRESS:=chenjian@163.com}"
	
	# Allow access to dashboards without having to log in
	# Export these variables so grafana picks them up
	export GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED:-true}
	export GF_SERVER_HTTP_PORT=${GRAFANA_PORT}
	export GF_SERVER_PROTOCOL=${GF_SERVER_PROTOCOL:-http}
	
	echo "Starting a utility program that will configure Grafana"
	setup_grafana >/dev/stdout 2>/dev/stderr &
	
	echo "Starting Grafana in foreground mode"
	exec /usr/sbin/grafana-server \
	  --homepath=/usr/share/grafana \
	  --config=/etc/grafana/grafana.ini \
	  cfg:default.paths.data="$GF_PATHS_DATA"  \
	  cfg:default.paths.logs="$GF_PATHS_LOGS"   \
	  cfg:default.smtp.enabled="$GF_SMTP_ENABLED"    \
	  cfg:default.smtp.host="$GF_SMTP_HOST"     \
	  cfg:default.smtp.user="$GF_SMTP_USER"     \
	  cfg:default.smtp.password="$GF_SMTP_PASSWORD"    \
	  cfg:default.smtp.skip_verify="$GF_SMTP_SKIP_VERIFY" \
	  cfg:default.smtp.from_address="$GF_SMTP_FROM_ADDRESS"

**Comment by chenjian158978** [comment]
@DirectXMan12 Can you close this issue please? thx a lot.

**Comment by orientzc** [comment]
@chenjian158978 
sorry. i use
docker run -p 3000:3000 -e "GF_SMTP_ENABLED=true" -e "GF_SMTP_HOST=smtp.aaa.com:25" -e "GF_SMTP_FROM_ADDRESS=xxx" -e "GF_SMTP_USER=xxx" -e "GF_SMTP_PASSWORD="yyy" -e "GF_SMTP_SKIP_VERITY=true". and i also met the same problem. i use your solution of edit the run.sh to solve it. Success. but i want to know that what's wrong with the way of ENV. what i missed. could anyone help me? Thanks.

**Comment by chenjian158978** [comment]
@orientzc 
Could you show me the full command of your `docker run -p 3000:3000 -e "GF_SMTP_ENABLED=true" -e "GF_SMTP_HOST=smtp.aaa.com:25" -e "GF_SMTP_FROM_ADDRESS=xxx" -e "GF_SMTP_USER=xxx" -e "GF_SMTP_PASSWORD="yyy" -e "GF_SMTP_SKIP_VERITY=true"`?
Thx a lot.

**Comment by orientzc** [comment]
@chenjian158978 
Thanks. like this?
first, i edit /etc/hosts in machine. my smtp IP is 132.35.108.22. and i add
132.35.108.22 hq.smtp.gra.cn
second, i use --net=host instead of -p 3000:3000 to use the hosts in machine.
docker run --net=host -e "GF_SMTP_ENABLED=true" -e "GF_SMTP_HOST=hq.smtp.gra.cn:25" -e "GF_SMTP_FROM_ADDRESS=orientzc@gra.cn" -e "GF_SMTP_USER=orientzc@gra.cn" -e "GF_SMTP_PASSWORD="""#password#"""" -e "GF_SMTP_SKIP_VERIFY=true" grafana/grafana:latest

and i tried 
docker run -p 3000:3000 -e "GF_SMTP_ENABLED=true" -e "GF_SMTP_HOST=101.35.108.22:25" -e "GF_SMTP_FROM_ADDRESS=orientzc@gra.cn" -e "GF_SMTP_USER=orientzc@gra.cn" -e "GF_SMTP_PASSWORD="""#password#"""" -e "GF_SMTP_SKIP_VERIFY=true" grafana/grafana:latest

docker run -p 3000:3000 -e "GF_SMTP_ENABLED=true" -e "GF_SMTP_HOST=101.35.108.22:25" -e "GF_SMTP_FROM_ADDRESS=orientzc@gra.cn" -e "GF_SMTP_USER=orientzc@gra.cn" -e "GF_SMTP_PASSWORD=#password# -e "GF_SMTP_SKIP_VERIFY=true" grafana/grafana:latest

docker run --net=hosts -e "GF_SMTP_ENABLED=true" -e "GF_SMTP_HOST=hq.smtp.gra.cn:25" -e "GF_SMTP_FROM_ADDRESS=orientzc@gra.cn" -e "GF_SMTP_USER=orientzc@gra.cn" -e "GF_SMTP_PASSWORD=#password# -e "GF_SMTP_SKIP_VERIFY=true" grafana/grafana:latest

**Comment by chenjian158978** [comment]
@orientzc 
I think you just add the ENV into your container. **But this container do not start with those ENVs.**

Can you get my points?

You should use those ENV when your container start to RUN like below:

     exec /usr/sbin/grafana-server \
      --homepath=/usr/share/grafana \
      --config=/etc/grafana/grafana.ini \
      cfg:default.paths.data="$GF_PATHS_DATA"  \
      cfg:default.paths.logs="$GF_PATHS_LOGS"   \
      cfg:default.smtp.enabled="$GF_SMTP_ENABLED"    \
      cfg:default.smtp.host="$GF_SMTP_HOST"     \
      cfg:default.smtp.user="$GF_SMTP_USER"     \
      cfg:default.smtp.password="$GF_SMTP_PASSWORD"    \
      cfg:default.smtp.skip_verify="$GF_SMTP_SKIP_VERIFY" \
      cfg:default.smtp.from_address="$GF_SMTP_FROM_ADDRESS"

**Comment by orientzc** [comment]
@chenjian158978 
thanks very much. but i use 
docker run -p 3000:3000 -e "GF_SECURITY_ADMIN_PASSWORD=secret" grafana/grafana:latest
everything is ok. the run.sh is same. so i think Envs works.
the description of configuration container is https://hub.docker.com/r/grafana/grafana/

**Comment by chenjian158978** [comment]
@orientzc 
I run it by myself, and read `/etc/grafana/grafana.ini` and `run.sh`.

And now I get your point. 

In fact, I **DO NOT** know how to run the env of `GF_SECURITY_ADMIN_PASSWORD=secret` without adding it into the script of `run.sh` and then the envs are be overriden like the `Configuring your Grafana container` part of [https://hub.docker.com/r/grafana/grafana/](https://hub.docker.com/r/grafana/grafana/).

1. You can read the `grafana/grafana`'s Dockerfile, and maybe know how it works inside;
2. You can email the developers of grafana, they would help you more.

This is my suggestions.

**Comment by orientzc** [comment]
Thanks very much. @chenjian158978
