### ISSUE TITLE
Secrets not redacted on startup

### ISSUE THREAD

**Issue by astropuffin** [kubernetes/heapster#1530]
Most people will run heapster as a pod within kubernetes itself. Most people will also have some sort of log aggregation service for all pods. This can be a problem because secrets are exposed on startup if you enable logging, and then stored for long periods of time.

```
/ # /eventer --source=kubernetes --logtostderr --sink="elasticsearch:http://elas
ticsearch:9200?esUserName=logging&esUserSecret=$PASS&sniff=false"
I0215 22:26:15.030847      25 eventer.go:50] /eventer --source=kubernetes --logtostderr --sink=elasticsearch:http://elasticsearch:9200?esUserName=logging&esUserSecret=EXPOSED&sniff=false
I0215 22:26:15.030896      25 eventer.go:51] Eventer version 1.2.0
I0215 22:26:15.175666      25 eventer.go:73] Starting with ElasticSearch Sink sink
I0215 22:26:15.175697      25 eventer.go:87] Starting eventer
I0215 22:26:30.000351      25 manager.go:95] Exporting 59 events
```

Here are the relevant lines:
https://github.com/kubernetes/heapster/blob/master/events/eventer.go#L62
https://github.com/kubernetes/heapster/blob/master/metrics/heapster.go#L71

We should redact any secrets in the log. This isn't as simple as it sounds though, because this part of the code is very very early in the pipeline, it doesn't know what kind of sink is configured yet. The redaction code will either need to be sink aware (which is complicated) or there needs to be a standard interface for user/pass (and other auth) that can be parsed regardless of sink (which would probably be a Good Thing<sup>TM</sup> anyway).

Alternative: Might be easier just to implement V levels with glog and punt this to V0 or equivalent.

**Comment by DirectXMan12** [comment]
We should probably get secret information as a Kubernetes secret object (pass in a secret name).

**Comment by astropuffin** [comment]
oooh yeah that could work. That way you know which are secrets, regardless of sink.

**Comment by DirectXMan12** [comment]
It shouldn't be too hard to change over the various sinks (even without knowledge of how the particular sinks work).

We could either have heapster actually fetch the secret, or just rely on secret mounting, and have Heapster look in a specific (configurable) spot.

@piosz WDYT?

**Comment by DirectXMan12** [comment]
Heapster is now deprecated.  No new sinks or features will be added.  See https://github.com/kubernetes/heapster/blob/master/docs/deprecation.md#initial-deprecation-kubernetes-111 for more details.
