### ISSUE TITLE
How to use historical apis?

### ISSUE THREAD

**Issue by tianshapjq** [kubernetes/heapster#1533]
I found that there are some apis about historical data in the source code, but no docs describing this. Is this a new feature that we decided not to expose yet? Or somewhere else I can read the docs?
I have to query the historical data, and it would be better to query directly form Heapster than db.

**Comment by tianshapjq** [comment]
I found there are historical rest apis which can query data from the backend storages, like influxdb. The apis can just learn from the source code, seems no docs describing about this yes. I think this may be helpful for you @jbehrends

**Comment by DirectXMan12** [comment]
That work went in place, but never really left alpha.  It's being deprecated in favor of the monitoring vision work.  While we don't have a direct replacement for it yet, we keep an eye in sig-autoscaling and sig-instrumentation in the 1.7 or 1.8 timeframe.
