### ISSUE TITLE
Heapster may lose other nodes' stats

### ISSUE THREAD

**Issue by tianshapjq** [kubernetes/heapster#1543]
I found something that may cause losing data for the cluster:
If nodes in the cluster do not have the same system date, Heapster will lose some nodes' stats. Such as the system date which Heapster located at is larger than other nodes for 2 minutes, Heapster will lose all other nodes' stats.
Do we need to note this in the docs? Or we have any features to avoid this? I think this may be important for users.

**Comment by DirectXMan12** [comment]
clusters tend to not react well in general to differing times.  I was under the general impression that you need to have system time synced across your cluster for Kubernetes in general to work properly.

**Comment by andyxning** [comment]
Agree with @directxman12. Time synchronization for all node in a distributed system is necessary and a preliminary.

**Comment by tianshapjq** [comment]
@DirectXMan12 @andyxning thx, I just thought if it's neccessary to note in the docs?

**Comment by andyxning** [comment]
@tianshapjq I am afraid that we may not add this to docs. @DirectXMan12 any thoughts?

**Comment by tianshapjq** [comment]
close since it's getting no response.
