### ISSUE TITLE
 When I use idea-go to start heapster.go, like this:

### ISSUE THREAD

**Issue by libn-net** [kubernetes/heapster#1549]
C:\dev\idea-go\bin\runnerw.exe C:/dev/FrameWork/go/go1.7.5\bin\go.exe build -o "C:\Users\libn\AppData\Local\Temp\Build heapster.go and rungo" C:/dev/idea_workspace/gopath/src/k8s.io/heapster/metrics/heapster.go
# command-line-arguments
metrics\heapster.go:187: undefined: setupHandlers
metrics\heapster.go:195: undefined: newAuthHandler
metrics\heapster.go:201: undefined: newAuthHandler

go version : 1.7.5
program arguments: 
--source=kubernetes:https://xxx
--sink=kafka:?brokers=xxx:9092&timeseriestopic=k8s-metrics&eventstopic=k8s-events
--tls_cert=C:\dev\idea_workspace\gopath\key1\ca.crt
--tls_key=C:\dev\idea_workspace\gopath\key1\cs_client.key
--tls_client_ca=C:\dev\idea_workspace\gopath\key1\cs_client.crt

I am a go language beginner, I am not sure if I am a problem with the configuration, can you help me?

thanks for your help.

**Comment by DirectXMan12** [comment]
something is not set up properly with your IDE -- it looks like it's not pulling in the rest of the packages in the project, if I had to guess.  Take a look at the Makefile do see how we normally build Heapster.
