### ISSUE TITLE
Problem with empty io.kubernetes.container.terminationMessagePath tag when using OpenTSDB sink

### ISSUE THREAD

**Issue by JamiKarvanen** [kubernetes/heapster#1554]
Heapster outputs metrics with an empty io.kubernetes.container.terminationMessagePath tag, which makes OpenTSDB unable to accept those. Heapster should report the default path (/dev/termination-log) or there should be a way to omit empty tags completely. Or am I missing something?

**Comment by DirectXMan12** [comment]
we should probably skip empty metric labels in the OpenTSDB sink, then.  Assigning to the OpenTSDB maintainer.

**Comment by DirectXMan12** [comment]
cc @bluebreezecf

**Comment by jakon89** [comment]
As per https://github.com/OpenTSDB/opentsdb/issues/412 and current OpenTSDB [logic](https://github.com/OpenTSDB/opentsdb/blob/master/src/core/IncomingDataPoints.java#L117) it looks that empty tags are not allowed. I would mark tag where value is empty with defaultTagValue or delete this tag at all. What do you think? I will be glad to send quick PR if needed.

**Comment by bluebreezecf** [comment]
@jakon89
In my preview tries, the OpenTSDB does not allow empty tags. So i prefer to send defaultTagValue if the value if empty.

**Comment by caitong93** [comment]
> mark tag where value is empty with defaultTagValue

Would defaultTagValue be something like `____empty_tag_value` ?
