### ISSUE TITLE
ci-heapster-canarypush seems broken for a long while

### ISSUE THREAD

**Issue by krzyzacy** [kubernetes/heapster#1556]
```
W0302 18:29:53.278] + docker build -t kubernetes/heapster:canary --no-cache=true --pull=true --file=deploy/docker/canary/Dockerfile .
W0302 18:29:53.313] unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /var/lib/jenkins/workspace/ci-heapster-canarypush/go/src/k8s.io/heapster/deploy/docker/canary: no such file or directory
```

any ideas?

**Comment by piosz** [comment]
@timstclair @vishh any ideas?

**Comment by krzyzacy** [comment]
I think the issue is https://github.com/kubernetes/heapster/pull/1387 removed deploy/docker/canary/Dockerfile, while the canarypush job is still referencing it. Is the job still needed? @luxas

**Comment by luxas** [comment]
I don't think that explicit canary Dockerfile is needed, instead we can use the normal Dockerfile for building a canary image just by a retagging

**Comment by krzyzacy** [comment]
shall I delete the ci job?

**Comment by luxas** [comment]
No objections from me
