### ISSUE TITLE
Other types of sources?

### ISSUE THREAD

**Issue by dynek** [kubernetes/heapster#1565]
Hello,

Not an issue per-se but rather a question to which I can't seem to find any answer.
Is heapster able to read metrics from anything else than cadvisor?
api-server, etcd and kube-dns (maybe others) expose prometheus like /metrics and I wanted to know if these are fetchable using Heapster?

Thanks for the great work guys!

**Comment by DirectXMan12** [comment]
Heapster only reads from Kubelet, actually.  Kubelet re-serves the cAdvisor information in a different format.

If you want to fetch the `/metrics` endpoint metrics, you'll have to have something else fetch them (e.g. Prometheus itself, or another tool that speaks prometheus format).
