### ISSUE TITLE
New retention option doesn't work

### ISSUE THREAD

**Issue by yannrouillard** [kubernetes/heapster#1579]
I recently tried to enable the new retention option available since heapster v1.3.0.
Unfortunately, it doesn't work.

I enable with the following heapster command:
```
--sink=influxdb:http://monitoring-influxdb:8086?retention=1d
```

But the k8s database still has the default infinite policy:
```
> show RETENTION POLICIES;
name    duration shardGroupDuration replicaN default
----    -------- ------------------ -------- -------
default 0s       168h0m0s           1        true
```

I see nowhere in the logs the message: `Created retention policy 'default'`:
```
I0320 03:07:10.549742       1 heapster.go:72] /heapster --source=kubernetes.summary_api:https://kubernetes.default.svc.cluster.local/ --sink=influxdb:http://monitoring-influxdb:8086?retention=1d --metric_resolution=60s
I0320 03:07:10.549781       1 heapster.go:73] Heapster version v1.3.0
I0320 03:07:10.550047       1 configs.go:61] Using Kubernetes client with master "https://kubernetes.default.svc.cluster.local" and version v1
I0320 03:07:10.550073       1 configs.go:62] Using kubelet port 10255
I0320 03:07:10.554659       1 influxdb.go:252] created influxdb sink with options: host:monitoring-influxdb:8086 user:root db:toto
I0320 03:07:10.554697       1 heapster.go:196] Starting with InfluxDB Sink
I0320 03:07:10.554707       1 heapster.go:196] Starting with Metric Sink
I0320 03:07:10.750151       1 heapster.go:106] Starting heapster on port 8082
I0320 03:07:13.033675       1 handlers.go:215] No metrics for pod [..]
[...]
I0320 03:08:05.253490       1 influxdb.go:215] Created database "toto" on influxDB server at "monitoring-influxdb:8086"
I0320 03:08:13.026905       1 handlers.go:215] No metrics for [...]
```

**Comment by yannrouillard** [comment]
After having a look at the source code, I think the error lies here:
```
	if resp, err := sink.client.Query(q); err != nil {
		if !(resp != nil && resp.Err != nil && strings.Contains(resp.Err.Error(), "already exists")) {
			err := sink.createRetentionPolicy()
			if err != nil {
				return err
			}
		}
	}
```

If I understand well, the createRetentionPolicy function will only be launched if there is an error in the Database creation query, so it will not happen at least the first time, and probably not the subsequent time as `CREATE DATABASE` doesn't return an error if it doesn't exist from what I saw.

I fixed that but it still doesn't work after as the 'default' retention policy already exists and so the creation fails with error `ERR: retention policy already exists`.

Is there something wrong in my setup or is this really supposed to work ?

**Comment by yannrouillard** [comment]
Other issue: the retention configuration patch has only been applied on the metrics sink but not on the events sink.
As by default they are on the same database, it means that if the eventer create the database first the retention duration will be wrong.

**Comment by yannrouillard** [comment]
Proposed pull request: #1581

**Comment by webeindustry** [comment]
This is very necessary. I need a retention policy set.

**Comment by LLParse** [comment]
Any status on this? Would really like to see this feature soon. Thanks!

**Comment by arausuy** [comment]
Are there any updates on the status of this?

**Comment by woodlee** [comment]
This seems to still be an issue, but the robot's policy prevents me from re-opening it.
