### ISSUE TITLE
heapster failed to write metrics to opentsdb

### ISSUE THREAD

**Issue by kelify** [kubernetes/heapster#1585]
hi , i have some problems in heapster writing metrics to opentsdb, when heapster write it ,the heapster expose this error : "E0323 02:43:05.287352       1 driver.go:74] failed to write metrics to opentsdb - Failed to parse response for POST http://x.x.x.x:4242/api/put?summary: invalid character '<' looking for beginning of value"

so how can i solve this error , thinks

**Comment by manolama** [comment]
@kelify Any way you can post the JSON being sent to TSDB and returned from it? Maybe TCPDump it?

**Comment by jakon89** [comment]
Hi kelify!

Do you use any http proxy in front of OpenTSDB? 
I did take a look at the OpenTSDB client source code and it doesn't check response code at all. Maybe it should check http status codes? As per [docs](http://opentsdb.net/docs/build/html/api_http/put.html) - OpenTSDB return 204 HTTP in case of successful request. @bluebreezecf

**Comment by bluebreezecf** [comment]
@jakon89 Thanks for your meaningful advice. I wil dig into the doc and refresh the OpenTSDB client if it needs

**Comment by hayatAmine** [comment]
hi, 
@jakon89 i have the same error , have you fin a solution ?
Thanks  in Advance

**Comment by buddyledungarees** [comment]
I ran into this during setup and the most likely problem is that your tsdb instance doesn't have chunking enabled and/or max_chunk_size isn't set large enough.

Another issue you might run into is opentsdb's default tag limit is 8, which is way too low for the prometheus style usage of tags/labels. I had to increase my limit to 12 to start accepting the default metrics from heapster.

**Comment by byxorna** [comment]
I can confirm this is a pain to debug. After tcpdumping and finding opentsdb reports a Chunked Encoding error even with requests are not chunked, I had to add the opentsdb settings:
```
tsd.http.request.enable_chunked = true
tsd.http.request.max_chunk = 111000
```
then debug with a captured request to replay against `/api/put?details` to figure out what the problem is. Would be dope to have better indications in heapster about errors experienced writing metrics.

It would be great to be able to filter tags from the outgoing metrics to stay below the tag limit, i.e. `?dropTags=nodename,namespace_id,host_id,pod_id`

**Comment by DirectXMan12** [comment]
you should be able to control that via the `ignore-label` and `store_label` flags.

**Comment by byxorna** [comment]
@DirectXMan12 is that documented in the docs? last i looked, i didnt see it there.

**Comment by DirectXMan12** [comment]
you can see it under `--help`, and it's also in `docs/storage_schema.md`.
