### ISSUE TITLE
Heapster not collecting stats from one node in cluster

### ISSUE THREAD

**Issue by willtrking** [kubernetes/heapster#1586]
Working through getting Kubernetes into production, and trying to figure out why Heapster isn't collecting stats from one node in our test cluster. There are 4 nodes total, and Heapster can't get stats from the node that it's running on. 

Heapster logs as follows:
```
E0323 06:54:12.239208       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://172.20.61.31:10255/stats/container/": Post http://172.20.61.31:10255/stats/container/: dial tcp 172.20.61.31:10255: getsockopt: connection timed out
W0323 06:54:12.239256       1 manager.go:102] Failed to get kubelet:172.20.61.31:10255 response in time
W0323 06:54:25.000515       1 manager.go:147] Failed to get all responses in time (got 6/7)
```

Just those 3 lines repeated for the majority of the logs, the startup section of the logs for heapster look like the following:

```
I0323 03:13:01.157782       1 heapster.go:71] /heapster --source=kubernetes:https://kubernetes.default --sink=influxdb:http://monitoring-influxdb:8086
I0323 03:13:01.157817       1 heapster.go:72] Heapster version v1.3.0-beta.1
I0323 03:13:01.158090       1 configs.go:61] Using Kubernetes client with master "https://kubernetes.default" and version v1
I0323 03:13:01.158108       1 configs.go:62] Using kubelet port 10255
E0323 03:13:07.195199       1 influxdb.go:238] issues while creating an InfluxDB sink: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp 100.70.234.73:8086: getsockopt: no route to host, will retry on use
I0323 03:13:07.195223       1 influxdb.go:252] created influxdb sink with options: host:monitoring-influxdb:8086 user:root db:k8s
I0323 03:13:07.195269       1 heapster.go:193] Starting with InfluxDB Sink
I0323 03:13:07.195282       1 heapster.go:193] Starting with Metric Sink
I0323 03:13:07.205548       1 heapster.go:105] Starting heapster on port 8082
W0323 03:14:25.000457       1 manager.go:147] Failed to get all responses in time (got 6/7)
I0323 03:14:25.017181       1 influxdb.go:215] Created database "k8s" on influxDB server at "monitoring-influxdb:8086"
W0323 03:15:25.000455       1 manager.go:147] Failed to get all responses in time (got 6/7)
```

Not sure if it's relevant, but we're using Canal CNI. Also confirmed cAdvisor is running on that host, again unsure if this is relevant.

**Comment by DirectXMan12** [comment]
what's your Heapster configuration look like?  Are you using the old source `--sink=kubernetes:` or the summary source `--sink=kubernetes.summary_api`?

**Comment by willtrking** [comment]
I'm using influxdb, and was just testing it out with the default config from the influxdb deployment yaml files:

https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/influxdb/heapster-deployment.yaml

In case it changes:
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      containers:
      - name: heapster
        image: gcr.io/google_containers/heapster-amd64:v1.3.0-beta.1
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://monitoring-influxdb:8086
```

**Comment by DirectXMan12** [comment]
so, first things first, I'd reccomend switching to `--source=kubernetes.summary_api`.  If I had to guess, based on the error message, what's going on is this: the non-summary API source can require multiple HTTP requests for each node.  Due to *something* (network congestion, the number of requests, load, etc), Heapster isn't able to complete all of the HTTP requests in a reasonable mount of time.  The summary source uses a single HTTP request per node, so it shouldn't have that problem.

**Comment by ntquyen** [comment]
@DirectXMan12 I got the same problem, heapster not collect haft of my nodes. Switching to `--source=kubernetes.summary_api` not help. And heapster keep printing:
```
E0414 06:46:19.750431       1 streamwatcher.go:109] Unable to decode an event from the watch stream: object to decode was longer than maximum allowed size
E0414 06:46:19.884893       1 streamwatcher.go:109] Unable to decode an event from the watch stream: object to decode was longer than maximum allowed size
W0414 06:46:19.885646       1 reflector.go:330] k8s.io/heapster/metrics/heapster.go:327: watch of *api.Node ended with: very short watch
E0414 06:46:29.480993       1 streamwatcher.go:109] Unable to decode an event from the watch stream: object to decode was longer than maximum allowed size
```

**Comment by kaijparo** [comment]
I got this too -- important to note that this is only happening in a cluster deployed with canal networking and in a private topology via kops in aws. 

Same setup in my public cluster does not have this problem

**Comment by DirectXMan12** [comment]
@kaijparo can pods access the node IPs with canal networking?

@ntquyen what version of Kubernetes are you using?  CoreOS stable version doesn't really tell me anything.  It looks like the watch cache of nodes isn't populating correctly.

**Comment by kaijparo** [comment]
I'm having trouble getting an interactive terminal for the heapster pod, but I can get a busybox going and wget the url for the missing node without issue:

> / # wget http://10.202.8.62:10255/stats/container/
> Connecting to 10.202.8.62:10255 (10.202.8.62:10255)
> index.html           100% |***********************************************************************************************************************************************************| 57822   0:00:00 ETA
> / # ls
> bin         dev         etc         home        index.html  proc        root        sys         tmp         usr         var
> / # cat index.html
> {
>   "/": {
>    "name": "/",
>    "subcontainers": [
>     {
>      "name": "/docker"
>

**Comment by devent** [comment]
Hello, I have the same problem with my cluster. Everything else works fine.

In my tests I can connect to the master node running nc from heapster pod, but I can't connect to the worker node running the same nc from the heapster pod.

```
From heapster pod
/ # wget http://andrea-master-0.muellerpublic.de:39556
Connecting to andrea-master-0.muellerpublic.de:39556 (185.24.220.41:39556)
wget: error getting response: Connection reset by peer
Master node
root@andrea-master-0:~# nc -l 66 < kubectl-system.sh
invalid connection to [185.24.220.41] from (UNKNOWN) [37.252.124.149] 41476
Works
```

```
From heapster pod
/ # wget http://andrea-node-0.muellerpublic.de:52339
Connecting to andrea-node-0.muellerpublic.de:52339 (37.252.124.149:52339)
wget: can't connect to remote host (37.252.124.149): Connection timed out
```

The exact error is
```
2017-04-21T09:21:12.184653499Z W0421 09:21:12.184455       1 manager.go:102] Failed to get kubelet_summary:37.252.124.149:10255 response in time
2017-04-21T09:21:25.000604903Z W0421 09:21:25.000396       1 manager.go:147] Failed to get all responses in time (got 1/2)
2017-04-21T09:22:12.216373835Z E0421 09:22:12.216138       1 summary.go:97] error while getting metrics summary from Kubelet andrea-node-0.muellerpublic.de(37.252.124.149:10255): Get http://37.252.124.149:10255/stats/summary/: dial tcp 37.252.124.149:10255: getsockopt: connection timed out
```

Versions.
heapster 1.3.0

```
root@andrea-master-0:~# ksys version
Client Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4", GitCommit:"7243c69eb523aa4377bce883e7c0dd76b84709a1", GitTreeState:"clean", BuildDate:"2017-03-07T23:53:09Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"5", GitVersion:"v1.5.4+coreos.0", GitCommit:"97c11b097b1a2b194f1eddca8ce5468fcc83331c", GitTreeState:"clean", BuildDate:"2017-03-08T23:54:21Z", GoVersion:"go1.7.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by pastushenko** [comment]
Hello! We have the same problem.
`
Failed to get kubelet:10.0.5.186:10255 response in time
W0426 08:41:25.000504       1 manager.go:147] Failed to get all responses in time (got 4/5)
`
Kubernetes version: v1.6.1+coreos.0
Heapster version: v1.3.0-beta.1

We have 5 nodes in cluster.
We use private network.
As network provider we use flannel.
I found out that the heapster can't collect monitoring data from the node where his pod is placed.
In my case - the heapster pod is placed on node #4.
From node #4 i can telnet self kubelet (port: 10255), but i can't telnet same kubelet from any container on node #4.
From other nodes and other containers placed on other nodes - the problem don't appear (i can telnet kubelet on node #4)

**Comment by takama** [comment]
@willtrking  By default Calico blocks traffic from workload endpoints to the host itself with an iptables `DROP` action. If you want to allow traffic from endpoint to host, set this parameter to `ACCEPT`:
```
        - name: calico-node
          image: quay.io/calico/node:v1.1.1
          env:
            - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
              value: "ACCEPT"
```

**Comment by takama** [comment]
@pastushenko You can allow traffic from containers to the host itself using firewall rules especially to the port 10255. (Interfaces: flannel.1, docker0)

**Comment by pastushenko** [comment]
@takama - thanks. The problem was fixed by changing firewall rules.

**Comment by devent** [comment]
@takama Thank you, my issue was resolved by applying `FELIX_DEFAULTENDPOINTTOHOSTACTION=ACCEPT`. I think you can close the issue now, because it looks like it's not an issue with Heapster.

**Comment by willtrking** [comment]
@takama Thank you!! Fixed it for me as well

**Comment by iamrandys** [comment]
Does anyone have any idea on how to configure FELIX_DEFAULTENDPOINTTOHOSTACTION=ACCEPT if Calico was used to create the Kubernetes cluster using Kops?

`kops create cluster --networking calico`

**Comment by jurgenweber** [comment]
for those that `kops create cluster --networking canal`

`kubectl edit ds canal -n kube-system`

add the environment variable as per the above with the other environment variables for the container named:

```    spec:
      containers:
      - env:
        - name: DATASTORE_TYPE
          value: kubernetes
 ...
        - name: FELIX_DEFAULTENDPOINTTOHOSTACTION
          value: ACCEPT
        image: calico/node:v1.0.2
        imagePullPolicy: IfNotPresent
        name: calico-node
```

To make it live you have two optinos, either delete the pods so they recreate or add this to your updatestratergy, replace 'DeleteOnly' with:

```  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
```

and it will go and updated it all after saving the edit.

**Comment by chenjianjun19920702** [comment]
@pastushenko  k8s cluster already close firewalld, how to change firewall rules, Looking forward to your reply, thanks!!!

**Comment by zwlsuperman** [comment]
@pastushenko @willtrking @DirectXMan12 
 k8s cluster already close firewalld, how to change firewall rules，
Looking forward to your reply, thanks!!!
and I use flanal network,
heapster pods error:

_E0626 15:04:12.278239       1 manager.go:101] Error in scraping containers from kubelet_summary:39.107.155.74:10255: Get http://39.107.155.74:10255/stats/summary/: dial tcp 39.107.155.74:10255: getsockopt: connection timed out
W0626 15:04:25.001017       1 manager.go:152] Failed to get all responses in time (got 4/5)

[root@ao-docker01 ~]# kubectl describe hpa
Name:                                                  spider001
Namespace:                                             default
Labels:                                                <none>
Annotations:                                           <none>
CreationTimestamp:                                     Tue, 26 Jun 2018 15:28:21 +0800
Reference:                                             Deployment/spider001
Metrics:                                               ( current / target )
  resource cpu on pods  (as a percentage of request):  <unknown> / 50%
Min replicas:                                          1
Max replicas:                                          6
Conditions:
  Type           Status  Reason                   Message
  ----           ------  ------                   -------
  AbleToScale    True    SucceededGetScale        the HPA controller was able to get the target's current scale
  ScalingActive  False   FailedGetResourceMetric  the HPA was unable to compute the replica count: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
Events:
  Type     Reason                        Age                 From                       Message
  ----     ------                        ----                ----                       -------
  Warning  FailedComputeMetricsReplicas  15m (x481 over 4h)  horizontal-pod-autoscaler  failed to get cpu utilization: unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
  Warning  FailedGetResourceMetric       3s (x511 over 4h)   horizontal-pod-autoscaler  unable to get metrics for resource cpu: unable to fetch metrics from resource metrics API: the server could not find the requested resource (get pods.metrics.k8s.io)
