### ISSUE TITLE
Add CloudWatch as DataSource with AWS IAM ROLE will got an error in grafana

### ISSUE THREAD

**Issue by axot** [kubernetes/heapster#1588]
$ kubectl logs -f monitoring-grafana-2293934309-n5qzp --namespace=kube-system
t=2017-03-29T10:08:07+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="RequestError: send request failed\ncaused by: Post https://monitoring.ap-northeast-1.amazonaws.com/: x509: failed to load system roots and no roots provided"

**Comment by DirectXMan12** [comment]
if you're still seeing this, please re-open.
