### ISSUE TITLE
heapster-nanny complains when run with system:heapster RBAC permissions

### ISSUE THREAD

**Issue by edevil** [kubernetes/heapster#1589]
I've tried running the heapster pod with a serviceAccount with the system:heapster role but "nanny" complains about not having permissions to perform certain operations. Is the role badly defined?

nanny log
```
I0401 00:00:54.492157       1 nanny_lib.go:109] Resources are not within the expected limits: updating the deployment.
E0401 00:00:54.494259       1 nanny_lib.go:111] the server does not allow access to the requested resource (get deployments.extensions heapster-v1.2.0-beta.1)
```

apiserver log
```
I0331 23:50:03.392482       1 rbac.go:87] RBAC DENY: user "system:serviceaccount:kube-system:heapster" groups [system:serviceaccounts system:serviceaccounts:kube-system system:authenticated] cannot "get" resource "deployments.extensions" named "heapster-v1.2.0-beta.1" in namespace "kube-system"
```

I ran the following commands to create the serviceAccount:
```
    kubectl create serviceaccount heapster --namespace=kube-system
    kubectl create clusterrolebinding heapster-role --clusterrole=system:heapster --serviceaccount=kube-system:heapster --namespace=heapster
```

**Comment by DirectXMan12** [comment]
this should probably be filed against the main kube repo (since the problem is policy and non Heapster), although I'd argue that the RBAC is correct in denying the Heapster pod the ability to modify its own configuration.  That feels poor from a security perspective.

**Comment by DirectXMan12** [comment]
cc @piosz

**Comment by piosz** [comment]
cc @mwielgus @x13n
