### ISSUE TITLE
system:heapster ClusterRole lacking privileges 

### ISSUE THREAD

**Issue by michaelajr** [kubernetes/heapster#1595]
Kubernetes 1.6.1
-----------------

The `system:heapster` ClusterRole appears to be missing the ability to HTTP GET and HTTP PUT to `deployments.extensions`.  Here is my local update - not sure if this the *right* way to do it - seems there should be a way to provide HTTP PUT to only `deployment.extensions` and not all the other resources (least privilege). But it is a hacked workaround.

```apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    kubernetes.io/bootstrapping: rbac-defaults
  name: system:heapster 
rules:
- apiGroups:
  - ""
  - extensions
  resources:
  - events
  - namespaces
  - nodes
  - pods
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
```

**Comment by DirectXMan12** [comment]
Why should the `system:heapster` role be able to GET and PUT extensions.deployments?  The Heapster code should only be able to GET/LIST and even then only what it needs to know about to function: Events, Namespaces, Nodes, and Pods.

**Comment by michaelajr** [comment]
Good question. But it does. Did not work without it. Something to do with the Dashboard maybe?

**Comment by c-knowles** [comment]
I was wondering if this is the same issue as https://github.com/kubernetes/heapster/issues/1589? I've been trying to tackle this for kube-aws in https://github.com/kubernetes-incubator/kube-aws/issues/685, I agree with the comments from @DirectXMan12 about not giving heapster the ability to modify its own configuration. Are there any working examples of heapster with nanny in the wild?

**Comment by DirectXMan12** [comment]
@piosz might know

**Comment by piosz** [comment]
cc @mwielgus @x13n

**Comment by piosz** [comment]
I was not aware of any problems with pod_nanny permissions. If there are any we need to update rbac policies so that the pod nanny has appropriate permissions to do its job.

I agree that it's a weird situation when Heapster pod wants to modify itself and long term we may want to introduce maybe a separate controller for this purpose. See https://github.com/kubernetes/kubernetes/issues/46763

**Comment by piosz** [comment]
@x13n could you please verify this?

**Comment by x13n** [comment]
pod_nanny for heapster at the moment existsing in the same pod as heapster itself, so if it is forbidden from modifying this pod requirements/limits, it won't work. However, ClusterRole is set only in yaml example from heapster repo:

https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/influxdb/heapster.yaml

but is not set in main kubernetes repo, which is used when setting up a cluster:

https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-

https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/influxdb/heapster-controller.yaml

Right now the problem will show up only when both pod_nanny and RBAC are used for Heapster at the same time. So, short term, giving those permissions looks like the way to go. Long term, as @piosz wrote, we need kubernetes/kubernetes#46763.

**Comment by c-knowles** [comment]
https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/heapster-rbac.yaml seems to have the config needed sort out the pod nanny issue. I'm not always sure of the definitive setup as it seems to be distributed across repos and there's a lot of duplication, if anyone could help clarify for me it would be helpful to pulling in upstream changes into kube-aws.

**Comment by x13n** [comment]
/remove-lifecycle rotten

https://github.com/kubernetes/heapster/pull/1612 introduced a ClusterRoleBinding for heapster, but nothing for pod_nanny. Reusing https://github.com/kubernetes/kubernetes/blob/master/cluster/addons/cluster-monitoring/heapster-rbac.yaml will be enough here.

/cc @luxas who made the original change.
