### ISSUE TITLE
Cannot use grafana-cli

### ISSUE THREAD

**Issue by Kliton** [kubernetes/heapster#1596]
I cannot install plugins with grafana image: gcr.io/google_containers/heapster-grafana-amd64:v4.0.2
I'm on GCE.

When i attach to pod with "exec -ti podName -- /bin/sh" i can start bin in /usr/sbin like grafana-server but not "grafana-cli" it always says: not found..

**Comment by DirectXMan12** [comment]
@piosz do we have the grafana-cli in our images?  Should we?

**Comment by Ascendance** [comment]
YES

**Comment by DirectXMan12** [comment]
If grafana-cli is just for managing plugins, I'm tempted to say that things like installing plugins should be done at image build time, not at runtime, and that if you want to install plugins, you can pull in grafana-cli separately.

I'm open to other opinions though

**Comment by dasher** [comment]
How about using an env var to pass a list of plugins to be installed at run time (as per the offical grafana way https://github.com/grafana/grafana-docker#installing-plugins-for-grafana-3 )?

**Comment by andyxning** [comment]
I agree with @dasher to provide a configuration method to provide a way to install plugins at runtime cause we can not confirm what plugins to install at compile time.

**Comment by DirectXMan12** [comment]
> cause we can not confirm what plugins to install at compile time.

Sure, but presumably the admin/user deploying grafana does, right?  So they should have an image
```dockerfile
FROM  gcr.io/google_containers/heapster-grafana-amd64:v4.0.2

# install our plugins and then remove grafana-cli to avoid runtime security issues
COPY grafana-cli /tmp/grafana-cli
RUN /tmp/grafana-cli do-some-stuff
RUN rm /tmp/grafana-cli
```

and use that for running Grafana on their cluster.

**Comment by djschny** [comment]
Considering the [official docker image for grafana](https://github.com/grafana/grafana-docker#installing-plugins-for-grafana-3) supports `GF_INSTALL_PLUGINS` I was hoping the following would work:

```
        - name: GF_INSTALL_PLUGINS
          value: raintank-kubernetes-app
```

**Comment by diegocn** [comment]
I can confirm it @djschny. Tried to use env, as suggested by official docker image for grafana, and doesn't work.

```
> kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6e
f37", GitTreeState:"clean", BuildDate:"2017-03-28T16:36:33Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"
}
Server Version: version.Info{Major:"1", Minor:"6+", GitVersion:"v1.6.6-rancher1", GitCommit:"973d2fa162b887a6f696f4574b8
5e949d480a071", GitTreeState:"clean", BuildDate:"2017-06-17T03:54:44Z", GoVersion:"go1.7.6", Compiler:"gc", Platform:"li
nux/amd64"}
```

**Comment by DirectXMan12** [comment]
Closing as per my response above.  If you want to do something special for your cluster, build your own image.
