### ISSUE TITLE
Redondant deploy configuration with kubernetes repository

### ISSUE THREAD

**Issue by kartoch** [kubernetes/heapster#1598]
It seems the deployement configuration proposed here:
https://github.com/kubernetes/heapster/tree/08c8af3/deploy/kube-config
Are also available here (with more recent updates):
https://github.com/kubernetes/kubernetes/tree/69fd7aa/cluster/addons/cluster-monitoring/influxdb
Maybe a good idea to close the heapster directory ?

**Comment by DirectXMan12** [comment]
@piosz is there any reason for us to keep around two separate copies of the deployment information?  I'd tend to agree with @kartoch here...

**Comment by piosz** [comment]
I had similar thoughts many times in the past and eventually came to the conclusion that there is a lot of template boilerplate + addon resizer out of the box in Kubernetes deployment version, so it's not possible to just create Heapster deployment without using `kube-up.sh` scripts. At the same time there was a number of issues filed in Heapster repo about not working deployment files so it seems there is a number of folks using them.

I think at some point it would be great to have them in a single place but I'm afraid we are not ready for this yet.
