### ISSUE TITLE
About network rx and tx

### ISSUE THREAD

**Issue by TracyBin** [kubernetes/heapster#1599]
hi, I want to collect network traffic data. When I use the following command, the result confused me.
```
[root@252-vm ~]# curl -L http://10.244.0.13:8082/api/v1/model/nodes/252-vm/metrics/network/rx_rate
{
  "metrics": [
   {
    "timestamp": "2017-04-19T07:47:00Z",
    "value": 869
   },
   {
    "timestamp": "2017-04-19T07:48:00Z",
    "value": 978
   },
   {
    "timestamp": "2017-04-19T07:49:00Z",
    "value": 977
   }
  ],
  "latestTimestamp": "2017-04-19T07:49:00Z"
 }
```
There is three dev in my node, eth0,cni and flannel0. And also other docker net dev.
Which dev data is collected by this command?

**Comment by piosz** [comment]
@bowei @dashpole @timstclair @vishh do you know?

**Comment by DirectXMan12** [comment]
hmm... probably the underlying metrics are labeled metrics in Heapster, but the model API doesn't expose those so well...

**Comment by DirectXMan12** [comment]
In the internal representation, they're probably labeled per network adapter.

**Comment by timstclair** [comment]
It's based on eth0. It's currently hard coded, but there's a couple open bugs to fix that (https://github.com/kubernetes/kubernetes/issues/28407)

**Comment by bowei** [comment]
Closing in favor of kubernetes/kubernetes#28407

/close
