### ISSUE TITLE
Is there a config to enable ssl connection between heapster and Elasticsearch to sink metrics to Elasticsearch

### ISSUE THREAD

**Issue by lcnsir** [kubernetes/heapster#1603]
Is there a config to enable ssl connection between heapster and Elasticsearch to sink metrics to Elasticsearch

**Comment by lcnsir** [comment]
?

**Comment by andyxning** [comment]
@lcnsir heapster and eventer uses [olivere/elastic](https://github.com/olivere/elastic) as the ES client. I have find nothing info about ssl for it.

However, after diving into the code, it seems that `olivere/elastic` uses golang default http client to process http requests. So, the question can be addressed by confirm that whether http default client supports ssl. 

It seems that golang http default client supports well known certificates. As for self-issued certificates, i am afraid that there is no way to do this for `olivere/elastic` and even heapster and eventer. 

you can try it with well known certificastes according [elasticsearch doc](https://github.com/kubernetes/heapster/blob/master/docs/sink-configuration.md#elasticsearch).

Any feedback is appreciated. :)

**Comment by DirectXMan12** [comment]
cc @AlmogBaku @andyxning @huangyuqi

**Comment by AlmogBaku** [comment]
As we discussed before - I'm not in favor of providing CA file or bypassing the check. As a solution, you can attach your CA to the container's known CAs by the kubernetes manifest.

/close
