### ISSUE TITLE
Disable logging or switching log level doesn't work

### ISSUE THREAD

**Issue by alexandrst88** [kubernetes/heapster#1609]
Hi! I'm trying to disable logging of heapster of change log level, with `--v=1` or `--v=2`. But it always logs INFO and WARNING level.
I'm running following version with args:
```        image: gcr.io/google_containers/heapster-amd64:v1.3.0
        imagePullPolicy: Always
        command:
        - /heapster
        - "--source=kubernetes:https//kube-host"
        - --sink=opentsdb:http://tsdb-hosts
        - --metric_resolution=300s
        - --v=1```

**Comment by andyxning** [comment]
@alexandrst88 `glog` can not disable log. 
* without any `--v` option, output generic log like `glog.Info` or `glog.Warning`
* with setting `--v=1` option, output verbose log `glog.V(1).Info`
* with setting `--v=2` option, output verbose log `glog.V(2).Info`

you can take a look at [glog usage info](https://github.com/golang/glog/blob/master/glog.go#L21-L70).

**Comment by alexandrst88** [comment]
@andyxning does it possible to log only critical or error level?

**Comment by andyxning** [comment]
You can only  adjust `stderrthreshold=WARNING` command line argument to control the log level when only logging to stderr by setting `logtostderr=true`.

As for logging to files, i am afraid that there is no common way to accomplish this.

BTW, i am curious that why you want to disable info logs.

**Comment by DirectXMan12** [comment]
for positerity, you can also use `--logtostderr` to *only* log to std err.
