### ISSUE TITLE
Grafana setup should use password from `GF_SECURITY_ADMIN_PASSWORD`

### ISSUE THREAD

**Issue by olalonde** [kubernetes/heapster#1615]
The environment variable to change the default admin password in Grafana is `GF_SECURITY_ADMIN_PASSWORD` and not `GRAFANA_PASSWD`. Therefore it would make sense to use that env variable in https://github.com/kubernetes/heapster/blob/master/grafana/setup_grafana.go

**Comment by adambkaplan** [comment]
Similar issue reported in #1623

**Comment by DirectXMan12** [comment]
Fixed by  	05f739e
