### ISSUE TITLE
Dashboards are not compatible with latest grafana/Influxdb

### ISSUE THREAD

**Issue by kotarusv** [kubernetes/heapster#1617]
These dashboards are not working when trying to import to Grafana/InfluxDB/heapster Setup. Are they compatible with newer version of grafana? 

Srinivas Kotaru

**Comment by DirectXMan12** [comment]
Can you please indicate which version of Heapster and which version of Graphana and InfluxDB you are using?

**Comment by kotarusv** [comment]
I'm using all latest versions

InfluxDB shell version: 1.2.2
Grafana : 4.2.0
Heapster : v1.3.0

**Comment by wedgeV** [comment]
I just updated to Grafana 4.2.0, but that image had different VOLUMEs compared to the heapster grafana image, that made it loose all the dashboards and settings. I solved this by taking the Grafana 4.2.0 image, and removing the `VOLUME` directive in the Dockerfile and then build/deploy that image.

@kotarusv Not sure if that's the issue you're running into, but this worked for me.
