### ISSUE TITLE
[Dashboard] No Graphs, followed guidance

### ISSUE THREAD

**Issue by DarkBlaez** [kubernetes/heapster#1619]
Looking for the exact install instructions to get Heapster, InfluxDB, Grafana working and Dashboard to include graphs. I am using kubeadm to install a basic 3 node cluster. Typically I use the ansible scripts to do the full install of kubernetes on Centos 7.3. However, decided to try kubeadm. To get Heapster/InfluxDB/Grafana in stalled I followed the guidance of : kubectl create -f deploy/kube-config/influxdb/

Services were successfully created. However, Grafana throws an error on the UI that no server found and Dashboard still missing the graphs, etc.

I have looked online and found very little if any step-by-step instructions of getting this working when using kubeadm as the base installer for the cluster.

Kubeadm installs latest from repo which is v1.6.2 of kubernetes. Using Calico for the networking. Dashboard functional (minus graphs) along with all services are running with no issues

Heapster: v1.3.0
InfluxDB: v1.1.1
Grafana: v4.0.2

Please advise

Thanks
DB

**Comment by DirectXMan12** [comment]
Are there any issues in the Heapster logs?  Have you tried asking the dashboard repo?

**Comment by DarkBlaez** [comment]
I will ask the dashboard repo since this issue seems to get punted along and no one can even spell out the exact instructions as referenced above

**Comment by DarkBlaez** [comment]
So here is how I have installed this:

1. Git clone heapster project
2. Just use the kube.sh in deploy folder to initiate. Suppose I could use kubectl directly as well but result is the same when I have done so

3. I modify grafana.yaml in (/deploy/kube-config/influxdb) to use the api server proxy
    value: /api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/

no other changes. Grafana can see the template, shows Cluster and Pod as the choices. The InfluxDB data source is connected with no issues, however, there is no data points showing in Grafana

4. In checking heapster it is running. I query it with curl via:
curl localhost:8001/api/v1/proxy/namespaces/kube-system/services/heapster/metrics

The result is a long list of metrics

5. Checking further...
curl localhost:8001/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/debug/allkeys

I get a return of:
[
  "cluster"
 ]

What more can be done to check to see if heapster is feedin influxdb the data. This seems like perhaps the issue possibly.

Thanks
DB

**Comment by DirectXMan12** [comment]
> Also is cAdvisor part of the equation ?

Heapster makes use of the cAdvisor built in to the Kubelet.

If you run Heapster at high verbosity (`--v=10`), what do the Heapster logs say?
