### ISSUE TITLE
Alternatives to Heapster

### ISSUE THREAD

**Issue by soufiane8096** [kubernetes/heapster#1622]
Hi,

I would like to know if there is alternatives to Heapster. Do you know why Kubernetes choose Heaspter ? 

Thank you

**Comment by DirectXMan12** [comment]
This is not really an appropriate question for the Heapster issue tracker.  StackOverflow, the mailing list, or Slack are more appropriate venues for this discussion.  FWIW, we are moving in a direction of encouraging alternatives, as opposed to having all data flow through Heapster.  Check out the [monitoring vision](https://github.com/kubernetes/community/blob/master/contributors/design-proposals/monitoring_architecture.md) for more information.
