### ISSUE TITLE
InfluxDB can't sink pod without labels

### ISSUE THREAD

**Issue by watercraft** [kubernetes/heapster#1625]
I'm testing with InfluxDB V0.9 and an older version of Heapster so the problem may be solved in a different way.
However, I have a fix that works for us to consider.
The problem is that we are not collecting container stats for a pod that doesn't have labels.
This version of Heapster is pushing down a tag called "labels" for the container that is an empty string.
When I remove this tag with the empty string in the InflluxDB sink code, the data points are taken.

**Comment by DirectXMan12** [comment]
I do seem to recall seeing this issue before, possibly on another sink.  Can you reproduce with the latest Heapster?

**Comment by watercraft** [comment]
I have tried with the latest Heapster.  We will be upgrading to whatever is recommended for k8s 1.6 in the next month or so.  If it is not fixed by that version, I'll be caring my patch forward.
