### ISSUE TITLE
Does heapster support k8s pod label

### ISSUE THREAD

**Issue by kongbo1987** [kubernetes/heapster#1631]
I  want  to query a list pod metric in heapster by app name
is it possible to add k8s pod label like app to pod metric?

**Comment by DirectXMan12** [comment]
This is only supported for the resource metrics API (`/apis/metrics/v1alpha1/...`).  In that case, you can pass label selectors.  However, that API only provides CPU and memory.  The custom metrics API (not served through Heapster) also supports label selectors, but there are no providers for that yet (hopefully, we'll have one soon).
