### ISSUE TITLE
InfluxDB Sink : Tags support

### ISSUE THREAD

**Issue by kotarusv** [kubernetes/heapster#1632]
We have 3+ Kubernetes clusters. I spinoff a heapster pod on each cluster and sending metrics data to single centralized InfluxDB. All looking good and able to see the data. Since I am sending all metrics data from 3 clusters to single InfluxDB database, i am unable to differentiate the data. Is it possible to add tags like cluster=east cluster=east etc at heapster Sink definition? 

i want to query something like

select * from heapster_table where cluster=east or cluster=west etc 

I looked into documentation and couldn't find anyway to add tags at influxDB sink definition.

**Comment by andyxning** [comment]
Currently we do not support `cluster` tag. [Heapster supports `cluster_name` argument for ElasticSearch sink to differentiate different Kubernetes clusters](https://github.com/kubernetes/heapster/blob/master/docs/sink-configuration.md#elasticsearch).

**Comment by kotarusv** [comment]
Can we support cluster name tag for InfluxDB sink as well? I think that is very important  in multi cluster environment rather depending on regular expressions.

**Comment by andyxning** [comment]
I also think so. Will do it recently.
