### ISSUE TITLE
PV Info

### ISSUE THREAD

**Issue by kotarusv** [kubernetes/heapster#1638]
a pod can have a 1 or more PV's mounted inside the container. is it possible to check what is the size of the pV and utilization %? 

Use Case:

We have hundreds of PV in our kubernetes cluster. Unfortunately there is no way to find out how much storage being using by PODs to plan capacity well in advance as well as bill the client based on the usage pattern 

There is no direct way at this point. We have to mount the volume again in  a intermediate system and issue du command to check utilization or work with storage team to get the numbers. This is not scalable solution.

Srinivas Kotaru

**Comment by DirectXMan12** [comment]
This would be a better request for cAdvisor or the Kubelet.  Heapster just collects the metrics.
