### ISSUE TITLE
Containers "runtime" are renamed to "docker-daemon" 

### ISSUE THREAD

**Issue by piosz** [kubernetes/heapster#1639]
The reason is that due to legacy issue in Heapster we needed to translate "runtime" to "docker-daemon" for system containers and it seems that by accident we do it for all containers. See more details https://github.com/kubernetes/heapster/blob/master/metrics/sources/summary/summary.go#L351.

**Comment by piosz** [comment]
cc @timstclair @dashpole

**Comment by timstclair** [comment]
Oh yeah, that should only be done on system containers. Definitely a bug.
