### ISSUE TITLE
Is there a way to publish application events

### ISSUE THREAD

**Issue by ashic** [kubernetes/heapster#1640]
I'm using k8s + heapster + influxdb + grafana. It picks up all the kubernetes metrics, etc. Is there a way to publish business events from applications so that they get into influx, and then show up in grafana?

**Comment by DirectXMan12** [comment]
No.  That would be part of the "third-party" pipelines described in the monitoring design document: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/monitoring_architecture.md
