### ISSUE TITLE
socker_writer sink with json output format support

### ISSUE THREAD

**Issue by djsly** [kubernetes/heapster#1644]
I am creating this issue as to see if it would be accepted to enhanced Heapster with a new TCP sink and a new json serializer.

We are currently using `telegraf` to query `prometheus` metrics and sending those to `logstash` using the https://github.com/influxdata/telegraf/tree/master/plugins/outputs/socket_writer output. We are serializing the data in https://github.com/influxdata/telegraf/blob/master/docs/DATA_FORMATS_OUTPUT.md#json since telegraf does not support custom CA for https with elasticsearch. Using the following go client: http://olivere.github.io/elastic/

I would like to use the same mechanisms with Heapster / Eventer and support both metrics and events serialized as JSON following the same format from `telegraf` and sink those to a TCP/UDP writer. 

Before I start writing the support, any objections or differnt views on the subject ?

Thanks!

**Comment by DirectXMan12** [comment]
Is there a reason that the elasticsearch sink for Heapster wouldn't work for you?

**Comment by djsly** [comment]
Unfortunately, the ElasticSearch cluster is provided by a different team. We are not giving the credentials for it. Their entry point to the cluster is LogStash at the moment.

**Comment by DirectXMan12** [comment]
I'm a little hesitant to support this, since it seems not quite as generally useful (since most people can probably just use the elasticsearch sink), and every new sink in Heapster adds maintenance burden to us.

WDYT @piosz

**Comment by andyxning** [comment]
I agree with @DirectXMan12 since it seems ES has already meet the demands.
