### ISSUE TITLE
why the same config ,heapster1.2 can work,but not 1.3

### ISSUE THREAD

**Issue by Chentongxuedefanhua** [kubernetes/heapster#1645]
![cache_1490c46f0ea3c1d3](https://cloud.githubusercontent.com/assets/18111540/26032690/c7784b8c-38cb-11e7-8a02-aea98474cb82.jpg)

**Comment by DirectXMan12** [comment]
looks like your kubeconfig file is not set up properly.  I'd check that (the error is from client-go, validating the kubeconfig).  Alternatively, if you're running on cluster, you shouldn't have to manually specify a kubeconfig -- you can just rely on in-cluster config.

**Comment by Chentongxuedefanhua** [comment]
Thanks for your reply，The problem has been settled，thanks，@DirectXMan12
