### ISSUE TITLE
Failed to list *v1.Namespace: User "system:serviceaccount:kube-system:heapster" cannot list namespaces at the cluster scope 

### ISSUE THREAD

**Issue by huangjiasingle** [kubernetes/heapster#1652]
git clone https://github.com/kubernetes/heapster.git 
cd heapster/deploy/kube-config/influxdb && create -f ./
the all pod is running, but the dashboard and grafana doesn't get the metri of node and pod's 
so l use kubectl logs heapster 's name  ,the log show this : 

Failed to list *v1.Node: User "system:serviceaccount:kube-system:heapster" cannot list nodes at the cluster scope. (get nodes)

Failed to list *v1.Pod: User "system:serviceaccount:kube-system:heapster" cannot list pods at the cluster scope. (get pods)

laste day i use this in another k8s's cluster , it's ok 

i see the heapster's yaml ,it doesn't exist role defined

**Comment by DirectXMan12** [comment]
there should be a Heapster role automatically created as part of the bootstrap policy.  Make sure that role is present (if not, sync your bootstrap policy), and make sure there's a clusterrolebinding binding the `kube-system:heapster` serviceaccount to that clusterrole.

**Comment by DirectXMan12** [comment]
(feel free to re-open the issue if that doesn't work).

**Comment by huangjiasingle** [comment]
my k8s cluster env is v1.6.3,  role and rolebinding named kube-system:heapster doesn't exsit,so l have to create it by manual.

**Comment by DirectXMan12** [comment]
make sure you sync your bootstrap policy -- the policy is definitely in the set of bootstrap policy for 1.6.3 (I just checked): https://github.com/kubernetes/kubernetes/blob/v1.6.3/plugin/pkg/auth/authorizer/rbac/bootstrappolicy/policy.go#L199

**Comment by jiripospisil** [comment]
Just bumped into it as well and solved it by doing [1]. Maybe the step is just missing in the [guide](https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md)? 

```
[1] kubectl create -f deploy/kube-config/rbac/heapster-rbac.yaml
```

**Comment by ffahri** [comment]
@jiripospisil thats solves myself too thanks

**Comment by h34dless** [comment]
solved it with that, too - but had to delete the heapster pod for it to be effective
