### ISSUE TITLE
Decrease Influxdb tags

### ISSUE THREAD

**Issue by andyxning** [kubernetes/heapster#1654]
Currently, we have a lot of influxdb tags. IMO, some of them are duplicated. This may cause a problem when the cluster size growing and the number of data stored in Influxdb is growing. 

According to [Influxdb Doc in v1.2](https://docs.influxdata.com/influxdb/v1.2/concepts/schema_and_data_layout/#don-t-have-too-many-series), the more cardinality the series are, the more memory will be used, thus Influxdb will do more and more GC during service. Even Golang is enhancing its GC, we should also enhance our heapster usage to decrease Influxdb memory.

Assumption of Duplication:
* `namespace_id` and `namespace_name`
  * Prefer `namepsace_name`
* `pod_id` and `pod_name`
  * Prefer `pod_name`
* `pod_namespace` has been marked as deprecated. When will this tag be deleted?
* `nodename` and `hostname`
  * Prefer `nodename`

@kubernetes/heapster-maintainers @piosz @DirectXMan12

**Comment by DirectXMan12** [comment]
this seems reasonable to me.  I'd welcome a patch.

**Comment by andyxning** [comment]
@DirectXMan12 I will work on a patch recently. I think we should just do this just for Influxdb sink for now. Once all other sinks make an agreement on this, we should refactor this from the original source.

**Comment by piosz** [comment]
My opinion is that we can remove `pod_namespace` and one of `nodename` and `hostname`.

We should keep both `pod_id` and `pod_name` because the former is guaranteed to be unique and is the computer friendly while the latter is human friendly. Same with namespace.

**Comment by andyxning** [comment]
Does it really useful by adding `pod_id` or `namespace_id`? What is the usage?

**Comment by andyxning** [comment]
AFAIK, kubernetes has no api having a uuid as a query parameter(please let me know if i am wrong). If we need uuid info, by composing time, namespace, and pod name we can query kubernetes for corresponding uuid.

**Comment by ringtail** [comment]
pod_id is very useful if you need to find something unique

**Comment by andyxning** [comment]
namespace_name + pod_name can also uniquely determine a pod.

**Comment by ringtail** [comment]
namespace_name + pod_name is not unique in historical metrics.

**Comment by andyxning** [comment]
> namespace_name + pod_name is not unique in historical metrics.

This quite be true. But i am curious about your demand on what you need a unique identification among the total time window metrics.

**Comment by ringtail** [comment]
Every time deployment release change it's ReplicaSet and Pod and then you need to update the current pod or ReplicaSet to deployment monitor job. so if you want to get the metrics before this release, you need to get the specific data with unique id otherwise you must query the metrics with much more complex statement to avoid data obfuscation.

**Comment by andyxning** [comment]
IIUC, you mean that you want to query historical pod metrics, right?

Since deployment name in a namespace is unique and ReplicaSet and Pod name are both derived from deployment name, it should be ok to uniquely identify the pods for different releases plus time range since only one deployment release should exist in a namespace at a time and the same for pods and resplicasets.
