### ISSUE TITLE
Failed to create infuxdb

### ISSUE THREAD

**Issue by bluishpe** [kubernetes/heapster#1655]
I always get this error after I configured grafana/influxdb/heapster

1 influxdb.go:150] Failed to create infuxdb: failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp 10.104.9.9:8086: getsockopt: connection timed out

it does not matter what combination of versions I try, it always fails. any idea why?

what should I be checking?

**Comment by andyxning** [comment]
@bluishpe Have you tried to access ` http://monitoring-influxdb:8086/ping` in the chrome address bar or `wget  http://monitoring-influxdb:8086/ping`

**Comment by bluishpe** [comment]
when I try:

wget http://monitoring-influxdb:8086/ping
--2017-05-21 03:44:59--  http://monitoring-influxdb:8086/ping
Resolving web-proxy.in.hpecorp.net (web-proxy.in.hpecorp.net)... 16.1X7.XX.X10
Connecting to web-proxy.in.hpecorp.net (web-proxy.in.hpecorp.net)|16.1X7.XX.X10|:8080... connected.
Proxy request sent, awaiting response... 404 Not Found
2017-05-21 03:45:00 ERROR 404: Not Found.

**Comment by bluishpe** [comment]
when I try:

wget http://monitoring-influxdb:8086/ping
--2017-05-21 03:44:59--  http://monitoring-influxdb:8086/ping
Resolving web-proxy.XXX.net (web-proxy.XXX.net )... 16.XXX.XX.210
Connecting to web-proxy.XXX.net (web-proxy.XXX.net)|16.XXX.XX.210|:8080... connected.
Proxy request sent, awaiting response... 404 Not Found
2017-05-21 03:45:00 ERROR 404: Not Found.

**Comment by andyxning** [comment]
According to the response, it seems that it is the wrong configuration in the reverse proxy about `monitoring-influxdb` instead of heapster.

You should check and confirm that you setting up an influxdb instance correctly.

**Comment by bluishpe** [comment]
You should check and confirm that you setting up an influxdb instance correctly.
          Do you know what I should be checking exactly?

Thanks!

**Comment by andyxning** [comment]
* check if the instance ping endpoint is accessible by `ip:port/ping`.
* If it is accessible through `ip:port/ping`, then you should check your reverse proxy settings. If this is the truth, could you please paste the configuration. 
* If it can not be accessed by `ip:port/ping`, then you should firstly check whether the influxdb instance is running.

**Comment by bluishpe** [comment]
do you have the steps for me to verify the setup correctly?

My heapster has the following config:

apiVersion: v1
kind: ServiceAccount
metadata:
  name: heapster
  namespace: kube-system
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: heapster
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: kubernetes/heapster:canary
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes.summary_api:''
        - --sink=influxdb:http://monitoring-influxdb:8086
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  name: heapster
  namespace: kube-system
spec:
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 30310
  selector:
    k8s-app: heapster
  type: NodePort

**Comment by andyxning** [comment]
Sorry for not making it clear that what i have proposed for checking is targeted for influxdb. Comments has been updated, please take a look at [this](https://github.com/kubernetes/heapster/issues/1655#issuecomment-302921431).

**Comment by andyxning** [comment]
Seems that you may try this `wget http://monitoring-influxdb/ping`. Remove the `8086` port.

**Comment by bluishpe** [comment]
Can you tell me the exact working version of below so that I can reconfigure the setup:
Kubernetes version
heapster
grafana
influxdb
flannel
kube-dns

**Comment by andyxning** [comment]
I am not faimilar with kube-dns. Have you tried minotoring-influxdb without the port 8086?

YOU deploy influxdb in kubernetes cluster?

**Comment by bluishpe** [comment]
Yes, have deployed in a kuberneter cluster, version 1.5.4
what should I use instead of kube-dns? do we have another option?

**Comment by bluishpe** [comment]
even without port its the same error:

 wget http://monitoring-influxdb/ping
--2017-05-21 08:07:46--  http://monitoring-influxdb/ping
Resolving web-proxy.XXX.net (web-proxy.XXX.net)... 16.XXXX.28.210
Connecting to web-proxy.XXX.net (web-proxy.XXX.net)|16.XXX.210|:8080... connected.
Proxy request sent, awaiting response... 404 Not Found
2017-05-21 08:07:47 ERROR 404: Not Found.

**Comment by andyxning** [comment]
Could you please paste the k8s rc/pod configuration about influxdb

**Comment by andyxning** [comment]
you should try to wget inside heapster pod

**Comment by bluishpe** [comment]
Can I edit /etc/hosts of the heapster to include ip and name of influxdb so that ping is successful between them?

**Comment by bluishpe** [comment]
influxDB yaml

kind: Deployment
metadata:
  name: monitoring-influxdb
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        task: monitoring
        k8s-app: influxdb
    spec:
      containers:
      - name: influxdb
        image: gcr.io/google_containers/heapster_influxdb:v0.7
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
      volumes:
      - name: influxdb-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    task: monitoring
    # For use as a Cluster add-on (https://github.com/kubernetes/kubernetes/tree/master/cluster/addons)
    # If you are NOT using this as an addon, you should comment out this line.
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-influxdb
  name: monitoring-influxdb
  namespace: kube-system
spec:
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    nodePort: 30321
    protocol: TCP
  - name: api
    port: 8086
    targetPort: 8086
    nodePort: 30322
    protocol: TCP
  selector:
    k8s-app: influxdb
  type: NodePort

**Comment by andyxning** [comment]
wget http://monitoring-influxdb:30322/ping

**Comment by bluishpe** [comment]
Same error
port 30322 is for external connectivity. However here it seems like with pods there is no communication. Heapster should communicate to influxdb via 8086...please correct me if I am wrong.

 wget http://monitoring-influxdb:30322/ping
--2017-05-21 08:25:31--  http://monitoring-influxdb:30322/ping
Resolving web-proxy.XXXX.net (web-proxy.XXXX.net)... 16.XX.XX.210
Connecting to web-proxy.XXXX.net (web-proxy.XXXX.net)|16.XX.XX.210|:8080... connected.
Proxy request sent, awaiting response... 404 Not Found
2017-05-21 08:25:32 ERROR 404: Not Found.

**Comment by andyxning** [comment]
Have you tried the wget within the heapster pod?

Why your wget resulting 16.*, i.e. public ip address

**Comment by bluishpe** [comment]
Is this the right way to execute within heapster pod?

 kubectl --namespace=kube-system exec heapster-1865471235-7sbfx -- wget http://monitoring-influxdb:8086/ping
wget: bad address 'monitoring-influxdb:8086'


 kubectl --namespace=kube-system exec heapster-1865471235-7sbfx -- wget http://monitoring-influxdb:30322/ping
wget: bad address 'monitoring-influxdb:30322'

**Comment by bluishpe** [comment]
16.xx is the proxy within our company to access outside internet from that node.

**Comment by andyxning** [comment]
I guess maybe this is related to your `/etc/resolv.conf` settings. Can you please run the following command and paste the response.
`kubectl --namespace=kube-system exec heapster-1865471235-7sbfx -- cat /etc/resolv.conf`

**Comment by bluishpe** [comment]
Here is the output:

kubectl --namespace=kube-system exec heapster-1865471235-7sbfx -- cat /etc/resolv.conf
search kube-system.svc.cluster.local svc.cluster.local cluster.local hpeswlab.net
nameserver 10.96.0.10
options ndots:5

**Comment by andyxning** [comment]
Your influxdb pod should be accessible by `monitoring-influxdb.kube-system.svc.cluster.local/ping` according to [doc](https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/).

**Comment by bluishpe** [comment]
I get this output:

 kubectl --namespace=kube-system exec -ti heapster-1865471235-7sbfx -- nslookup kubernetes.default
Server:    (null)
Address 1: ::1 localhost
Address 2: 127.0.0.1 localhost

nslookup: can't resolve 'kubernetes.default': Name does not resolve



kubectl get pods --namespace=kube-system -l k8s-app=kube-dns
NAME                        READY     STATUS    RESTARTS   AGE
kube-dns-2924299975-gzhj9   4/4       Running   0          18h



kubectl get ep kube-dns --namespace=kube-system
NAME       ENDPOINTS                     AGE
kube-dns   10.244.0.4:53,10.244.0.4:53   18h

**Comment by andyxning** [comment]
It seems that the kube-dns is not working properly. You should check if it is set up properly.

**Comment by bluishpe** [comment]
Any suggestion to check kube-dns.
Is there an alternative to kube-dns that I can use in my setup?

**Comment by andyxning** [comment]
Sorry. I am not familiar with kube-dns. You should also check for the logs of kube-dns and whether the service for kube-dns is available.

**Comment by bluishpe** [comment]
Yes it running:

kubectl get services --all-namespaces
NAMESPACE     NAME                  CLUSTER-IP       EXTERNAL-IP   PORT(S)                         AGE
default       kubernetes            10.96.0.1        <none>        443/TCP                         19h
kube-system   heapster              10.96.203.201    <nodes>       80:30310/TCP                    3h
kube-system   kube-dns              10.96.0.10       <none>        53/UDP,53/TCP                   19h
kube-system   monitoring-grafana    10.110.164.244   <nodes>       80:30320/TCP                    3h
kube-system   monitoring-influxdb   10.104.155.62    <nodes>       8083:30321/TCP,8086:30322/TCP   3h

I don't see any errors in the logs for dns pod.

**Comment by DirectXMan12** [comment]
you also need to make sure you've set up the right flags on your Kubernetes cluster to auto-inject the DNS info.  IIRC, it's a flag on the Kubelet.
