### ISSUE TITLE
failed to start heapster container for the reason that can't join network of a non running container

### ISSUE THREAD

**Issue by hzfeng87** [kubernetes/heapster#1667]
I set up kubernetes with kubeadm and created heapster v1.3.0. But I found the pods can't start. It showed that 'rpc error: code = 2 desc = failed to start container "98fe84318e33ce449a19522443117474542bdf1849d00378eaf2cb6edf1b744d": Error response from daemon: cannot join network of a non running container: 2d2e8e9be946ef6eda66589dcdebfc35b0dc44bd79ca995dc1e87044d445b96f'

Then I described the heapster pod and found that '  33s	1s	5	kubelet, a01-r04-i217-59.jd.local		Warning	FailedSync	Error syncing pod, skipping: failed to "CreatePodSandbox" for "heapster-2315332064-0cscb_kube-system(ce7ef602-45dc-11e7-952d-40f2e9f16ec2)" with CreatePodSandboxError: "CreatePodSandbox for pod \"heapster-2315332064-0cscb_kube-system(ce7ef602-45dc-11e7-952d-40f2e9f16ec2)\" failed: rpc error: code = 2 desc = NetworkPlugin cni failed to set up pod \"heapster-2315332064-0cscb_kube-system\" network: \"cni0\" already has an IP address different from 10.244.2.1/24"
'

**Comment by hzfeng87** [comment]
my cni0 has the IP 10.244.3.1 and it was assigned after I created flannel. I am confused that why 10.244.2.1/24 is required force.

**Comment by DirectXMan12** [comment]
this is not a Heapster issue.
