### ISSUE TITLE
Would Heapster 1.0 work with Kubernetes 1.4 ?

### ISSUE THREAD

**Issue by deevya2000** [kubernetes/heapster#1668]
I really liked the /stats in the url in Heapster 1.0 that would give me a aggregation of all the metrics per hour,per day and per minute. I dont see that in Heapster 1.3. Is there some other way to get the data that is being returned by the /stats url in heapster 1.3 ? If not, then I would like to use Heapster1.0 (that had the /stats) along with my Kubernetes 1.4. Please let me know if this is possible

**Comment by DirectXMan12** [comment]
I'd expect that Heapster 1.0 should work with Kubernetes 1.4, but I'm not sure.  I'd have test it out to see.  At any rate, I'd avoid become dependent on any of those APIs -- they're not official APIs, and are likely to disappear.  If you want aggregation, please use one of the sinks.

**Comment by deevya2000** [comment]
I did try Kubernetes 1.4 with Heapster 1.0, it did work but I was not able to get the /stats API. Has it been discontinued ?

**Comment by deevya2000** [comment]
and is there any place I can find more info about aggregation in sinks ?

**Comment by DirectXMan12** [comment]
it's sink-dependent -- each sink has it's own query language that you could use to do that.

**Comment by deevya2000** [comment]
Thanks, also I had one more question, I dont see the file system metrics (filesystem/usage,filesystem/limit,
filesystem/available)  in Heapster 1.3 data that I receive from the REST API call, all I see  for my kubernetes dashboard pod is 

0	"memory/major_page_faults_rate"
1	"network/tx_errors_rate"
2	"network/rx_errors"
3	"network/tx_errors"
4	"memory/usage"
5	"memory/working_set"
6	"network/rx_errors_rate"
7	"cpu/request"
8	"uptime"
9	"cpu/limit"
10	"network/tx_rate"
11	"network/tx"
12	"cpu/usage_rate"
13	"network/rx"
14	"network/rx_rate"
15	"memory/page_faults_rate"
16	"memory/limit"
17	"memory/request"

Was this removed or is there some other way to retrieve them ?

**Comment by DirectXMan12** [comment]
it should still be there, according to the code.  I'd warn that Heapster 1.3 is relatively new, so is mostly tested against Kubernetes 1.5/1.6, not 1.4

**Comment by deevya2000** [comment]
Which version of Heapster would you suggest running against Kubernetes 1.4 ?

**Comment by DirectXMan12** [comment]
v1.2.0 is probably fine.
