### ISSUE TITLE
kafka sink is not able to rejoin via url specified in config

### ISSUE THREAD

**Issue by Kokan** [kubernetes/heapster#1672]
Heapster version: 1.2.0 (I tried 1.3.0 but we are using 1.2.0 in our system).
Only the kafka sink is configured with an url. That url is not directly one of the address of the kafka instance, but rather gives back all of the running avaiable kafka ips:

DNS is used to reach each instance (in kafka the below addresses configured as advertised address also).
kafka1.kafka
kafka2.kafka
kafka3.kafka

Because the number of kafka instances are dynamic, we do not know what is a valid address only the kafka, which gives back all of the above.

Heapster can connect and bootstrap fine. At this point it connects to one of the kafkaX.kafka. Everything is fine.

But if an instance failes we do not restart it, but remove and create a new instance which gots a new url and ip from the pool. Therefore the address can be the same, or completely different.
The kafka sink tries to connect to the same address and not the address configured in heapster, therefore sometimes it cannot reconnect.

**Comment by Kokan** [comment]
@huangyuqi ping

**Comment by DirectXMan12** [comment]
cc @miaoyq / @Kokan if this is still the case, feel free to act on it.

**Comment by Kokan** [comment]
This is still an issue, and I have a patch somewhere for it, but that is an ugly hack.
Actually I think this is a more common issue, there should be a way for each sink to "heal" from such issue.

What I mean when the `ExportData` is called, it could return a status, and if the command failed the manager could re-create that  `DataSink`. My patch had similar to this, but actually implemented inside `ExportData` that is not so clean solution. Also the current `RiemannSink` has this re-connection inside the `ExportData`.

Like `DataSink` could have a `Restart` method and `ExportData` a return value, and the manager could call restart if needed. Would it be okay in this way ?

**Comment by DirectXMan12** [comment]
Something like that sounds fairly reasonable.  Tag me when you submit the PR.
