### ISSUE TITLE
A misstake on the web .md file

### ISSUE THREAD

**Issue by wjdfx** [kubernetes/heapster#1673]
The  .md file 16 sloc display: image: gcr.io/google_containers/heapster-grafana-amd64:v4.2.0
It's wrong,the right info is : v4.0.2 , not v4.2.0
https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/influxdb/grafana.yaml

[#1669](url)

**Comment by DirectXMan12** [comment]
looks like a duplicate of the referenced issue.  Closing
