### ISSUE TITLE
Deleted pods show up in grafana

### ISSUE THREAD

**Issue by ompraash** [kubernetes/heapster#1675]
Version:
grafana: 4.0.2
heapster: 1.3.0-beta.1
influxdb: 1.1.1
kube version: 1.5.1

I am not sure if it is a feature, but let me start with my scenario. 

1. kube cluster has multiple pods across different namespaces.
2. Heapster, grafana and influxdb is working, can watch all stats.
3. After deleting few pods, grafana -> podname dropdown does not remove them.
    a. If the PODS are deleted, grafana -> podname drop down does not display the POD is deleted. Only way we can learn is there is no stats available.
 
Is this how it functions? or some setup is wrong on our end.

**Comment by DirectXMan12** [comment]
I'm not super familiar with how Grafana works, but I'd guess that it's because the series still exists in the TSDB -- the old metrics are still there, so you can still access the information for that pod.  Perhaps someone else can clarify, though.

**Comment by ompraash** [comment]
@DirectXMan12 shouldn't the system add a tag to the podname to indicate it is deleted. This would be a feature.

**Comment by DirectXMan12** [comment]
you should probably just scope your queries to a particular span of time... that should prevent deleted pods from showing up, I believe.

**Comment by andyxning** [comment]
It seems that the time range you specify contains both deleted pods and currently running pods. Once you specify show series from the time pods deleted, they should not show up.

**Comment by ompraash** [comment]
@andyxning @DirectXMan12 that is not true. Have the pods deleted 24 hrs ago, and yet i see them in the drop-down. thou do not show any stats, but yes the drop down list yet appears.

**Comment by andyxning** [comment]
@ompraash 

This may be related with Grafana top-down query. I guess the template variable does not apply the time range. It just do `show tag values`.

**Comment by andyxning** [comment]
@ompraash 

Please take a look at this [Grafana PR #3472](https://github.com/grafana/grafana/issues/3427) and [Grafana PR #4281](https://github.com/grafana/grafana/pull/4281). I suggest you give `On Time 
 Range Change` a try. 

![10](https://user-images.githubusercontent.com/2404712/26919456-56bbd8c2-4c68-11e7-9164-d23448beb876.png)

**Comment by ompraash** [comment]
@andyxning i tried as suggested but did not work. let me delete and recreate my env again.

**Comment by andyxning** [comment]
This is confusing. Hope you make some feedback after recreate you env and test again.
