### ISSUE TITLE
no heapster-grafana-amd64:v4.2.0 image

### ISSUE THREAD

**Issue by jwfang** [kubernetes/heapster#1676]
only found the following on https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/heapster-grafana-amd64
```
Name            Tags	Virtual size	Uploaded
ab7927a702b4    v4.0.2  43.1 MB         Jan 20, 2017
```

should i be a paid user for v4.2.0 ?

**Comment by kachkaev** [comment]
Also facing this. Temporary had to 

```bash
kubectl delete -f https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/grafana.yaml

http https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/grafana.yaml > grafana.yaml
sed -i 's/4.2.0/4.0.2/' grafana.yaml
kubectl create -f grafana.yaml
rm grafana.yaml
```

`http` command is from [httpie](https://httpie.org/) package.

**Comment by stresler** [comment]
Why close the duplicate issue that has a PR on it to fix this? Would it make more sense to close this one and re-open the one with the change on it?

**Comment by piosz** [comment]
I've built `gcr.io/google-containers/heapster-grafana-amd64:v4.2.0`. Please check the new one.
