### ISSUE TITLE
pods and cluster dashboard is not coming

### ISSUE THREAD

**Issue by SankarMittapally** [kubernetes/heapster#1685]
Hello,

 I am trying to configuring the heapster with kubernetes cluster with help of kubeadm. my cluster is up and running fine but heapster is unable to detect the information from the cluster, grafana is not connecting to influxdb also. Please let me know how to fix this issue.
![kubernetes](https://user-images.githubusercontent.com/13848964/27090763-bf0b1ab6-507b-11e7-88c2-3b182fbaf388.PNG)

```
root@kubernetes:/home/smittapally/heapster/deploy/kube-config/influxdb# kubectl get pods --all-namespaces
NAMESPACE     NAME                                    READY     STATUS    RESTARTS   AGE
kube-system   etcd-kubernetes                         1/1       Running   0          27m
kube-system   heapster-1428305041-7gnkm               1/1       Running   0          12m
kube-system   kube-apiserver-kubernetes               1/1       Running   0          27m
kube-system   kube-controller-manager-kubernetes      1/1       Running   0          27m
kube-system   kube-dns-3913472980-v08qd               3/3       Running   0          28m
kube-system   kube-proxy-5m50q                        1/1       Running   0          15m
kube-system   kube-proxy-srgkr                        1/1       Running   0          28m
kube-system   kube-scheduler-kubernetes               1/1       Running   0          28m
kube-system   kubernetes-dashboard-2039414953-tccb6   1/1       Running   0          26m
kube-system   monitoring-grafana-2107815241-b8626     1/1       Running   0          9m
kube-system   monitoring-influxdb-3480804314-43nqx    1/1       Running   0          12m
root@kubernetes:/home/smittapally/heapster/deploy/kube-config/influxdb#

```

**Comment by DirectXMan12** [comment]
> my cluster is up and running fine but heapster is unable to detect the information from the cluster, grafana is not connecting to influxdb also

Let's do this one at a time.  What are the symptoms of Heapster not being able to gather metrics?  You'll need to provide more information.  Please also provide versions of Kubernetes and Heapster.

**Comment by SankarMittapally** [comment]
Please find the details below. Actually I am able to access grafana dashboard but there is no pods and cluster dashboards and tried to establish connection between grafana and influxdb datasource got the above error. Please guide me how to fix this issue.

`root@kubernetes:/home/smittapally# kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:33:17Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
root@kubernetes:/home/smittapally#
`
I pulled the heapster repository and deployed the grafana and influxdb and heapster.
`root@kubernetes:/home/smittapally/heapster# git log -1
commit 7a7c2c2c2c31b2d953da407a38fb4fe5d71ba2a1
Merge: 89c4ab5 61e7497
Author: Solly Ross <directxman12+github@gmail.com>
Date:   Tue Jun 6 11:30:11 2017 -0400

    Merge pull request #1670 from yaacov/source-summary-rss-memory

    Export rss memory in summary source
root@kubernetes:/home/smittapally/heapster# git branch
* master
root@kubernetes:/home/smittapally/heapster#
`

heapster-amd64:v1.3.0
heapster-influxdb-amd64:v1.1.1
heapster-grafana-amd64:v4.0.2

**Comment by DirectXMan12** [comment]
So, is Heapster itself working?  Is it just not grafana that's working?

**Comment by SankarMittapally** [comment]
yes, all three services are up and running but not connected to Kubernetes cluster to get the data.

**Comment by DirectXMan12** [comment]
Wait, how have you confirmed that Heapster isn't connected to Kubernetes, then?  Are you able to access the Heapster API?

**Comment by SankarMittapally** [comment]
I am unable to access any API, it is saying system:anonymous. I used to NodePort for Grafana and came to know that graphs are not there.

**Comment by DirectXMan12** [comment]
ok, so first let's figure out if Heapster is working.  You might just have a Grafana issue.  You should try running `kubectl proxy` in one terminal window, and then `curl localhost:8001/api/v1/namespaces/kube-system/services/proxy/api/v1/model/namespaces` and see if that returns anything.

**Comment by jasonkenneth** [comment]
I'm running into this issue. The only change I am making is toggling the anonymous enabled environment variable:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "false"

When it's true, both the anonymous user and logging in as admin have the datasource set and the dashboards available.

When it's false, anonymous access to grafana is disabled; however, when logging in as admin, there is no datasource configured and (logically) there are no dashboards to see.

**Comment by geekofalltrades** [comment]
@jasonkenneth , I was running into the same issue, and I just solved it.

When you disable anonymous auth, you have to also enable basic auth:

    - name: GF_AUTH_BASIC_ENABLE
      value: "true"

If we look at the [source code of the Grafana setup script](https://github.com/kubernetes/heapster/blob/v1.4.3/grafana/setup_grafana.go#L98), we see that it constructs a URL to communicate with the Grafana API which includes basic auth credentials for the default admin user. So, if anonymous auth isn't enabled, we have to turn on basic auth, instead, otherwise the script can't communicate with the Grafana API to set up the data source and the dashboards.

The other issue that I discovered during this troubleshooting process was that the grafana `run.sh` script [defaults anonymous auth to on](https://github.com/kubernetes/heapster/blob/v1.4.3/grafana/run.sh#L5). This is the opposite of the Grafana default, and results in unexpected behavior. In order to turn off anonymous auth, you must *explicitly* set

    - name: GF_AUTH_ANONYMOUS_ENABLED
      value: "false"

in the grafana Deployment manifest. I think this behavior should be documented, because I spent a long time troubleshooting why my Grafana interface was still visible without login, even after I removed the anonymous auth options from the config. I was expecting removing the configuration values to revert me to the Grafana defaults.

**Comment by gcstr** [comment]
Hi, I'm running the same issue and I can't get any other from Grafana than one pod on `kube-system` namespace.

@DirectXMan12, running `curl localhost:8001/api/v1/namespaces/kube-system/services/proxy/apis/metrics/v1alpha1/namespaces/kube-system/pods`

    {
      "kind": "Status",
      "apiVersion": "v1",
      "metadata": {},
      "status": "Failure",
      "message": "the server could not find the requested resource",
      "reason": "NotFound",
      "details": {},
      "code": 404
    }

**Comment by DirectXMan12** [comment]
you appear to have missed putting an actual service name in your curl -- it should be 
`curl localhost:8001/api/v1/namespaces/kube-system/services/heapster/proxy/apis/metrics/v1alpha1/namespaces/kube-system/pods`
