### ISSUE TITLE
Unable to launch heapster with apiserver

### ISSUE THREAD

**Issue by BenjaminITS** [kubernetes/heapster#1690]
Hey,

I want to launch heapster with apiserver on kubernetes 1.6.1 but I always get the same error :

> I0620 14:15:14.915656       1 heapster.go:72] /heapster --source=kubernetes.summary_api:'' --api-server=true --client-ca-file=/srv/kubernetes/ca.crt --tls-cert-file=/srv/kubernetes/server.cert --tls-private-key-file=/srv/kubernetes/server.key
I0620 14:15:14.915802       1 heapster.go:73] Heapster version v1.3.0
I0620 14:15:14.916299       1 configs.go:61] Using Kubernetes client with master "https://10.3.0.1:443" and version v1
I0620 14:15:14.916376       1 configs.go:62] Using kubelet port 10255
I0620 14:15:15.004367       1 heapster.go:196] Starting with Metric Sink
E0620 14:15:15.011457       1 heapster.go:122] Could not create the API server: missing clientCA file
I0620 14:15:15.107040       1 heapster.go:106] Starting heapster on port 8082

Here it is how I generate my certs :

> openssl genrsa -out ca.key 2048
openssl req -x509 -new -nodes -key ca.key -days 10000 -out ca.crt -subj "/CN=localhost"
openssl genrsa -out server.key 2048
openssl req -new -key server.key -out apiserver.csr -subj "/CN=localhost" -config openssl.conf
openssl x509 -req -in apiserver.csr -CA ca.crt -CAkey cca.key -CAcreateserial -out server.cert -days 3650 -extensions v3_req -extfile openssl.conf

With this openssl.conf :

> [req]
req_extensions = v3_req
distinguished_name = req_distinguished_name
[req_distinguished_name]
[ v3_req ]
basicConstraints = CA:TRUE
subjectAltName = @alt_names
[alt_names]
DNS.1 = heapster.kube-system
DNS.2 = localhost

And after I launch heapster with these yaml files :

> apiVersion: v1
kind: Secret
metadata:
  name: heapster-apiserver-secrets
  namespace: kube-system
  labels:
    k8s-app: heapster
type: Opaque
data:
  ca.crt: LS0t[...]LQo=
  server.cert: LS0t[...]Cg==
  server.key: LS0t[...]tLQo=

> kind: Service
apiVersion: v1
metadata:
  name: heapster
  namespace: kube-system
  labels:
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: "Heapster"
spec:
  ports:
    - port: 80
      targetPort: 8082
  selector:
    k8s-app: heapster

> apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: heapster-v1.3.0
  namespace: kube-system
  labels:
    k8s-app: heapster
    kubernetes.io/cluster-service: "true"
    version: v1.3.0
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: heapster
      version: v1.3.0
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v1.3.0
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        scheduler.alpha.kubernetes.io/tolerations: '[{"key":"CriticalAddonsOnly", "operator":"Exists"}]'
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v1.3.0
          name: heapster
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
              scheme: HTTP
            initialDelaySeconds: 180
            timeoutSeconds: 5
          command:
            - /heapster
            - --source=kubernetes.summary_api:''
            - --api-server=true
            - --client-ca-file=/srv/kubernetes/ca.crt
            - --tls-cert-file=/srv/kubernetes/server.cert
            - --tls-private-key-file=/srv/kubernetes/server.key
          volumeMounts:
          - name: heapster-apiserver-secrets
            mountPath: /srv/kubernetes/
            readOnly: true
          - name: ssl-certs
            mountPath: /etc/ssl/certs
            readOnly: true
        - image: gcr.io/google_containers/addon-resizer:1.6
          name: heapster-nanny
          resources:
            limits:
              cpu: 50m
              memory: 90Mi
            requests:
              cpu: 50m
              memory: 90Mi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: MY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /pod_nanny
            - --cpu=80m
            - --extra-cpu=4m
            - --memory=200Mi
            - --extra-memory=4Mi
            - --threshold=5
            - --deployment=heapster-v1.3.0
            - --container=heapster
            - --poll-period=300000
            - --estimator=exponential
      volumes:
      - name: heapster-apiserver-secrets
        secret:
          secretName: heapster-apiserver-secrets
      - name: ssl-certs
        hostPath:
          path: /etc/ssl/certs

Even if I let heapster generate the certs and key by his own I get this error. 
Do I miss something ?

**Comment by DirectXMan12** [comment]
Sorry, that message is a bit misleading.  It looks like you're missing the *requestheader* client CA file.  The API server code in Heapster isn't new enough to automatically fetch it from Kubernetes, so you'll need to pass `--requestheader-client-ca-file` as well (see https://github.com/kubernetes-incubator/apiserver-builder/blob/master/docs/concepts/auth.md for more info on the different CA files).
