### ISSUE TITLE
Heapster should handle duplicated stats from kubelet gracefully

### ISSUE THREAD

**Issue by fgrzadkowski** [kubernetes/heapster#1697]
Ref https://github.com/kubernetes/kubernetes/issues/47853

**Comment by piosz** [comment]
@loburm could you please take a look? Thanks!

**Comment by DirectXMan12** [comment]
we need to make sure we log this if it happens, among other things.  In the past, we've had too many spots in the collection code which silently ignores errors or missing data.

**Comment by DirectXMan12** [comment]
@piosz: it looks @loburm isn't yet on the list of people that I can assign to, it looks like

**Comment by piosz** [comment]
@DirectXMan12 I asked Filip to add him to heapster-reviewers team.

**Comment by fgrzadkowski** [comment]
@DirectXMan12 @piosz Fixed.

**Comment by piosz** [comment]
@fgrzadkowski thx

**Comment by loburm** [comment]
With #1708 merged, I'm closing this issue.

**Comment by piosz** [comment]
Unfortunately this is not fixed yet. We've seen duplicated containers with non-zero resource usage. Will send a fix soon.

**Comment by piosz** [comment]
#1790 fixed the problem in 1.4. Decreasing the priority - we need to fix this in HEAD as well.
