### ISSUE TITLE
Unable to build grafana for other platforms

### ISSUE THREAD

**Issue by piosz** [kubernetes/heapster#1698]
After #1624 is merged I'm not able to build grafana for other platforms than `amd64`.

See https://github.com/kubernetes/heapster/pull/1624/files#r123724923

**Comment by piosz** [comment]
cc @adambkaplan @luxas

**Comment by andyxning** [comment]
Seems like unexpected change.

**Comment by luxas** [comment]
Should be fixed with changing back to `arm`...

**Comment by andyxning** [comment]
@luxas Could you please make a PR to change this. :)

**Comment by luxas** [comment]
PR made, PTAL
