### ISSUE TITLE
Update Sinks Configuration Documentation

### ISSUE THREAD

**Issue by salilgupta1** [kubernetes/heapster#1705]
Currently, [sink-configuration.md](https://github.com/kubernetes/heapster/blob/master/docs/sink-configuration.md) and [sink-owners.md](https://github.com/kubernetes/heapster/blob/master/docs/sink-owners.md) state that the Kafka sink doesn't not support K8s API events. However, there seems to be code that does allow Kafka to accept events.  @huangyuqi can you confirm this?

**Comment by SleepyBrett** [comment]
I just found this after seeing the documentation mentioning that kafka doesn't support a sink for events. It certainly used to (back in like 1.2-1.3 if my memory serves). Is there a reason this was removed?
