### ISSUE TITLE
V1.4.0: Unable to change index name in elasticsearch sink

### ISSUE THREAD

**Issue by dvdklnr** [kubernetes/heapster#1707]
With 

sink config:

`        - "--sink=elasticsearch:http://elasticsearch.monitoring.svc:9200?index=k8sevents?cluster_name={{ .Values.clusterName }}?sniff=0"`

error:

`W0630 00:47:10.151271       1 driver.go:75] Failed to export data to ElasticSearch sink: elastic: Error 400 (Bad Request): Invalid index name [k8sevents?cluster_name=prod.us-west-6.aws.k8s?sniff=0-2017.06.30], must not contain the following characters [ , ", *, \, <, |, ,, >, /, ?] [type=invalid_index_name_exception]`

**Comment by piosz** [comment]
@AlmogBaku @andyxning @huangyuqi

**Comment by outcoldman** [comment]
@dvdklnr you should separate parameters with `&`, not with multiple `?`, so it should be `--sink=elasticsearch:http://elasticsearch.monitoring.svc:9200?index=k8sevents&cluster_name={{ .Values.clusterName }}&sniff=0`

**Comment by dvdklnr** [comment]
Thank you for pointing it out, it's not clear from the examples.

**Comment by AlmogBaku** [comment]
can we close it?

**Comment by dvdklnr** [comment]
yes, please
