### ISSUE TITLE
V1.4.0 Failed to parse /etc/grafana/grafana.ini, open /etc/grafana/grafana.ini: no such file or directory

### ISSUE THREAD

**Issue by Robbilie** [kubernetes/heapster#1709]
Failed to parse /etc/grafana/grafana.ini, open /etc/grafana/grafana.ini: no such file or directory

there is no such file in there since the config dir is in /usr/share/grafana
theres at least a defaults file…

**Comment by andyxning** [comment]
@Robbilie there is a [PR](https://github.com/kubernetes/heapster/pull/1700) will add a default and empty `grafana.ini` if not exist already. See this [diff](https://github.com/kubernetes/heapster/pull/1700/files#diff-4e2886e52abad1c51e63e647f21e1c9a) for more info.


BTW, you can mount a configuration file into `/etc/grafana/grafana.ini`.

**Comment by Robbilie** [comment]
i know that i can mount a config file into it but i would rather not.
i have no idea why the config file is missing and this was really annoying when i tried to upgrade to 1.4.

any eta when a release with the fix is expected?

**Comment by andyxning** [comment]
@Robbilie The fix can only add an empty `grafana.ini` which may not be what you want. The desired way is to mount a customized `grafana.ini`. :)

**Comment by Robbilie** [comment]
thats not the desired way. the official grafana and previous versions of heapsters grafana had a grafana.ini and i dont see why the 1.4.0 release shouldnt have one

**Comment by andyxning** [comment]
@robbilie Having not know that we have a grafana.ini in previous release. Will check this later.

**Comment by Robbilie** [comment]
lol theres literally no reason to not have one, 1.3 aswell as official grafana releases had one

**Comment by andyxning** [comment]
@Robbilie You mean `gcr.io/google_containers//heapster-grafana-amd64:v4.0.2`

**Comment by Robbilie** [comment]
@andyxning with one less slash yeah, thats the previous one which had the ini, https://hub.docker.com/r/grafana/grafana/ has the ini aswell

**Comment by trunet** [comment]
any workaround? trying to deploy a brand new heapster and having problems

**Comment by Robbilie** [comment]
mount the file into the pod…
although this should imo be fixed ASAP in a 4.2.1 release bc this is just annoying and breaking…

**Comment by DirectXMan12** [comment]
I believe @piosz is working on it, and it's marked as high priority.  We should have a fix soon.

**Comment by doubaokun** [comment]
Change the image to be gcr.io/google_containers/heapster-grafana-amd64:v4.0.2 will fix this issue.

**Comment by Robbilie** [comment]
thats not a fix, i used to use a newer grafana image while waiting for heapster 1.4 because i need certain grafana notification channels

**Comment by piosz** [comment]
Apologies for the problems. @loburm is investigating this.

**Comment by trunet** [comment]
any news?

**Comment by loburm** [comment]
Sorry for the delay, I'm looking at this problem now. I will post update as soon as will find a root cause of issue.

**Comment by loburm** [comment]
This commit on the side of grafana is the root cause of the issue:
https://github.com/grafana/grafana/commit/b191638f416b33451113bc4e8b95085cdf09cf64

Shortly: previously they have been always creating grafana.ini file but in January this part was moved to the postinst script which is executed only when we actually install package on the system (in our case we just extracting files, so script is not executed).

I'll try to find workaround. Maybe we can use official grafana image for this.

**Comment by loburm** [comment]
Unfortunately, solution with docker image officially provided by the grafana is not going to work. This image is built only for amd64 (we support different arch) and image size almost 2 times bigger.

So I have prepared PR that just manually copies configuration files to /etc/grafana/: https://github.com/kubernetes/heapster/pull/1728

**Comment by ffahri** [comment]
check this https://github.com/kubernetes/heapster/issues/1722
v4.0.2 
change to --> image: gcr.io/google_containers/heapster-grafana-amd64:v4.0.2

**Comment by loburm** [comment]
@ffahri this is not a fix of problem. Some users need features that have been released in 4.2.0 or later we just can't stuck with version 4.0.2 forever.

**Comment by loburm** [comment]
PR was merged. Tomorrow I'll push a new image to the gcr.

**Comment by loburm** [comment]
Image is pushed. In #1731 updates deploy file.

**Comment by discostur** [comment]
@loburm just tested the new image and it works without any problems ;)

**Comment by loburm** [comment]
@discostur thanks for checking it.

Considering that last PR was merged, I'm closing this issue.

**Comment by emansom** [comment]
It works again. Thanks guys. 👍 
![screen shot 2017-07-18 at 11 26 58](https://user-images.githubusercontent.com/981494/28310257-297eb72c-6bac-11e7-8185-002245ebd113.png)

**Comment by jpds** [comment]
As a heads-up, this is still broken in the https://github.com/kubernetes/heapster/tree/release-1.4 branch

**Comment by andyxning** [comment]
@DirectXMan12 @piosz @loburm we should cherrypick #1728 to release-1.4.

@jpds As a workaround, give [v1.4.1](https://github.com/kubernetes/heapster/releases/tag/v1.4.1) a try.

**Comment by BruceShenC** [comment]
@andyxning I have tried but it still fail
