### ISSUE TITLE
Grafana cannot connect to datasource over servicename, only IP.

### ISSUE THREAD

**Issue by vdmkenny** [kubernetes/heapster#1716]
```
heapster-grafana version: 4.0.2
kube-dns version: 1.14.4
OS: Centos 7.3
Kubernetes version: 1.5.2
```

I am having an issue where my grafana pod can only connect to the influxdb pod when it is using the service IP.
It would be assumed that kube-dns is not working, but when opening a shell on the grafana pod (with docker exec) it is able to resolve the hostname:
```
/ # ping monitoring-influxdb.kube-system.svc.cluster.local
PING monitoring-influxdb.kube-system.svc.cluster.local (10.250.88.148): 56 data bytes
```
So IP resolving works (for some reason I need the entire FQDN but that's another issue...) 
But when entering this hostname into the datasource configuration I simply get 
"Unknown error: InfluxDB Error: undefined". When entering the IP, it works.

What's going on here? I would prefer not to set the IP in the influxdb service staticly.

**Comment by s-miyoshi-fj** [comment]
I have same problem.

ENV:
  heapster-grafana version: 4.4.1
  kubeadm: 1.7.0
  OS: CentOS 7.2.1511

**Comment by DirectXMan12** [comment]
@piosz have you seen anything like this before?

**Comment by ReSearchITEng** [comment]
even worst, if one tries to define the grafana datasource to the prometheus service (under ...srv.cluster.local) (or even the ClusterIP), it fails.

**Comment by Tenzer** [comment]
This sounds very similar to what is talked about here: https://github.com/kubernetes/kubernetes/issues/45790. I'm seeing the same problem and a workaround is to configure Grafana to contact InfluxDB via '127.0.0.1' instead of the service hostname.

I have not been able to find a way to solve it properly for now.
