### ISSUE TITLE
heapster can not access kubelet 10255 

### ISSUE THREAD

**Issue by liyulai2017** [kubernetes/heapster#1718]
1.heapster+influxDB+grafana  deployed  in k8s cluster ,and on the k8s  master host.
2.the node ip =10.2.22.0  ==flannel0
3. access 'curl http://10.2.22.0:10255/stats/container/' on the host is ok.
---------------------------------------------
E0711 09:01:05.007837       1 kubelet.go:233] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://10.2.22.0:10255/stats/container/": Post http://10.2.22.0:10255/stats/container/: dial tcp 10.2.22.0:10255: connect: network is unreachable

**Comment by DirectXMan12** [comment]
please ensure that your container networking is set up properly, and that in your networking setup, pods have permission to access the nodes.  Further ensure that you haven't disabled access to Kubelet on that port.

**Comment by MaXinjian** [comment]
I have meet the exact same problem.@liyulai2017  Have you solve this problem?

**Comment by M-Ayman** [comment]
make sure the port 10255 is opened on all nodes

**Comment by fanhongli** [comment]
vi /etc/systemd/system/kubelet.service.d/10-kubeadm.conf

change to like this 

Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml --read-only-port=10255 "

then 

systemctl daemon-reload

systemctl restart kubelet
