### ISSUE TITLE
Monitor PVC disk io/space usage

### ISSUE THREAD

**Issue by dnavre** [kubernetes/heapster#1719]
I wasn't able to find anything for this. FS stats that heapster provides are, as I understand it, node related and in no consistent way track the disk parameters of a PVC.

This, in my opinion, is a crucial component of any production kubernetes setup.

I investigated monitoring tools other than heapster but wasn't able to find anything with this functionality. The only normal solution that I see as of this moment is creating manually configured agent-containers in each of the pods which will have labeling and configuration for all the PVCs. This seems to be an overkill to me. Agents that monitor the disk usage and are installed as a DaemonSet I guess won't be able to provide this functionality cause they will confuse the PVCs, as the same PVC may be mounted as /dev/xvda and the next time as /dev/xvdb.

So, is there a ready solution that I'm missing or is this indeed something that still needs to be implemented?

P.S.
I'm not sure if heapster is the right place to open this issue, maybe it should have been in the main kubernetes project?

**Comment by DirectXMan12** [comment]
Yeah, open in the main Kubernetes repo.  Heapster merely scrapes the metrics provided by Kubelet

**Comment by dnavre** [comment]
I just checked the Kublet API and it is returning that data. Here's an example:
```
{
    "podRef": {
     "name": "mongo-shard-one-0",
     "namespace": "default",
     "uid": "248d8673-6553-11e7-845b-0203d18125f4"
    },
    "startTime": "2017-07-10T10:10:51Z",
    "containers": [
     {
      "name": "mongo",
      "startTime": "2017-07-10T10:12:22Z",
      "cpu": {
       "time": "2017-07-14T19:39:12Z",
       "usageNanoCores": 24500208,
       "usageCoreNanoSeconds": 17524856640381
      },
      "memory": {
       "time": "2017-07-14T19:39:12Z",
       "availableBytes": 669958144,
       "usageBytes": 2916573184,
       "workingSetBytes": 2475769856,
       "rssBytes": 2034851840,
       "pageFaults": 6895170,
       "majorPageFaults": 1683
      },
      "rootfs": {
       "time": "2017-07-14T19:39:12Z",
       "availableBytes": 13413863424,
       "capacityBytes": 19988041728,
       "usedBytes": 330313728,
       "inodesFree": 4950160,
       "inodes": 5242880,
       "inodesUsed": 45
      },
      "logs": {
       "time": "2017-07-14T19:39:12Z",
       "availableBytes": 13413863424,
       "capacityBytes": 19988041728,
       "usedBytes": 24576,
       "inodesFree": 4950160,
       "inodes": 5242880,
       "inodesUsed": 292720
      },
      "userDefinedMetrics": null
     },
     {
      "name": "filebeat",
      "startTime": "2017-07-10T10:12:28Z",
      "cpu": {
       "time": "2017-07-14T19:39:12Z",
       "usageNanoCores": 155419,
       "usageCoreNanoSeconds": 104380152043
      },
      "memory": {
       "time": "2017-07-14T19:39:12Z",
       "usageBytes": 11821056,
       "workingSetBytes": 11239424,
       "rssBytes": 10301440,
       "pageFaults": 29772,
       "majorPageFaults": 537
      },
      "rootfs": {
       "time": "2017-07-14T19:39:12Z",
       "availableBytes": 13413863424,
       "capacityBytes": 19988041728,
       "usedBytes": 163926016,
       "inodesFree": 4950160,
       "inodes": 5242880,
       "inodesUsed": 30
      },
      "logs": {
       "time": "2017-07-14T19:39:12Z",
       "availableBytes": 13413863424,
       "capacityBytes": 19988041728,
       "usedBytes": 20480,
       "inodesFree": 4950160,
       "inodes": 5242880,
       "inodesUsed": 292720
      },
      "userDefinedMetrics": null
     }
    ],
    "network": {
     "time": "2017-07-14T19:39:21Z",
     "rxBytes": 32309235058,
     "rxErrors": 0,
     "txBytes": 106828584460,
     "txErrors": 0
    },
    "volume": [
     {
      "time": "2017-07-14T19:37:43Z",
      "availableBytes": 13413883904,
      "capacityBytes": 19988041728,
      "usedBytes": 21782528,
      "inodesFree": 4950160,
      "inodes": 5242880,
      "inodesUsed": 2,
      "name": "logs"
     },
     {
      "time": "2017-07-10T10:10:43Z",
      "availableBytes": 4187172864,
      "capacityBytes": 4187185152,
      "usedBytes": 12288,
      "inodesFree": 1022253,
      "inodes": 1022262,
      "inodesUsed": 9,
      "name": "default-token-w300s"
     },
     {
      "time": "2017-07-14T19:37:43Z",
      "availableBytes": 140919939072,
      "capacityBytes": 158399967232,
      "usedBytes": 10569945088,
      "inodesFree": 9830308,
      "inodes": 9830400,
      "inodesUsed": 92,
      "name": "data"
     },
     {
      "time": "2017-07-10T10:10:43Z",
      "availableBytes": 4187181056,
      "capacityBytes": 4187185152,
      "usedBytes": 4096,
      "inodesFree": 1022257,
      "inodes": 1022262,
      "inodesUsed": 5,
      "name": "mongo-keyfile"
     }
    ]
   }
```

I can help you out with the implementation if needed. If you tell me approximately what should be done I'll try to do it :)

**Comment by dnavre** [comment]
I did have a look at the code and indeed it looks that heapster is actually collecting the volume metrics and they should be present in my influxdb with `resoruce_id = Volume:data` label. but I don't have a metric like that. Instead, I have some with resource_id:/dev/xvda1 or something similar which isn't informative at all as the device name in /dev/* is more or less random.

I guess a little bit more digging in the code is needed.

**Comment by dnavre** [comment]
I did some more investigation and turns out that to enable the summary API one needs to change the protocol in the source from `kubernetes:` to `kubernetes.summary_api:`. This is not documented anywhere and nowhere is it written what's the difference is. Should I document it as comments in the example configuration files?

**Comment by DirectXMan12** [comment]
We should really have documentation for that somewhere (if we don't, I'd gladly accept a PR).  The summary source uses the summary API, while the non summary source uses a series of calls to the old stats API.  The summary source is the newer and more supported of the two.
