### ISSUE TITLE
Metrics pub-sub

### ISSUE THREAD

**Issue by jimmidyson** [kubernetes/heapster#172]
While thinking about other services that would require metrics, e.g. alerting, autoscaling, etc, switching to a pub-sub model would allow for services to build around the metrics data. For example, if heapster could publish metrics to e.g. Apache Spark / Kafka then other services could subscribe to topics & provide functionality.

We could split up topics into a hierarchy something like namespace / pod / container, aggregate at each level & enforce security at those layers too.

**Comment by vishh** [comment]
Good idea. This seems better than having heapster expose the data directly.

**Comment by liuhewei** [comment]
@jimmidyson We are working on a heapster kafka-sink to pub metrics to kafka, but we don't separate metrics from different ns/pod/containers to different topics as you said. Our idea now is "one topic for one k8s cluster". Our purpose is similar to your thought: provide metrics to different backend services such as alerting, autoscaling, not only for storage and dashboard.

**Comment by jimmidyson** [comment]
@liuhewei Sounds great!

**Comment by liuhewei** [comment]
@vishh I have a question here about the "--sink" flag: 
The kafka-client usually need be configured multiple tcp endpoints for a broker cluster, typically:
`var kafkaAddrs = []string{"192.168.1.2:9092", "192.168.1.2:9093"}`
It's different with other existing sinks such as influxdb/hawkular which usually has only one http_url as  the endpoint.

And I checked the [sink extension's interface](https://github.com/kubernetes/heapster/blob/master\extpoints/interfaces.go#L32), then found it supports only one and http-only endpoint (`*url.URL`):
`type SinkFactory func(*url.URL, HeapsterConf) ([]sinksApi.ExternalSink, error)`

It's a problem now, and what's your suggestion? Thanks.

**Comment by vishh** [comment]
The URL part is optional. For the kafka case, you can take in a list of IPs
as a query param.
Another option is to use a DNS name and resolve the name to all its IPs.

**Comment by huangyuqi** [comment]
@vishh , I am developing the kafka sink. Shall I commit a wip PR to accept some guys' comments? Thanks : )

**Comment by vishh** [comment]
Awesome :)
Do post a WIP. We can provide some feedback, if applicable, before you
spend a lot of much time on the PR.

**Comment by mwielgus** [comment]
Kafka sink is avaiable for metrics.

**Comment by piosz** [comment]
Closing as Kafka is already supported.
