### ISSUE TITLE
Support ES ttl

### ISSUE THREAD

**Issue by andyxning** [kubernetes/heapster#1733]
What about we support ES TTL to auto delete events after specified time?

Storing events 3 months ago seems useless.

/cc @AlmogBaku @DirectXMan12

**Comment by AlmogBaku** [comment]
can you please send a ref to the ES documentation about that?

**Comment by andyxning** [comment]
Sorry for the inconvience. According to tthe release doc about ES 5.0, https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_50_mapping_changes.html#_literal__timestamp_literal_and_literal__ttl_literal.

_ttl has been removed in favor of time-based index or cron query-by-delete. So close this as we have upgraded to ES 5.
