### ISSUE TITLE
error: error converting YAML to JSON: yaml: line 1095: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by justlooks** [kubernetes/heapster#1738]
when i try install release-1.3 ,it say 
[root@k8s-master monitor]# kubectl create -f https://github.com/kubernetes/heapster/tree/release-1.3/deploy/kube-config/influxdb
error: error converting YAML to JSON: yaml: line 1095: mapping values are not allowed in this context

**Comment by DirectXMan12** [comment]
can you figure out which file in that directory the issue is coming from?  The error alone doens't help much.

**Comment by DirectXMan12** [comment]
also, please state the version of Kubernetes that you are using

**Comment by justlooks** [comment]
i use k8s v1.7 ,strange thing is i download all yaml ,and use "kubectl apply -f " ,all work fine
