### ISSUE TITLE
Unable to Send Alerts in Grafana

### ISSUE THREAD

**Issue by mashayev** [kubernetes/heapster#1741]
Hey, 

I was trying to send alert from Grafana v4.4.* and it's not working, I've the same issue described in [this question](https://community.grafana.com/t/unable-to-send-alerts-in-grafana-4-1-1/1939)

As part of my troubleshooting I was referred to http://docs.grafana.org/alerting/rules/#troubleshooting, I need to update the `Grafana’s ini config file` How do I do that in heapster?

Does anyone faced this issue before? Are you able to send alerts from Grafana?

**Comment by ffahri** [comment]
you can build your own image with your own config
https://github.com/kubernetes/heapster/tree/master/grafana
be careful for dont send public docker hub

**Comment by DirectXMan12** [comment]
That is the correct answer.  You should build a custom image with your own `grafana.ini`.  You can even use the existing image as a base image.
