### ISSUE TITLE
'/api/v1/model/nodes/' returns IP addresses instead of node names

### ISSUE THREAD

**Issue by matt-deboer** [kubernetes/heapster#1742]
Using the api to list nodes returns IP addresses; however, attempting to use those IP addresses to request metrics results in empty arrays.

Attempting to query node-level metrics using one of the returned values results in an empty result: `/api/v1/model/nodes/{one of the IPs returned}/metrics` => `[]`

However, using the _actual_ node names does return node-level metrics:
`/api/v1/model/nodes/{actual node name}/metrics` => `[
  "memory/major_page_faults_rate",
  "network/rx_errors",
  "network/tx_errors",
  "memory/page_faults",
  "memory/cache",
  "memory/request",
...
]`

The result is that I cannot use `/api/v1/model/nodes` to list nodes and then subsequently request metrics for the resulting nodes; I instead have to obtain the list of nodes via some other mechanism.

We are using the `aws` cloud provider, if that makes a difference here.

**Comment by matt-deboer** [comment]
Just found that as a workaround, one can extract the correct node list by hitting `/api/v1/model/debug/allkeys` and doing some string manipulation/deduping...

**Comment by DirectXMan12** [comment]
The model API is deprecated.  Please use the resource metrics API (`/apis/metrics/v1alpha1/nodes`) instead.
