### ISSUE TITLE
the problem about multiple namespace

### ISSUE THREAD

**Issue by yin32167** [kubernetes/heapster#1743]
I have some namespaces, when i login in grafana, i just can see "default" and "kube-system" namespaces and cannot find others

**Comment by DirectXMan12** [comment]
Without knowing details about your cluster, there's nothing we can do.  Please indicate your versions of Heapster and Kubernetes, and check the Heapster logs.

**Comment by i7clock** [comment]
@yin32167 just type in the name of your namespace and it will show your pods.. at least thats what helped me

**Comment by DanyalITMO** [comment]
Hi everybody,
I got the same error as @yin32167. I also have some namespaces like default, kube-public, kube-system, nginx-ingress, test1, test2 and etc. I installed Heapster stack from
deploy/kube-config/influxdb/ and
deploy/kube-config/rbac/heapster-rbac.yaml
I install latest version of container:
heapster-grafana-amd64:v4.4.1
heapster-amd64:v1.4.1
heapster-influxdb-amd64:v1.1.1
In Grafana in dashboard "Pods" I can select only "kube-system" or "default" namespaces and in "default" there are no pods at all (although there are some). In "kube-system" those pods are seen, which are deployed only on two out of ten nodes. In dashboard "Cluster" I can see all my nodes.

When I open URL heapster I see only two namespaces - "kube-system" and "nginx-ingress".
```
curl http://10.110.178.213/api/v1/model/namespaces/
[
  "nginx-ingress",
  "kube-system"
```
Could you please help me to install Heapster correctly?
I have the following configuration on all my nodes:
**#lsb_release -a**
`Description:	Ubuntu 16.04.2 LTS`
**#uname -r**
`4.4.0-79-generic`

**#kubectl version**
```
Client Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.4", GitCommit:"793658f2d7ca7f064d2bdf606519f9fe1229c381", GitTreeState:"clean", BuildDate:"2017-08-17T08:48:23Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"7", GitVersion:"v1.7.3", GitCommit:"2c2fe6e8278a5db2d15a013987b53968c743f2a1", GitTreeState:"clean", BuildDate:"2017-08-03T06:43:48Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
```
**docker version**
```
docker version
Client:
 Version:      1.12.6
 OS/Arch:      linux/amd64
```

**Comment by DanyalITMO** [comment]
I solved my problem with heapster. If you want to have actual information in Grafana from database you need to configure Template:
1. go to YOUR_DASHBOARD (for example Pods) - Templating
2. press "Edit" in tab Variables
3. set fields "Data source =  influxdb-datasource" and "Refresh = On Dashboard Load"
After that you will have actual namespaces and pods list.

@DanyalITMO
> But when I open URL heapster, I see only two namespaces - "kube-system" and "nginx-ingress".

Just restart kubelet service on all the nodes. For my Ubuntu 16.04:
`systemctl restart kubelet`
Now I have all my namespaces and pods in my InfluxDB.

**Comment by yin32167** [comment]
@DanyalITMO   thanks very much, i try it and it works. and i find that you needn't restart your kubelet, just press the 'Save & Test' button in 'Data Sources', it will reload the namespaces
