### ISSUE TITLE
InfluxDB sink not working with Heapster 1.4.0

### ISSUE THREAD

**Issue by kerneljack** [kubernetes/heapster#1761]
Hi there, I've created a brand new Kubernetes 1.7.2 cluster on GKE and it installs Heapster 1.4.0 into the kube-system namespace by default.

I'm trying to make this heapster use InfluxDB as a sink. I have installed InfluxDB using this yaml file:
https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/influxdb/influxdb.yaml

I'm then trying to edit the default Heapster deployment to use InfluxDB as a sink by adding this to the Spec:
```
- --sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086
```

I can see in the logs that once I edit the Deployment for Heapster, it creates a brand new pod which uses an InfluxDB sink:
```
I0810 17:04:18.179192       1 influxdb.go:278] created influxdb sink with options: host:monitoring-influxdb.kube-system.svc.cluster.local:8086 user:root db:k8s
I0810 17:04:18.179438       1 heapster.go:196] Starting with InfluxDB Sink
I0810 17:04:18.179592       1 heapster.go:196] Starting with Metric Sink
I0810 17:04:18.278195       1 heapster.go:106] Starting heapster on port 8082
```

On the InfluxDB pod, I can see the following in the logs:
```
[httpd] x.x.x.x - root [10/Aug/2017:17:04:18 +0000] "GET /ping HTTP/1.1" 204 0 "-" "heapster/v1.4.0" f22c095d-7ded-11e7-8003-000000000000 64
```

And then after a few seconds, the new Heapster pod that was created gets destroyed automatically and rebuilt *without* the `--sink=influxdb` changes that I added. I suspect that it is the `pod-nanny` which is also running that's doing this.

In any case, I'm not sure that Heapster is able to create the InfluxDB database properly, perhaps because that `/ping` is not working properly? Has anyone encountered this with a new 1.7.2 cluster yet? 

**UPDATE** It's actually marked as a cluster-service, that's why my changes are getting overwritten. So what is the right method to use to add an InfluxDB sink to Heapster?

**Comment by DirectXMan12** [comment]
I suspect you'd have to change the cluster addon configuration.

**Comment by kerneljack** [comment]
@DirectXMan12 thanks, but what is the right method to do that? I was thinking of using ConfigMaps but the Heapster docs don't mention if that's possible or supported. I tried editing the deployment where the addon is defined as I mentioned, but that gets reverted by the cluster pretty quickly.

**Comment by DirectXMan12** [comment]
Apologies, I'm not super familiar with the cluster addon manager (it's now how I usually run Heapster).

@piosz can you assist here?
