### ISSUE TITLE
InfluxDB memory leakage

### ISSUE THREAD

**Issue by alok87** [kubernetes/heapster#1764]
**What?**
InfluxDB memory in few days increases from 2GB to 13-14GB. There is some leakage.
We had setup grafana-influxdb-heapster following this document - https://github.com/kubernetes/heapster/tree/master/deploy/kube-config/influxdb
Our cluster spec:
```
node: m4.xlarge, 4cores 16GB
kubernetes version: 1.6.4
influx version: `image: gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1`
```
We are running influx without any limits presently.
- How can we fix this?
- What is the ideal limit i should set for influx-grafana and heapster pods.

**Comment by DirectXMan12** [comment]
This is not really a Heapster question.  Please look at the InfluxDB docs and/or file a bug with Influx

**Comment by alok87** [comment]
@DirectXMan12 i agree but this is the version mentioned in the example heapster doc.

**Comment by swade1987** [comment]
@alok87 we are seeing the same issue running version 1.1.1 on Kubernetes 1.7.4.

Over the past two days, it spiked at 21.41GB memory usage and is now running at 14.30GB.
