### ISSUE TITLE
Heapster 1.4.0 and InfluxDB configuration

### ISSUE THREAD

**Issue by kerneljack** [kubernetes/heapster#1765]
Hi, I have created a brand new Kubernetes 1.7.2 cluster on GKE and it installs Heapster 1.4.0 by default in the kube-system namespace. I've read in various places that Heapster uses InfluxDB by default? How does it do that and where does it look for it? 

I've installed InfluxDB in my cluster but Heapster is not using it from what I can see in the logs and in the InfluxDB database itself. Since it's installed as a cluster addon, I'm unable to edit it's deployment and add a `--sink` configuration. Is there a different method to add an InfluxDB sink to Heapster 1.4.0 then? Maybe a ConfigMap?

**Comment by DirectXMan12** [comment]
Heapster is able to talk to InfluxDB as a sink, if configured.  What does your Heapster config look like?

**Comment by DirectXMan12** [comment]
closing b/c no response
/close
