### ISSUE TITLE
Dynamically configure backends

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#177]
Heapster should have a REST endpoint that supports dynamically adding or deleting monitoring backends. This will let heapster be deployed before the monitoring backends become available.

**Comment by rjnagal** [comment]
Does heapster handle auth today? State modifying APIs would require some kind of Auth setup option - maybe just like the basic one we have in cAdvisor.

**Comment by vishh** [comment]
Good point. No auth exists today. We can leverage cadvisor auth. In
kubernetes, heapster will be accessible via the apiserver and we can rely
on the api-server auth policy for heapster.

**Comment by mwielgus** [comment]
There should be no volatile configuration changes. Cycling heapster with new configuration is much easier today as the internal state is relatively small.
