### ISSUE TITLE
Consider migrating travis test coverage to prow

### ISSUE THREAD

**Issue by fejta** [kubernetes/heapster#1771]
ref https://github.com/kubernetes/test-infra/issues/4019

If you are having issues with Travis (most likely: flakes, auto-testing by non-org members), consider running these tests on prow instead. Prow is the official/expected/supported CI framework sig-testing would like people to use.

https://github.com/kubernetes/test-infra/tree/master/prow

**Comment by DirectXMan12** [comment]
@piosz @loburm @x13n I can try and take a look at this next week, unless one of you wants to handle it.

**Comment by fejta** [comment]
We don't use travis
/assign @krzyzacy

**Comment by krzyzacy** [comment]
/reopen
this is heapster :-(

**Comment by krzyzacy** [comment]
@DirectXMan12 assume the only requirement for `make unit` is go?

**Comment by DirectXMan12** [comment]
yeah, that should be the only requirement
