### ISSUE TITLE
Move heapster jobs into their own project

### ISSUE THREAD

**Issue by fejta** [kubernetes/heapster#1773]
This is a notice that the heapster jobs may begin failing at any time as we shut down jenkins - https://github.com/kubernetes/test-infra/issues/190

**Comment by DirectXMan12** [comment]
@piosz @loburm @x13n we need to migrate testing it looks like.  Can one of you take a look at this?

**Comment by fejta** [comment]
These jobs will start failing in the extremely near future

**Comment by fejta** [comment]
Please migrate them out of jenkins and into their own GCP project (if this hasn't happened already)

**Comment by x13n** [comment]
I need more context here. What jobs, where is this configured?

**Comment by BenTheElder** [comment]
> I need more context here. What jobs, where is this configured?

- All the heapster jobs running in test-infra via jenkins
- https://github.com/kubernetes/test-infra, the triggers are in prow/config.yaml and the rest of the config is in jobs/config.json and jenkins/job-configs. 
  - Any jobs in jenkins/job-configs need to be moved to their own jenkins project or ideally migrated off of jenkins to prow. We are going to shut down the kubernetes jenkins and heapster/ cadvisor tests have been running on these clusters.

/cc @dashpole we discussed the cadvisor jobs and may look at heaspter as well *if we have time*.

**Comment by x13n** [comment]
With https://github.com/kubernetes/test-infra/pull/6359 merged, I guess this is done? Please reopen if not.
