### ISSUE TITLE
Plugin Problems, Restart, plugins not showing up.

### ISSUE THREAD

**Issue by Nemesisesq** [kubernetes/heapster#1779]
I'm having trouble getting the world ping plugin to show up. I am supposed to restart the server but when I try to shell into the pod and restart the server it says service is not installed. Also even though I did managed to get the plugin installed It is not showing up in the dashboard. Please help.

**Comment by DirectXMan12** [comment]
What are you referring to?  Grafana?  Influx?  Please be specific and provide more information about your setup.

**Comment by Nemesisesq** [comment]
I am trying to restart grafana but service is not installed and I have a hard time finding how to restart the grafana-server on this installation

**Comment by DirectXMan12** [comment]
Honestly, if you need to customize Grafana, I'd recommend building your own Docker image with the customizations.  Note that since grafana is running in a container, you probably want to build the plugins into the image and restart the image, not try to restart the server within the image.
