### ISSUE TITLE
Setup scripted dashboards in Grafana for kube pods

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#178]
[Scripted dashboards](http://docs.grafana.org/reference/scripting/) might help auto-generate dashboards for pods and services based on user input like pod name, pod id, labels, container name, etc. This feature might help users who are not familiar with grafana or our Influxdb storage schema.

**Comment by thucatebay** [comment]
This should be covered in https://github.com/kubernetes/heapster/pull/599, right?

**Comment by piosz** [comment]
There is already a support for template dashboards.
