### ISSUE TITLE
Deployment broken with grafana and influxdb ImagePullBackOff

### ISSUE THREAD

**Issue by jpds** [kubernetes/heapster#1783]
Hello,

Brand new kubeadm cluster, run:

```
$ git clone https://github.com/kubernetes/heapster.git
$ cd heapster/deploy/kube-config/
$ kubectl apply -f rbac/
$ kubectl apply -f influxdb/
$ kubectl get pods --all-namespaces
...
kube-system   monitoring-grafana-3630659854-1181s     0/1       ImagePullBackOff   0          2h
kube-system   monitoring-influxdb-1957622127-c7l7n    0/1       ImagePullBackOff   0          2h
```

Most likely related to a1fee3cbdc810e251ada9db3f464a6a951980a3b

I've seen this happen a few times in the past now so it would be great if image publishing was fixed (#1469, #1669)

**Comment by analbeard** [comment]
I also saw the same issues a few hours ago on a newly-provisioned cluster with the latest checkout of head.

**Comment by miramar-labs** [comment]
the images are not in the google repo

**Comment by igormilovanovic** [comment]
same here

**Comment by analbeard** [comment]
@miramar-labs 

> so who is updating the versions in the yaml files without checking that the images are actually up in the google repo?

I couldn't agree more - such a basic and obvious thing to do.

**Comment by analbeard** [comment]
paging @piosz

**Comment by miramar-labs** [comment]
same thing with : https://raw.githubusercontent.com/kubernetes/heapster/master/deploy/kube-config/influxdb/grafana.yaml

**Comment by miramar-labs** [comment]
the two URLs are still broken... any idea when this will be fixed?

**Comment by patricklucas** [comment]
To summarize, the [latest available influxdb image](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/heapster-influxdb-amd64) is v1.1.1 ([v1.3.3 referenced in influxdb.yaml](https://github.com/kubernetes/heapster/blob/d2a1cf189921a68edd025d034ebdb348d7587509/deploy/kube-config/influxdb/influxdb.yaml#L16)) and the [latest available grafana image](https://console.cloud.google.com/gcr/images/google-containers/GLOBAL/heapster-grafana-amd64) is v4.4.1 ([v4.4.3 referenced in grafana.yaml](https://github.com/kubernetes/heapster/blob/d2a1cf189921a68edd025d034ebdb348d7587509/deploy/kube-config/influxdb/grafana.yaml#L16)).

Both versions were bumped by @luxas on 2017-06-26 in 480a1ca21fe65882dd41f28cd9296a825fbbb602. @luxas could you explain and/or rollback this change?

**Comment by merqurio** [comment]
We hit this issue too. Modifying the versions to the ones pointed out by @patricklucas solved the problem.

**Comment by luxas** [comment]
We're just waiting for a Googler to push the image
cc @caesarxuchao @vishh @piosz @nicksardo or someone else, could you please push the images?

**Comment by miramar-labs** [comment]
those Googler's must be super busy ;)

**Comment by miry** [comment]
Maybe better to change documentation to use stable versions:

```shell
$ git clone https://github.com/kubernetes/heapster.git
$ cd heapster/deploy/kube-config/
$ git checkout release-1.4
....
```

**Comment by liangrog** [comment]
Even release-1.4 can't work.
Issue with grafana:

`kube-system   monitoring-grafana-762361155-s36lx                                          0/1       CrashLoopBackOff   3          1m`

Here is the log:
`Starting a utility program that will configure Grafana
Starting Grafana in foreground mode
t=2017-08-28T04:37:09+0000 lvl=crit msg="Failed to parse /etc/grafana/grafana.ini, open /etc/grafana/grafana.ini: no such file or directory%!(EXTRA []interface {}=[])"`

**Comment by analbeard** [comment]
Yup, 1.4 was broken so using head is necessary, but broken.

**Comment by miramar-labs** [comment]
no real sense of urgency ...

**Comment by AlexB138** [comment]
Just to clarify, while waiting for Googlers to push those images, what is the current working config? 1.4.1 doesn't work, and head doesn't work.

**Comment by jpds** [comment]
@AlexB138 1.4 works fine with the fix in the comment here: https://github.com/kubernetes/heapster/issues/1709#issuecomment-315979971

**Comment by miguellgt** [comment]
I used these images and it works.

gcr.io/google-containers/heapster-influxdb-amd64:v1.1.1
gcr.io/google-containers/heapster-grafana-amd64:v4.4.1


![screen shot 2017-08-31 at 1 48 13 pm](https://user-images.githubusercontent.com/4840205/29940045-913e68de-8e53-11e7-839a-d7e4446ec272.png)

**Comment by hbokh** [comment]
Even with the above mentioned workaround, the dashboard is nowhere looking as it used to be.
At this moment I can't get it to look like this anymore - https://kubernetes.io/docs/tasks/access-application-cluster/web-ui-dashboard/ There's only a list of pods...
Is this missing behavior related to these workaround?

Besides I seems like there is a SPOF when it comes to releasing and image-pushing in this project.

**Comment by analbeard** [comment]
@hbokh I've also been seeing this issue since my initial comment - I tried the workaround before it was suggested but none of the Heapster-provided metrics were available. Ended up deciding to wait for the updated images to be pushed to GCR, however as you note this does seem to be a massive SPOF - its taking a very long time to get two images built/pushed.

**Comment by hbokh** [comment]
@piosz Would you be so kind and (make somebody) push the right image-versions before you resume working on https://github.com/kubernetes-incubator/metrics-server? 😇
Much appreciated, dziękuję!

**Comment by miramar-labs** [comment]
even if you revert back to the latest images up in the repo, the graphs don't show up anymore... this is because the web app is doing some health check with heapster right at the start and its a one-shot thing .. if it fails you never see the graphs for the lifetime of that pod. The healthcheck used to work but is now failing due to some change in the heapster api whereby it now returns failure until enough data has been scraped .. which takes a couple of minutes. So the trick appears to be - kill the dashboard pod a couple of minutes after your cluster has started up .. this will cause it to reload and this time the initial healthcheck will pass (as you've got data) .. and you will see the graphs again.

**Comment by thenux** [comment]
So guys...just to summarize, I have a cluster of 3 nodes in Google Cloud Platform, so I deployed my guestbook and now I want to use Heapster to monitor my metrics.
I followed the guide with InfluxDB and Grafana in https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md

But when I do `kubectl create -f deploy/kube-config/influxdb/` I just get ImagePullBackOff from the grafana and influxdb pods...what should I do?

**Comment by piosz** [comment]
I've just released the following images:
`gcr.io/google_containers/heapster-grafana-<platform>:v4.4.3`
`gcr.io/google_containers/heapster-influxdb-<platform>:v1.3.3`

Please verify them.

**Comment by thenux** [comment]
Yep! It seems fine now with the last edit for the new images :)

**Comment by heckj** [comment]
@luxas @piosz is it now functional for you? I just tried this evening, and only now found this bug. I've been debugging (and could use help debugging) from https://github.com/kubernetes/heapster/issues/1804. I'm not sure the images that were pushed are "good"...

Would love to hear I'm off base and missing something obvious.

**Comment by luxas** [comment]
If you have a problem, report a bug

**Comment by heckj** [comment]
Thanks @luxas - I did, before I found this thread: #1804
