### ISSUE TITLE
Influxdb latest images missing in registry

### ISSUE THREAD

**Issue by alok87** [kubernetes/heapster#1797]
**What?** 
Changes to update influxdb yamls been merged to master in this PR - https://github.com/kubernetes/heapster/pull/1777 but the the images have not been pushed to heapster.

Can some googler push it to registry ?

**Comment by jpds** [comment]
See #1783.

**Comment by piosz** [comment]
I've just released the following images:
`gcr.io/google_containers/heapster-grafana-<platform>:v4.4.3`
`gcr.io/google_containers/heapster-influxdb-<platform>:v1.3.3`

Please verify them.
