### ISSUE TITLE
How to configure mutual authentication ssl in 1.3

### ISSUE THREAD

**Issue by shsjshentao** [kubernetes/heapster#1800]
I have tried anyway and any configs.
It is no effects about auth client certificates.

        - --api-server
        - --tls-cert=/etc/ssl/certs/server.crt
        - --tls-key=/etc/ssl/certs/server.key
        - --tls-ca-file=/etc/ssl/certs/ca.crt
        - --tls-cert-file=/etc/ssl/certs/server.crt
        - --tls-private-key-file=/etc/ssl/certs/server.key
        - --requestheader-client-ca-file=/etc/ssl/certs/ca.crt
        - --tls-client-ca=/etc/ssl/certs/ca.crt

**Comment by DirectXMan12** [comment]
Can you clarify what, exactly, you're trying to accomplish here?
