### ISSUE TITLE
There's no change log?

### ISSUE THREAD

**Issue by gswallow** [kubernetes/heapster#1802]
Am I dense, and missed the change log?  I had issues with heapster 1.3.0, decided to upgrade to 1.4.2 and the elasticsearch issue seems to have gone away.  I'd like to know why.

**Comment by jeroenjacobs1205** [comment]
You might take a look here: https://github.com/kubernetes/heapster/releases

At the 1.4.0 notes, you can see they fixed some ElasticSearch stuff.

**Comment by gswallow** [comment]
Thanks!
