### ISSUE TITLE
Influxdb sink - missing metrics

### ISSUE THREAD

**Issue by eran-totango** [kubernetes/heapster#1812]
Hi,

i have an heapster V1.4.2 deployment in my standalone kubernetes V1.5.2 cluster that sends metrics to influxdb.
I'm using this command at startup:
```
/heapster 
--source=kubernetes:http://MY_KUBE_CLUSTER:8080 
--sink=influxdb:http://MY_INFLUX_HOST:8086?db=kubernetes&cluster_name=test&withfields=true&retention=30d
```

The metrics are successfully sent to influxdb, however i still have some issues.

**What issues i see:**
1. I only see the "hostname" tag in the filesystem measurement. I don't see it in any other measurement (CPU, memory, network or uptime)
2.  I think i have missing metrics according to https://github.com/kubernetes/heapster/blob/master/docs/storage-schema.md. For example, these are the only fields i see in the filesystem measurement : 
![image](https://user-images.githubusercontent.com/17027773/30521269-a70c12cc-9bc5-11e7-9915-ad9da5ac0d0c.png)
It happens in other measurements too.
Could it be related to the fact that i'm using influxdb fields?

Thanks for your help.

**Comment by kinsu** [comment]
for what i can say this appears that it is not related with influx sink only.
at least filesystem/available is missing from Kafka sink as well as ElasticSearch sink

**Comment by kinsu** [comment]
are there any news on this? 
As mentioned above this appear to happen in ES sink too. Shouldn't the title change too ?
