### ISSUE TITLE
heapster 1.3.0 crashing too much without clear reason

### ISSUE THREAD

**Issue by JuneZhao** [kubernetes/heapster#1813]
root@k8s-agent-ECC3CC6B-0:/var/lib/docker/containers# kubectl --version
Kubernetes v1.6.6

zjune@k8s-agent-ECC3CC6B-0:~$ docker ps | grep heapster
21b2f632edd1        gcrio.azureedge.net/google_containers/addon-resizer@sha256:cf5e34dc058ced9b3f8235139c4f956afb61480ef76dc403c2b00b8d161cfa74                "/pod_nanny --cpu=80m"   36 seconds ago      Up 34 seconds                              k8s_heapster-nanny_heapster-2708163903-bpwlj_kube-system_5b973d51-9c34-11e7-9335-000d3a804764_0
6449dde66a7a        gcrio.azureedge.net/google_containers/heapster@sha256:65ae164393dafb43adec833f2ab2b20db1dc9d21600b2dd5ad4177a26fbd621b                     "/heapster --source=k"   36 seconds ago      Up 35 seconds                              k8s_heapster_heapster-2708163903-bpwlj_kube-system_5b973d51-9c34-11e7-9335-000d3a804764_0
6faa81e9f282        gcrio.azureedge.net/google_containers/pause-amd64:3.0                                                                                      "/pause"                 37 seconds ago      Up 36 seconds                              k8s_POD_heapster-2708163903-bpwlj_kube-system_5b973d51-9c34-11e7-9335-000d3a804764_0
[output.txt](https://github.com/kubernetes/heapster/files/1309812/output.txt)
I've put the detailed journalctl -u kubelet log on the attachement

Any idea?

**Comment by DirectXMan12** [comment]
I'd need to see the heapster logs (`kubectl logs $HEAPSTER_POD_NAME`) to figure much out.

**Comment by JuneZhao** [comment]
@DirectXMan12  let me first attach the pods infor:
zjune@k8s-master-ECC3CC6B-0:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                                READY     STATUS        RESTARTS   AGE
default       discuz-1878213324-8jr94                             1/1       Running       12         7d
default       keystone-3099452964-f33bm                           1/1       Running       45         7d
default       mongo-0                                             2/2       Running       14         7d
default       myk8s--release-datadog-jgvfg                        1/1       Running       36         34d
default       myk8s--release-datadog-qmq55                        1/1       Running       36         34d
default       myk8s--release-kube-state-metrics-694891158-pv6kf   1/1       Running       8          7d
default       splunk-1114074158-n3n5z                             1/1       Running       8          7d
default       ssr-935902835-34pgr                                 1/1       Running       8          7d
default       wordpress-4094249903-kp6jv                          1/1       Running       7          7d
default       wordpress-mysql-3536461403-03z3n                    1/1       Running       8          7d
**kube-system   heapster-2708163903-4dvdv                           0/2       Terminating   0          1m
kube-system   heapster-2708163903-zxrq7                           2/2       Running       0          4s
kube-system   heapster-867061013-bpc6l                            0/2       Terminating   0          9s**
kube-system   kube-addon-manager-k8s-master-ecc3cc6b-0            1/1       Running       45         20d
kube-system   kube-apiserver-k8s-master-ecc3cc6b-0                1/1       Running       45         20d
kube-system   kube-controller-manager-k8s-master-ecc3cc6b-0       1/1       Running       121        20d
kube-system   kube-dns-v20-5nxlr                                  3/3       Running       24         7d
kube-system   kube-dns-v20-nb5k7                                  3/3       Running       24         7d
kube-system   kube-proxy-8bcw4                                    1/1       Running       44         41d
kube-system   kube-proxy-ff6c6                                    1/1       Running       45         41d
kube-system   kube-scheduler-k8s-master-ecc3cc6b-0                1/1       Running       125        20d
kube-system   kubernetes-dashboard-3995387264-4ht1g               1/1       Running       7          7d
kube-system   tiller-deploy-3019006398-b83zr                      1/1       Running       9          7d

The whole log while I am logging
zjune@k8s-master-ECC3CC6B-0:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                                READY     STATUS        RESTARTS   AGE
default       discuz-1878213324-8jr94                             1/1       Running       12         7d
default       keystone-3099452964-f33bm                           1/1       Running       45         7d
default       mongo-0                                             2/2       Running       14         7d
default       myk8s--release-datadog-jgvfg                        1/1       Running       36         34d
default       myk8s--release-datadog-qmq55                        1/1       Running       36         34d
default       myk8s--release-kube-state-metrics-694891158-pv6kf   1/1       Running       8          7d
default       splunk-1114074158-n3n5z                             1/1       Running       8          7d
default       ssr-935902835-34pgr                                 1/1       Running       8          7d
default       wordpress-4094249903-kp6jv                          1/1       Running       7          7d
default       wordpress-mysql-3536461403-03z3n                    1/1       Running       8          7d
kube-system   heapster-2708163903-4dvdv                           0/2       Terminating   0          1m
kube-system   heapster-2708163903-zxrq7                           2/2       Running       0          4s
kube-system   heapster-867061013-bpc6l                            0/2       Terminating   0          9s
kube-system   kube-addon-manager-k8s-master-ecc3cc6b-0            1/1       Running       45         20d
kube-system   kube-apiserver-k8s-master-ecc3cc6b-0                1/1       Running       45         20d
kube-system   kube-controller-manager-k8s-master-ecc3cc6b-0       1/1       Running       121        20d
kube-system   kube-dns-v20-5nxlr                                  3/3       Running       24         7d
kube-system   kube-dns-v20-nb5k7                                  3/3       Running       24         7d
kube-system   kube-proxy-8bcw4                                    1/1       Running       44         41d
kube-system   kube-proxy-ff6c6                                    1/1       Running       45         41d
kube-system   kube-scheduler-k8s-master-ecc3cc6b-0                1/1       Running       125        20d
kube-system   kubernetes-dashboard-3995387264-4ht1g               1/1       Running       7          7d
kube-system   tiller-deploy-3019006398-b83zr                      1/1       Running       9          7d
zjune@k8s-master-ECC3CC6B-0:~$ kubectl logs heapster-2708163903-zxrq7  -n kube-system
Error from server (NotFound): pods "heapster-2708163903-zxrq7" not found
zjune@k8s-master-ECC3CC6B-0:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                                READY     STATUS    RESTARTS   AGE
default       discuz-1878213324-8jr94                             1/1       Running   12         7d
default       keystone-3099452964-f33bm                           1/1       Running   45         7d
default       mongo-0                                             2/2       Running   14         7d
default       myk8s--release-datadog-jgvfg                        1/1       Running   36         34d
default       myk8s--release-datadog-qmq55                        1/1       Running   36         34d
default       myk8s--release-kube-state-metrics-694891158-pv6kf   1/1       Running   8          7d
default       splunk-1114074158-n3n5z                             1/1       Running   8          7d
default       ssr-935902835-34pgr                                 1/1       Running   8          7d
default       wordpress-4094249903-kp6jv                          1/1       Running   7          7d
default       wordpress-mysql-3536461403-03z3n                    1/1       Running   8          7d
kube-system   heapster-2708163903-p4rgj                           2/2       Running   0          40s
kube-system   kube-addon-manager-k8s-master-ecc3cc6b-0            1/1       Running   45         20d
kube-system   kube-apiserver-k8s-master-ecc3cc6b-0                1/1       Running   45         20d
kube-system   kube-controller-manager-k8s-master-ecc3cc6b-0       1/1       Running   121        20d
kube-system   kube-dns-v20-5nxlr                                  3/3       Running   24         7d
kube-system   kube-dns-v20-nb5k7                                  3/3       Running   24         7d
kube-system   kube-proxy-8bcw4                                    1/1       Running   44         41d
kube-system   kube-proxy-ff6c6                                    1/1       Running   45         41d
kube-system   kube-scheduler-k8s-master-ecc3cc6b-0                1/1       Running   125        20d
kube-system   kubernetes-dashboard-3995387264-4ht1g               1/1       Running   7          7d
kube-system   tiller-deploy-3019006398-b83zr                      1/1       Running   9          7d
zjune@k8s-master-ECC3CC6B-0:~$ kubectl logs heapster-2708163903-p4rgj  -n kube-system
Error from server (NotFound): pods "heapster-2708163903-p4rgj" not found
zjune@k8s-master-ECC3CC6B-0:~$ kubectl logs heapster-2708163903-p4rgj  -n kube-system
Error from server (NotFound): pods "heapster-2708163903-p4rgj" not found
zjune@k8s-master-ECC3CC6B-0:~$ kubectl get pods --all-namespaces
NAMESPACE     NAME                                                READY     STATUS    RESTARTS   AGE
default       discuz-1878213324-8jr94                             1/1       Running   12         7d
default       keystone-3099452964-f33bm                           1/1       Running   45         7d
default       mongo-0                                             2/2       Running   14         7d
default       myk8s--release-datadog-jgvfg                        1/1       Running   36         34d
default       myk8s--release-datadog-qmq55                        1/1       Running   36         34d
default       myk8s--release-kube-state-metrics-694891158-pv6kf   1/1       Running   8          7d
default       splunk-1114074158-n3n5z                             1/1       Running   8          7d
default       ssr-935902835-34pgr                                 1/1       Running   8          7d
default       wordpress-4094249903-kp6jv                          1/1       Running   7          7d
default       wordpress-mysql-3536461403-03z3n                    1/1       Running   8          7d
kube-system   heapster-2708163903-4p4bs                           2/2       Running   0          12s
kube-system   kube-addon-manager-k8s-master-ecc3cc6b-0            1/1       Running   45         20d
kube-system   kube-apiserver-k8s-master-ecc3cc6b-0                1/1       Running   45         20d
kube-system   kube-controller-manager-k8s-master-ecc3cc6b-0       1/1       Running   121        20d
kube-system   kube-dns-v20-5nxlr                                  3/3       Running   24         7d
kube-system   kube-dns-v20-nb5k7                                  3/3       Running   24         7d
kube-system   kube-proxy-8bcw4                                    1/1       Running   44         41d
kube-system   kube-proxy-ff6c6                                    1/1       Running   45         41d
kube-system   kube-scheduler-k8s-master-ecc3cc6b-0                1/1       Running   125        20d
kube-system   kubernetes-dashboard-3995387264-4ht1g               1/1       Running   7          7d
kube-system   tiller-deploy-3019006398-b83zr                      1/1       Running   9          7d
zjune@k8s-master-ECC3CC6B-0:~$ kubectl logs heapster-2708163903-4p4bs  -n kube-system
Error from server (BadRequest): a container name must be specified for pod heapster-2708163903-4p4bs, choose one of: [heapster heapster-nanny]
zjune@k8s-master-ECC3CC6B-0:~$ kubectl logs heapster-2708163903-4p4bs  -n kube-system heapster
I0919 02:23:55.459423       1 heapster.go:72] /heapster --source=kubernetes.summary_api:""
I0919 02:23:55.459602       1 heapster.go:73] Heapster version v1.3.0
I0919 02:23:55.460160       1 configs.go:61] Using Kubernetes client with master "https://10.0.0.1:443" and version v1
I0919 02:23:55.460337       1 configs.go:62] Using kubelet port 10255
I0919 02:23:55.462527       1 heapster.go:196] Starting with Metric Sink
I0919 02:23:55.565644       1 heapster.go:106] Starting heapster on port 8082
zjune@k8s-master-ECC3CC6B-0:~$ kubectl logs heapster-2708163903-4p4bs  -n kube-system heapster-nanny
I0919 02:23:54.463166       1 pod_nanny.go:56] Invoked by [/pod_nanny --cpu=80m --extra-cpu=0.5m --memory=140Mi --extra-memory=4Mi --threshold=5 --deployment=heapster --container=heapster --poll-period=300000 --estimator=exponential]
I0919 02:23:54.463522       1 pod_nanny.go:68] Watching namespace: kube-system, pod: heapster-2708163903-4p4bs, container: heapster.
I0919 02:23:54.463584       1 pod_nanny.go:69] cpu: 80m, extra_cpu: 0.5m, memory: 140Mi, extra_memory: 4Mi, storage: MISSING, extra_storage: 0Gi
I0919 02:23:54.468723       1 pod_nanny.go:110] Resources: [{Base:{i:{value:80 scale:-3} d:{Dec:<nil>} s:80m Format:DecimalSI} ExtraPerNode:{i:{value:5 scale:-4} d:{Dec:<nil>} s: Format:DecimalSI} Name:cpu} {Base:{i:{value:146800640 scale:0} d:{Dec:<nil>} s:140Mi Format:BinarySI} ExtraPerNode:{i:{value:4194304 scale:0} d:{Dec:<nil>} s:4Mi Format:BinarySI} Name:memory}]

You will notice the heapster deployment fail several times I would recommend to read the output to check heapster fail reason

**Comment by arindam00** [comment]
I am also facing the same issue with Heapster version 1.3.0. Is there a bug with heapster version 1.3.0 ?

**Comment by andyxning** [comment]
@JuneZhao @arindam00 

According to the kubelet log:
> Sep 18 05:44:55 k8s-agent-ECC3CC6B-0 docker[3056]: I0918 05:44:55.506240    3104 kuberuntime_manager.go:370] No sandbox for pod "heapster-2708163903-nd4hw_kube-system(7f67b525-9c34-11e7-9335-000d3a804764)" can be found. Need to start a new one

> Sep 18 05:44:50 k8s-agent-ECC3CC6B-0 docker[3056]: W0918 05:44:50.630850    3104 docker_sandbox.go:263] NetworkPlugin kubenet failed on the status hook for pod "heapster-2708163903-bpwlj_kube-system": Unexpected command output nsenter: cannot open /proc/54947/ns/net: No such file or directory

Seems this is related with you Kubernetes settings.

**Comment by jackyycheng** [comment]
I'm also seeing this issue as well...

**Comment by feiskyer** [comment]
I think it's not a heapster problem, we encounter same problem with v1.4.x images.

A quick fix for the problem is removing the label from heapster deployment: `kubernetes.io/cluster-service: "true"`.
