### ISSUE TITLE
pod_name=null in response 

### ISSUE THREAD

**Issue by huyhoang-goappable** [kubernetes/heapster#1814]
With all the query group by pod_name, I always get the response with a pod_name=null

`>  select "value" from "cpu/usage_rate" where "namespace_name" = 'kube-system' and time > now() - 5m group by "pod_name"
name: cpu/usage_rate
tags: pod_name=
time                value
----                -----
1505723040000000000 77
1505723100000000000 75
1505723160000000000 77
1505723220000000000 74`

And grafana also displays it 
![screen shot 2017-09-18 at 15 34 07](https://user-images.githubusercontent.com/28326648/30534142-0396500e-9c87-11e7-85f6-5dde14199cc6.png)

**Comment by DirectXMan12** [comment]
might be a bug in our influx sink
