### ISSUE TITLE
How to install plugins to Grafana

### ISSUE THREAD

**Issue by SviataslauDauhuchyts** [kubernetes/heapster#1815]
I'm trying to install a new plugin to Grafana. I've connected to my pod, used ```grafana-cli plugins install raintank-kubernetes-app``` command. The output of this command was show as "successful". But I still can't see this plugin in the list of available ones.

**Comment by DirectXMan12** [comment]
this is not the appropriate forum for grafana-specific questions, but I'd note that installing plugins at runtime like that is probably a bad idea, since they will not last through pod restart.
