### ISSUE TITLE
certificate is valid for x.x.x.x, not y.y.y.y

### ISSUE THREAD

**Issue by aaryabhatt** [kubernetes/heapster#1816]
Heapster is not able show data of two nodes servers, while it is showing data for rest of other servers.

when I run below command it don't show or gives the data of two servers while it shows rest of server

kubectl top node --heapster-namespace='openshift-infra' --heapster-port='80' --heapster-service=heapster --heapster-scheme=https

oc get node  ##return all nodes with ready

**using openshift 3 with below versions**
oc v1.5.1
kubernetes v1.5.2+43a9be4
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://prodmasternode1.abc.com:8443
openshift v1.5.1
kubernetes v1.5.2+43a9be4

**Steps To Reproduce**

1. I had setup of 9 servers with one master and one infra node.
2. Now I have to interchange two server, due to hardware, one was heavy server and other with lesser hardware.
3. I uninstall these these two servers with ansible by creating a separate host file for only these two servers.
4. Delete the node from cluster with oc delete node nodename.
5. Interchange the dns for both these servers.
6. Re add these servers to openshift with ansible scaleup . It added successfully.
7. I can run pods on these servers properly and everything looks fine.
8. Install the hawkular metrics with ansible too.
9. Now after sometime I realised that metrics not giving data for these two nodes.

**Current Result**

heapster logs keep showing logs for both these nodes and below line.

```
E0921 05:03:35.015487       1 summary.go:97] error while getting metrics summary from Kubelet proddatanode1.groupzeal.com(136.243.59.150:10250): Get https://136.243.59.150:10250/stats/summary/: x509: certificate is valid for 136.243.74.226, not 136.243.59.150
--
  | E0921 05:03:35.029178       1 summary.go:97] error while getting metrics summary from Kubelet proddatanode4.groupzeal.com(136.243.74.226:10250): Get https://136.243.74.226:10250/stats/summary/: x509: certificate is valid for 136.243.59.150, not 136.243.74.226
```
I found this issue https://github.com/kubernetes/heapster/issues/571 something related to mine.
Can I regenerate certificate for only these two servers. Or I have generate certificate for all 9 servers

like this
oadm ca create-server-cert --cert=master.server.crt --key=master.server.key --signer-cert=/etc/origin/master/ca.crt --signer-key=/etc/origin/master/ca.key --signer-serial=/etc/origin/master/ca.serial.txt --hostnames=kubernetes.default.svc,kubernetes.default.svc.cluster.local,localhost,openshift.default.svc.cluster.local,127.0.0.1,proddatanode4.groupzeal.com,proddatanode5.groupzeal.com,proddatanode3.groupzeal.com
with name of rest of other nodes too.

one more thing, EFK logging is also running on my setup and lot of pods are running, will it effect any of them?

Thanks.
Amit Bondwal

**Comment by aaryabhatt** [comment]
or do I need to follow this to redeploy node certificates
https://docs.openshift.com/container-platform/3.3/install_config/redeploying_certificates.html#redeploying-node-certificates

**Comment by DirectXMan12** [comment]
this almost certainly indicates that the certificates on your nodes are mismatched.  Try regenerating the certificates for those nodes.  Furthermore, this is not the correct place to ask about OpenShift deployment issues.

**Comment by aaryabhatt** [comment]
Thanks DirectXMan12, I asked it here because did not get any response on openshift origin for this same issue and found something similar issue here and openshift origin based on kubernetes.
