### ISSUE TITLE
heapster-amd64 v1.4.0 can not get whole cluster info

### ISSUE THREAD

**Issue by nefuddos** [kubernetes/heapster#1818]
When i deploy the heapster-amd64 v1.4.0 in the kubernetes, there are just a part of node resource info show at grafana and dashboard. But i can see all the digital info with kubernetes-dashboard-amd64, and what is the matter of this? why heapster cann't gather all the cluster info?

**Comment by DirectXMan12** [comment]
you're going to have to clarify what you mean.  It's not clear from what you've posted.
