### ISSUE TITLE
empty metrics

### ISSUE THREAD

**Issue by erkules** [kubernetes/heapster#1821]
I'm running heapster-v1.4.1 on a k8s 1.7.6.
Heapster fails to get the metrics:

~~~
curl heapster.kube-system/api/v1/model/namespaces/deploy/pods/web-1652643263-28fl/metrics/cpu/usage
{
  "metrics": [],
  "latestTimestamp": "0001-01-01T00:00:00Z"
~~~

**Comment by DirectXMan12** [comment]
if you want support, please provide more details than that.  Specifically, what do the logs look like?  How long did you wait before looking for metrics?
