### ISSUE TITLE
"Heapster currently supports Kubernetes and CoreOS natively"

### ISSUE THREAD

**Issue by craigbox** [kubernetes/heapster#1830]
From the README:

> Heapster currently supports Kubernetes and CoreOS natively. 

Where does this "CoreOS only" come from?  It feels like you are saying "Kubernetes on CoreOS", where you might be trying to say Heapster can look at metrics on CoreOS as well as on Kubernetes.

Is this still true, given things like Google COOS?

**Comment by DirectXMan12** [comment]
IIRC, at one point there was some feature where Kubernetes could collect metrics from CoreOS absent an installation of Kubernetes.  We probably need to update that part of the README.

**Comment by DirectXMan12** [comment]
feel free to submit a PR removing the "and CoreOS" part.
