### ISSUE TITLE
Add a way to install custom plugins

### ISSUE THREAD

**Issue by felixPG** [kubernetes/heapster#1835]
Hi:

Please, could you add a way to install custom plugins at pod creation time? Probably a config file with plugin urls that allow the installation!!

Now I cant install plugins, I have grafana running and when I install plugin with grafana-cli plugin never appear in the UI, also, where are the plugins directory???

**Comment by DirectXMan12** [comment]
Do you mean Grafana plugins?  If so, you should be installing plugins at image creation time.  Create a new image with ours as the base image, and install during the `docker build` phase.

**Comment by felixPG** [comment]
Ok, I make the same work and all ok, but the option of values with plugins to install is a good way.
