### ISSUE TITLE
Librato backend tags not working

### ISSUE THREAD

**Issue by sgmiller** [kubernetes/heapster#1836]
Using this config:

  Command:
      /heapster
      --source=kubernetes.summary_api:''
      --sink=librato:?username=$(LIBRATO_EMAIL)&token=$(LIBRATO_TOKEN)&prefix=kubernetes&tags=environment&tag_environment=dev
      --metric-resolution=30s
      --vmodule=*=4

I get tags that Heapster generates from Kubernetes labels, etc, but the configured environment tag does not appear in resulting metrics.

**Comment by DirectXMan12** [comment]
cc @johanneswuerbach

**Comment by johanneswuerbach** [comment]
Thanks @DirectXMan12 

@sgmiller I'm using a similar argument and it works
`--sink=librato:?username=$LIBRATO_EMAIL&token=$LIBRATO_TOKEN&prefix=k8s&tags=cluster,environment&tag_cluster=xxx&tag_environment=production`

Which version of heapster are you running?

**Comment by sgmiller** [comment]
v1.4.1
