### ISSUE TITLE
Heapster API server with Kubernetes 1.8

### ISSUE THREAD

**Issue by Joseph-Irving** [kubernetes/heapster#1840]
Hi, 

I've upgraded one of our clusters to 1.8 and discovered that I can no longer use Heapster as an APIService for things like Horizontal Pod Autoscaling as in 1.8 the metrics apis is now `/apis/metrics.k8s.io/v1beta1` instead of `apis/metrics/v1alpha1`.

The kube-controller logs `failed to get supported resources from server: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server could not find the requested resource` Which is the 404 that heapster gives.

Am I just missing something or is this something that will be updated at some point?

**Comment by DirectXMan12** [comment]
No, that is correct.  Heapster is deprecated for that purpose.  You should use metrics-server instead.  It was noted in the 1.8 release notes as a required action.

**Comment by Joseph-Irving** [comment]
Ah right thanks, I got a bit confused as it mentioned using the metrics-server but in the before upgrading section:
```
The metrics APIs, custom-metrics.metrics.k8s.io and metrics, were moved from v1alpha1 to v1beta1, and renamed to custom.metrics.k8s.io and metrics.k8s.io, respectively. If you have deployed a custom metrics adapter, ensure that it supports the new API version. If you have deployed Heapster in aggregated API server mode, upgrade Heapster to support the latest API version.
```
Which I assumed meant that heapster would be still be supporting the metrics api.

**Comment by DirectXMan12** [comment]
ah, sorry about that.  The release notes may have gotten a bit out of sync with the plans for Heapster as things got shuffled around.
