### ISSUE TITLE
Add Docker events to eventer

### ISSUE THREAD

**Issue by julianvmodesto** [kubernetes/heapster#1842]
Heapster collects Kubernetes events, but it seems we don't watch the Docker daemon and collect Docker events, similar to how Datadog will do this. I'd like to collect error events from Docker, for example for OOMs (https://github.com/DataDog/dd-agent/pull/2866/files).

**Comment by DirectXMan12** [comment]
Most people seem to be using something like https://github.com/heptiolabs/eventrouter.  Eventer doesn't really get much love these days, so it's probably more worthwhile looking there.

Furthermore, collecting Docker events would make Eventer significantly more complicated, so I suspect we'd would not be incredibly likely to accept such a patch, unfortunately.  This is probably the kind of thing that you'd want to set up separately in your monitoring pipeline.
