### ISSUE TITLE
Skipping rates for various calculations - k8s 1.8.0

### ISSUE THREAD

**Issue by tokiwinter** [kubernetes/heapster#1846]
I am running heapster 1.4.3 on a k8s 1.8.0 cluster (I've tried 1.4.0 too). InfluxDB 1.3.3. No matter what I set `--metric-resolution` to, I see this, always slightly larger than the value set for `--metric-resolution`. Here, it is using the default of 60s:
```
I1012 15:02:05.040687       1 rate_calculator.go:53] Skipping rates for namespace:kube-system/pod:kube-dns-7797cb8758-wjs94 - different create time new:2017-10-12 15:01:11 +0000 UTC  old:2017-10-12 15:00:10 +0000 UTC
```
I see this for most resource types, and as a result, metrics are sporadically missing when I query via `kubectl top {pods,nodes}`.

Example:
```
# kubectl top pods
NAME                       CPU(cores)   MEMORY(bytes)
foo-ab2d3s          17m          7Mi
busybox-56db8bd9d7-2s96p   0m           1Mi
busybox-56db8bd9d7-jm2j9   0m           1Mi
busybox-56db8bd9d7-lwzzn   0m           0Mi
busybox-56db8bd9d7-lkv8l   0m           0Mi
busybox-56db8bd9d7-cqlgq   0m           0Mi
busybox-56db8bd9d7-xpvz9   0m           1Mi
foo-98b9se          58m          8Mi
foo-kipb9a          37m          8Mi
...
# kubectl top pods
NAME                       CPU(cores)   MEMORY(bytes)
busybox-56db8bd9d7-cqlgq   0m           0Mi
busybox-56db8bd9d7-2s96p   0m           1Mi
busybox-56db8bd9d7-jm2j9   0m           1Mi
busybox-56db8bd9d7-lwzzn   0m           0Mi
foo-98b9se          59m          8Mi
foo-kipb9a          42m          8Mi
```
And here are some of the associated log messages:
```
1012 15:08:05.039841       1 rate_calculator.go:53] Skipping rates for namespace:default/pod:busybox-56db8bd9d7-lkv8l - different create time new:2017-10-12 15:08:05 +0000 UTC  old:2017-10-12 15:05:22 +0000 UTC
I1012 15:08:05.039867       1 rate_calculator.go:53] Skipping rates for namespace:kube-system/pod:kube-flannel-ds-8ntzq/container:kube-flannel - different create time new:2017-10-12 15:08:05 +0000 UTC  old:2017-10-12 15:05:22 +0000 UTC
I1012 15:08:05.039878       1 rate_calculator.go:53] Skipping rates for namespace:default/foo-ab2d3s - different create time new:2017-10-12 15:08:05 +0000 UTC  old:2017-10-12 15:04:22 +0000 UTC
```
Please can you advise? I've just cranked things up to `--v=9` and am capturing the log, so if you need any of that information, I can provide it.

**Comment by tokiwinter** [comment]
I've tried running heapster standalone, and it seems considerably worse:
```
I1012 17:58:05.129966       1 rate_calculator.go:53] Skipping rates for namespace:default/pod:busybox-56db8bd9d7-lwzzn/container:busybox - different create time new:2017-10-12 17:57:53.918666406 +0000 UTC  old:2017-10-12 17:49:33.262530678 +0000 UTC
```
There is an ~eight minute difference there. Can some light be shed on what is going on?

**Comment by DirectXMan12** [comment]
hmmm...

First things first, double check that the times are identical between all your nodes and masters (NTP, etc).  Once you've confirmed that, does anything jump out at you at log-level 9?  Look for messages about creating placeholder entries and similar.

**Comment by tokiwinter** [comment]
Yeah, ntp/time sync across all nodes is good (was the first thing I checked), as for logs, I'll check when I'm working on this again (context switching is a great thing), probably within the next day or so.
