### ISSUE TITLE
heapster and proxy

### ISSUE THREAD

**Issue by erkules** [kubernetes/heapster#1847]
Accessing heapster in an environment with a proxy will not work. 
So an `kubectl top nodes` returns the proxy page ending `  vertic (get services http:heapster:)`

I just wonder who calls to heapster, so I can add heapster to the NO_PROXY of that Pod/Service.

**Comment by DirectXMan12** [comment]
most of the things that call Heapster do so by making a request to the API server's HTTP proxy (the `services/proxy` subresource).  Is the issue that you can't access that, or that the API server is configured to go through a proxy when contacting services?
