### ISSUE TITLE
Heapster pod crashes continously - panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by githubvick** [kubernetes/heapster#1855]
I'm using Kubespray to install and configure a Kubernetes cluster. Kubernetes version running is 1.7.5

The heapster version of image used is gcr.io/google_containers/heapster-amd64:v1.4.2. 
Heapster  grafana version of image used is  gcr.io/google_containers/heapster-grafana-<platform>:v4.4.3
Heapster influxdb version of image used is gcr.io/google_containers/heapster-influxdb-<platform>:v1.3.3

After a couple of minutes the pod fails with this below error. It has restarted hundreds of times.

```
panic: runtime error: slice bounds out of range

goroutine 172 [running]:
k8s.io/heapster/metrics/sources/kubelet.(*kubeletMetricsSource).decodeMetrics(0xc4202a32c0, 0xc420238a00, 0xc420e09b60, 0xc420238c62, 0xc4202a2540)
        /go/src/k8s.io/heapster/metrics/sources/kubelet/kubelet.go:162 +0x1279
k8s.io/heapster/metrics/sources/kubelet.(*kubeletMetricsSource).ScrapeMetrics(0xc4202a32c0, 0xed17cab34, 0xc400000000, 0x255d380, 0xed17cab70, 0xc400000000, 0x255d380, 0x195b8e9)
        /go/src/k8s.io/heapster/metrics/sources/kubelet/kubelet.go:241 +0x3e3
k8s.io/heapster/metrics/sources.scrape(0x23d2dc0, 0xc4202a32c0, 0xed17cab34, 0xc400000000, 0x255d380, 0xed17cab70, 0x0, 0x255d380, 0x0)
        /go/src/k8s.io/heapster/metrics/sources/manager.go:169 +0x2a0
k8s.io/heapster/metrics/sources.(*sourceManager).ScrapeMetrics.func1(0xc420415540, 0x23d2dc0, 0xc4202a32c0, 0xc4202a3500, 0xed17cab34, 0x0, 0x255d380, 0xed17cab70, 0x0, 0x255d380, ...)
        /go/src/k8s.io/heapster/metrics/sources/manager.go:99 +0x155
created by k8s.io/heapster/metrics/sources.(*sourceManager).ScrapeMetrics
        /go/src/k8s.io/heapster/metrics/sources/manager.go:115 +0x387

```

I've been trying to debug this for a couple of days, I tried to change versions of heapster-amd64 and other image combinations of grafana and influxdb. But none of them worked. I also tried to disable dns once as I saw in another issue in github, but it didnt work as well. Pls suggest what might be wrong.

**Comment by DirectXMan12** [comment]
looks like a bug in the legacy kubelet source, which really just needs to be removed.  Please try using `--source=kubernetes.summary_api=...` and see if you hit the bug.  A quick glance seems to indicate that it's due to a hack put in place to extract container names

**Comment by githubvick** [comment]
hi @DirectXMan12 Thx a lot, it worked, I'll close the issue in another few minutes to make sure it doesn't restart
