### ISSUE TITLE
Kafka Sink needs new maintainers

### ISSUE THREAD

**Issue by DirectXMan12** [kubernetes/heapster#1860]
The current maintainer of the Kafka sink, @huangyuqi, appears to be unresponsive.  We need at least one (preferably two) maintainers to review PRs and handle issues in order for the sink to continue to exist in Heapster.

See also #1792 

 @miaoyq @Kokan @juanluisvaladas you've all contributed to the Kafka sink.  Are any of you interested?

**Comment by miaoyq** [comment]
@DirectXMan12  I would like to be the maintainer of Kafka sink. :)

**Comment by juanluisvaladas** [comment]
Thanks, but unfortunately I don't know nearly enough about kafka. I don't think I can take this responsibility in good faith.

**Comment by Kokan** [comment]
It would be a great opportunity for me.

**Comment by DirectXMan12** [comment]
@miaoyq @Kokan awesome.  Can one of you two file a PR to update the sink-owners doc?  Remove the old Kafka maintainer, and add yourselves as the current ones.

**Comment by Kokan** [comment]
@DirectXMan12 yes, see #1863

**Comment by DirectXMan12** [comment]
just merged the PR.  Looks good.
