### ISSUE TITLE
Too many pods

### ISSUE THREAD

**Issue by gertjan-carbon** [kubernetes/heapster#1862]
I have made a dashboard to view the amount of pods of a certain container that are active at any given time.

``SELECT count("value") FROM "uptime" WHERE "type" = 'pod_container' AND "namespace_name" =~ /$namespace$/ AND "container_name" =~ /$container$/ AND $timeFilter GROUP BY time($interval), "container_name" fill(null) ``

This was working great for a while, until one of my "containers" showed a steady decline till 0 yesterday.

All other dashboards are fine, but this one is not anymore.
Now this service autoscales from 5 to 75 pods, and does this about twice hourly, so the amount of pods that have ever existed add up rapidly.

Even on the PODS dashboard (only modified the datasource and refresh on dashboard load bug) I can no longer get all my pods of this type visual .. (right now name-[0-1, A-K] are what is listed in the drop down) and that list is shrinking.

I can't find any limit in the SQL query, or settings, so I assume it might be a hardcode limit?

Some of the details that might help:
Kubernetes 1.7.2
KOPS 1.7.0
Runs on AWS
Stack is the latest I think:
gcr.io/google_containers/heapster-amd64:v1.4.0 
gcr.io/google_containers/heapster-grafana-amd64:v4.4.1
gcr.io/google_containers/heapster-influxdb-amd64:v1.1.1

![decline](https://user-images.githubusercontent.com/30525907/32227545-a15ba7c0-be43-11e7-9a3a-7e38c96786e4.png)

edit:

From the heapster logs:
``E1101 09:29:05.468743       1 influxdb.go:186] InfluxDB write failed: {"error":"partial write: max-series-per-database limit exceeded: db=k8s (1000000/1000000) dropped=346"}
E1101 09:29:05.872432       1 influxdb.go:186] InfluxDB write failed: {"error":"partial write: max-series-per-database limit exceeded: db=k8s (1000000/1000000) dropped=333"}
E1101 09:29:06.027021       1 influxdb.go:186] InfluxDB write failed: {"error":"partial write: max-series-per-database limit exceeded: db=k8s (1000000/1000000) dropped=384"}``

I missed this yesterday as I restarted heapster just before creating this Issue to see if that would help.

**Comment by gertjan-carbon** [comment]
Fixed it by adding INFLUXDB_DATA_MAX_SERIES_PER_DATABASE = 0 to the environmental settings of the pod.
As suggested in https://github.com/influxdata/docs.influxdata.com/issues/710

**Comment by xorpierre** [comment]
@gertjan-carbon Can you show me how this is suppose to look like?
I added the env var to the deployment and I see it in the running pod as this:

`spec:
  containers:
  - command:
    - /heapster
    - --source=kubernetes:https://kubernetes.default
    - --sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086
    env:
    - name: INFLUXDB_DATA_MAX_SERIES_PER_DATABASE
      value: "0"
`

But I still run into the error, it seems influxdb is ignoring the variable

**Comment by gertjan-carbon** [comment]
Looks like they have changed the settings a bit:

http://docs.influxdata.com/influxdb/v1.6/administration/config/ <http://docs.influxdata.com/influxdb/v1.6/administration/config/>

And it can also be this setting: INFLUXDB_DATA_MAX_VALUES_PER_TAG

It seems your setting is correct although I have used single instead of double quotes.
