### ISSUE TITLE
Unable to retrieve Heapster Metrics through REST API

### ISSUE THREAD

**Issue by khaled-nabil** [kubernetes/heapster#1867]
I am running my kubernetes v1.6.11-gke.0 cluster on GKE. Within the cluster heapster-v1.3.0 (gcr.io/google_containers/heapster-amd64:v1.3.0) pod is running.

However when trying to retrieve heapster metrics through the REST API, there appears to be an issue, as showing below:
```
localhost:8001/api/v1/model/metrics
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "the server could not find the requested resource",
  "reason": "NotFound",
  "details": {},
  "code": 404
}

```
and 
```
localhost:8001/api/v1/proxy/namespaces/kube-system/services/heapster/
404 page not found

```
Moreover, kube-dns seems unreachable too
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for service \"kube-dns\"",
  "reason": "ServiceUnavailable",
  "code": 503
}

```
Using kubectl cluster-info services seem to be working well.

Any suggestion on where to start debugging the issue from?

**Comment by DirectXMan12** [comment]
The Heapster model API needs to be accessed on the Heapster pod/service itself, not your main API server.  If you want to use the API server proxy, use the service name `http:heapster:`.  However, I would not recommend using the model API at all.  It's deprecated.

**Comment by khaled-nabil** [comment]
@DirectXMan12 Thanks for the clarification, it seems I have missed that part.
I haven't read anywhere that model API is deprecated, perhaps an update of [model.md](/kubernetes/heapster/blob/master/docs/model.md) is due. Is heapster to be replaced by kube-state-metrics?

**Comment by DirectXMan12** [comment]
Heapster is being replaced by metrics-server.  The model API never left alpha, and we have no plans to do so.  I believe we marked it as deprecated at some point, but you're correct, the model document should probably also mention it.  Feel free to make a PR :-)
