### ISSUE TITLE
Tracking issue for adding GPU metrics to heapster

### ISSUE THREAD

**Issue by andyxning** [kubernetes/heapster#1872]
This is a tracking issue for adding GPU metrics to heapster.
* bump cadvisor to [latest](https://github.com/google/cadvisor/commit/c99f2418fa7bbc6fc54159fa50f0043f882e9e7c)
* add support for GPU metrics for kubelet summary api endpoint
* add support for GPU metrics for normal cAdvisor endpoint

/cc @DirectXMan12 @piosz @loburm @mindprince @vishh

**Comment by piosz** [comment]
It's not fixed yet
