### ISSUE TITLE
k8s database not created in InfluxDB

### ISSUE THREAD

**Issue by Guillaume-Mayer** [kubernetes/heapster#1875]
I followed the InfluxDB guide, the pods were correctly created (except for the heapster one that already existed).
In Grafana, the datasource source for InfluxDB is already set, but the k8s database does not exist.
Am I supposed to create it ?

GET /query?q=SHOW+DATABASES
Gives me:
{"results":[{"statement_id":0,"series":[{"name":"databases","columns":["name"],"values":[["_internal"]]}]}]} 

Thanks in advance

**Comment by leezout** [comment]
Same issue here, it doesn't create k8s database.

**Comment by Guillaume-Mayer** [comment]
I was able to fix my issue manually adding `–sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086` in the heapster deploy.
So it was an Azure issue I guess.

**Comment by DirectXMan12** [comment]
closing as per comments
