### ISSUE TITLE
Metrics simplification for influxDB

### ISSUE THREAD

**Issue by andyxning** [kubernetes/heapster#1880]
For now, counter type metrics will have both counter metrics and the rate metrics. However, the most and only useful metrics are the rate metrics actually. This is fine for small clusters. However, when the clusters and running pods becomes more and more larger, the original counter metrics will only add stress on the metrics sinks.

For example, `cpu/usage` is useless IMO as for `cpu/usage_rate` is more useful.
IMHO, metrics in below tables can be deleted before exported to sinks

| Metric Name | Description |
|------------|-------------|
| cpu/usage | CPU hard limit in millicores. |
| memory/page_faults | Number of page faults. |
| memory/major_page_faults | Number of major page faults. |
| network/rx | Cumulative number of bytes received over the network. |
| network/rx_errors |  Cumulative number of errors while receiving over the network. |
| network/tx | Cumulative number of bytes sent over the network. |
|network/tx_errors | Cumulative number of errors while sending over the network. |

With deleting original counter metrics, we can reduce the stress for metric sinks and without loss any useful metrics. :)

/cc @DirectXMan12 @loburm @piosz

**Comment by loburm** [comment]
What will happen if some users depend on this metrics?

**Comment by DirectXMan12** [comment]
`cpu/usage` is not the hard limit in millicores -- it's the cumulative CPU time used by the process.  These metrics are still useful for people who want to do their own rate calculations.  Depending on the sink, it's *almost* better to provide the counter metrics only, and let the sink to a better rate calculation than Heapster can.  I don't think we should remove either, or, at the very least, should just make it an option.

**Comment by andyxning** [comment]
@DirectXMan12 Make it an option is good for me. By giving a switch, it should be fine to let users to choose whether to disable or enable those counter metrics depends on their demand. Will change the PR.
