### ISSUE TITLE
How to update an existing autoscale setting?

### ISSUE THREAD

**Issue by chinajuanbob** [kubernetes/heapster#1887]
Hi,

I hit an error after issue this command twice

```
$: kubectl autoscale deployment echo-http-backend --cpu-percent=20 --min=1 --max=10
Error from server (AlreadyExists): horizontalpodautoscalers.autoscaling "echo-http-backend" already exists
```

So how to update or delete an existing one, is there a doc for it?

ENV
minikube v0.23.0

Thanks a lot!

**Comment by DirectXMan12** [comment]
this is not an appropriate question for the Heapster repository.  Questions about Kubernetes itself should be directed at [StackOverflow](https://stackoverflow.com/questions/tagged/kubernetes), or by reading the Kubernetes documentation: https://kubernetes.io/docs/tasks/run.../horizontal-pod-autoscale-walkthrough/
