### ISSUE TITLE
InfluxDB/Heapster/Grafana show incorrect individual memory usage values at pod and host level.

### ISSUE THREAD

**Issue by pcm32** [kubernetes/heapster#1893]
Hi there!

Using the setup available in deploy/kube-config/influxdb, I can observe that there some incorrect plots on the grafana side for memory usage:

- Pod level: the individual memory usage values change for a defined pod and a defined time frame when the length of the period plotted (last 2 days, last 7 days) changes (for the same temporal points of course). See an example in [this gist](https://gist.github.com/pcm32/612a79bee6c2fecfa6e4e9387bde9ce9).

- Host level: we see memory usage values reported that go beyond the actual VMs real logical memory (95 GiB for VMs that have 12 GiB for instance). These machines have no swap, so no memory could be considered in this way.

This is running on a Kubernetes 1.8.1 cluster, deployed with Kubespray v2.3.0, on top of Ubuntu Xenial cloud images on OpenStack.

Containers for Grafana/Heapster/InfluxDB are:

Grafana: gcr.io/google_containers/heapster-grafana-amd64:v4.4.3
Heapster: gcr.io/google_containers/heapster-amd64:v1.4.0
Influxdb: gcr.io/google_containers/heapster-influxdb-amd64:v1.3.3

Any ideas? Thanks!

**Comment by pcm32** [comment]
I think that the incorrect part lies in the Grafana query for influxdb being used. Currently it is doing a sum over the time interval used in the group by, 

```
SELECT sum("value") 
FROM "memory/usage" 
WHERE "type" = 'node' AND "nodename" =~ /$nodename$/ 
              AND $timeFilter 
GROUP BY time($interval), "nodename" fill(null)
```

which is probably aggregating things differently on larger or smaller time intervals. Using the mean or the median as aggregator function in the select, you don't see the compounded effect over different time lapses (value levels stay the same, regardless of the time window chosen).

**Comment by pcm32** [comment]
I can confirm that the same is currently happening with the CPU usage graphs, if you change the time window, values change for the same time points. I know what to change now, and if you agree with the change (I would change the aggregator to mean in all the grafana queries on the json files, in lines like [this](https://github.com/kubernetes/heapster/blob/a2ec4cb45407edab53948236468fec6b702447d8/grafana/dashboards/cluster.json#L80)), I'm happy to create a PR with it.

**Comment by pcm32** [comment]
Possibly `max` is an even better aggregator as well, as `mean` will soften peaks, giving you false impressions when it comes to discovering whether you use to much of the resources...

**Comment by abelsromero** [comment]
What's the status on this? I understand the PR is waiting for validarion.
Honestly, we are seeing the same problem and fixing the dashboards, but it would be nice to have it merged in upstream.

**Comment by pcm32** [comment]
I have updated the PR to use mean instead of max @abelsromero, now it depends on project owners.

**Comment by pcm32** [comment]
I have assigned the PR a project owner, so that it can be merged and we can close this.

**Comment by abelsromero** [comment]
Thanks for keeping an eye on this.
