### ISSUE TITLE
Heapster reports inconsistent memory usage stats for cluster/node/pod

### ISSUE THREAD

**Issue by chengwang86** [kubernetes/heapster#1897]
I have a heapster container (image: `wavefronthq/heapster-amd64:latest`; used with a wavefront-proxy container) in a k8s cluster (kubernetes version 1.8.2).

The cluster has two worker nodes, and below is what I observed 
```
heapster.cluster.memory.usage:           1.8G
heapster.node.memory.node_utilization:   vm1=89%, vm2=82%
heapster.node.memory.node_allocatable:   vm1=vm2=4GB
heapster.node.memory.node_capacity:      vm1=vm2=4.144GB
heapster.node.memory.usage:              vm1=3.6GB, vm2=3.3GB
sum(heapster.pod.memory.usage):          vm1=1.7GB, vm2=125MB
```
So the two worker nodes have 8GB RAM in total and the cluster uses 1.8 GB. But then why are the node_utilization values so high?

**Comment by DirectXMan12** [comment]
this is a bit confusing, but cluster usage is the sum of all namespace usage, while node usage, IIRC, is at least partially just recorded directly, so thats probably what you're seeing (just pod usage vs pod+system usage).
