### ISSUE TITLE
Measured uptime are randomly reseted 

### ISSUE THREAD

**Issue by mrblackus** [kubernetes/heapster#1899]
Hi,

Since a couple of weeks, our reported uptime for most of our pods are incorrect and reset to 0 frequently but at a random rate (sometimes it's reset after a couple of minutes/seconds, sometimes a couple of hours).

The data are sinked to influxdb and displayed with Grafana.
Here is a screenshot of the uptime of some MongoDB nodes over a week (none of them have restarted). Only the blue line (node-2) is correct, all other are reset randomly.

![grafana_-_new_dashboard](https://user-images.githubusercontent.com/2353980/33493241-b57c56d4-d6bf-11e7-9a5d-efd1a825625f.png)

Versions:
- kubernetes: 1.8.3
- heapster: 1.4.3 amd64
- influxdb: 1.1.1 amd64

Any idea of what is going wrong?

**Comment by mrblackus** [comment]
After investigation, it seems that uptime resets happen when there is some load on the pod, but it's not always true...

Here is a graph with uptime in yellow, and CPU usage in millicores in green.
![](https://user-images.githubusercontent.com/2353980/33545247-c6390c5e-d8dd-11e7-9475-07e1dcda4725.png)

**Comment by khaled-nabil** [comment]
If you're running your cluster on GKE, my guess is that you're running a second Deployment of Heapster in order to dump metrics into InfluxDB sink. If that's the case, do both Heapster metrics match?
It might be useful to look into CPU and Memory Utilization at the the Node.

**Comment by mrblackus** [comment]
You're right, I have a second heapster deployment that sinks data on InfluxDB, and the default kubernetes one that sinks them to StackDriver.
I couldn't find the CPU usage per pod on StackDriver, but memory reporting seems to be the same on InfluxDB and StackDriver.

After digging more, I found [this issue](https://github.com/google/cadvisor/issues/1607) on cAdvisor that looks interesting. Not sure if it's linked or not, but after reading heapster code, it's unlinkely that this code is doing something wrong, so kubelet or cAdvisor might be responsible.

**Comment by DirectXMan12** [comment]
FYI, you can configure a single Heapster to dump to multiple sinks.
