### ISSUE TITLE
How to start with Heapster?

### ISSUE THREAD

**Issue by Asher-Shoshan** [kubernetes/heapster#1903]
Can't figure out what exactly to do and start using  Heapster in my on-premises Kubernetes cluster.
Download the yaml files (which ones)  and 'kubectl create -f ..."?
What about cadvisor?  Do I have to run it outside Kubernetes?
How is that related to Kubernetes-Dashboard?
Thanks,

**Comment by kawych** [comment]
Heapster deployment files are [here](https://github.com/kubernetes/heapster/tree/master/deploy/kube-config), choose the ones according to your backend. You shouldn't have to run cadvisor.
