### ISSUE TITLE
Failed to create influxdb : received status code 400 from server

### ISSUE THREAD

**Issue by tirumaraiselvan** [kubernetes/heapster#1913]
Hi all,

I am trying to run heapster on one kubernetes cluster and influxdb + grafana on another kubernetes cluster. So I setup my heapster like so:

      - command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:https://influxdb.monitoring-stg.hasura-app.io
        image: gcr.io/google_containers/heapster-amd64:v1.4.3

The sink endpoint is up and running as verified by ` curl -v https://influxdb.monitoring-stg.hasura-app.io` which return 204.

But heapster logs throws the following error:

`influxdb.go:175] Failed to create influxdb: Retention Policy creation failed: received status code 400 from server`

I went into the influxdb server using the client and saw there was no db called k8s ( I am guessing it should be created by heapster). 

Any advice?

**Comment by x13n** [comment]
Looks like there is some connectivity, so I'd try checking influxdb logs to see why it returned this error.

**Comment by tirumaraiselvan** [comment]
I don't see any access request by heapster in influxdb logs. 

This is what it looks like:

[I] 2017-12-14T10:43:19Z InfluxDB starting, version unknown, branch unknown, commit unknown
[I] 2017-12-14T10:43:19Z Go version go1.8.3, GOMAXPROCS set to 1
[I] 2017-12-14T10:43:19Z Using configuration at: /etc/config.toml
[I] 2017-12-14T10:43:19Z Using data dir: /data/data service=store
[I] 2017-12-14T10:43:19Z opened service service=subscriber
[I] 2017-12-14T10:43:19Z Starting monitor system service=monitor
[I] 2017-12-14T10:43:19Z 'build' registered for diagnostics monitoring service=monitor
[I] 2017-12-14T10:43:19Z 'runtime' registered for diagnostics monitoring service=monitor
[I] 2017-12-14T10:43:19Z 'network' registered for diagnostics monitoring service=monitor
[I] 2017-12-14T10:43:19Z 'system' registered for diagnostics monitoring service=monitor
[I] 2017-12-14T10:43:19Z Starting precreation service with check interval of 10m0s, advance period of 30m0s service=shard-precreation
[I] 2017-12-14T10:43:19Z Starting snapshot service service=snapshot
[I] 2017-12-14T10:43:19Z Starting continuous query service service=continuous_querier
[I] 2017-12-14T10:43:19Z Starting HTTP service service=httpd
[I] 2017-12-14T10:43:19Z Authentication enabled:false service=httpd
[I] 2017-12-14T10:43:19Z Listening on HTTP:[::]:8086 service=httpd
[I] 2017-12-14T10:43:19Z Starting retention policy enforcement service with check interval of 30m0s service=retention
[I] 2017-12-14T10:43:19Z Listening for signals
[I] 2017-12-14T10:43:19Z Storing statistics in database '_internal' retention policy 'monitor', at interval 10s service=monitor
[httpd] 10.140.0.17,10.60.2.68 - - [14/Dec/2017:10:44:52 +0000] "GET /ping HTTP/1.0" 204 0 "-" "curl/7.47.0" d0cd680d-e0bb-11e7-8001-000000000000 202
[I] 2017-12-14T11:13:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T11:43:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T12:13:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T12:43:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T13:13:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T13:43:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T14:13:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T14:43:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T15:13:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T15:43:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T16:13:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T16:43:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T17:13:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T17:43:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T18:13:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T18:43:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T19:13:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T19:43:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T20:13:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T20:43:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T21:13:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T21:43:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T22:13:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T22:43:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T23:13:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-14T23:33:19Z new shard group 2 successfully precreated for database _internal, retention policy monitor service=metaclient
[I] 2017-12-14T23:43:19Z retention policy shard deletion check commencing service=retention
[I] 2017-12-15T00:09:50Z Snapshot for path /data/data/_internal/monitor/1 written in 251.384356ms engine=tsm1
