### ISSUE TITLE
Help Wanted - Cannot connect to influxdb via influx client.

### ISSUE THREAD

**Issue by rohansahai** [kubernetes/heapster#1918]
Not sure if this a heapster issue, but I figured someone might have a better idea than me what exactly is going wrong (I'm new to this stack).

I'm trying to actually use the influxdb shell to set a retention policy on some data (remove references to old terminated pods so our grafana graphs are a bit more useful). I run

`kubectl get services -n kube-system | grep influxdb`

to find our influx service ip. And then I run:

`influx -host YOUR_INFLUX_SERVICE_IP -port 8086`

but it hangs and eventually times out with a `getsockopt: connection timed out` error. Grafana has no problem adding influxdb as a data source. The influxdb url specified there isn't an IP but rather the service name (`http://monitoring-influxdb:8086`), connecting to that via the client also does not work.

Thanks for the awesome open source product!

**Comment by x13n** [comment]
This doesn't look to be a problem with Heapster, so closing. Please use slack/stackoverflow for this type of questions.

That being said, your influxdb probably doesn't expose any external IP which is why you cannot reach it. Grafana runs in the same cluster, so internal IP is enough there.

**Comment by rohansahai** [comment]
ok sorry about that, thanks
