### ISSUE TITLE
New feature - add POD ownerReferences

### ISSUE THREAD

**Issue by evilezh** [kubernetes/heapster#1924]
We have information about pods, but it would be much more useful if we would have owner metadata as extra labels:
owner_type: deployment/daemonset/statefulSet/......
owner_name: deployment-1

That would provide much better visibility for stats and I could template in grafana something like:
owner_type, owner_name, pod_id, container_id
CHART CHART CHART

If we could include at least top owner, it would be great benefit.

**Comment by DirectXMan12** [comment]
Heapster is now deprecated.  No new sinks or features will be added.  See https://github.com/kubernetes/heapster/blob/master/docs/deprecation.md#initial-deprecation-kubernetes-111 for more details.
