### ISSUE TITLE
Pod cpu usage calculation method for HPA

### ISSUE THREAD

**Issue by maartenvermeyen** [kubernetes/heapster#1925]
Can someone explain how the cpu usage is calculated inside pods with multiple containers for use with an HPA? 
Is it the mean value and how is this calculated?

For example:
If we have 2 containers:
- Container1 requests 0.5 cpu and uses 0 cpu
- Container2 requests 1 cpu and uses 2 cpu

If we calculate both seperatly and take the mean: (0% + 200%)/2 = 100% usage?
If we take the sums and take the mean: 2/1.5 = 133% usage?

Or is my logic way off?

**Comment by maartenvermeyen** [comment]
I moved the question to stackoverflow: https://stackoverflow.com/questions/48172151/kubernetes-pod-cpu-usage-calculation-method-for-hpa

**Comment by x13n** [comment]
I think this is more of a HPA question, not a heapster question. I guess @MaciekPytel should know.
