### ISSUE TITLE
Improve Kafka Sink with SASL/SSL configuration

### ISSUE THREAD

**Issue by ryarnyah** [kubernetes/heapster#1928]
Today kafka sink does not support security configuration. Also the library "https://github.com/optiopay/kafka" does not seem to support it yet but "https://github.com/Shopify/sarama" did.

Is there a plan to support SASL/SSL? If yes, can we propose PR to migrate to sarama to support it?

Edit: see https://github.com/kubernetes/heapster/pull/1931

**Comment by Kokan** [comment]
> Is there a plan to support SASL/SSL? 

I have no plan to do it in the near feature, but glad to see such PR :)

> If yes, can we propose PR to migrate to sarama to support it?

Of course you can. But changes that does not improve, personally I do not like. Therefore it must improve something, while still provides the same set of features.
A few thing also important:
* active development/community
* good compatibility
* usable api

At first sight it looks promising to me, but I think to review most of those things I am going to review the PR and gave my feedback about the above mentioned.

**Comment by miaoyq** [comment]
@ryarnyah Thanks, I will review this PR.
