### ISSUE TITLE
Negative value on "disk/io_read_bytes_rate" and "disk/io_write_bytes_rate"

### ISSUE THREAD

**Issue by qhyou11** [kubernetes/heapster#1935]
Hi all,  

I am running heapster on one kubernetes cluster with influxdb as backends , and get some negative value on "disk/io_read_bytes_rate" and "disk/io_write_bytes_rate" .  
Because metric "disk/io_write_bytes" and "disk/io_read_bytes" got "resource_id" as  tag, but "Process" in "rate_calculator.go" didn't consider such case.  
```
		if metricName == core.MetricDiskIORead.MetricDescriptor.Name || metricName == core.MetricDiskIOWrite.MetricDescriptor.Name {
				for _, itemNew := range newMs.LabeledMetrics {
					foundNew, foundOld = false, false
					if itemNew.Name == metricName {
						metricValNew, foundNew = itemNew.MetricValue, true
						for _, itemOld := range oldMs.LabeledMetrics {
							if itemOld.Name == metricName {
								metricValOld, foundOld = itemOld.MetricValue, true
								break
							}
						}
					}
```
line 70 should be something like " if itemOld.Name == metricName && itemOld.Labels["resource_id"] == itemNew.Labels["resource_id"]{" ?

**Comment by DirectXMan12** [comment]
Since you've already tracked down the issue, can you submit a PR to fix it?  Thanks!

**Comment by andyxning** [comment]
Close this via #2008 
/close
