### ISSUE TITLE
influxdb tries to listen on wrong address

### ISSUE THREAD

**Issue by szaharici** [kubernetes/heapster#1939]
Hello,

I am trying to run heapster on a newly created baremetal server running kubernetes 1.9.2 as described here https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md
However, InfluxDB fails to start because it is trying to use a wrong address
```
kubectl logs monitoring-influxdb-6c4b84d695-664cl -n kube-system
[I] 2018-01-25T20:22:45Z InfluxDB starting, version unknown, branch unknown, commit unknown
[I] 2018-01-25T20:22:45Z Go version go1.8.3, GOMAXPROCS set to 4
[I] 2018-01-25T20:22:45Z Using configuration at: /etc/config.toml

 8888888           .d888 888                   8888888b.  888888b.
   888            d88P"  888                   888  "Y88b 888  "88b
   888            888    888                   888    888 888  .88P
   888   88888b.  888888 888 888  888 888  888 888    888 8888888K.
   888   888 "88b 888    888 888  888  Y8bd8P' 888    888 888  "Y88b
   888   888  888 888    888 888  888   X88K   888    888 888    888
   888   888  888 888    888 Y88b 888 .d8""8b. 888  .d88P 888   d88P
 8888888 888  888 888    888  "Y88888 888  888 8888888P"  8888888P"

run: open server: listen: listen tcp 10.132.11.24:8088: bind: cannot assign requested address
```
I have no idea where the range 10.132 comes from...it is not the on the nodeip range or pod network range
If I edit the monitoring-influxdb deployment to just run influxd, instead of ```["influxd", "--config", "/etc/config.toml"]``` heapster starts correclty

**Comment by szaharici** [comment]
I dug a bit around and found the cause, we do have a localhost.<default-domain> entry on our DNS server that is always resolved when using localhost instead of reading the entry from the /hosts file. This is triggered by the absence of /etc/nsswitch.conf speicifying the host file priority in the docker image

**Comment by DirectXMan12** [comment]
Oof.  Yeah, `localhost` should resolve to the loopback address.  Does your DNS server not respond with NXDOMAIN for `localhost`?  That seems strange...

Anyway, I'm closing this be.  Feel free to re-open if you disagree.
