### ISSUE TITLE
Impossible to configure authenticated InfluxDB sink when passwords contain a `#` symbol

### ISSUE THREAD

**Issue by kevinschoon** [kubernetes/heapster#1949]
Hi --

The Heapster executable reads sink options as a parameterized URL which is parsed with the built-in `net/url` library. For example one might run Heapster with an Inflxudb sink as follows:

```
heapster --source=kubernetes.summary_api:'' --sink='influxdb:https://my-node.com:8086?retention=INF&secure=true&user=user@company.com&pw=my#Password'
```
This is [parsed](https://github.com/kubernetes/heapster/blob/release-1.5/common/flags/flags.go#L46-L50) in the `common/flags` package where `net/url` [splits](https://github.com/golang/go/blob/release-branch.go1.10/src/net/url/url.go#L449-L463) the query on what is seen as a fragment identifier `#` mutating it's value storing one half in `url.Fragment` and the other in `url.Values`.

In the example above the password would be returned as `my` and `Password` would be stored in `url.Fragment` which results in Influxdb rightly denying us access. 

```
E0201 23:21:05.177750   17033 influxdb.go:219] InfluxDB write failed: {"error":"authorization failed"}
```
It should be trivial to create an explicit `--influxdb-password` flag or similar and I am of the opinion that using `net/url` to parse these arguments from the CLI is abuse of the package anyway and that explicit flags should be favoured entirely. 

Thank you for your work on Heapster!

**Comment by DirectXMan12** [comment]
Does percent-escaping (URL escaping) the password work?  It probably should.  Please try that.

**Comment by kevinschoon** [comment]
@DirectXMan12 Thank you for the follow up, escaping the password resolves the error. I opened the issue because it wasn't immediately clear to me how the parameters were being parsed (although it is indeed a URL) or how it was being validated.

**Comment by DirectXMan12** [comment]
ok, I'm closing the issue since URL-escaping works.
