### ISSUE TITLE
No data points in Grafana when manually configuring InfluxDB retention policy

### ISSUE THREAD

**Issue by xvzup** [kubernetes/heapster#1953]
Hi,

as it is currently not possible to set the InfluxDB retention policy in the Kubernetes manifest, I created a Kubernetes job which sets the retention policy in InfluxDB. The command I am using is:

CREATE RETENTION POLICY one_week ON k8s DURATION 7d REPLICATION 1 DEFAULT

The retention policy is successfully set as it appears when calling SHOW RETENTION POLICIES

However when I connect to Grafana there are no more data points! 

Thank you for your work on heapster!

**Comment by acobaugh** [comment]
The retention policy that heapster writes to is hardcoded to `default`: https://github.com/kubernetes/heapster/blob/d25a176baee4554dc59052785c4ee940fc94d305/metrics/sinks/influxdb/influxdb.go#L214

If you're manually creating your RP, you'll have to name it `default`. Note that this is not the same as the default RP, which is the RP written to when the client does not specify one.
