### ISSUE TITLE
Grafana dashboards are invalid

### ISSUE THREAD

**Issue by tettaji** [kubernetes/heapster#1958]
When building the Grafana image from source, you'll notice that the Cluster and Pods dashboards aren't loaded. The reason being that `cluster.json` and `pods.json` are missing the top `dashboard` object, which was explicitly removed in commit https://github.com/kubernetes/heapster/commit/e960cd47fb14847f642ef275da01726496e7faff

Oddly enough the latest docker image does contain the right json files.

**Comment by DirectXMan12** [comment]
cc @acobaugh
