### ISSUE TITLE
I have installed and run heapsterbut when I open grafana, it show no data point

### ISSUE THREAD

**Issue by yujmo** [kubernetes/heapster#1967]
![qq 20180226172424](https://user-images.githubusercontent.com/23295281/36662688-2a7077c4-1b1a-11e8-9640-85698e186a4e.png)

I will boom

**Comment by DirectXMan12** [comment]
can't really help you without more details about your setup, Heapster logs, etc

**Comment by yujmo** [comment]
root@node1:~# kubectl logs heapster-5c448886d-dpzjc -n kube-system
`168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: dial tcp 192.168.125.223:10255: getsockopt: connection refused
E0227 04:42:05.004917       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: dial tcp 192.168.125.224:10255: getsockopt: connection refused
E0227 04:42:05.006337       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: dial tcp 192.168.125.225:10255: getsockopt: connection refused
I0227 04:42:05.020566       1 influxdb.go:241] Created database "k8s" on influxDB server at "monitoring-influxdb.kube-system.svc:8086"
E0227 04:43:05.001748       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: dial tcp 192.168.125.224:10255: getsockopt: connection refused
E0227 04:43:05.012134       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: dial tcp 192.168.125.225:10255: getsockopt: connection refused
E0227 04:43:05.014361       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: dial tcp 192.168.125.223:10255: getsockopt: connection refused
E0227 04:44:05.021694       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: dial tcp 192.168.125.224:10255: getsockopt: connection refused
E0227 04:44:05.021997       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: dial tcp 192.168.125.225:10255: getsockopt: connection refused
E0227 04:44:05.024203       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: dial tcp 192.168.125.223:10255: getsockopt: connection refused
E0227 04:45:05.008247       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: dial tcp 192.168.125.225:10255: getsockopt: connection refused
E0227 04:45:05.010556       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: dial tcp 192.168.125.223:10255: getsockopt: connection refused
E0227 04:45:05.022405       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: dial tcp 192.168.125.224:10255: getsockopt: connection refused
E0227 04:46:05.011317       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: dial tcp 192.168.125.225:10255: getsockopt: connection refused
E0227 04:46:05.014376       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: dial tcp 192.168.125.224:10255: getsockopt: connection refused
E0227 04:46:05.019240       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: dial tcp 192.168.125.223:10255: getsockopt: connection refused
E0227 04:47:05.002541       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: dial tcp 192.168.125.224:10255: getsockopt: connection refused
E0227 04:47:05.003915       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: dial tcp 192.168.125.225:10255: getsockopt: connection refused
E0227 04:47:05.011263       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: dial tcp 192.168.125.223:10255: getsockopt: connection refused
E0227 04:48:05.005722       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: dial tcp 192.168.125.223:10255: getsockopt: connection refused
E0227 04:48:05.008550       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: dial tcp 192.168.125.224:10255: getsockopt: connection refused
E0227 04:48:05.010068       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: dial tcp 192.168.125.225:10255: getsockopt: connection refused
E0227 04:49:05.016274       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: dial tcp 192.168.125.224:10255: getsockopt: connection refused
E0227 04:49:05.017228       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: dial tcp 192.168.125.223:10255: getsockopt: connection refused
E0227 04:49:05.021759       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: dial tcp 192.168.125.225:10255: getsockopt: connection refused
E0227 04:50:05.001998       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: dial tcp 192.168.125.225:10255: getsockopt: connection refused
E0227 04:50:05.009307       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: dial tcp 192.168.125.224:10255: getsockopt: connection refused
E0227 04:50:05.019225       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: dial tcp 192.168.125.223:10255: getsockopt: connection refused
E0227 04:51:05.007700       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: dial tcp 192.168.125.224:10255: getsockopt: connection refused
E0227 04:51:05.012015       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: dial tcp 192.168.125.225:10255: getsockopt: connection refused
E0227 04:51:05.012498       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: dial tcp 192.168.125.223:10255: getsockopt: connection refused
E0227 04:52:05.011015       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: dial tcp 192.168.125.225:10255: getsockopt: connection refused
E0227 04:52:05.013206       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: dial tcp 192.168.125.224:10255: getsockopt: connection refused
E0227 04:52:05.022190       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: dial tcp 192.168.125.223:10255: getsockopt: connection refused
E0227 04:53:05.003211       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: dial tcp 192.168.125.225:10255: getsockopt: connection refused
E0227 04:53:05.018451       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: dial tcp 192.168.125.224:10255: getsockopt: connection refused
E0227 04:53:05.021221       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: dial tcp 192.168.125.223:10255: getsockopt: connection refused
E0227 04:54:05.003500       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: dial tcp 192.168.125.224:10255: getsockopt: connection refused
E0227 04:54:05.020013       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: dial tcp 192.168.125.225:10255: getsockopt: connection refused
E0227 04:54:05.024419       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: dial tcp 192.168.125.223:10255: getsockopt: connection refused
E0227 04:55:05.007243       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: dial tcp 192.168.125.225:10255: getsockopt: connection refused
E0227 04:55:05.015208       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: dial tcp 192.168.125.223:10255: getsockopt: connection refused
E0227 04:55:05.016165       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: dial tcp 192.168.125.224:10255: getsockopt: connection refused
E0227 04:56:05.005913       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: dial tcp 192.168.125.224:10255: getsockopt: connection refused
E0227 04:56:05.007933       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: dial tcp 192.168.125.225:10255: getsockopt: connection refused
E0227 04:56:05.021608       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: dial tcp 192.168.125.223:10255: getsockopt: connection refused`


this is my  heapster's logs . (*^_^*)

**Comment by yujmo** [comment]
while I change env KUBELET_PORT="--port=10255".
`E0227 05:01:05.014232       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"
E0227 05:02:05.011760       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"
E0227 05:02:05.015159       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"
E0227 05:02:05.015918       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"
E0227 05:03:05.005381       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.224:10255/stats/container/": Post http://192.168.125.224:10255/stats/container/: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"
E0227 05:03:05.007570       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.225:10255/stats/container/": Post http://192.168.125.225:10255/stats/container/: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"
E0227 05:03:05.009288       1 kubelet.go:231] error while getting containers from Kubelet: failed to get all container stats from Kubelet URL "http://192.168.125.223:10255/stats/container/": Post http://192.168.125.223:10255/stats/container/: malformed HTTP response "\x15\x03\x01\x00\x02\x02\x16"`

**Comment by yujmo** [comment]
` root@node1:/etc/kubernetes# curl https://192.168.125.223:10255/stats/container/ -k --cert ssl/node-node1.pem --key ssl/node-node1-key.pem `
`      "working_set": 1998614528,
      "failcnt": 0,
      "container_data": {
       "pgfault": 290569,
       "pgmajfault": 716
      },
      "hierarchical_data": {
       "pgfault": 290569,
       "pgmajfault": 716
      }
     },
     "network": {
      "name": "calid5b47182ebd",
      "rx_bytes": 1133962,
      "rx_packets": 12512,
      "rx_errors": 0,
      "rx_dropped": 2,
      "tx_bytes": 1991637,
      "tx_packets": 12167,
      "tx_errors": 0,
      "tx_dropped": 0,
      "interfaces": [
       {
        "name": "calid5b47182ebd",
        "rx_bytes": 1133962,
        "rx_packets": 12512,
        "rx_errors": 0,
        "rx_dropped": 2,
        "tx_bytes": 1991637,
        "tx_packets": 12167,
        "tx_errors": 0,
        "tx_dropped": 0
       },
       {
        "name": "caliee096b9f5c1",
        "rx_bytes": 147690,
        "rx_packets": 1188,
        "rx_errors": 0,
        "rx_dropped": 2,
        "tx_bytes": 270520,
        "tx_packets": 1305,
        "tx_errors": 0,
        "tx_dropped": 0
       },
       {
        "name": "cali898bec5c12e",
        "rx_bytes": 1978859,
        "rx_packets": 10876,
        "rx_errors": 0,
        "rx_dropped": 2,
        "tx_bytes": 1381159,
        "tx_packets": 12205,
        "tx_errors": 0,
        "tx_dropped": 0
       },
       {
        "name": "cali6d9b6ffb01b",
        "rx_bytes": 402790,
        "rx_packets": 3462,
        "rx_errors": 0,
        "rx_dropped": 0,
        "tx_bytes": 7151304,
        "tx_packets": 4790,
        "tx_errors": 0,
        "tx_dropped": 0
       },
       {
        "name": "calibf7a888fa87",
        "rx_bytes": 3308817,
        "rx_packets": 3796,
        "rx_errors": 0,
        "rx_dropped": 2,
        "tx_bytes": 663839,
        "tx_packets": 3479,
        "tx_errors": 0,
        "tx_dropped": 0
       },
       {
        "name": "cali5ed7e9a2744",
        "rx_bytes": 650615,
        "rx_packets": 7018,
        "rx_errors": 0,
        "rx_dropped": 2,
        "tx_bytes": 12437019,
        "tx_packets": 8249,
        "tx_errors": 0,
        "tx_dropped": 0
       },
       {
        "name": "tunl0",
        "rx_bytes": 1128901543,
        "rx_packets": 373879,
        "rx_errors": 0,
        "rx_dropped": 0,
        "tx_bytes": 794618068,
        "tx_packets": 248147,
        "tx_errors": 0,
        "tx_dropped": 0
       },
       {
        "name": "eth0",
        "rx_bytes": 3684904786,
        "rx_packets": 3339772,
        "rx_errors": 0,
        "rx_dropped": 0,
        "tx_bytes": 977187888,
        "tx_packets": 1758004,
        "tx_errors": 0,
        "tx_dropped": 0
       }
      ],
      "tcp": {.....`

so default heapster is need https

**Comment by yujmo** [comment]
<img width="602" alt="image" src="https://user-images.githubusercontent.com/23295281/36712886-e8847f0c-1bc5-11e8-89bd-a0600f5a4c25.png">


I'm sorry

**Comment by drewboswell** [comment]
I'm having the same problem, how did you solve this? Did you "just" enable kubeletHttps?
