### ISSUE TITLE
New data batch has timestamp before the previous one

### ISSUE THREAD

**Issue by RouR** [kubernetes/heapster#1970]
**Description**

Error in logs - rate_calculator.go:40 New data batch has timestamp before the previous one

> E0301 09:46:31.374766       1 rate_calculator.go:40] New data batch has timestamp before the previous one: new:2018-03-01 09:46:15 +0000 UTC old:2018-03-01 09:46:25 +0000 UTC
> E0301 10:07:23.589411       1 rate_calculator.go:40] New data batch has timestamp before the previous one: new:2018-03-01 10:07:05 +0000 UTC old:2018-03-01 10:07:15 +0000 UTC
> E0301 10:15:51.987528       1 rate_calculator.go:40] New data batch has timestamp before the previous one: new:2018-03-01 10:15:35 +0000 UTC old:2018-03-01 10:15:45 +0000 UTC
> E0301 10:21:20.315539       1 rate_calculator.go:40] New data batch has timestamp before the previous one: new:2018-03-01 10:21:05 +0000 UTC old:2018-03-01 10:21:15 +0000 UTC
> E0301 10:32:42.962842       1 rate_calculator.go:40] New data batch has timestamp before the previous one: new:2018-03-01 10:32:25 +0000 UTC old:2018-03-01 10:32:35 +0000 UTC
> E0301 12:31:21.107895       1 rate_calculator.go:40] New data batch has timestamp before the previous one: new:2018-03-01 12:31:05 +0000 UTC old:2018-03-01 12:31:15 +0000 UTC
> E0301 12:41:20.227160       1 rate_calculator.go:40] New data batch has timestamp before the previous one: new:2018-03-01 12:41:05 +0000 UTC old:2018-03-01 12:41:15 +0000 UTC
> E0301 14:30:06.797398       1 rate_calculator.go:40] New data batch has timestamp before the previous one: new:2018-03-01 14:29:45 +0000 UTC old:2018-03-01 14:29:55 +0000 UTC
> E0301 16:21:23.657295       1 rate_calculator.go:40] New data batch has timestamp before the previous one: new:2018-03-01 16:21:05 +0000 UTC old:2018-03-01 16:21:15 +0000 UTC
> E0301 16:31:24.037091       1 rate_calculator.go:40] New data batch has timestamp before the previous one: new:2018-03-01 16:31:05 +0000 UTC old:2018-03-01 16:31:15 +0000 UTC

**Steps to reproduce:**
Install from https://github.com/kubernetes/heapster

> apiVersion: extensions/v1beta1
> kind: Deployment
> metadata:
>   name: heapster
>   namespace: kube-system
> spec:
>   replicas: 1
>   template:
>     metadata:
>       labels:
>         task: monitoring
>         k8s-app: heapster
>     spec:
>       serviceAccountName: heapster
>       containers:
>       - name: heapster
>         image: k8s.gcr.io/heapster-amd64:v1.4.3
>         imagePullPolicy: IfNotPresent
>         command:
>         - /heapster 
>         - --source=kubernetes
>         - --metric-resolution=5s 
>         - --sink=influxdb:http://monitoring-influxdb.kube-system.svc:8086?db=heapster
> 

> root@MNBL250:~#  lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04.3 LTS
> Release:        16.04
> Codename:       xenial

> root@MNBL250:~# timedatectl
>       Local time: Fri 2018-03-02 15:09:00 UTC
>   Universal time: Fri 2018-03-02 15:09:00 UTC
>         RTC time: Fri 2018-03-02 15:09:00
>        Time zone: Etc/UTC (UTC, +0000)
>  Network time on: yes
> NTP synchronized: yes
>  RTC in local TZ: no

> kubectl version
> Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.0", GitCommit:"925c127ec6b946659ad0fd596fa959be43f0cc05", GitTreeState:"clean", BuildDate:"2017-12-15T21:07:38Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"windows/amd64"}
> Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
> 

**Describe the results you received:**

![image](https://user-images.githubusercontent.com/1227355/36906606-696e5916-1e47-11e8-97ab-704fd4b24e3a.png)

**Describe the results you expected:**

No errors

**Comment by DirectXMan12** [comment]
check the times on your nodes.  Make sure they're all in sync.

**Comment by RouR** [comment]
This was done before open this issue.
Maybe i did it wrong
What do you advise?

**Comment by kawych** [comment]
Similar issue #1988 has been noticed for Stackdriver sink, it may have the same root cause. Waiting for more input there.
