### ISSUE TITLE
Please update your kubernetes vendoring to a release without security issues

### ISSUE THREAD

**Issue by nim-nim** [kubernetes/heapster#1980]
Since all kubernetes clients have just been released due to a CVE, please release an heapster version based on a kubernetes version with the security fix (1.7.14 or 1.8.9 or 1.9.4, 1.9.4 would be the nicest)

**Comment by kawych** [comment]
Probably we should release 1.9.4, #1849 is  bumps it to 1.9.3 and is almost ready.

**Comment by DirectXMan12** [comment]
Are you referring to the subpath volume CVE?  That doesn't affect clients, I believe.
