### ISSUE TITLE
FAIL: TestCreateElasticSearchServiceV2

### ISSUE THREAD

**Issue by Charleslvn** [kubernetes/heapster#1986]
With:
    go 1.9.4 x86_64
    github.com/kubernetes/heapster 1.5.2

Hello, 
I try to build and test your project and it fails with :

> FAIL: TestCreateElasticSearchServiceV2 (0.00s)
> panic: reflect: call of reflect.Value.Int on zero Value [recovered]
>         panic: reflect: call of reflect.Value.Int on zero Value
> 
> goroutine 6 [running]:
> testing.tRunner.func1(0xc4201260f0)
>         /usr/lib/golang/src/testing/testing.go:711 +0x2d4
> panic(0x559913dc3c80, 0xc4200d6720)
>         /usr/lib/golang/src/runtime/panic.go:491 +0x287
> reflect.Value.Int(0x0, 0x0, 0x0, 0x559913aefaa9)
>         /usr/lib/golang/src/reflect/value.go:914 +0x143
> k8s.io/heapster/common/elasticsearch.TestCreateElasticSearchServiceV2(0xc4201260f0)
>         /builddir/build/BUILD/heapster-1.5.2/_build/src/k8s.io/heapster/common/elasticsearch/elasticsearch_test.go:64 +0x715
> testing.tRunner(0xc4201260f0, 0x559913e2cad8)
>         /usr/lib/golang/src/testing/testing.go:746 +0xd2
> created by testing.(*T).Run
>         /usr/lib/golang/src/testing/testing.go:789 +0x2e0
> exit status 2
> FAIL    k8s.io/heapster/common/elasticsearch    0.012s
> 
Could you help me please ?

Thanks

**Comment by DirectXMan12** [comment]
They seem to pass for me, on the master branch.  Please try again with master and go 1.10, and report back if there is still an issue.
