### ISSUE TITLE
Add load metric about a cgroup/container

### ISSUE THREAD

**Issue by andyxning** [kubernetes/heapster#1987]
**Description**
Currently heapster does not collect cgroup/container cpu load metrics. But it seems that cpu load is supported in cAdvisor https://github.com/google/cadvisor/blob/master/utils/cpuload/cpuload.go.

/kind feature

**Comment by DirectXMan12** [comment]
Heapster is now deprecated, so no new features or sinks will be added.  Please see https://github.com/kubernetes/heapster/blob/master/docs/deprecation.md#initial-deprecation-kubernetes-111 for more information.
