### ISSUE TITLE
Heapster sink configuration to influxdb fails when using password variable from kubernetes secret

### ISSUE THREAD

**Issue by dhu041** [kubernetes/heapster#1994]
**Description**

When heapster is configured to log kubernetes cluster monitoring data into influxdb with authentication parameters (username and password) it works. But for security reason I used kubernetes "secret"  instead of writting the heapster user password in plaintext. So the password will be retrieved from kubernetes secret and set as a variable in hepaster sink url. 
The env configuration section for the heapster pod is as follows -

-env: 
- name: heappass
          valueFrom:
          secretKeyRef:
            name: <secret-name>
            key: heapsterpassword
        command:
          - /heapster
          - --source=kubernetes:https://kubernetes.default?auth=/var/lib/kube-proxy/kubeconfig&apiVersion=v1
          - --sink=influxdb:http://localhost:8086?user=heapsteruser&pw=$heappass&db=k8s  

But this doesn´t work and I get the following error message in the container log
          influxdb.go:186] InfluxDB write failed: {"error":"authorization failed"}

Using influx CLI, I can log in to the influx database as the heapsteruser, so I think the problem seems to be specifying the heapster user password as a variable in the sink-url. Can anyone give an idea on how to fix this?

**Describe the results you received:**. 

1 influxdb.go:241] Created database "k8s" on influxDB server at "localhost:8086"    
1 influxdb.go:186] InfluxDB write failed: {"error":"authorization failed"}

**Output of `heapster --version`:**.   

```
1.4.2
```

**Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"8", GitVersion:"v1.8.1", GitCommit:"f38e43b221d08850172a9a4ea785a86a3ffa3b3a", GitTreeState:"clean", BuildDate:"2017-10-11T23:27:35Z", GoVersion:"go1.8.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by DirectXMan12** [comment]
is the shell interpolation being done?  I suspect that's the issue.  I don't think there's anything that'll do shell interpolation unless you explicitly launch a shell which launches Heapster.

**Comment by zhuchenjie** [comment]
I have same problem so...
