### ISSUE TITLE
401 Unauthorized with kubelet https port and readonly disabled

### ISSUE THREAD

**Issue by paphillon** [kubernetes/heapster#2005]
**Description**
Kubelet readonly port is disabled and heapster is configured with below options
--source=kubernetes.summary_api:https://kubernetes.default?kubeletPort=10250&kubeletHttps=true&insecure=true

However, it fails with the below error message. 

E0405 05:11:05.032332       1 summary.go:97] error while getting metrics summary from Kubelet worker01.corp.acme.com(10.51.35.6:10250): request failed - "401 Unauthorized", response: "Unauthorized"

Heapster RBAC is enabled, I have also tried with useServiceAccount=true, but no luck. 

**Steps to reproduce:**
Kubelet configuration:

  --client-ca-file=/etc/kubernetes/kubelet/ca-kubelet.pem \\
  --tls-cert-file=/etc/kubernetes/kubelet/${HOSTNAME}-kubelet.pem \\
  --tls-private-key-file=/etc/kubernetes/kubelet/${HOSTNAME}-kubelet-key.pem \\
  --read-only-port=0 \\
  --cadvisor-port=0 \\

Note: Kubelet has it's own Certificate authority, that is used to generate kubelet server certificates and corresponding client certificates for Api server 

Apiserver:
  --kubelet-certificate-authority=/etc/kubernetes/apiserver/ca-kubelet.pem \\
  --kubelet-client-certificate=/etc/kubernetes/apiserver/${HOSTNAME}-kubelet-client.pem \\
  --kubelet-client-key=/etc/kubernetes/apiserver/${HOSTNAME}-kubelet-client-key.pem \\
  --kubelet-https=true \\

With the above settings, I believe heapster needs kubelet client certificates, however, I don't see any option available in heapster to provide this information.

**Describe the results you received:**

error while getting metrics summary from Kubelet worker01.corp.acme.com(10.51.35.6:10250): request failed - "401 Unauthorized", response: "Unauthorized"

**Output of `heapster --version`:**

```
Heapster version v1.4.2
```

**Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:55:54Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by towolf** [comment]
Had the problem as well, until I found this:

You can add `--authentication-token-webhook` to the kubelet startup flags, such that the Bearer token of Heapster is used for auth and not only client certs.

**Comment by towolf** [comment]
Ah, yes. Sorry. I just found this in my bash history. I had forgotten about it:
`[2018-04-14 15:05:11] kubectl -n kube-system edit clusterrole system:heapster`
