### ISSUE TITLE
grafana setup fails because its not listening on loopback

### ISSUE THREAD

**Issue by kplimack** [kubernetes/heapster#2006]
**Description**
grafana is failing to setup because its listening on its Ip interface, not the loopback.  some other issues say this is fixed, but its not working with the latest version.

```
t=2018-04-06T03:33:20+0000 lvl=info msg="Initializing HTTP Server" logger=http.server address=0.0.0.0:3000 protocol=http subUrl= socket=
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
Can't access the Grafana dashboard. Error: Get http://admin:admin@localhost:3000/api/org: dial tcp: i/o timeout. Retrying after 5 seconds...
```

**Output of `heapster --version`:**

```
        image: k8s.gcr.io/heapster-grafana-amd64:v4.4.3```

**Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.2", GitCommit:"5fa2db2bd46ac79e5e00a4e6ed24191080aa463b", GitTreeState:"clean", BuildDate:"2018-01-18T09:42:01Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}```

**Comment by wenzuowei110** [comment]
same problem
