### ISSUE TITLE
Kafka sink does not recover after Kafka restart

### ISSUE THREAD

**Issue by mikenorgate** [kubernetes/heapster#2017]
**Description**

Heapster is unable to send events to Kafka after the Kafka cluster has been torn down and restarted

**Steps to reproduce:**

- Setup Heapster with a Kafka sink `/heapster --source=kubernetes:https://kubernetes.default --sink=kafka:?brokers=bootstrap.kafka.svc.cluster.local:9092`

- Tear down and restart all pods making the Kafka cluster

**Errors from Heapster logs**

```
W0418 19:37:25.141498       1 manager.go:119] Failed to push data to sink: Apache Kafka Sink
E0418 19:37:26.095386       1 driver.go:55] Failed to produce metric message: failed to produce message to heapster-metrics: cannot fetch metadata. No topics created?
E0418 19:37:27.898317       1 driver.go:55] Failed to produce metric message: failed to produce message to heapster-metrics: cannot fetch metadata. No topics created?
E0418 19:37:29.723280       1 driver.go:55] Failed to produce metric message: failed to produce message to heapster-metrics: cannot fetch metadata. No topics created?
E0418 19:37:31.589612       1 driver.go:55] Failed to produce metric message: failed to produce message to heapster-metrics: cannot fetch metadata. No topics created?
```

**Output of `heapster --version`:**

```
1.4.3
```

**Comment by bartebor** [comment]
The same happens in version `1.5.2`.

**Comment by Kokan** [comment]
Is it possible that it is the same issue as #1672 ?

**Comment by bartebor** [comment]
#1672 looks like a some DNS cache problem, so after IP change it no longer works. It is possible that OP is in this situation because of using cluster DNS.

In my case however there is no IP change ("static" DNS), just broker restart, possibly with some maintenance measures, i.e. topic truncation.

**Comment by mikenorgate** [comment]
I am using cluster DNS so it could well be a DNS cache issue that I am seeing

**Comment by Kokan** [comment]
I think the root cause is simple -in both cases - that in case of error, the connection is not properly re-created. You could see that kind of behavior with other sinks, in case of failure the producer is re-created.

I had a patch, but now it is lost at my former company private gitlab, and probably the core itself moved along also. If you want to address this I could give you more guide, but I do not see that I am going to have time to fix it.
