### ISSUE TITLE
heapster-nanny failed to start results in dashboard failed to start

### ISSUE THREAD

**Issue by JuneZhao** [kubernetes/heapster#2037]
**Description**

**Steps to reproduce:**

**Describe the results you received:**
I need some help you from you guys regarding an error occurred on heapster-nanny container since it blocks dashboard to start:

log of heapster-nanny:
E0428 10:00:02.985241       1 nanny_lib.go:95] Error while querying apiserver for resources: the server has asked for the client to provide credentials (get pods heapster-342135353-8m5xn)
E0428 13:55:48.086484       1 nanny_lib.go:95] Error while querying apiserver for resources: the server has asked for the client to provide credentials (get pods heapster-342135353-8m5xn)
E0428 16:34:46.386532       1 nanny_lib.go:95] Error while querying apiserver for resources: the server has asked for the client to provide credentials (get pods heapster-342135353-8m5xn)
E0428 17:45:30.294490       1 nanny_lib.go:95] Error while querying apiserver for resources: the server has asked for the client to provide credentials (get pods heapster-342135353-8m5xn)
E0428 22:34:42.582481       1 nanny_lib.go:95] Error while querying apiserver for resources: the server has asked for the client to provide credentials (get pods heapster-342135353-8m5xn)
E0428 23:11:08.437273       1 reflector.go:315] k8s.io/contrib/addon-resizer/nanny/kubernetes_client.go:108: Failed to watch *v1.Node: the server has asked for the client to provide credentials (get nodes)
E0428 23:32:03.772933       1 nanny_lib.go:95] Error while querying apiserver for resources: the server has asked for the client to provide credentials (get pods heapster-342135353-8m5xn)

log for container of  heapster:
I0420 03:29:52.957828       1 handlers.go:215] No metrics for pod default/vistamicroservices-3080061194-1p86h
E0420 03:33:05.000330       1 summary.go:389] Node k8s-master-3688e46e-0 is not ready
E0420 03:34:05.000259       1 summary.go:389] Node k8s-master-3688e46e-0 is not ready
E0420 03:35:05.000557       1 summary.go:389] Node k8s-master-3688e46e-0 is not ready
E0420 03:36:05.000303       1 summary.go:389] Node k8s-master-3688e46e-0 is not ready
E0420 03:41:05.000354       1 summary.go:389] Node k8s-agent-3688e46e-4 is not ready
E0420 03:41:05.000383       1 summary.go:389] Node k8s-agent-3688e46e-1 is not ready
E0420 03:41:05.000400       1 summary.go:389] Node k8s-master-3688e46e-2 is not ready
I0420 03:41:28.062581       1 handlers.go:264] No metrics for container jhipster-registry in pod default/jhipster-registry-610758079-7kf16
I0420 03:41:28.062608       1 handlers.go:215] No metrics for pod default/jhipster-registry-610758079-7kf16
I0420 03:41:29.382635       1 handlers.go:264] No metrics for container vistamicroservices in pod default/vistamicroservices-3080061194-1p86h
I0420 03:41:29.382694       1 handlers.go:215] No metrics for pod default/vistamicroservices-3080061194-1p86h

It shows this  error even after a reboot of the container:

kubectl exec heapster-342135353-8m5xn -n kube-system -c heapster-nanny reboot

apiserver pod shows below:
10:19 AM Victor Pachas: C:\Users\victor.pachas> kubectl logs kubernetes-dashboard-924040265-068vg -n kube-system
Using HTTP port: 8443
Using in-cluster config to connect to apiserver
Using service account token for csrf signing
No request provided. Skipping authorization header
Successful initial request to the apiserver, version: v1.7.7
No request provided. Skipping authorization header
Creating in-cluster Heapster client
Could not enable metric client: Health check failed: an error on the server ("unknown") has prevented the request frucceeding (get services heapster). Continuing.

It was deployed with azure container service-K8S on version 1.7.7.

**Describe the results you expected:**

**Output of `heapster --version`:**

**Output of `kubectl version`:**
v1.7.7

```
(paste your output here)
```

**Comment by JuneZhao** [comment]
@kubernetes/sig-azure-bugs

**Comment by JuneZhao** [comment]
@kubernetes/sig-scalability-bugs

**Comment by DirectXMan12** [comment]
Sounds like you haven't correctly set of the auth for the nanny.  Does the service account have the right permissions, etc?

**Comment by JuneZhao** [comment]
@DirectXMan12  how can we check that, it is managed  by azure, i dont know where to check

**Comment by DirectXMan12** [comment]
`kubectl get roles` and `kubectl get rolebindings`.  Please read up on cluster roles in the official Kubernetes documentation
