### ISSUE TITLE
Grafana do not have cluster and pods dashboards after I build a new docker image

### ISSUE THREAD

**Issue by owenJiao** [kubernetes/heapster#2039]
I tried to build a new grafana image, when I ran it in a pod, the status of this pod is running ,but when I opened the browser, I found there were not pod and cluster list in dashboards, and I checked the log, there 
is  no error message showed in log file. so could you  tell me where I should notice?

**Comment by ttarczynski** [comment]
Is it maybe the same issue as #2013 ?

**Comment by SFHfeihong** [comment]
I have same problem. The version of  grafana  is v5.0.4.

**Comment by wu105** [comment]
For new clusters installations getting grafana v5.0.4, the grafana does not provide any pre-loaded dashboards.   With grafana v4.4.3 we used previuosly, dashboards cluster and pod are pre-loaded.  

Our work around is to save the dashboards from clusters that do have the cluster and pod dashboards as json files, and import them into the new cluster's grafana.    

New heapster versions should continue to include clulster and pod as built in dashboard as earlier versions.  If someone knows good  dashboards for kubernetes on grafana.com, please share with us.  I tried quite a few and still prefer the cluster and pod dashboards.

**Comment by wu105** [comment]
compared with  #2013, this thread points an issue showed up between v4.4.3 and v5.0.4 and contains a workaround by saving the dashboards from clusters that do have the cluster and pod dashboards as json files, and import them into the new cluster's grafana.
