### ISSUE TITLE
Error pulling heapster-influxdb-amd64:v1.5.2

### ISSUE THREAD

**Issue by dsemarketer** [kubernetes/heapster#2059]
docker pull k8s.gcr.io/heapster-influxdb-amd64:v1.5.2

Pulling repository k8s.gcr.io/heapster-influxdb-amd64
unauthorized: authentication required

**Comment by amihura** [comment]
`Failed to pull image "k8s.gcr.io/heapster-influxdb-amd64:v1.5.2": rpc error: code = Unknown desc = Error response from daemon: manifest for k8s.gcr.io/heapster-influxdb-amd64:v1.5.2 not found`

**Comment by dionmes** [comment]
Same here.

**Comment by borisding1994** [comment]
Same here.

**Comment by nanno77** [comment]
Same here.

**Comment by Joshscorp** [comment]
same here

**Comment by Mechtecs** [comment]
Same here.

**Comment by mingweiLIU** [comment]
Same here.

**Comment by kithral** [comment]
Same - Tags Available

v1.1.1 and v1.3.3

**Comment by modernix** [comment]
Same here.

**Comment by Tizeen** [comment]
Same here.

**Comment by divyangjp** [comment]
`v1.5.2` is not available on Google container registry. Using `v1.3.3.` made it work.
