### ISSUE TITLE
Cpu/usage - what does it mean 'cumulative'?

### ISSUE THREAD

**Issue by jakubbujny** [kubernetes/heapster#2062]
I found in metrics documentation: https://github.com/kubernetes/heapster/blob/master/docs/storage-schema.md
that cpu/usage metric is "Cumulative CPU usage on all cores.". I want to understand better that sentence because actually for me cumulative means:
I first second pod consumed 30 milicores + in second 40 milicores + in third 80 milicores + ... + in sixtieth X milicores so cumulative CPU usage says me: 30+40+80+...+X = Y, if my metrics resolution is set to 60s

Actually what I'm observing in measurements are some ridiculous numbers like:
07/10/18 11:06:00PM 4047611667776
07/10/18 11:07:00PM 4048010937744
07/10/18 11:08:00PM 4048542631034

When I'm calculating the diff it comes that my pod consumed between 11:06 and 11:07 399269968 milicores what is about 399269 vCores - I'm running in AWS so it means that I actually need about 4160  m5.24xlarge instance and I'm paying for that about 20k$ per hour what actually is not truth.

Could you explain my what's wrong in my considerations? Or I just discovered some bug? I have about 100 pods running on quite small k8s cluster and cpu/usage for all looks quite strange, as described.

**Comment by avgKol** [comment]
Here is an explanation for "Cumulative CPU usage on all cores" 

https://github.com/kubernetes/dashboard/issues/1010#issuecomment-324632866

**Comment by jakubbujny** [comment]
I'm sorry but with that description I still don't know how to interpret such big numbers which I'm observing. Should I report bug?

**Comment by DirectXMan12** [comment]
CPU usage (i.e. not `cpu/usage_rate`) is measured over time -- it's the amount of time that the process was running on the given processor, so if your pod was running for at 500 millicores for 2 seconds, you'd have a usage of 1 second.  IIRC, usage is actually measured here in nanoseconds, so large numbers are reasonable  If you're seeing this on `usage_rate`, then you have an issue.

**Comment by jakubbujny** [comment]
Now it makes perfect sense - thank you! I looked on graphs, calculated non negative derivative and compared to usage_rate and it's totally fine. Please consider placing that information in documentation/readme - especially that it's actually CPU time metric like those from Linux kernel from /proc/stat in [nanoseconds]

**Comment by DirectXMan12** [comment]
I'd be happy merge a PR with that documentation update, since, yeah, that's poorly worded.  In general, though, we're in the process of deprecating Heapster, and the replacements have working that make it a bit more obvious, IMO

**Comment by jakubbujny** [comment]
@DirectXMan12 - ready to merge :)
