### ISSUE TITLE
Grafana displays the pods which have been deleted long ago

### ISSUE THREAD

**Issue by SFHfeihong** [kubernetes/heapster#2066]
k8s version: 1.9.3
heapster version: 1.4.2
influxdb version: 1.3.3
grafana version: 4.4.3

Problem：Grafana displays the pods which have been deleted long ago

![vm_km _q1 726 amx34s2hn](https://user-images.githubusercontent.com/27404167/42867452-3c8bd654-8aa2-11e8-8bbf-ab4ad6217d33.png)

**Comment by DirectXMan12** [comment]
cc @andyxning @acobaugh

**Comment by andyxning** [comment]
This is the desired result, imo. As all the metrics data are stored in influxdb. If the data was not deleted from influxdb in a retention policy interval, it should be visible to end users.

**Comment by SFHfeihong** [comment]
Based on https://github.com/kubernetes/heapster/issues/1179, I have deal with it successfully. Thank you!!
