### ISSUE TITLE
Changing container names -> series growth

### ISSUE THREAD

**Issue by mtsgrd** [kubernetes/heapster#2067]
I don't think I have the right terminology to even describe this accurately, but I am running a K8s cluster on AWS (kops + CoreOS). I have a pretty standard heapster + influxdb + grafana setup to monitor my containers.

The problem is that after a few weeks my influxdb instance starts crashing because of memory pressure. This is because the series count in the k8s db grows beyond ~300k. What I notice is that every minute I see new series with container names like related to `system.slice`.

Dumping all the series names using `influx -host monitoring-influxdb.kube-system -database k8s -execute 'show series'`, I constantly see new entries like the following.

```
$> diff series-2018-07-19-1.txt series-2018-07-19-2.txt | grep page_faults
> memory/major_page_faults,cluster_name=default,container_name=system.slice/system-sshd.slice/sshd@159782-172.20.98.153:22-218.65.30.43:53064.service,nodename=ip-172-20-98-153.eu-west-1.compute.internal,type=sys_container
> memory/page_faults,cluster_name=default,container_name=system.slice/system-sshd.slice/sshd@159782-172.20.98.153:22-218.65.30.43:53064.service,nodename=ip-172-20-98-153.eu-west-1.compute.internal,type=sys_container
```

These series were created because the `id` in `...sshd@[id]` changes. Would anyone be able to help me understand what this id is, and what part of my setup causes these to change?

**Comment by DirectXMan12** [comment]
I'd guess those are pseudo-containers (cgroup hierarchies) being created by systemd, and cadvisor is picking up on those and exporting them.

cc @acobaugh @andyxning

**Comment by mtsgrd** [comment]
Any help would be appreciated. It was 4 days since I last checked, and in this time the number of series has grown by 60k(!)

**Comment by acobaugh** [comment]
There wouldn't be anything you could do with influxdb. You could probably write a continuous query to drop points that match a certain pattern, or just throw something into cron.

A properly tuned influxdb system should be able to handle at least a million series, likely 10's of millions. Are the additional series causing an issue for you?

Make sure you have an RP configured to bound the series growth in time. If you have a k8s cluster with a lot of churn, you may need to make this very short.
