### ISSUE TITLE
Multiple Deployment Errors

### ISSUE THREAD

**Issue by Queuecumber** [kubernetes/heapster#2072]
**Description**

I have multiple problems when deploying after following the instructions found on the wiki (and elsewhere).

Using the exact steps in the wiki I get the following error message in the heapster log (along with a similar one for *v1.Node)

```
k8s.io/heapster/metrics/heapster.go:328: Failed to list *v1.Pod: Get https://kubernetes.default/api/v1/pods?resourceVersion=0: dial tcp: lookup kubernetes.default on 10.0.100.10:53: no such host
```

According to my understanding of kubernetes, looking up `kubernetes.default` from inside a pod *should* be working but it isn't. When I replace the `--source` argument with the fully qualified domain name `https://kubernetes.default.svc.cluster.local` then lookup succeeds. 

After making this change and redeploying, however, I get the following error

```
Error in scraping containers from kubelet:192.168.122.188:10255: failed to get all container stats from Kubelet URL "http://192.168.122.188:10255/stats/container/": Post http://192.168.122.188:10255/stats/container/: dial tcp 192.168.122.188:10255: getsockopt: connection refused
```

I have deployed the RBAC configuration for heapster, my setup commands were:

```
kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/v1.5.3/deploy/kube-config/influxdb/influxdb.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/v1.5.3/deploy/kube-config/rbac/heapster-rbac.yaml
kubectl apply -f https://raw.githubusercontent.com/kubernetes/heapster/v1.5.3/deploy/kube-config/influxdb/heapster.yaml
```

The cluster was deployed with kubeadm, the coredns configuration is

```
:53 {
    errors
    health
    kubernetes cluster.local in-addr.arpa ip6.arpa {
       pods insecure
       upstream
       fallthrough in-addr.arpa ip6.arpa
    }
    prometheus :9153
    proxy . /etc/resolv.conf
    cache 30
    reload
}
```

The network uses kube-router with cni config

```
{
  "name":"kubernetes",
  "type":"bridge",
  "bridge":"kube-bridge",
  "isDefaultGateway":true,
  "ipam": {
    "type":"host-local"
  }
}
```

Please let me know if I can provide any more information to diagnose

**Output of `heapster --version`:**

Not sure how to do this, the heapster container doesn't provide a shell that I know of. The image version pulled in the yaml file is v1.5.3

**Output of `kubectl version`:**

```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by DirectXMan12** [comment]
Generally, when Heapster can't connect to your nodes, it's a problem with your networking set.  More specifically, certain networking vendors don't allow pods to connect to node IPs by default, and you have to manually allow it.  Unfortunately, there's not much advice I can provide here, since it's highly specific to your networking setup.

**Comment by Queuecumber** [comment]
Sorry I'm not sure what you mean by networking vendor, I'm not doing anything non-standard here it's a bare metal install on a VM running on my laptop for evaluation purposes.

**Comment by Queuecumber** [comment]
I should also point out that its a single-node cluster in theory packets shouldnt even be leaving the machine, I'm not sure how a network vendor would be relevant

**Comment by Queuecumber** [comment]
So there were actually a couple of things going wrong but it is worth pointing out that heapster requires kubelet to have its readOnlyPort set to 10255. Kubeadm does not provide an easy way to do this with its config file, but you can instead update /etc/default/kubelet to set KUBELET_EXTRA_ARGS=--read-only-port 10255

**Comment by DirectXMan12** [comment]
> So there were actually a couple of things going wrong but it is worth pointing out that heapster requires kubelet to have its readOnlyPort set to 10255

Alternatively, you can just tell Heapster not to use the read-only port.  There's flags on the source to do this -- see https://github.com/kubernetes/kubernetes/pull/65102.

Sorry for the initially terse response -- we end up getting a lot of issues that boil down to "My CNI plugin/overlay network blocks pod<->communication out of the box".

**Comment by Queuecumber** [comment]
Yeah that looks perfect, it's too bad it requires a source change to work. Probably the default should be to use the secure port for everything right?

**Comment by DirectXMan12** [comment]
It's been the default in at least a couple of distros for a while now, but hasn't been in kubernetes for various reasons.  It'll be the default in metrics-server soon.
