### ISSUE TITLE
Graphite sink reports filesystem metrics for different POD volumes in same timeseries/metric

### ISSUE THREAD

**Issue by chrbayer84** [kubernetes/heapster#2076]
**Description**

Graphite sink reports filesystem metrics for different POD volumes in same timeseries/metric. When using the Graphite sink the POD-level metrics for filesystems don't report individual metrics for different volumes. Instead, the one metric for the POD filesystem/[usage, availability, limit] contains randomly interleaved values for the different volumes. See screenshot (tooltip):
<img width="1363" alt="grafana_-_um_-_kubernetes_heapster" src="https://user-images.githubusercontent.com/773005/43312139-b262e520-918c-11e8-82d0-87ac3e608d45.png">
```
[root@carbonj-p1-0 /]# df -h
Filesystem      Size  Used Avail Use% Mounted on
overlay         173G  8.4G  157G   6% /
tmpfs            64M     0   64M   0% /dev
tmpfs            15G     0   15G   0% /sys/fs/cgroup
/dev/xvdbb      4.9T  2.9T  2.0T  60% /data
/dev/xvda9      173G  8.4G  157G   6% /conf
shm              64M     0   64M   0% /dev/shm
tmpfs            15G   12K   15G   1% /run/secrets/kubernetes.io/serviceaccount
tmpfs            15G     0   15G   0% /proc/scsi
tmpfs            15G     0   15G   0% /sys/firmware
```

It seems that one of 15G tmpfs is reported as well as the mounted volume. The root disk is not reported (which is correct behavior). I assume that the 15G volume is my config map that's mounted as a volume.

**Steps to reproduce:**
Create a POD with at least two volume mounts and hook up Heapster to a Graphite sink. Query metric `nodes.*.pods.<namespace>.<pod>.filesystem.available`

**Describe the results you received:**
One time series with data for two distinct metrics reporting in the same series

**Describe the results you expected:**
Multiple different series, one per filesystem

**Output of `heapster --version`:**

```
version: v1.3.0
commit: abbfe6e0
```

**Output of `kubectl version`:**

```
Kubernetes v1.5.3+coreos.0
```

**Comment by DirectXMan12** [comment]
@jsoriano @theairkit
