### ISSUE TITLE
heapster version is not bumped heapster-1.5.4 tag.

### ISSUE THREAD

**Issue by chakravarthy392** [kubernetes/heapster#2077]
Whenever a new tag releases , hepaster version would be bumped to that latest version in `Makefile` and some other `yaml` files (`deploy/kube-config/google/heapster.yaml` , `deploy/kube-config/google/heapster.yaml` , etc ...). But for 1.5.4 version the heapster version is remained as 1.5.3 in those files.

**Steps to reproduce:**
1.Install and export go
2.go get github.com/tools/godep
3.cd $HOME/src/k8s.io/
4.git clone https://github.com/kubernetes/heapster.git
5.cd heapster
6.git checkout tags/v1.5.4
7.cd $HOME/src/k8s.io/heapster
8.make 
**Describe the results you received:**
Installation is successful but old version of Heapster (1.5.3) is getting installed.

**Describe the results you expected:**
Heapster version should be displayed as 1.5.4

**Output of `heapster --version`:**

```
version: v1.5.3
```

**Comment by 007** [comment]
See https://github.com/kubernetes/heapster/issues/1917 but realize you probably shouldn't bother with new versions of heapster and should invest your time in implementing prometheus or similar.

**Comment by chakravarthy392** [comment]
@007 They have been mentioning that Heapster is depreciated from last 3 months but released a latest version to fix some issues. The latest version is not even updated in Makefile. So I just want to know if 1.5.4 is only getting installed even though it shows 1.5.3 as version !!
