### ISSUE TITLE
did not create cluster, pods dashboard in grafana

### ISSUE THREAD

**Issue by Hokwang** [kubernetes/heapster#2090]
**Description**

I guess there's no problem in heapster, influxdb, grafana,
and kubernetes/dashboard can show CPU, memory graphs
but grafana does not show cluster, pods dashboard after pod running.

**Steps to reproduce:**
I am in corporate proxy env. and use kubeadm for kubernetes cluster.
and using alternative dashboard and nginx-ingress.

'# kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/master/src/deploy/alternative/kubernetes-dashboard.yaml
'# kubectl create -f dashboard-admin.yaml
'# kubectl create -f dashboard-ingress.yaml

'# vi /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
Environment="KUBELET_CONFIG_ARGS=--config=/var/lib/kubelet/config.yaml --read-only-port=10255"
(adding read-only-port)
'# systemctl daemon-reload; systemctl restart kubelet

'# git clone https://github.com/kubernetes/heapster.git
'# vi heapster/deploy/kube-config/influxdb/grafana.yaml
'- name: GF_SERVER_ROOT_URL
  value: /grafana
(editing value to /grafana)
'# kubectl create -f heapster/deploy/kube-config/influxdb/
'# kubectl create -f heapster/deploy/kube-config/rbac/heapster-rbac.yaml
'# kubectl create -f grafana-ingress.yaml

**Describe the results you received:**
can see CPU, memory graph in dashboard 
but can not see any dashboard in grafana

**Describe the results you expected:**
can see CPU, memory graph in dashboard 
also can see cluster, pods dashboard in grafana automatically

**Output of `heapster --version`:**
heapster-amd64:v1.5.4

**Output of `kubectl version`:**
'# kubectl version --short
Client Version: v1.11.2
Server Version: v1.11.2

I guess there's no error messages in any pods.
If you need more logs, please let me know.

**Comment by Hokwang** [comment]
I tried to use 1.10.7 and 1.9.10, but there's problem still.

and I tried to do not use ingress, so use NodePort, but problem still exists.

I want to know how grafana create dashboard automatically 
and can anybody tell me a normal log for that?

**Comment by lixianyang** [comment]
I have the same issue
image version:
heapster-grafana-amd64:v5.0.4
heapster-influxdb-amd64:v1.5.2
heapster-amd64:v1.5.4

**Comment by Hokwang** [comment]
@DirectXMan12 can you comment anything? I need some help.

**Comment by DirectXMan12** [comment]
unfortunately, I'm not super-familiar with the grafana setup.  Are there any logs in the grafana pod?
