### ISSUE TITLE
Can't load data

### ISSUE THREAD

**Issue by nlamirault** [kubernetes/heapster#22]
i setup Heapster in a Kubernetes cluster with an Influxdb backend and Grafana like in the README.
I can log into Grafana using admin/admin and into the InfluxDB UI using root/root.
In Grafana UI i've got this error : 

```
InfluxDB Error : Clouldn't look up columns
```

In the InfluxDB UI, i click "Explore Data" for the *k8s* database, and i try this request :+1: 

```
select * from /.*/ limit 1
```

And i've got an error message : 

```
ERROR : Clouldn't look up columns
```

**Comment by mwielgus** [comment]
Obsolete.
