### ISSUE TITLE
Handle duplicate events

### ISSUE THREAD

**Issue by saad-ali** [kubernetes/heapster#224]
If an event watch fails, then heapster automatically restarts the watch. But it firsts re-lists which causes all events that Kubernetes API Server is aware of to be re-fetched. Today theses events are just re-pushed to the sinks, resulting in duplicate events.

If the event watch gets stuck in a crash loop, this could result in tons of duplicate events being created in the sinks.

Suggestions to prevent this from happening:
* Shorterm: Create an in-memory cache tracking all previously seen event UIDs. If an event is seen again, it should be dropped and not sent to the sinks.
* Longterm: Persist this event UID cache to disk (consider using LevelDB), so that if the heapster binary restarts, it still does not create duplicates.
  * For GCE the backing volume could be a persistent disk, so that even if the heapster pod is killed and recreated on another minion, it still retains its memory and does not push duplicates to sinks.

**Comment by piosz** [comment]
Currently there is no way to export the same event twice, however it is possible to miss some of them. Closing in favor of new issue.
