### ISSUE TITLE
Add a Elasticsearch Sink

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#227]
Elasticsearch is well suited for handling events. It might be useful for metrics as well, but not a priority. Kubernetes runs a ELK setup by default.

**Comment by rohitsardesai83** [comment]
I am interested in contributing towards this. Do let me know I can pick this up . Thanks !

**Comment by piosz** [comment]
PR in flight #733

**Comment by huangyuqi** [comment]
thanks @piosz 
I will rebase #733 , and fix it.

**Comment by piosz** [comment]
Thanks @huangyuqi. Looking forward for you change.

**Comment by djsly** [comment]
HI @huangyuqi , we are also interested in the this PR. We though it was dead and planned in trying to see how easy it was to bring it back to life. Happy to see that you are back. Looking forward to this change!

**Comment by titilambert** [comment]
Hello !
@huangyuqi I don't know if you already started the work, but due to my job deadlines, I need it quickly.
So, I started the merge for ES sink from your commits.
It's here: https://github.com/titilambert/heapster/tree/sink_es
Events are working. Metrics and tests are missing...

**Comment by titilambert** [comment]
PR created here: https://github.com/kubernetes/heapster/pull/1144

**Comment by huangyuqi** [comment]
I will update the PR #733 today
BTW, @titilambert , in PR #1144 , you can cherry-pick my commit .

**Comment by titilambert** [comment]
@huangyuqi It seems I was not clear. I already did the job: I cherry-pick your commits and I merge it in 2 commits and create PR #1144.
It just missing the metrics parts (which is not really useful... generally people use influxDB for metrics)
You can rebase on PR #1144, before adding your changes, in order to avoid to redo the done work...

**Comment by huangyuqi** [comment]
@piosz I have done the ES sink in #733, please review.

**Comment by piosz** [comment]
#733 is merged.
