### ISSUE TITLE
Push node metrics with node labels

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#240]
As of now node metrics that are pushed with container name "/" do not contain node labels.

**Comment by EranGabber** [comment]
I prefer that node metrics will be easily distinguishable from container metrics.
Do you plan to have the node label as the "hostname" or somewhere else?
I suggest that node metrics will have an empty container name (instead of "/").

**Comment by vishh** [comment]
Good idea! Another possible approach will be to add another label called
'type' that will refer to the kind of object a given metrics belongs to.
The 'type' can be 'Container', 'Pod', 'Node', 'Replication Controller',
etc. WDYT?

**Comment by EranGabber** [comment]
The 'type' label is a much better idea. In this way you can have different label names for different resource types, and you could simply omit labels that do not make sense for the particular resource.

**Comment by vishh** [comment]
Awesome.

**Comment by piosz** [comment]
closing in favor of #1133
