### ISSUE TITLE
export list of metric names

### ISSUE THREAD

**Issue by EranGabber** [kubernetes/heapster#241]
The (cluster-insight data collector)[https://github.com/google/cluster-insight] should annotate elements in the context graph with the query parameters for fetching the corresponding Heapster data from InfluxDB or GCM. The most robust way of producing the query parameters is for Heapster to provide the list of metric names it exports to either backend, and an indication which backend (InfluxDB or GCM) is currently active. For InfluxDB, Heapster should include the host IP and port or host name and port of the InfluxDB instance it is writing to. Preferably it should also export the name of the InfluxDB database that contains the metrics.

**Comment by DirectXMan12** [comment]
I'm not certain we want to do this, and there hasn't been any movement on this for a while now.
