### ISSUE TITLE
Improve Heapster/CoreOS documentation

### ISSUE THREAD

**Issue by krancour** [kubernetes/heapster#259]
Any chance of more complete documentation and unit files for the "various components" mentioned here?

https://github.com/GoogleCloudPlatform/heapster/blob/master/docs/coreos.md#unit-files-for-the-various-components

**Comment by vishh** [comment]
Good suggestion. I will add a more detailed guide once I get some spare
cycles.

**Comment by piosz** [comment]
Out of the scope of the project - only Kubernetes deployments are supported. See more details: https://github.com/kubernetes/heapster/blob/master/docs/proposals/vision.md
