### ISSUE TITLE
Heapster does not get the data pulled from the kubernetes source

### ISSUE THREAD

**Issue by biswars** [kubernetes/heapster#277]
I am using Heapster on Kubernetes but getting the following errors repeatedly. Can I get some help what might be the cause of it ?

E0505 10:58:17.112286       6 reflector.go:115] Failed to list *api.Node: the server could not find the requested resource

I have done the following analysis but yet to resolve it. Appreciate good help on this.

Analysis:
Kuberenetes version used 0.16 and the cluster is up and running and I can list down the minions.
I can log in to the influxDB with port 8083 and able to get two empty DBs grafana and K8s.
I don's see any error in the apiserver logs
Kubelet - keeps giving the following error (which I think can be ignored but not sure though)

May 05 11:48:59 core-02 kubelet[1125]: I0505 11:48:59.474012    1125 container.go:242] Failed to update stats for container "/system.slice/docker-71396fb64906817513a0f59d6b9f70c19f8601bb22aea451be44a75f5ac550f4.scope": failed to read stat from "/sys/class/net/statistics/rx_bytes" for device "", continuing to push stats

May 05 11:41:23 core-02 kubelet[1125]: E0505 11:41:23.848334    1125 reflector.go:158] watch of *api.Pod ended with: very short watch

May 05 10:24:19 core-02 kubelet[1125]: E0505 10:24:19.193859    1125 reflector.go:158] watch of *api.Service ended with: unexpected end of JSON input

**Comment by vishh** [comment]
Can you post heapster logs and some information about your kubernetes setup? Are you running on GCE or bare-metal? How have you set up networking?

**Comment by biswars** [comment]
Here is the Heapster log:
/opt/bin/kubectl log monitoring-heapster-controller-9ihq3
2015-05-06T07:09:23.181452490Z + EXTRA_ARGS=
2015-05-06T07:09:23.181452490Z + '[' '!' -z --kubernetes_version=v1beta3 ']'
2015-05-06T07:09:23.181452490Z + EXTRA_ARGS=--kubernetes_version=v1beta3
2015-05-06T07:09:23.181452490Z + '[' '!' -z 10.100.0.1 ']'
2015-05-06T07:09:23.181452490Z + EXTRA_ARGS='--kubernetes_master 10.100.0.1:80 --kubernetes_version=v1beta3'
2015-05-06T07:09:23.181452490Z + HEAPSTER=/usr/bin/heapster
2015-05-06T07:09:23.181452490Z + case $SINK in
2015-05-06T07:09:23.181452490Z + HEAPSTER='/usr/bin/heapster --sink influxdb'
2015-05-06T07:09:23.181452490Z + '[' '!' -z 10.100.0.1 ']'
2015-05-06T07:09:23.181452490Z + INFLUXDB_ADDRESS=
2015-05-06T07:09:23.181452490Z + '[' '!' -z 10.100.44.240 ']'
2015-05-06T07:09:23.181452490Z + INFLUXDB_ADDRESS=10.100.44.240:80
2015-05-06T07:09:23.181452490Z + /usr/bin/heapster --sink influxdb --sink_influxdb_host 10.100.44.240:80 --kubernetes_master 10.100.0.1:80 --kubernetes_version=v1beta3
2015-05-06T07:09:24.244084682Z I0506 07:09:24.213734       8 heapster.go:45] /usr/bin/heapster --sink influxdb --sink_influxdb_host 10.100.44.240:80 --kubernetes_master 10.100.0.1:80 --kubernetes_version=v1beta3
2015-05-06T07:09:24.244084682Z I0506 07:09:24.242699       8 heapster.go:46] Heapster version 0.10.0
2015-05-06T07:09:24.252171510Z I0506 07:09:24.249727       8 kube.go:237] Using Kubernetes client with master "http://10.100.0.1:80" and version v1beta3
2015-05-06T07:09:24.252171510Z I0506 07:09:24.249780       8 kube.go:238] Using kubelet port "10250"
2015-05-06T07:09:24.252171510Z I0506 07:09:24.250028       8 driver.go:164] Using influxdb on host "10.100.44.240:80" with database "k8s"
2015-05-06T07:09:24.551762140Z E0506 07:09:24.532776       8 reflector.go:115] Failed to list *api.Node: the server could not find the requested resource
2015-05-06T07:09:24.551867724Z E0506 07:09:24.544043       8 driver.go:175] Database creation failed: Post http://10.100.44.240:80/db?u=root&p=root: net/http: transport closed before response was received. Retrying after 30 seconds
2015-05-06T07:09:25.541940354Z E0506 07:09:25.541854       8 reflector.go:115] Failed to list *api.Node: the server could not find the requested resource
2015-05-06T07:09:26.568185275Z E0506 07:09:26.550427       8 reflector.go:115] Failed to list *api.Node: the server could not find the requested resource
2015-05-06T07:09:27.562186149Z E0506 07:09:27.561886       8 reflector.go:115] Failed to list *api.Node: the server could not find the requested resource
2015-05-06T07:09:28.570102593Z E0506 07:09:28.569595       8 reflector.go:115] Failed to list *api.Node: the server could not find the requested resource
2015-05-06T07:09:29.576157889Z E0506 07:09:29.575924       8 reflector.go:115] Failed to list *api.Node: the server could not find the requested resource
2015-05-06T07:09:30.582672970Z E0506 07:09:30.582291       8 reflector.go:115] Failed to list *api.Node: the server could not find the requested resource
2015-05-06T07:09:31.589976589Z E0506 07:09:31.589723       8 reflector.go:115] Failed to list *api.Node: the server could not find the requested resource
2015-05-06T07:09:32.596224621Z E0506 07:09:32.595927       8 reflector.go:115] Failed to list *api.Node: the server could not find the requested resource
2015-05-06T07:09:33.606609261Z E0506 07:09:33.606137       8 reflector.go:115] Failed to list *api.Node: the server could not find the requested resource
2015-05-06T07:09:34.616152119Z E0506 07:09:34.615970       8 reflector.go:115] Failed to list *api.Node: the server could not find the requested resource
2015-05-06T07:09:35.648468652Z E0506 07:09:35.647990       8 reflector.go:115] Failed to list *api.Node: the server could not find the requested resource

Kubernetes Setup:
Version - v0.16.0-1-gfc76242f4afd2c
Network Set up - Test set up with virtual box's NAT (not GCE). Kubernetes set up is done with private etcd discovery and post set up able to list the minions and also able to run pods. Able to access the minions from the host system and able to access cadvisor at port 4194

yaml files used: https://github.com/GoogleCloudPlatform/heapster.git commit -e3b3b0584de41e1da1d58c9b8b99313ee0812f4d 

Let me know if any further info needed on this.

**Comment by vishh** [comment]
The issue is this flag `--kubernetes_version=v1beta3`. I removed it on
HEAD. Can you retry with configs from latest HEAD? Sorry for the trouble!

**Comment by biswars** [comment]
Thanks for all your responses so far; much appreciated. In fact, the flag issue of --kubernetes_version=v1beta3 was observed and that was the reason to settle to a working version for this set up. Also, had done some testing by copying the heapster binary from the docker container and running without the flag that resulted in some other error. But I can confirm this back exactly on the error once I am back to my working network after few hours from now.

Before that (sorry but since it seems I am into a different time zone, so taking some feedback early), could you let me know which version of kubernetes, coreos, etcd (private discovery or clustered) and heapster (you have already mentioned to try from the latest) you have run the set up successfully ? So that I can straight away work on that and confirm you back.

**Comment by vishh** [comment]
I would recommend picking up a kubernetes release from kubernetes repo and
using the heapster version built into that. Every kubernetes release runs a
version of heapster by default and I would suggest sticking to that.

**Comment by biswars** [comment]
When checked on the heapster repo, I did not observe any update as mentioned by you (on the flag change). This perfectly makes sense as the flag is set inside the docker image "kubernetes/heapster:v0.11.0" in order to run as container. But When I run the pods & services using the config files from HEAD, I still get the flag error. So, there is no change to the image either.

However, as per my earlier method, I could extract the heapster binary from the exited docker container (thanks to "docker cp" command) and run heapster without `--kubernetes_version=v1beta3`. 

But the following is the error in heapster:

May 07 05:03:32 core-02 kubelet[1113]: E0507 05:03:32.559349    1113 kubelet.go:1288] Unable to mount volumes for pod "monitoring-heapster-controller-jlu5p_default": secrets "token-system-monitoring" not found; skipping pod
May 07 05:03:32 core-02 kubelet[1113]: E0507 05:03:32.791071    1113 pod_workers.go:103] Error syncing pod 5c00e9a1-f476-11e4-8dd9-0800279924c6, skipping: secrets "token-system-monitoring" not found
May 07 05:03:32 core-02 kubelet[1113]: I0507 05:03:32.815953    1113 event.go:200] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"monitoring-heapster-controller-jlu5p", UID:"5c00e9a1-f476-11e4-8dd9-0800279924c6", APIVersion:"v1beta3", ResourceVersion:"2020", FieldPath:""}): reason: 'failedSync' Error syncing pod, skipping: secrets "token-system-monitoring" not found
May 07 05:03:42 core-02 kubelet[1113]: E0507 05:03:42.587797    1113 secret.go:116] Couldn't get secret default/token-system-monitoring
May 07 05:03:42 core-02 kubelet[1113]: E0507 05:03:42.597299    1113 kubelet.go:1288] Unable to mount volumes for pod "monitoring-heapster-controller-jlu5p_default": secrets "token-system-monitoring" not found; skipping pod
May 07 05:03:42 core-02 kubelet[1113]: E0507 05:03:42.757533    1113 pod_workers.go:103] Error syncing pod 5c00e9a1-f476-11e4-8dd9-0800279924c6, skipping: secrets "token-system-monitoring" not found
May 07 05:03:42 core-02 kubelet[1113]: I0507 05:03:42.762674    1113 event.go:200] Event(api.ObjectReference{Kind:"Pod", Namespace:"default", Name:"monitoring-heapster-controller-jlu5p", UID:"5c00e9a1-f476-11e4-8dd9-0800279924c6", APIVersion:"v1beta3", ResourceVersion:"2020", FieldPath:""}): reason: 'failedSync' Error syncing pod, skipping: secrets "token-system-monitoring" not found

And the Heapster POD status is always in Pending state.

(This is aparantly due to the secrete as a volume addition in the HEAD tag. Any changes need to be made in the host files/directories ?)

Then I continued with the just prior commit 331d9228cb464d50cb3414fc9f81cbda7ebfc8af
This time able to run Heapster successfully listening to the port 8082

But following is the error in heapster:
I0507 04:50:38.403239    8612 heapster.go:50] hs/heapster --sink influxdb:http://10.100.116.226:80 --source=kubernetes:http://10.100.0.1:80
I0507 04:50:38.408021    8612 heapster.go:51] Heapster version 0.11.0
I0507 04:50:38.412493    8612 kube_factory.go:97] Using Kubernetes client with master "http://10.100.0.1:80" and version v1beta1
I0507 04:50:38.434382    8612 kube_factory.go:98] Using kubelet port 10255
W0507 04:50:38.450605    8612 request.go:288] field selector: v1beta1 - pods - DesiredState.Host - : need to check if this is versioned correctly.
I0507 04:50:38.520599    8612 driver.go:371] created influxdb sink with options: {root root 10.100.116.226:80 k8s false}
I0507 04:50:38.528436    8612 heapster.go:62] Starting heapster on port 8082
W0507 04:50:38.634983    8612 request.go:288] field selector: v1beta1 - pods - DesiredState.Host - : need to check if this is versioned correctly.
E0507 04:55:38.499291    8612 reflector.go:158] watch of *api.Node ended with: very short watch
W0507 04:55:38.618639    8612 request.go:288] field selector: v1beta1 - pods - DesiredState.Host - : need to check if this is versioned correctly.
E0507 04:55:38.623958    8612 reflector.go:158] watch of *api.Pod ended with: very short watch
E0507 04:55:39.000137    8612 kube_events.go:168] Event watch loop was terminated due to error. Will restart it. Error: Events watchLoop failed with error: watchLoop channel closed
E0507 04:55:39.001577    8612 heapster.go:121] failed to get information from source - Events watchLoop failed with error: watchLoop channel closed
W0507 04:55:39.650032    8612 request.go:288] field selector: v1beta1 - pods - DesiredState.Host - : need to check if this is versioned correctly.
W0507 04:55:39.768627    8612 request.go:288] field selector: v1beta1 - pods - DesiredState.Host - : need to check if this is versioned correctly.

So failed again :-(

Thanks for you suggestion on running heapster from kubernetes repo. So do you mean, I need to clone the repo and build the kubernetes binary and then run the heapster, influxDB and grafana PODs ? (Assume I don't need to build the heapster, influxDB and grafana as these are referred as docker images in the .yaml config files)

However, since I had the kubernetes 0.16.0 binary, I tried runing heapster with that and from the config files present in the "kubernetes repo" but still faced the heapster issue with similar logs as above. This time, I observed the follwoing error in the kubernetes apiserver logs which was not there in the earlier cases:

Error in kube-apiserver:
I0507 06:16:26.871017   22089 server.go:400] Using self-signed cert (/var/run/kubernetes/apiserver.crt, /var/run/kubernetes/apiserver.key)
I0507 06:16:44.716810   22089 logs.go:41] http: TLS handshake error from 172.17.8.1:63329: remote error: unknown certificate authority
E0507 06:27:39.949671   22089 etcd_helper_watch.go:401] unknown action: expire

Note: In all the above cases I can list down the minions, run/get the POD and Service details so I am quite sure the kuberenetes clusture is up and running as expected but always welcome your inputs.
Also, I can open the cAdvisor at port 4194 and influxDB at 8083 with two DBs grafana and k8s. But no data as heapster fails to pull stats from kubelet.

Inputs on how to make this work is greatly appreciated.

**Comment by vishh** [comment]
If you run with the latest kubernetes version (0.16.0+), secrets should work. I will try running heapster HEAD against 0.16.2 today and update this thread.

Did you setup a cluster with kubernetes version 0.16.0 from scratch or did you upgrade the different components manually?

If you use the heapster configs from Kubernetes release 0.16.0, what errors do you observe? The etcd watch errors are benign. You can ignore them. 
Can you also try adding `--vmodule=*=5` flag to `FLAGS` env variable in `heapster-controller.yaml` file? This will make heapster spit out more debugging logs.  

We have continuous integration tests in the kubernetes repo and so heapster bundles with every kube release is supposed to just work.

**Comment by biswars** [comment]
Did you setup a cluster with kubernetes version 0.16.0 from scratch or did you upgrade the different components manually?
Ans: I am using kube-apiserver, kubelet, proxy, kube-register, kube-controller-manager, kube-scheduler binaries and setting up the clustur manaually. The cluster runs fine and I can list/run the pods

Few observations here while using the kubernetese repo and the config files present there.
Inside the file heapster-controller.yaml I see the heapster is started using --sink influxdb:http://monitoring-influxdb.default.kubernetes.local:8086. How will it resolve the domain here ? Do I need to change the domain to my local IP as influxDB is running on 8086 on my local IP. After changing this (hope am at right path), when I access grafana using https://172.17.8.102:6443/api/v1beta1/proxy/services/monitoring-grafana/ I don't see grana UI but just an empty page with text "{{alert.title}}". Following is the screenshot of this.
![untitled](https://cloud.githubusercontent.com/assets/6812249/7535926/29f3186e-f5a8-11e4-8c84-9c9c975f007f.jpg)

Next, I inspected the port where grafana ui is running by listing out the kubernetes services. When I opened the ui directly with the grafana ui port, I can see the grafana page but empty graphs as shown in the follwoing screen shot.
![grafana_empty](https://cloud.githubusercontent.com/assets/6812249/7535982/cb152fa2-f5a8-11e4-8b57-546a626cadfd.jpg)

When I move my cursor over the empty graph, it shows influx DB 404.
![grafana_empty_error](https://cloud.githubusercontent.com/assets/6812249/7536060/ac5a6734-f5a9-11e4-853e-15e406451950.jpg)

When I analysed with network analyser for the first graph, I see the following URL is getting hit

http://172.17.8.102:53370/api/v1beta1/proxy/services/monitoring-grafana/db/k8s/series?p=root&q=select+container_name,+derivative(value)+from+%22cpu%2Fusage_ns_cumulative%22+where+time+%3E+now()+-+5m+group+by+time(5s),+container_name+order+asc&u=root

and Response is 404

(Here 53370 is where the grafana ui is listening).

Next, when I log in to influxdb ui using port 8083, I can log in successfully and list the series with "list series" query. So I feel somehow grafana is not able to get the data from influxdb.

I am stuck at this point for a long time today. Really appreciate any input to progress.

**Comment by vishh** [comment]
@biswars: How are you deploying heapster? Can you get rid of your existing heapster setup and run the following commands?
`kubectl.sh create -f <kubernetes_repo>/cluster/addons/dns/`
`kubectl.sh create -f <kubernetes_repo>/cluster/addons/cluster-monitoring/influxdb/`

The first command helps setup cluster local dns for service discovery. The second command sets up heapster, influxdb and grafana.
Can you figure out if InfluxDB has the metrics data after running these commands? Once we get that part to work, we can focus on why Grafana dashboard is not working for you.

**Comment by biswars** [comment]
I have not set up the dns in the kubernetes cluster so far but yeah, heapster is deployed as per the command you have mentioned above.
The dns part, I can confirm once I am back to my work network after few hours.

In the mean time, I can confirm you that I have seen the metrics data in the InfluxDB (the value in the "time" column was zero always though not sure why) with all the pods, container_name, cpu, io, memory stats and multiple rows. But could not get these reflected in the grafana ui. The IP address you see above is the IP address of the minion where the influxDB pod is running.

As it seems I am in a different time zone, highly appreciate if you could provide any input on the grafana ui issue before I get to my work network and run the dns set up.

**Comment by vishh** [comment]
For Grafana, take a look [here](https://github.com/GoogleCloudPlatform/heapster/blob/master/docs/influxdb.md#production-setup-for-influxdb-and-grafana). You can add a public IP, which in your case can be your node's IP, to the Grafana service. This change requires re-loading your influxdb-grafana controller.

**Comment by biswars** [comment]
I am taking this point and will be exercising this as well along with dns set up. But the set up I am running is completely on my local machine with VMs running by virtual box. So, it is not a production set up and might not need to add public IP to the node as I can access it directly.

Any other inputs you would like to provide here for the 404 error in grafana dashboard graphs ?

**Comment by vishh** [comment]
You can also look at the browser console to find out what queries are
failing and potentially why.

**Comment by biswars** [comment]
Did some more analysis and able to get the grafana ui. Here are my observations:
As mentioned above, I was trying to access grafana by hitting the url https://172.17.8.102:6443/api/v1beta1/proxy/services/monitoring-grafana/. Observed that the internal urls getting hit in the browser is https://172.17.8.102:6443/api/v1beta1/proxy/namespaces/default/services/monitoring-grafana/. (this always gives HTTP 404)
When I access the url https://172.17.8.102:6443/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/ then the ui comes up.
So, a question here - who does this url redirection ? Is it due to the pods used here are with v1beta3 ?

Queries:
1. The "All containers CPU usage - stacked shows "No datapoints" initially with only grafana, influxdb and heapster running. The query run is "select container_name, derivative(value) from "cpu/usage_ns_cumulative" where time > now() - 5m group by time(5s), container_name " which gives empty result when I tried in influxdb ui. Is it the normal behavior ? The memory usage graph shows the gauge value properly.

2.  The grafana ui shows two rows distinctively for the pods heapster and influx-grafana. When I run more pods onto the cluster it does not add similar rows for each pod. Is this the normal behavior ?

3. I used the 0.16.2 kubernetes binaries so that I can use the secrets as volume as you had mentioned earlier. But I still get error due to missing "token-system-monitoring" and pod does not get deployed. Just out of curiosity, where is this secret defined ? In heapster-controller.json, it is just referenced but I think it should be defined somewhere isn't it ? (Note, as mentioned earlier I am using the kubernetes binaries manually and not on GCE. So, not sure if I need to define the secrete separately)

**Comment by vishh** [comment]
The apiserver now runs with v1beta3 version by default. I have updated the
setup guide to use v1beta3 instead of v1beta1.

1. Grafana does not auto generate graphs for new pods. You can add scripts
I believe to achieve that. If you are interested in this feature to work,
feel free to post a PR.

2. Tokens are required to access the apiserver. This is to make sure that
the apiserver is secure. Take a look at `docs/authentication.md` in
Kubernetes repo.
To work around the token issue for now, use the latest heapster configs
from heapster repo and update "--source=kubernetes:http://kubernetes-ro"
flag to be "--source=kubernetes:http://kubernetes-ro?auth=". That should
get you past the token issue. Do keep in mind that this wont work for long
in upstream kubernetes.

**Comment by shwetalakhimpur** [comment]
@biswars - I am unable to access the Grafana UI
When I access the url https://172.17.8.102:6443/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/ then the ui comes up.

Please help me understand the IP:port here. 
Is this is IP which is running monitoring-influx-grafana-controller-y3qn3 ? This is the IP listed under IP or HOST when we do "kubectl get pods"
172.17.8.102:6443

The port 6443, is this the port listed in "grafana-service.json" ?

**Comment by vishh** [comment]
The IP in that URL is that of the kubernetes api-server.

**Comment by shwetalakhimpur** [comment]
Thanks Vish, we may continue troubleshooting on the other thread, I have provided more details
https://github.com/GoogleCloudPlatform/heapster/issues/338

**Comment by biswars** [comment]
Today I tried the same set up with kubernetes head (1.0.3) and getting error in running heapster. The error log shows the followings:

I0817 10:25:38.552690       1 heapster.go:55] /heapster --source=kubernetes:'' --sink=influxdb:http://172.17.8.102:8086
I0817 10:25:38.552754       1 heapster.go:56] Heapster version 0.17.0
F0817 10:25:38.552885       1 heapster.go:62] open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

Note: I am not using any secrets as I was not using with kubernetes version 0.16 earlier. Any suggestion on how to make this work ? The earlier set up with kubernetes version 0.16 still works perfect.

**Comment by vishh** [comment]
Take a look at kubernetes cluster setup guides. You missed the section on "service accounts" most likely. It is supposed to be setup by default, but it requires enabling a plugin. Sorry for the confusion!

**Comment by biswars** [comment]
Thanks Vishh for pointing this out. I could proceed to the extent of setting up the service accounts with secrets but it seems I am still missing something to make it work. I am providing the the set up details (I know I need to struggle as am setting up locally but hopeful as it was working fine with earlier version of kubernetes).

Set up with observation:

$ kubectl get svc
NAME                 CLUSTER_IP      EXTERNAL_IP   PORT(S)         SELECTOR             AGE
kubernetes           10.100.0.1      <none>        443/TCP         <none>               6h

I believe the RO service is now deprecated. But not able to hit this using "curl https://10.100.0.1:443" instead curl with -k (ssl connection without certs) option works. This is discussed in [#4290](https://github.com/kubernetes/kubernetes/issues/4290) but not too sure on the solution on how to place the certs.

Service account set up:
As per the suggestion above, api-server started with admission-control plugin as mentioned in https://github.com/kubernetes/kubernetes/blob/master/docs/admin/admission-controllers.md. Able to get the service accounts but could not get the secrets associated with it.

As could not get any guide within the community, had searched and got this useful link [#11355](https://github.com/kubernetes/kubernetes/issues/11355#issuecomment-127378691). Post creation of the self-signed key manually and restarting the api-server and controller manager able to get the secrets associated with the service account (namespace "default")

However, running heapster shows the followings logs. Anything missing still ?

I0818 10:23:15.669769       1 heapster.go:55] /heapster --source=kubernetes:'' --sink=influxdb:http://172.17.8.102:8086
I0818 10:23:15.675855       1 heapster.go:56] Heapster version 0.17.0
E0818 10:23:15.677549       1 helper.go:247] expected to load root ca config from /var/run/secrets/kubernetes.io/serviceaccount/ca.crt, but got err: open /var/run/secrets/kubernetes.io/serviceaccount/ca.crt: no such file or directory
I0818 10:23:15.679510       1 kube_factory.go:168] Using Kubernetes client with master "https://10.100.0.1:443" and version "v1"
I0818 10:23:15.679679       1 kube_factory.go:169] Using kubelet port 10255
E0818 10:23:16.231170       1 reflector.go:136] Failed to list *api.Namespace: Get https://10.100.0.1:443/api/v1/namespaces: x509: failed to load system roots and no roots provided
E0818 10:23:16.262881       1 kube_events.go:96] Failed to load events: Get https://10.100.0.1:443/api/v1/events: x509: failed to load system roots and no roots provided
E0818 10:23:16.269705       1 reflector.go:136] Failed to list *api.Pod: Get https://10.100.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%21%3D: x509: failed to load system roots and no roots provided
E0818 10:23:16.272718       1 reflector.go:136] Failed to list *api.Node: Get https://10.100.0.1:443/api/v1/nodes: x509: failed to load system roots and no roots provided
I0818 10:23:16.274954       1 driver.go:376] created influxdb sink with options: {root root 172.17.8.102:8086 k8s false}

**Comment by vishh** [comment]
Have you looked at the [source config docs](https://github.com/kubernetes/heapster/blob/master/docs/source-configuration.md#current-sources) in this repo?

**Comment by biswars** [comment]
Thanks @vishh . With the serviceAccounts set properly, could get the heapster up and running properly with master and single node. However, when I add one more node to the cluster (running only kubelet and proxy services) and heapster happens to run on that node, then I get the following error. (Note: I don't get any error and heapster runs fine with single node running on the master itself.). 

core@core-02 ~ $ kubectl logs -f monitoring-heapster-v8-5fatp --namespace=kube-system
I0821 10:35:12.208070       1 heapster.go:55] /heapster --source=kubernetes:'' --sink=influxdb:http://monitoring-influxdb:8086
I0821 10:35:12.208244       1 heapster.go:56] Heapster version 0.17.0
I0821 10:35:12.214370       1 kube_factory.go:168] Using Kubernetes client with master "https://10.100.0.1:443" and version "v1"
I0821 10:35:12.214575       1 kube_factory.go:169] Using kubelet port 10255
E0821 10:35:12.257887       1 reflector.go:136] Failed to list *api.Pod: Get https://10.100.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%21%3D: EOF
E0821 10:35:12.259134       1 reflector.go:136] Failed to list *api.Node: Get https://10.100.0.1:443/api/v1/nodes: EOF
E0821 10:35:12.259621       1 reflector.go:136] Failed to list *api.Namespace: Get https://10.100.0.1:443/api/v1/namespaces: EOF
E0821 10:35:12.261380       1 kube_events.go:96] Failed to load events: Get https://10.100.0.1:443/api/v1/events: EOF
I0821 10:35:12.265586       1 driver.go:376] created influxdb sink with options: {root root monitoring-influxdb:8086 k8s false}
I0821 10:35:12.273340       1 heapster.go:66] Starting heapster on port 8082
E0821 10:35:12.279199       1 kube_events.go:96] Failed to load events: Get https://10.100.0.1:443/api/v1/events: EOF
E0821 10:35:13.262188       1 reflector.go:136] Failed to list *api.Pod: Get https://10.100.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%21%3D: EOF
E0821 10:35:13.269873       1 reflector.go:136] Failed to list *api.Namespace: Get https://10.100.0.1:443/api/v1/namespaces: EOF
E0821 10:35:13.271305       1 reflector.go:136] Failed to list *api.Node: Get https://10.100.0.1:443/api/v1/nodes: EOF
E0821 10:35:14.266397       1 reflector.go:136] Failed to list *api.Pod: Get https://10.100.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%21%3D: EOF
E0821 10:35:14.279837       1 reflector.go:136] Failed to list *api.Node: Get https://10.100.0.1:443/api/v1/nodes: EOF
E0821 10:35:14.282135       1 reflector.go:136] Failed to list *api.Namespace: Get https://10.100.0.1:443/api/v1/namespaces: EOF
E0821 10:35:15.270247       1 reflector.go:136] Failed to list *api.Pod: Get https://10.100.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%21%3D: read tcp 10.100.0.1:443: connection reset by peer
E0821 10:35:15.288348       1 reflector.go:136] Failed to list *api.Namespace: Get https://10.100.0.1:443/api/v1/namespaces: EOF
E0821 10:35:15.290524       1 reflector.go:136] Failed to list *api.Node: Get https://10.100.0.1:443/api/v1/nodes: read tcp 10.100.0.1:443: connection reset by peer
E0821 10:35:16.274316       1 reflector.go:136] Failed to list *api.Pod: Get https://10.100.0.1:443/api/v1/pods?fieldSelector=spec.nodeName%21%3D: read tcp 10.100.0.1:443: connection reset by peer
E0821 10:35:16.297905       1 reflector.go:136] Failed to list *api.Node: Get https://10.100.0.1:443/api/v1/nodes: EOF
E0821 10:35:16.299074       1 reflector.go:136] Failed to list *api.Namespace: Get https://10.100.0.1:443/api/v1/namespaces: EOF


When I log in to the heapster container running on the separate node, I can see the ca.crt and token (inside /var/run/secrets/kubernetes.io/serviceaccount/) same as that of containers running in the first node. Not sure what might be the issue still. Don't get any related error in kube-apiserver log though. Anything I am missing ?

**Comment by vishh** [comment]
Heapster is having trouble accessing the API server. Can you check
kube-proxy logs on the heapster node to ensure there are no proxy issues?

cc @mikedanese

**Comment by imesh** [comment]
Hi @vishh, I'm also seeing this problem on Kubernetes 1.0.6. Anyway to resolve this?
Thanks

**Comment by imesh** [comment]
AFAIU the problem is with the SSL certificate configuration in Heapster. The HTTPS call to Kubernetes API fails due to a certificate issue. I was able to get around this by specifying the HTTP Kubernetes API URL in the heapster controller as below:

```
--source=kubernetes:http://172.17.8.101:8080?inClusterConfig=false
```

**Comment by piosz** [comment]
This is obsolete. Try to use the new Heapster 1.0.
