### ISSUE TITLE
fleetEndpoint over https

### ISSUE THREAD

**Issue by genti-t** [kubernetes/heapster#287]
Im trying to figure out if there is a way to put :
 FLEETCTL_CA_FILE
 FLEETCTL_CERT_FILE
 FLEETCTL_KEY_FILE
with :
--source=cadvisor:coreos?fleetEndpoint=https://$private_ipv4:2379

Or fleetEndpoint over ssl is not supported yet ?

**Comment by vishh** [comment]
SSL files have to be plumbed [here](https://github.com/GoogleCloudPlatform/heapster/blob/master/sources/nodes/coreos.go#L66). Will you be able to post a PR? 
If not, I will get to it soon.

**Comment by piosz** [comment]
Out of the scope of the project - only Kubernetes deployments are supported. See more details: https://github.com/kubernetes/heapster/blob/master/docs/proposals/vision.md
