### ISSUE TITLE
GCM sink is too slow in flushing data

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#289]
GCM sink takes a long time to flush metrics. The delay is more pronounced under scale (100 node cluster or running a lot of containers). Is it possible to alter the flushing model for GCM sink and make it perform lesser number of GCM requests?

**Comment by vmarmol** [comment]
Will take a look

**Comment by piosz** [comment]
I can take a look.

**Comment by vmarmol** [comment]
FWIW, we've tested it on larger cluster and it has been okay. Since we only scrape data every few mins.

**Comment by piosz** [comment]
Ok. Thanks for the update. Did you test it with many pods (i.e. 100 nodes, 10 pods/node)?

**Comment by vmarmol** [comment]
IIRC we tested on a 100node cluster but more likely with 5 pods/node

**Comment by piosz** [comment]
Sounds reasonable. Should this issue be closed?

**Comment by mwielgus** [comment]
GCM sink was rewritten.
