### ISSUE TITLE
Support Riemann sink

### ISSUE THREAD

**Issue by jfoy** [kubernetes/heapster#293]
We'd like to stream our metrics to a [Riemann instance](http://riemann.io/) before sending them to influxdb. I'm working on a sink to support this.

**Comment by vishh** [comment]
+1. I have been experimenting with Bosun as well.

**Comment by satheessh** [comment]
we also need it

**Comment by erimatnor** [comment]
+1

**Comment by ivanthelad** [comment]
+1

**Comment by vishh** [comment]
Support for Riemann is now available on HEAD.

**Comment by duttadeep55** [comment]
Riemann

This sink supports metrics only. To use the reimann sink add the following flag:

--sink="riemann:<RIEMANN_SERVER_URL>[?<OPTIONS>]"
The following options are available:

ttl - TTL for writes to Riemann. Default: 60 seconds
state - FIXME. Default: ""
tags - FIXME. Default. none
storeEvents - Control storage of events. Default: true

**Comment by piosz** [comment]
According to https://github.com/kubernetes/heapster/blob/master/docs/sink-owners.md we are going to remove support for Riemann unless we will find owners for it.

cc @DirectXMan12 @jsoriano

**Comment by jamtur01** [comment]
@piosz @mcorbin and I are going to own the Riemann sink.
