### ISSUE TITLE
Heapster-InfluxDB does not give the containers' percentage of usage

### ISSUE THREAD

**Issue by biswars** [kubernetes/heapster#296]
The requirement is to take action based on the percentage of usage of the containers running on kubernetes cluster. Using heapster and influxDB, I can get the current and max usage of cpu/memory using the series "cpu/usage_ns_cumulative" and "memory/usage_bytes_gauge" but not the percentage of usage based on the limit set at the container.

The first impression was this behavior might be because of not setting the cpu/memory limit inside the pod yaml file. When I set the limit using the following, I observed the same behavior.
          cpu: 100
          memory: 50000000

When observed in the cAdvisor ui, it shows "Limit unlimited" in the Memory section and "Shares 1024 shares" in the CPU section.
Can I get the percentage of usage based on the limit set for the containers so that useful action can be taken ?

**Comment by vishh** [comment]
heapster currently does not store limits. +1 for storing limits which
should let you calculate/graph percentage usage.

**Comment by biswars** [comment]
Just a query here - even cAdvisor does not show the limit set to the container (at least in the web interface). So, are there any means to get the container limits using cAdvisor api directly ?

**Comment by vishh** [comment]
Yes. Cadvisor provides Spec and Status. Spec has the limits.

**Comment by biswars** [comment]
Thanks. Yeah, able to get the limits directly now and also able to co-relate with the data as sampled by heapster. For the memory usage, I am using the series "memory/usage_bytes_gauge" and works perfect.
However, having some issue with the cpu usage using the series "cpu/usage_ns_cumulative". Post some analysis, I guessed the "value" field in series "cpu/usage_ns_cumulative" gives the time in nano secs spent in the form of cpu cycles on specific container. Any suggestion on how to transform this value to the %age of cpu usage for a container ?
Note: I am able to get the cpu limit (as specified in the pod/rc yaml/json) also now which gives the cpu share per container (viz. 1024, 512 etc). But getting the %age using the limit value and "cpu/usage_ns_cumulative" is where am not able to get any co-relation.

**Comment by vishh** [comment]
There are two parts to your question:
1. How to calculate instantaneous usage:
I would recommend running continuous queries and creating a new
instantaneous series based on cpu/usage_ns_cumulative series. You can
calculate a derivative of this series with an appropriate time interval(1m
for example) and store in a separate series.
2. How to partition a node's CPU?
CPU shares are ratios and it is difficult to correlate usage with cpu
shares. I would recommend choosing a multiplier for each CPU, (1000 per CPU
for example) and coming up with a max shares per node. if your node has 4
cores, then it has a max of 4000 shares. Now each share translates to 1
millisecond of CPU usage per second. If you provide a container 1000
shares, then its limit is 1 second of CPU usage per second.
Note: CPU shares are proportional - What that means is that when the node
is fully loaded, each container is guaranteed by the kernel to get at least
their share's worth of CPU time.

Hope this helps!

**Comment by biswars** [comment]
Thanks. Very useful comments. One query before closing this. If I want to relate the above two parts to get the cpu usage per container can I take like this way;

a: Result of the new series from part 1 above gives the nano secs of cpu usage per 1m container-wise. From this get the number of seconds cpu usage per second. Assign this value as "m".

b: Based on the cpu shares per node (taking 1000 as per part 2 above) and limit set by the container (ex: 500 which is half of the cpu), if m == 0.5 then the container's cpu usage is 100%.

Would this be the right way ?

**Comment by vishh** [comment]
That sounds about right.

**Comment by biswars** [comment]
Thanks. Able to get the cpu % usage based on your suggestions and it works to certain extent. The issue I am facing is, I need to wait for more than 3/5 minutes before actually getting the instantaneous cpu usage.

The followings are the steps used:
Step 1: Every 1 minute interval, execute the query "select container_name, derivative(value) from "cpu/usage_ns_cumulative" where time > now() - 3m group by container_name order asc".

Step 2: Check the derivative as obtained in Step 1 against the threshold.

Step 3: Take action as appropriate.

Problem:
In Step 1 above, I very often get empty ("[]") json response. So if one cycle is lost, I need to wait for the second cycle (wait for 1 more minute).

Observation:
If the "3m" is replaced with "5m", I almost always get the valid json response. This is acceptable, if it is fine to wait for 5 minutes before getting the cpu instantaneous usage value. But I would like to take action as soon as the threshold is reached, which means getting the cpu usage derivative every 1 minute. But if I replace "3m" with "1m", I always get empty json response.

What could be the problem ?

Is it because heapster fails sometimes in updating the values to influxdb ? Are there any means of reducing the time interval at which heapster dumps the metrics to influxdb so that I can get the cpu derivatives every 1 minute ?

**Comment by biswars** [comment]
To answer above query, heapster polling interval can be changed in the pod definition file by cofiguring "--poll_duration" and with this the data points are populated. Does "--stats_resolution" also need to be set. By setting these values as "10s" and "5s" respectively, the data points can be retrieved from influxDB if externally polled at certain interval (using 60 sec). The only observation here is sometimes the data points are empty for time series "cpu/usage_ns_cumulative". Any configuration changes need to be made so that the data points can be retrieved always without fail ?

**Comment by vishh** [comment]
poll_duration determines how often heapster queries kubelets.
stats_resolution determines the downsampling that heapster performes. If
they both are equal heapster will not perform any downsampling.

**Comment by Lswith** [comment]
I think a better alternative could be the use of the difference aggregate. If you do the difference rather than the derivative you get better resolution.

**Comment by thirunavukkarasumca** [comment]
Hi Guys, I have doubt in calculating the CPU usage of Kube in percentage. I need to convert cpu/usage_ns_cumulative value to percentage with help of cpu/limit_gauge. Plz give some example for me to analysis....

**Comment by DirectXMan12** [comment]
I believe we have these mechanisms now
