### ISSUE TITLE
Track raw containers (cgroups) on all in a kubernetes cluster

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#30]
To have a complete understanding of resource usage in the cluster, heapster needs to track docker containers that do not belong to a pod and raw cgroups that exist on the system.

**Comment by rjnagal** [comment]
Can we just use the stats from root container and take a diff?

**Comment by vishh** [comment]
If we run the system daemons in separate cgroups, it is useful to track each of the raw cgroups separately.

**Comment by rjnagal** [comment]
True. These should be exported by Kubelet as a standard API. Otherwise, we
will end up picking lot of unrelated stuff that'll need to throw out. That
is lot of wasted bandwidth at cluster level.

**Comment by vishh** [comment]
Agreed!
