### ISSUE TITLE
Support Influxdb v0.9+

### ISSUE THREAD

**Issue by rjnagal** [kubernetes/heapster#302]
There are bunch of new features _and_ API changes.

**Comment by acconsta** [comment]
And apparently solves some [data corruption issues](https://news.ycombinator.com/item?id=9812572) related to clustering. Is there a time frame for this issue?

**Comment by rvrignaud** [comment]
Hello,

Is there anyone working on this one ? Influxdb 0.9.3 is coming and 0.8 branch will not live for a long time.

**Comment by vishh** [comment]
@mvdan: Did you make any progress on this?

**Comment by mvdan** [comment]
I'll try to have a PR by the end of the day.

**Comment by szubster** [comment]
Any news?
