### ISSUE TITLE
Trying to run heapster on openshift3

### ISSUE THREAD

**Issue by shilpapadgaonkar** [kubernetes/heapster#320]
Hi,
I am trying to run heapster on openshift3. I followed the documentation link https://github.com/GoogleCloudPlatform/heapster/blob/master/docs/influxdb.md

I also made changes to remove the environment variable INFLUXDB_EXTERNAL_URL from InfluxDB Grafana RC config and added a route so that Grafana service become reachable as an external service.

All services were created. InfluxDB and grafana started without issues. I am able to see the Grafana UI.

The monitoring-heapster-controller does not start though. It keeps showing me a pending state. I am not sure why..

I have read in the docu somewhere that I could provide heapster a kubernetes source explicitly. Do I need to do this while trying to run it on openshift3 ? Could you please let me know how I could do this?

Thanks in advance.

Regards,
Shilpa

**Comment by vishh** [comment]
Can you post logs from heapster pod? (`kubectl logs <heapster pod name>`)

**Comment by shilpapadgaonkar** [comment]
I could not get pod logs as the pod is not running yet. See attached pic
![heapster-pic](https://cloud.githubusercontent.com/assets/3367612/8051752/a92063a8-0e80-11e5-8d31-511fb50ead08.PNG)


The openshift master logs showed some errors though...
![openshift-master-logs](https://cloud.githubusercontent.com/assets/3367612/8051757/b73e810e-0e80-11e5-9147-b0655b6f601e.PNG)

**Comment by detiber** [comment]
@shilpapadgaonkar I've been working on this myself.  I've gotten a bit further than you have, but am still hitting a roadblock on the correct service URL to use internal to the cluster.  Here is my modified replication controller:
```
[openshift@ip-172-19-47-10 ~]$ cat heapster-rc.json 
{
    "apiVersion": "v1beta3",
    "kind": "ReplicationController",
    "metadata": {
	"labels": {
	    "name": "heapster"
	},
	"name": "monitoring-heapster-controller"
    },
    "spec": {
	"replicas": 1,
	"selector": {
	    "name": "heapster"
	},
	"template": {
	    "metadata": {
		"labels": {
		    "name": "heapster"
		}
	    },
	    "spec": {
		"containers": [
		    {
			"image": "kubernetes/heapster:v0.13.0",
			"name": "heapster",
			"command": [
			    "/heapster",
			    "--source=kubernetes:http://kubernetes-ro.default.local?auth=",
			    "--sink=influxdb:http://ip-172-19-51-208.ec2.internal:8086"
			]
		    }
		]
	    }
	}
    }
}
```
You will probably not want to edit the --sink flag for the heapster command I'm trying to route the metrics to an external InfluxDB instance instead of one running in a pod.

The first issue that I ran into was that /etc/kubernetes/kubeConfig/kubeConfig and /etc/ssl/certs do not exist on the OpenShift nodes.

The kubernetes-ro service is exposed, but I do not seem to be able to reach it using the skydns provided name (kubernetes-ro.default.local) or via the default service ip address (172.30.0.1), but I believe that is because the deployment I am running (OSE Beta3 or Beta4 builds should not suffer from that issue).

**Comment by shilpapadgaonkar** [comment]
Thanks @detiber for your help.
I modified a couple of things in the heapster-controller such as source to kkubernetes as --source=kubernetes:http://kubernetes-ro.default.local.

Now the pod atleast gets into a running state.

But now I face the same issue as you where the logs say that it cant find

**Comment by vishh** [comment]
cc @jimmydyson

**Comment by jimmidyson** [comment]
@vishh Are there any plans for heapster to use service accounts?

@shilpapadgaonkar You need to create a secret containing the contents of a kubeconfig file & mount it at the appropriate place in your pod. Should work, but not tried it recently.

**Comment by vishh** [comment]
Heapster uses a monitoring-token that is auto-generated on Kubernetes
clusters as part of the cluster setup process. I assume that is not the
case in Openshift?

**Comment by detiber** [comment]
@vishh as far as I can tell that is correct. @smarterclayton am I missing something, or do you have thoughts on how to bridge the gap (if any)

**Comment by smarterclayton** [comment]
We don't generate that token, but the token should be replaceable with a service account.  One sec, let me poke.

**Comment by smarterclayton** [comment]
Ok, so the token should be injected by the service account in openshift into the standard service account location /var/run/secrets/kubernetes.io/serviceaccount.  If you `ENVVAR=$(cat $file)` you can then pass it as an argument in the shell.

**Comment by jimmidyson** [comment]
@vishh That's right - the token isn't generated by default as it is with vanilla kubernetes. Just wondering why kube config is preferred to service account?

**Comment by jimmidyson** [comment]
@smarterclayton Heapster can't currently use bearer token auth so I'm sending in a PR now to do just that. I have it working locally against OpenShift.

**Comment by jimmidyson** [comment]
Sent in PR #324 to enable service accounts in heapster.

**Comment by jimmidyson** [comment]
There will be further difficulties in running Heapster on OpenShift such as #325 as access to kubelets is secured. I'll work on another PR for that to use the master proxy.

**Comment by jimmidyson** [comment]
I have this working by adding the read only port to the kubelet config in OpenShift. However this is not recommended as it is obviously a security risk. Working with the OpenShift team to try to resolve, but this is not a priority for them so may take a while to get working.

**Comment by shilpapadgaonkar** [comment]
Could you recommend some other working solution to gather metrics for openshift?

**Comment by shilpapadgaonkar** [comment]
@jimmidyson 

I now try to use the serviceAccount as specified by you in the source config docu and the logs show me the following:

E0617 14:10:25.465443       1 kube_events.go:96] Failed to load events: Get http://kubernetes-ro/api/v1beta3/events: dial tcp: lookup kubernetes-ro: no such host
E0617 14:10:25.702882       1 reflector.go:123] Failed to list *api.Node: Get http://kubernetes-ro/api/v1beta3/nodes: dial tcp: lookup kubernetes-ro: no such host
E0617 14:10:25.702945       1 reflector.go:123] Failed to list *api.Pod: Get http://kubernetes-ro/api/v1beta3/pods?fieldSelector=spec.host%21%3D: dial tcp: lookup kubernetes-ro: no such host

**Comment by jimmidyson** [comment]
There is no kubernetes-ro service, this should be https://kubernetes now, but requires a service account to be properly set up as you say. I'm documenting the deployment on openshift in the openshift docs by the end of this week (hopefully) so might be best to wait for that.

**Comment by shilpapadgaonkar** [comment]
Ok. sounds good

**Comment by shilpapadgaonkar** [comment]
@jimmidyson 
I can see only the pods running in the default namespace. Do I need a different role than the one mentioned in your documentation?

 oadm policy add-cluster-role-to-user \
    cluster-reader \
    system:serviceaccount:default:heapster

**Comment by jimmidyson** [comment]
@shilpapadgaonkar As long as the pods are using the default:heapster service account then it should be fine. Are you saying you're only getting metrics for the pods in the default namespace? Where are you looking?

**Comment by shilpapadgaonkar** [comment]
@jimmidyson 
Yes I am getting metrics on only the pods within the default namespace. I also have some pods running in demo namespace and i dont see any metrics from these pods

**Comment by jimmidyson** [comment]
Where are you looking? In grafana or in influxdb? Wonder if the query in grafana is only targeting the default namespace?

**Comment by shilpapadgaonkar** [comment]
i am looking in grafana.
query looks fine to me
where pod_namespace =~ /.+/

**Comment by smarterclayton** [comment]
@deads2k is there any reason why the service account token for a cluster reader wouldn't be able to access pods?  Can you help debug here

**Comment by deads2k** [comment]
> @deads2k is there any reason why the service account token for a cluster reader wouldn't be able to access pods? Can you help debug here

Seems to be working fine:
```
[deads@deads-dev-01 origin]$ export KUBECONFIG=openshift.local.config/master/admin.kubeconfig 

[deads@deads-dev-01 origin]$ oc get secrets
NAME                       TYPE                                  DATA      AGE
builder-dockercfg-goyxb    kubernetes.io/dockercfg               1         21s
builder-token-8xvwf        kubernetes.io/service-account-token   2         21s
builder-token-j9uw0        kubernetes.io/service-account-token   2         21s
default-dockercfg-3xc56    kubernetes.io/dockercfg               1         21s
default-token-czoly        kubernetes.io/service-account-token   2         21s
default-token-iwx0m        kubernetes.io/service-account-token   2         21s
deployer-dockercfg-qdiio   kubernetes.io/dockercfg               1         21s
deployer-token-n4i7n       kubernetes.io/service-account-token   2         21s
deployer-token-pg41k       kubernetes.io/service-account-token   2         21s

[deads@deads-dev-01 origin]$ oc describe secrets/default-token-czoly
Name:		default-token-czoly
Namespace:	default
Labels:		<none>
Annotations:	kubernetes.io/service-account.name=default,kubernetes.io/service-account.uid=fa6f4ad4-44f3-11e5-ae1e-28d2447dc82b

Type:	kubernetes.io/service-account-token

Data
====
ca.crt:	1066 bytes
token:	eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tY3pvbHkiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImZhNmY0YWQ0LTQ0ZjMtMTFlNS1hZTFlLTI4ZDI0NDdkYzgyYiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.Q7C2DQwQEy4oTalRpUDjSPtiZKfBNvp9aV7eSCcSseulxxF1EQNb5lmnvnOQDnnaku3gYRsAs3G_6VzBI3QssgVJGBY_O1vFOA0pXm8vRs4GE9e0fZ11UDRJXvOktMXwPPERfJ8-ufd58ENBxr1P2gH8R8gN0pUDKB9uf6D-nW685ZKWG5wPFK-OYL-kNLeB-V0zbxHJ37CU_H5jC8Nc9h-7B1jD9-3LGNhl0UneDr4VvZ1vEchacKnzbXRjvMsNLtHD2G6PEFoZRwKmzcUkG5oUwCrwfwbiYHzBAugKaeH9K2fPU7PD5EZPxmepXi05BrCa2mf_f9B6TRnMmdDRpw


[deads@deads-dev-01 origin]$ oc get pods --all-namespaces --token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tY3pvbHkiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImZhNmY0YWQ0LTQ0ZjMtMTFlNS1hZTFlLTI4ZDI0NDdkYzgyYiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.Q7C2DQwQEy4oTalRpUDjSPtiZKfBNvp9aV7eSCcSseulxxF1EQNb5lmnvnOQDnnaku3gYRsAs3G_6VzBI3QssgVJGBY_O1vFOA0pXm8vRs4GE9e0fZ11UDRJXvOktMXwPPERfJ8-ufd58ENBxr1P2gH8R8gN0pUDKB9uf6D-nW685ZKWG5wPFK-OYL-kNLeB-V0zbxHJ37CU_H5jC8Nc9h-7B1jD9-3LGNhl0UneDr4VvZ1vEchacKnzbXRjvMsNLtHD2G6PEFoZRwKmzcUkG5oUwCrwfwbiYHzBAugKaeH9K2fPU7PD5EZPxmepXi05BrCa2mf_f9B6TRnMmdDRpw
Error from server: User "system:serviceaccount:default:default" cannot list all pods in the cluster

[deads@deads-dev-01 origin]$ oadm policy add-cluster-role-to-user "cluster-reader" system:serviceaccount:default:default

[deads@deads-dev-01 origin]$ oc get pods --all-namespaces --token=eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4tY3pvbHkiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6ImZhNmY0YWQ0LTQ0ZjMtMTFlNS1hZTFlLTI4ZDI0NDdkYzgyYiIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.Q7C2DQwQEy4oTalRpUDjSPtiZKfBNvp9aV7eSCcSseulxxF1EQNb5lmnvnOQDnnaku3gYRsAs3G_6VzBI3QssgVJGBY_O1vFOA0pXm8vRs4GE9e0fZ11UDRJXvOktMXwPPERfJ8-ufd58ENBxr1P2gH8R8gN0pUDKB9uf6D-nW685ZKWG5wPFK-OYL-kNLeB-V0zbxHJ37CU_H5jC8Nc9h-7B1jD9-3LGNhl0UneDr4VvZ1vEchacKnzbXRjvMsNLtHD2G6PEFoZRwKmzcUkG5oUwCrwfwbiYHzBAugKaeH9K2fPU7PD5EZPxmepXi05BrCa2mf_f9B6TRnMmdDRpw
NAMESPACE   NAME      READY     STATUS    RESTARTS   AGE
[deads@deads-dev-01 origin]$ 
```

**Comment by deads2k** [comment]
> @jimmidyson 
> Yes I am getting metrics for only the pods within the default namespace. I also have some pods running in demo namespace and i dont see any metrics from these pods

@shilpapadgaonkar Can you show me the URLs you're requesting and the return codes you're getting back?  I wonder if you're accidentally specifying the namespace on your request.  You should be hitting `https://<yourip>:8443/api/v1/pods`.

**Comment by miheer** [comment]
I followed the instructions as per  https://docs.openshift.org/latest/admin_guide/cluster_metrics.html as a root i.e.system:admin user but, I'm been shown pods related to system:admin user and not the pods related to the user joe in the grafana UI.
I see  a tile in the grafana UI only for  node1 which has pods created by system:admin i.e root but, not node2 where pods of joe reside.

**Comment by david-martin** [comment]
@miheer I'm seeing similar behaviour after following through that guide.
I set it up in the `default` project, and exposed a route for the grafana service.
In the grafana UI it shows only containers that are on 1 of the 5 nodes in this OSE install.

The filters for showing all container cpu usage look ok to me e.g. `pod_namespace =~ /.+/`

**Comment by shilpapadgaonkar** [comment]
@deads2k 
I deleted all running pods, and redeployed the complete service and now I can see metrics of pods from all namespaces

**Comment by jimmidyson** [comment]
@miheer @david-martin Would you be able to post the output of:

`oc describe clusterPolicy default`
`oadm policy who-can get nodes`
`oadm policy who-can get pods`

`oc get rc heapster -n default | grep serviceAccount`

**Comment by jimmidyson** [comment]
Also:

`oc describe clusterPolicyBindings :default`

**Comment by jimmidyson** [comment]
I've just put in a PR for some minor updates to the documentation - mainly updating to latest heapster release (0.17.0) & a necessary firewall rule on each node.

Deployed on 3 node cluster & all worked straight OOTB with no customisations.

**Comment by shilpapadgaonkar** [comment]
@detiber 
You had mentioned here some time back about using an external influxDb.

"--sink=influxdb:http://ip-172-19-51-208.ec2.internal:8086"

Did you have to make sure of any pre-requisites (creating users, db, resetting any config files for auth) on the influxDb?

I am trying to now use an exterenal influxdb Vm and any hints would be very useful.

Thanks,
Shilpa

**Comment by piosz** [comment]
This is obsolete. Please try the new Heapster 1.0.2.
