### ISSUE TITLE
Help with accessing the Grafana path - Grafana will be accessible at https://<masterIP>/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/

### ISSUE THREAD

**Issue by shwetalakhimpur** [kubernetes/heapster#338]
The documentation says - https://github.com/GoogleCloudPlatform/heapster/blob/master/docs/influxdb.md

Grafana will be accessible at https://<masterIP>/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/

I am unable to access the Grafana UI. I am using a kubernetes cluster and all the services are pods are running. How do I troubleshoot this ? I have read through the issues discussion around this, but unfortunately it does not give clarity.

**Comment by shwetalakhimpur** [comment]
I seem to be on the same issues as this thread - stuck at 404 Not found, 
https://github.com/GoogleCloudPlatform/heapster/issues/203

**Comment by vishh** [comment]
Can you describe your cluster setup - Kube version, cloud provider, etc?
Can you verify if all the pods are running?
Can you drop 'proxy' keyword from URL and see if the api-server responds
with a grafana service object?

**Comment by shwetalakhimpur** [comment]
IBM Softlayer, CentOS Linux release 7.1.1503 (Core)
etcd-2.0.9-2.el7.x86_64
kubernetes-0.15.0-0.3.git0ea87e4.el7.x86_64

This is a cluster of 3 nodes, master is not set as a minion
>> kubectl get pods
>> kubectl get pods
monitoring-heapster-controller-t8p51         172.17.39.12   heapster       kubernetes/heapster:v0.13.0         119.x.x.x/119.x.x.x   name=heapster                                Running   8 hours
monitoring-influx-grafana-controller-y3qn3   172.17.39.13   influxdb       kubernetes/heapster_influxdb:v0.3   119.x.x.x/119.x.x.x   name=influxGrafana                           Running   8 hours
                                                            grafana        kubernetes/heapster_grafana:v0.7  

I tried this, 'I just Unable to Connect'
https://<Kubernetes Master IP>/api/v1beta3/namespaces/default/services/monitoring-grafana/

It is not clear to me on what should this IP be - the Host machine IP of the Kubernetes master or the IP listed under services.

I am using unauthenticated version, per your notes in "heapster-controller.json"
"command": [
                            "/heapster",
                            "--source=kubernetes:http://kubernetes-ro?auth=",
                            "--sink=influxdb:http://monitoring-influxdb:81"
]

and reduced token-ring from volumes.

**Comment by shwetalakhimpur** [comment]
[root@minion01 2015Jun11]# kubectl log monitoring-influx-grafana-controller-t3m8h grafana
2015-06-12T18:21:11.817897874Z Creating config file:  /opt/grafana/config.js.tmpl => /opt/grafana/config.js
2015-06-12T18:21:11.818159522Z
2015-06-12T18:21:11.818173274Z Creating service proxy: /db/ => http://monitoring-influxdb:80/db/
2015-06-12T18:21:11.818179873Z
2015-06-12T18:21:11.818185007Z Listening on :8080
2015-06-12T18:21:11.818190369Z

**Comment by vishh** [comment]
The IP is that of your master. It must be the IP that kubectl uses. You can
run 'kubectl config view` and figure out the master IP. Use that IP to
access Grafana.
Another option is to make Grafana kubernetes service externally accessible.
Take a look at this guide:
https://github.com/GoogleCloudPlatform/heapster/blob/master/docs/influxdb.md#production-setup-for-influxdb-and-grafana

**Comment by shwetalakhimpur** [comment]
The kube config does not have much data, is that a problem ? What should it look like ?
I have been following your guide, will try to make it externally accessible.
# kubectl config view
apiVersion: v1
clusters: []
contexts: []
current-context: ""
kind: Config
preferences: {}
users: []

I am trying to understand the issue here. All the required heapster services and pods are running OK. 
What are the potential things which could go wrong -
a - I am not hitting the right host/port/url. I am certain about my Master IP and trying with that.
b - Some settings are incomplete and missing ?
c - Which logs should I be looking to troubleshoot ?

**Comment by shwetalakhimpur** [comment]
I have set the Public IP grafana-service.json

http://<MASTER NODE>:8080/api/v1beta3/namespaces/default/services/monitoring-grafana/
{
  "kind": "Service",
  "apiVersion": "v1beta3",
  "metadata": {
    "name": "monitoring-grafana",
    "namespace": "default",
    "selfLink": "/api/v1beta3/namespaces/default/services/monitoring-grafana",
    "uid": "28227eb9-11f9-11e5-b3a8-06b8863a81b8",
    "resourceVersion": "340974",
    "creationTimestamp": "2015-06-13T18:22:32Z",
    "labels": {
      "kubernetes.io/cluster-service": "true",
      "kubernetes.io/name": "monitoring-grafana"
    }
  },
  "spec": {
    "ports": [
      {
        "name": "",
        "protocol": "TCP",
        "port": 80,
        "targetPort": 8080
      }
    ],
    "selector": {
      "name": "influxGrafana"
    },
    "portalIP": "10.254.231.84",
    "createExternalLoadBalancer": true,
    "sessionAffinity": "None"
  },
  "status": {}
}

**Comment by shwetalakhimpur** [comment]
Hi Vish,
If you could please help me with the next step.

What works -
http://MASTER-IP:8080/api/v1beta3/namespaces/default/services/monitoring-grafana/
==> Returns the "monitoring-grafana" service

http://INFLUXDB-IP:8083/
==> InfluxDB UI

http://MASTER-IP.166:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/#/dashboard/file/kubernetes.json
==> Grafana UI

What does NOT work -
JS Error on The Grafana UI - click on the Orange/Red Error image on the top left of all the graphs.
Message:
			e.columns is undefined
Stack trace:
			c.getTimeSeries/<@http://MASTER-IP:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/app/app.496fdc2e.js:18:7167
m/he@http://MASTER-IP:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/app/app.496fdc2e.js:7:30701
Yb@http://MASTER-IP:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/app/app.496fdc2e.js:7:17685
c.getTimeSeries@http://MASTER-IP:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/app/app.496fdc2e.js:18:7129
k@http://MASTER-IP:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/app/app.496fdc2e.js:18:10178
b@http://MASTER-IP:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/app/app.496fdc2e.js:7:10053
i@http://MASTER-IP:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/app/app.496fdc2e.js:9:30859
j/<@http://MASTER-IP:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/app/app.496fdc2e.js:9:31046
Rc/this.$get</l.prototype.$eval@http://MASTER-IP:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/app/app.496fdc2e.js:10:6185
Rc/this.$get</l.prototype.$digest@http://MASTER-IP:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/app/app.496fdc2e.js:10:4706
Rc/this.$get</l.prototype.$apply@http://MASTER-IP:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/app/app.496fdc2e.js:10:6450
h@http://MASTER-IP:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/app/app.496fdc2e.js:9:14669
q@http://MASTER-IP:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/app/app.496fdc2e.js:9:16489
kc/</u.onload@http://MASTER-IP:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/app/app.496fdc2e.js:9:17029

**Comment by shwetalakhimpur** [comment]
Per the heapster/docs/storage-schema.md, list series should show the all the metrics being pushed by heapster into influxdb. When I logon to the InfluxDB Admin, click on 'grafana' db, Explore Data,
>list series
I do not see the metrics. How do I check if there is trouble in heapster pushing data into the db ?

https://github.com/GoogleCloudPlatform/heapster/blob/master/docs/storage-schema.md

**Comment by shwetalakhimpur** [comment]
The issue is that the heapster process is not able to connect to apiserver. 

>>docker ps -f <CONTAINER  ID for kubernetes/heapster:v0.13.0>

E0616 15:27:29.027202       1 reflector.go:123] Failed to list *api.Pod: Get http://kubernetes-ro/api/v1beta3/pods?fieldSelector=spec.host%21%3D: dial tcp: lookup kubernetes-ro: no such host
E0616 15:27:29.821323       1 driver.go:321] Database creation failed: Post http://monitoring-influxdb:80/db?u=root&p=root: dial tcp: lookup monitoring-influxdb: no such host. Retrying after 30 seconds

**Comment by vishh** [comment]
Can you try accessing Grafana using the Public IP you assigned to it?
The concept behind Public IPs is that the service is accessible via that IP. So you don't have to go through the API server proxy anymore.

**Comment by shwetalakhimpur** [comment]
I am using a kubernetes cluster of 3 minions, where 1 is MASTER and 2 are MINIONS. 
I have listed the Public IPs to list the 2 minions in "monitoring-influxdb" service.

"heapster-controller.json", has the following command for heapster, where it says - influxdb:http://monitoring-influxdb:80". I was ideally expecting that it will discover the API service as the API-service is configured for the kube service on the minion.
Now, that when we have the Public IPs defined, should this URL influxdb:http://monitoring-influxdb:80" change OR will it discover the influxdb server's IP by looking into the iptable.

"command": [
                            "/heapster",
                            "--source=kubernetes:http://kubernetes-ro?auth=",
                            "--sink=influxdb:http://monitoring-influxdb:80"

**Comment by jimmidyson** [comment]
What version of kubernetes are you running? Have you deployed the DNS add-on? That's required if you're trying to use DNS for services as you are in this case.

**Comment by shwetalakhimpur** [comment]
IBM Softlayer, CentOS Linux release 7.1.1503 (Core)
etcd-2.0.9-2.el7.x86_64
kubernetes-0.15.0-0.3.git0ea87e4.el7.x86_64

OK. I will setup the SkyDNS - https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/dns.md

**Comment by jimmidyson** [comment]
That's a pretty old version of kubernetes & there have been significant improvements to the DNS stiff since then. Any chance you could upgrade?

**Comment by shwetalakhimpur** [comment]
I can upgrade. What is the best way to upgrade ?
Prior to that, i would want to get heapster running even if rather raw method.
Is there a way I can hard-code influxb service IP, so that heapster can reach it without setting up DNS?

Add host to this URL or add sink IP ?
influxdb:http://monitoring-influxdb:80"

**Comment by jimmidyson** [comment]
IIRC you can use env vars in sink URLs something like:

influxdb:http:// ${MONITORING_INFLUXDB_SERVICE_HOST}
:${MONITORING_INFLUXDB_SERVICE_PORT}

**Comment by shwetalakhimpur** [comment]
MONITORING_INFLUXDB_SERVICE_HOST has the local IP and not the Public IP.
Because of this the heapster server is not able to connect to the monitoring-influxdb. I could not find any environment variable which holds the public ip information which has been specified in the services.
What else can I try (before getting to the DNS setup), or force the two docker containers to launch on the same host.

**Comment by jimmidyson** [comment]
If you're running heapster in your cluster then you should be using the service IP (local IP as you call it), not the public IP. Service IPs should be fully routeable inside your cluster, if they're not then you have big problems with your cluster.

**Comment by shwetalakhimpur** [comment]
@jimmidyson - I am not sure what you mean. I followed this guide on Kubernetes cluster setup and it does say here that the Service IP is Kubernetes internal IP address defined in /etc/kubernetes/apiserver. I have the flannel setup which is in the 172.17.x.x range, and this is the IP being assigned as the docker containers come up. 
This IP is accessible from outside. However, the service IP which is  MONITORING_INFLUXDB_SERVICE_HOST, is not accessible.

Is there something amiss here - should service IP be the flannel range. 

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
http://www.severalnines.com/blog/installing-kubernetes-cluster-minions-centos7-manage-pods-services
You should get a 10.254.x.x IP range assigned to the mysql service. This is the Kubernetes internal IP address defined in /etc/kubernetes/apiserver. This IP is not routable outside, so we defined the public IP instead (the interface that connected to external network for that minion):
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by jimmidyson** [comment]
The service IP will not be routable from outside the cluster but should be routable from all pods in the cluster, regardless of what node they are running on. If not then you have a problem with your flannel set up.

You should not be sending data from heapster running in the cluster to a public IP, but rather to the service IP allocated by kubernetes, available in the MONITORING_INFLUXDB_SERVICE_HOST env var. The heapster pod should be able to route to the service IP.

**Comment by shwetalakhimpur** [comment]
OK. then I do need to review setup. I did cleanup all the public IPs, and I have only the service IPs for all the services. My flannel network is 172.17.23.0/16, the Service IP is 10.254.x.x

Thanks for your prompt responses. Appreciate it.

Another question  - on heapster command, do I absolutely must have the source=kubernetes ?

                           "/heapster",
                            "--source=kubernetes:http://kubernetes-ro?auth=",
                            "--sink=influxdb:http://${MONITORING_INFLUXDB_SERVICE_HOST}:80"
reflector.go:123] Failed to list *api.Node: Get http://kubernetes-ro/api/v1beta3/nodes
I get this error. I suppose this is because of the same issue where my serviceIP is not accessible across the cluster.

**Comment by jimmidyson** [comment]
If you don't specify the kubernetes source then heapster won't try to get any data from kubernetes - up to you whether you want that ;)

And yes it looks like the same issue - routing to service IPs from pods.

**Comment by shwetalakhimpur** [comment]
Thanks :). Will continue tomorrow, past midnight for me.

**Comment by shwetalakhimpur** [comment]
@jimmidyson

My updates, based on yesterday's discussion, I cleaned up my cluster to remove all Public IPs, and changed the 
Kubernetes API server inside /etc/kubernetes/apiserver, this is the same as my Flannel network

KUBE_SERVICE_ADDRESSES="--portal_net=172.254.0.0/16"
I am able to ping the Service IPs across the nodes in the cluster

Now the issues - 
1) The kubernetes api-server is still picking up the old IP , and I have no idea from where.
I could not find the cache for this. I rebooted the machine, and restarted all kubernetes,flannel, etcd services but no effect.

NAME                     LABELS                                                                     SELECTOR             IP                PORT(S)
kubernetes               component=apiserver,provider=kubernetes                                    <none>               10.254.0.2        443/TCP
kubernetes-ro            component=apiserver,provider=kubernetes                                    <none>               10.254.0.1        80/TCP


2) Heapster when it starts continues to give this error - this is expected as my kubernetes-ro is not discoverable service
The API server is listed in the kubelet config, but not sure why it does not take the info from there.

How do I make this work ? Will I have to setup the DNS service ?

E0618 13:29:52.448165       1 reflector.go:123] Failed to list *api.Node: Get http://kubernetes-ro/api/v1beta3/nodes: dial tcp: lookup kubernetes-ro: no such host
E0618 13:29:52.448165       1 reflector.go:123] Failed to list *api.Pod: Get http://kubernetes-ro/api/v1beta3/pods?fieldSelector=spec.host%21%3D: dial tcp: lookup kubernetes-ro: no such host

**Comment by jimmidyson** [comment]
Looking better! Yes you will need to set up the DNS add-on so that service names like `kubernetes-ro` are resolvable.

**Comment by shwetalakhimpur** [comment]
Hi, Please provide your inputs ob the following issue -

I am in this interesting situation, and let me try to explain. 

Situation A - 
1 - I can get the heapster to start with the influxdb properly, where I am able to see the data in the influxdb.
2 - I am unable to access the Grafana UI -

http://<MASTERNODE-IP>:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/#/dashboard/file/kubernetes.json

Error: 'dial tcp 172.17.39.55:8080: i/o timeout'
Trying to reach: 'http://172.17.39.55:8080/'

where 172.17.39.55 is the IP assigned to Grafana


Situation B -
1 - I am able to access the Grafana UI OK on URL
http://<MASTERNODE-IP>:8080/api/v1beta3/proxy/namespaces/default/services/monitoring-grafana/#/dashboard/file/kubernetes.json
The UI shows up but cannot show any data as the error shown is - influxDb Error: object Object not found
2 - This is because in this instance the influxdb is not populatd with data


In summary, I can either access the UI or my database is populated properly by heapster. Both are not happening together.
What could be problem here ? Port clash issue ? I have influxdb on port 4050. Grafana and Heapster on port 80

monitoring-grafana       kubernetes.io/cluster-service=true,kubernetes.io/name=monitoring-grafana   name=influxGrafana   172.254.85.167    80/TCP
monitoring-heapster      kubernetes.io/cluster-service=true,name=monitoring-heapster                name=heapster        172.254.17.236    80/TCP
monitoring-influxdb      kubernetes.io/cluster-service=true,name=monitoring-influxdb                name=influxGrafana   172.254.240.32    4050/TCP
monitoring-influxdb-ui   <none>                                                                     name=influxGrafana   172.254.172.226   8083/TCP
                                                                                                                                           8086/TCP

**Comment by vishh** [comment]
I suspect #249 should resolve all the proxy woes that you currently have.

**Comment by piosz** [comment]
Obsolete. Please try the newest version.
