### ISSUE TITLE
Is there support for docker-swarm?

### ISSUE THREAD

**Issue by yoanisgil** [kubernetes/heapster#367]
Hi,

I was wondering if heapster could collect metrics from a swarm cluster? If yes, how would that work? Maybe we can put together a quick tutorial explaining how  heapster  up and running with Swarm.

Bests,

Yoanis.

**Comment by vishh** [comment]
Swarm support doesn't exist as of now. Swarm doesn't seem to provide a
remote API to expose nodes. We can exec 'swarm list' and parse its output
to get a list of nodes. To begin with, we will need cadvisor running on all
nodes though.

Is this something you are interested in working on?

**Comment by yoanisgil** [comment]
Yes I am totally in for it. I will look into swarm API to see if there is something better than doing a swarm list and parsing the ouput ;)

**Comment by vishh** [comment]
Great. Let me know if you run into any issues.

**Comment by yoanisgil** [comment]
Hi @vishh 

I think it might be a good idea to update the sources documentation with an example of what the hosts files should look like for cAdvisor. Initially I though it was a host per file but I was so wrong ;). After reading a bit I cam with this:

{
  "Items": [
    {
      "Name": "N0",
      "IP": "192.168.99.105"
    },
    {
      "Name": "N0",
      "IP": "192.168.99.105"
    }
  ]
}

Let me know if you want me to create a PR for this ;)

Can you please let me know how heapster will work for those two sources above? When I go to InfluxDB and run `list series` it seems like metrics are global to the cluster and not specific to each individual host. Is that about right? Finally I think we should put together a docker-compose file which can help people up and running in no time, which is specially useful if you're a dev ;)

Bests,

Yoanis.

**Comment by vishh** [comment]
A doc PR will benefit everyone! Please do send it over. A compose file also
sounds very useful :)
A single hosts file is what heapster expects. In Influxdb, the host is just
a column as of now. There is one series per metric.

**Comment by yoanisgil** [comment]
Ok. I will try to send the PR today. In which directory should the docker-composer file should live?

**Comment by vishh** [comment]
under 'deploy/'

**Comment by yoanisgil** [comment]
@vishh doc PR is https://github.com/GoogleCloudPlatform/heapster/pull/373. Will create another for docker-compose.

**Comment by yoanisgil** [comment]
@vishh docker-compose pr is https://github.com/GoogleCloudPlatform/heapster/pull/374.

**Comment by yoanisgil** [comment]
@vishh I am having a git of a hard time setting up my dev environment and I cannot seem to find any documentation describing how to do it. I am on OSX Yosemite btw. Any ideas?

**Comment by vmarmol** [comment]
Heapster needs to generate some configs before building try running `make build` from the root (or take a look at the steps the Makefile takes).

**Comment by vishh** [comment]
@yoanisgil: Any progress on this issue?

**Comment by fiunchinho** [comment]
Any updates?

**Comment by piosz** [comment]
Out of the scope of the project - only Kubernetes deployments are supported. See more details: https://github.com/kubernetes/heapster/blob/master/docs/proposals/vision.md
