### ISSUE TITLE
Transition events handling into the cache

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#370]
The in-memory cache does not support events as of now. 
1. A new internal API needs to be defined for kube events
2. Kube events can be stored directly (async) into the cache
3. Events are pulled from the cache for the sinks.
4. Specific events are translated into metrics (sys ooms, container restarts, etc)

cc @afein

**Comment by vishh** [comment]
`1` through `3` is completed. `4` is still pending.

**Comment by mwielgus** [comment]
Obsolete. Eventer handles events in 0.20.
