### ISSUE TITLE
Heapster integration with Cadvisor and influxDB

### ISSUE THREAD

**Issue by mboussaa** [kubernetes/heapster#385]
I can't find documentation on Heapster integration with Cadvisor and influxDB.
Is it possible ? 

I am not using kubernates

**Comment by yoanisgil** [comment]
@mboussaa there is some work in process for this:

https://github.com/GoogleCloudPlatform/heapster/pull/374

you will need to install Docker/Docker Compose but I think it's worth the price. This PR is not merged yet but you can use my branch here:

https://github.com/yoanisgil/heapster/tree/docker-compose-example

and here is some documentation:

https://github.com/yoanisgil/heapster/tree/docker-compose-example/deploy/docker-compose

Let me know if you run into any issues ;).

**Comment by mboussaa** [comment]
Hello,
Thank you for you reply. In fact I am getting an error when executing docker compose up:
heapster_1 | E0706 09:30:58.868929       1 driver.go:322] Database creation failed: Server returned (404): 404 page not found
heapster_1 | . Retrying after 30 seconds

then I didn't understand how can I use heapster using your configuration files

**Comment by vmarmol** [comment]
What are you looking to run @mboussaa? If you're interested in a Heapster that collects from various (non-Kubernetes) cAdvisors it should be possible to set that up with Heapster today.

**Comment by piosz** [comment]
Out of the scope of the project - only Kubernetes deployments are supported. See more details: https://github.com/kubernetes/heapster/blob/master/docs/proposals/vision.md
