### ISSUE TITLE
Update "Running Heapster on Kubernetes" guide to kubernetes v1 API

### ISSUE THREAD

**Issue by nikhiljindal** [kubernetes/heapster#386]
The guide is still based on v1beta3. It talks about fields "createExternalLoadBalancer" and "PublicIPs", which are not there in latest kubernetes v1 API.

**Comment by nikhiljindal** [comment]
cc @vmarmol @vishh

**Comment by nikhiljindal** [comment]
cc @bgrant0607 @dchen1107

**Comment by piosz** [comment]
This is obsolete. The document no longer uses v1beta3 objects.
