### ISSUE TITLE
Kublet port 10250 Response Error

### ISSUE THREAD

**Issue by kgrvamsi** [kubernetes/heapster#404]
Hello,

When i'm trying to fetch the data of a particular minion through the kublet api i dont see any request passing through the api and i receive the following error when i curl

    [fedora@ip-10-20-30-95 ~]$ curl -v http://10.20.30.95:10250/stats/
    *   Trying 10.20.30.95...
    * Connected to 10.20.30.95 (10.20.30.95) port 10250 (#0)
    > GET /stats/ HTTP/1.1
    > User-Agent: curl/7.40.0
    > Host: 10.20.30.95:10250
    > Accept: */*
    >
    < HTTP/1.1 500 Internal Server Error
    < Content-Type: text/plain; charset=utf-8
    < Date: Mon, 13 Jul 2015 10:51:16 GMT
    < Content-Length: 72
    <
    Internal Error: received empty response from "container info for \"/\""

And i checked if the port is running on the minion or not and it is running 

    [fedora@ip-10-20-30-95 ~]$ netstat -vpln |grep 10250

    tcp        0      0 10.20.30.95:10250       0.0.0.0:*               LISTEN      -

I have referred to this issue and i see there is some metrics floating from the kublet api to heapster #15 and i see there is a example curl to fetch the metrics http://sprunge.us/QiJL

Can you please help me out on how i can get the cadvisor based kublet metrics of that particular minion.

**Comment by vishh** [comment]
Kubelet exposes a read only port that exposes the '/stats' endpoint. Can you try accessing via that port?

**Comment by piosz** [comment]
This is not related to Heapster.
