### ISSUE TITLE
Heapster v16 - CentOS support for Kubernetes API v1

### ISSUE THREAD

**Issue by shwetalakhimpur** [kubernetes/heapster#410]
How do I upgrade to the required version on Kubernetes which is required to support API v1 on Cent OS ?
The CentOS repository only contains kubernetes-v0.18
http://cbs.centos.org/repos/virt7-testing/x86_64/os/Packages/

**Comment by vishh** [comment]
Upgrade heapster or kubernetes? Can you clarify your question?

**Comment by piosz** [comment]
This is not related to Heapster project.
