### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by y00181991** [kubernetes/heapster#435]
I am on ubuntu 14.04,use heapster 0.16.0 and k8s 1.0;
and I modify kube-apiserver and kube-controller-manager start shell to make serviceaccount works

 function create-kube-apiserver-opts(){
   cat <<EOF > ~/kube/default/kube-apiserver
 KUBE_APISERVER_OPTS="--address=0.0.0.0 \
 --port=8080 \
 --etcd_servers=http://127.0.0.1:4001 \
 --admission_control=NamespaceLifecycle,NamespaceExists,ServiceAccount,ResourceQuota \
 --service-account-key-file=/srv/kubernetes/paul/server.pem \
 --logtostderr=false \
 --v=3 \
 --service-cluster-ip-range=${1}"
 EOF
 }
function create-kube-controller-manager-opts(){
   cat <<EOF > ~/kube/default/kube-controller-manager
 KUBE_CONTROLLER_MANAGER_OPTS="--master=127.0.0.1:8080 \
 --root-ca-file=/srv/kubernetes/paul/ca.pem \
 --service-account-private-key-file=/srv/kubernetes/paul/serverkey.pem \                                                                                                            
 --logtostderr=false \
 --v=3"
EOF
 
}
  }

when start heapster,I got these errors:

1 reflector.go:136] Failed to list *api.Node: Get https://192.168.3.1:443/api/v1/nodes: x509: certificate signed by unknown authority
E0724 16:03:44.847153       1 reflector.go:136] Failed to list *api.Namespace: Get https://192.168.3.1:443/api/v1/namespaces: x509: certificate signed by unknown authority
E0724 16:03:45.828436       1 reflector.go:136] Failed to list *api.Pod: Get https://192.168.3.1:443/api/v1/pods?fieldSelector=spec.nodeName%21%3D: x509: certificate signed by unknown authority

I use the self-signed  certificate,is that cause the problem?
serviceaccount feature must turn on and these certificate must be configured when using heapster version 0.16.0?
is there a way to access k8s use http?

**Comment by mvdan** [comment]
Very similar to #422, perhaps a duplicate.

**Comment by y00181991** [comment]
yes!

and my heapster-controller.yaml like this;

apiVersion: v1
kind: ReplicationController
metadata:
  name: monitoring-heapster-v5
  namespace: default
  labels:
    k8s-app: heapster
    version: v5
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v5
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v5
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
        - image: gcr.io/google_containers/heapster:v0.16.0
          name: heapster
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          command:
            - /heapster
            - --source=kubernetes:https://kubernetes:443?useServiceAccount=true&auth=&insecure=true
            - --sink=influxdb:http://monitoring-influxdb:8086

the flag insecure=true sounds not to work.

is there a way to force heapster access k8s master via http?

**Comment by mikedanese** [comment]
@y00181991 can you add

```
          volumeMounts: 
            - name: ssl-certs
              mountPath: /etc/ssl/certs
              readOnly: true
      volumes: 
        - name: ssl-certs
          hostPath: 
            path: "/etc/ssl/certs"
```

To the end of your yaml?

**Comment by y00181991** [comment]
I have tried this before, but it's not work;

 k8s api service generate the self-sign cert  by under /var/run/kubernetes  , this cert is CA itself,and I add it to my ca localstore (my os is ubuntu 14.04).

when I use curl to access api seriver from k8s api server , I got the error x509: certificate signed by unknown authority.

That means even I trust the CA on ubuntu 14.04, I will still got this error.

and the client cert and ca cert is mounted in my heapster container.

and I also have tried generate CA myself ,and use it to sign my server cert,config these cert in k8s api servise start shell and manager service start shell .

I also tried use kubernetes/cluster/gce/util.sh to generate these certs.

@mikedanese In my view ,in heapster 0.16.0 ,serviceaccount must be configed, all the cert must be mounted,otherwise heapter will raise an exception on start.
but on ubuntu 14.04 when self-cert used to config these k8s serviers ,  x509: certificate signed by unknown authority.

this block about two days, I am not sure am I clear , I am looking forward to your reponses and help~

**Comment by mikedanese** [comment]
It seems like a bug then if insecure=true used to work. Are you using `--root-ca-file` on the kube-controller-manager? It should point to a root CA signed for the apiserver's cert

**Comment by y00181991** [comment]
yes.

 --root-ca-file="": If set, this root certificate authority will be included in service account's token secret. This must be a valid PEM-encoded CA bundle.
      --service-account-private-key-file="": Filename containing a PEM-encoded private RSA key used to sign service account tokens.

suggest by:
http://kubernetes.io/v1.0/docs/admin/kube-controller-manager.html

**Comment by piosz** [comment]
This seems to be no longer a problem. Also please try to use a new stable version of Heapster.
