### ISSUE TITLE
create heapster-controller failed

### ISSUE THREAD

**Issue by fzu-huang** [kubernetes/heapster#443]
monitoring-heapster-controller-1g681         0/1       API error (404): Cannot start container 401801b72ef28b28f01bda500784d080b5dacfa6077c660e7b978b8ae7a5279a: [8] System error: exec: "/heapster": stat /heapster: no such file or directory

what's wrong??

**Comment by vishh** [comment]
What version of heapster are you using and what setup?

**Comment by fzu-huang** [comment]
version  0.17
i switch the version to 0.16 ，then when i create a  rc,  it is wrong  and log is : 
I0803 08:35:28.200069       1 heapster.go:52] /heapster --source=kubernetes:https://kubernetes --sink=influxdb:http://monitoring-influxdb:80
I0803 08:35:28.200157       1 heapster.go:53] Heapster version 0.16.0
E0803 08:35:28.200587       1 heapster.go:59] open /var/run/secrets/kubernetes.io/serviceaccount/token: no such file or directory

should i  do something in kubernetes???

**Comment by vishh** [comment]
You need to setup service accounts while setting up the cluster. Refer to
kubernetes admin guides.

**Comment by bh016088** [comment]
That should be referenced somewhere in the heapster config guide as service accounts are not a requirement for kubernetes.

**Comment by vishh** [comment]
@bh016088: https://github.com/kubernetes/heapster/blob/master/docs/source-configuration.md#kubernetes

**Comment by piosz** [comment]
Closing as obsolete. Try to use a new stable version of Heapster.
