### ISSUE TITLE
fail to create heapster-service

### ISSUE THREAD

**Issue by foxting1127** [kubernetes/heapster#452]
root@ahri:~/heapster/deploy/kube-config/influxdb# kubectl create -f heapster-service.json
Error from server: error when creating "heapster-service.json": Service "heapster" is forbidden: Namespace kube-system does not exist

I hope to use heapster to collect cadvisor's monitoring data to a db, but failed..anyone could help me with that?

**Comment by afein** [comment]
Hi, which version of Kubernetes are you using?
you can find out with ```kubectl version```

**Comment by foxting1127** [comment]
hi afein,
I used the kubernete version 1.0.1.

**Comment by vishh** [comment]
Can you post the output of `kubectl get pods,rc,svc --namespace-all`?

**Comment by foxting1127** [comment]
NAME                                         READY     STATUS    RESTARTS   AGE
monitoring-influx-grafana-controller-77ohm   2/2       Running   0          4m
CONTROLLER                             CONTAINER(S)   IMAGE(S)                            SELECTOR             REPLICAS
monitoring-influx-grafana-controller   influxdb       kubernetes/heapster_influxdb:v0.3   name=influxGrafana   1
                                       grafana        kubernetes/heapster_grafana:v0.7
NAME                     LABELS                                                                     SELECTOR             IP(S)           PORT(S)
kubernetes               component=apiserver,provider=kubernetes                                    <none>               192.168.3.1     443/TCP
monitoring-grafana       kubernetes.io/cluster-service=true,kubernetes.io/name=monitoring-grafana   name=influxGrafana   192.168.3.50    80/TCP
monitoring-influxdb      name=monitoring-influxdb                                                   name=influxGrafana   192.168.3.216   80/TCP
monitoring-influxdb-ui   <none>                                                                     name=influxGrafana   192.168.3.205   8083/TCP
                                                                                                                                         8086/TCP

**Comment by foxting1127** [comment]
--namespace-all flag seems not accepted in the command.

**Comment by foxting1127** [comment]
kubectl get pods,rc,svc --namespace-all
Error: unknown flag: --namespace-all
Run 'kubectl help' for usage.

**Comment by foxting1127** [comment]
Error from server: error when creating "../../heapster/deploy/kube-config/influxdb/heapster-controller.json": ReplicationController "heapster" is forbidden: Namespace kube-system does not exist
Error from server: error when creating "../../heapster/deploy/kube-config/influxdb/heapster-service.json": Service "heapster" is forbidden: Namespace kube-system does not exist

**Comment by vishh** [comment]
Oh my bad. It's `kubectl get pods,svc,rc --all-namespaces`

**Comment by vishh** [comment]
This is an issue with your kubernetes cluster. Latest clusters are expected to have a kube-system namespace created by default. I would suggest going through kubernetes admin guides and figuring out why the `kube-system` namespace is missing. Alternatively, you can also create kube-system namespace, or update heapster config to run it in the `default` namespace.

**Comment by foxting1127** [comment]
NAMESPACE   NAME                                         READY     STATUS    RESTARTS   AGE
default     monitoring-influx-grafana-controller-77ohm   2/2       Running   0          9m
NAMESPACE   NAME                     LABELS                                                                     SELECTOR             IP(S)           PORT(S)
default     kubernetes               component=apiserver,provider=kubernetes                                    <none>               192.168.3.1     443/TCP
default     monitoring-grafana       kubernetes.io/cluster-service=true,kubernetes.io/name=monitoring-grafana   name=influxGrafana   192.168.3.50    80/TCP
default     monitoring-influxdb      name=monitoring-influxdb                                                   name=influxGrafana   192.168.3.216   80/TCP
default     monitoring-influxdb-ui   <none>                                                                     name=influxGrafana   192.168.3.205   8083/TCP
                                                                                                                                                     8086/TCP
NAMESPACE   CONTROLLER                             CONTAINER(S)   IMAGE(S)                            SELECTOR             REPLICAS
default     monitoring-influx-grafana-controller   influxdb       kubernetes/heapster_influxdb:v0.3   name=influxGrafana   1
                                                   grafana        kubernetes/heapster_grafana:v0.7

**Comment by foxting1127** [comment]
Hi vishh,

Thanks for your reply. I am quite new to heapster and kubernetes, could you give me more guidelines? For example, how do I change heapster config to run it in the default namespace? 

thanks a lot!

**Comment by foxting1127** [comment]
I changed kubernetes to a prior version v.0.18.0, it gives me different error:


root@garen:~# kubectl create -f heapster/deploy/kube-config/influxdb/
Error from server: the server could not find the requested resource
Error from server: the server could not find the requested resource
Error from server: the server could not find the requested resource
Error from server: the server could not find the requested resource
Error from server: the server could not find the requested resource
Error from server: the server could not find the requested resource

**Comment by vishh** [comment]
Just replace 'kube-system' with 'default' in all the config files.

**Comment by foxting1127** [comment]
hi vishh, 

I see..thanks, I will try that.

**Comment by piosz** [comment]
I assume this is no longer a problem. Closing the issue.
