### ISSUE TITLE
StatStore percentile optimization

### ISSUE THREAD

**Issue by alexmavr** [kubernetes/heapster#473]
The StatStore currently calculates percentiles by extracting all represented values before performing sorting. This can be further optimized by sorting the bucket values themselves and then attempting to find the corresponding percentiles .

For example, if only one bucket is stored at a StatStore with 60 resolutions total, then 60 values will be generated before sorting. Instead of that, we could only extract that one bucket's value and return the corresponding percentiles as equal to that bucket's value.
In cases with multiple buckets, we would have to iterate from the back of the sorted bucket slice until we find the  corresponding percentile index that we are aiming for.

\cc @mvdan @vishh

**Comment by mvdan** [comment]
Thanks for opening this!

**Comment by fgrzadkowski** [comment]
Obsolete.
