### ISSUE TITLE
Model Garbage Collection

### ISSUE THREAD

**Issue by afein** [kubernetes/heapster#475]
As of now, the model does not perform garbage collection of entities that have dissapeared from the cluster. We should parse deletion events that are flowing into the cache and remove the corresponding references to PodInfo, NodeInfo and ContainerInfo structs.

This should be resolved before the next Heapster release.

**Comment by vishh** [comment]
@mwielgus: Has this issue been resolved by your recent PRs?

**Comment by mwielgus** [comment]
Completed (for now) with #518 #522 #527
