### ISSUE TITLE
Model API endpoints v2.0

### ISSUE THREAD

**Issue by alexmavr** [kubernetes/heapster#476]
The existing API structure reflects the top-down hierarchy of the actual model. However, there might be use cases where extracting bulk metrics and/or stats might be useful. 

Examples:
/metrics/namespaces/{namespace-name}/pods/?label=X&value=Y&start=Z&end=K 
returns all metrics of all pods in a namespace that satisfy the specified label:value pair within the optional start and end intervals.

/stats/namespaces/{namespace-name}/pods/{pod-name}/containers?label=X&value=Y&start=Z&end=K 
returns all stats of all containers in a pod that satisfy the specified label:value pair within the optional start and end intervals.

Similar top-level endpoints can be implemented, such as /metric-sum/, depending on actual usecases of the model.

\cc @vishh @mwielgus

**Comment by vishh** [comment]
@piosz: This is a proposal for a more long term API. Kindly take a look.

**Comment by piosz** [comment]
cc @fgrzadkowski

**Comment by fgrzadkowski** [comment]
This will be substituted by metrics API.
