### ISSUE TITLE
Add a generic Events API 

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#477]
An events API can be used to surface interesting and critical events targeted towards a cluster admin and also individual users. Here is a sample list of events:
1. Crash looping pods/containers 
2. Pods which get CPU throttled
3. Pods/containers that don't make any progress - critical for best effort tasks.
4. Wasted resources for containers - limits too high when compared to historical utilization.
5. Anomalies across pods with similar Spec (Controllers like Replication, daemon, etc) - Abnormal utilization (possibly due to network issues), suggestion for limits; if application metrics are made available, anomalies can be detected across those metrics as well
6. Cluster utilization - events on low and high thresholds 
7. Node flipping - flapping between ready and notready states
8. .....

@afein: Kindly add other use cases that I might have missed here.

**Comment by piosz** [comment]
Out of the scope of Heapster.
