### ISSUE TITLE
Add integration tests for the model APIs

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#487]
The model API semantics are not tested anywhere as of now. The existing heapster API e2e tests can be extended to test model APIs as well.

**Comment by vishh** [comment]
@afein @piosz @mwielgus Is anyone planning on working on this?

**Comment by piosz** [comment]
@jszczepkowski?

**Comment by afein** [comment]
I am currently busy for the remainder of this week. If noone else picks this up I could work on it over the weekend

**Comment by mwielgus** [comment]
I can take a look.

**Comment by mwielgus** [comment]
First test: #553
