### ISSUE TITLE
in influxdb sink, why storage [metric cumulative value] at series?

### ISSUE THREAD

**Issue by dotNetDR** [kubernetes/heapster#488]
Can I choose to storage each metric an average value, from start to end of time?

cumulative value for grafana display is not friendly, Because it is always growing.

**Comment by vishh** [comment]
Thanks for raising this issue! The answer is yes. Heapster already calculates instantaneous values. It should be straight forward to push instantaneous metrics. I would suggest sticking to the best available resolution.
The reason for storing cumulative is to give users the ability to shape the graph however they want. 
Will you be able to post a PR @dotNetDR ?

**Comment by dotNetDR** [comment]
Thank you for your reply.

I don't know how to find instantaneous values in that file.

is [/sinks/gcm/core.go](https://github.com/kubernetes/heapster/blob/release-0.16.0/sinks/gcm/core.go#L286) ?

**Comment by vishh** [comment]
Yes. The implementation is currently local to GCM sink. We can move the
instantaneous metrics to be top level metrics instead.
