### ISSUE TITLE
Handle metric limits in the model as constants

### ISSUE THREAD

**Issue by alexmavr** [kubernetes/heapster#493]
Limits are currently handled in the model as timeseries, requiring storage through a DayStore.

However, we should expect limits to be constant at the level of Container and Node metrics.
We can only store the latest value of each limit, which can be then used during the aggregation step to calculate the limits of more abstract entities such as Pods, Namespaces and eventually LabelQueries/RCs.

Resolving this issue should reduce the memory footprint of the model by up to half, depending on the observed metric variance.

**Comment by fgrzadkowski** [comment]
Obsolete
