### ISSUE TITLE
Add support for Go 1.5

### ISSUE THREAD

**Issue by mvdan** [kubernetes/heapster#495]
Once https://github.com/kubernetes/kubernetes/pull/13058 is merged, we can update the kubernetes dependency.

**Comment by mvdan** [comment]
Update - kubernetes is not ready yet. See the races still present that were found in https://github.com/kubernetes/kubernetes/pull/13838

**Comment by vishh** [comment]
@mvdan: Itchy to get rid of Go 1.4 huh :)

**Comment by mvdan** [comment]
:) Just adding the note in case anyone is thinking kubernetes is ready since it builds with 1.5.

**Comment by piosz** [comment]
As for now Heapaster is built with go 1.6
