### ISSUE TITLE
/api/v1/model/metrics/ response is empty 

### ISSUE THREAD

**Issue by sanjana-bhat** [kubernetes/heapster#501]
I am running heapster and I can see the metrics flowing to influxdb. But when I try to access the metrics using the following endpoint http://{master-ip}/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/metrics/ I get empty response. Same goes with /api/v1/model/namespaces/ and /api/v1/model/nodes/{node-name}/metrics

I use the following parameters  "--use_model=true","--model_resolution=1m". Any help here is really appreciated.

**Comment by vishh** [comment]
cc @afein

**Comment by afein** [comment]
Do you get any response when accessing `http://{master-ip}/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/`? 
Also, could you tell us the heapster version you're using through `kubectl logs <heapster-pod>`?

**Comment by sanjana-bhat** [comment]
Yes, I do get response for `http://{master-ip}/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/model/`
`[
  "metrics/",
  "namespaces/",
  "nodes/"
]`

Heapster version `0.17.0`

I do see these errors in the log
`W0827 03:52:04.018268       1 impl.go:515] Internal Error: reached unreachable CPU Usage parsing flow
W0827 03:52:04.018483       1 impl.go:515] Internal Error: reached unreachable CPU Usage parsing flow
W0827 03:52:04.018612       1 impl.go:515] Internal Error: reached unreachable CPU Usage parsing flow
E0827 03:52:04.021118       1 util.go:69] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/usr/local/google/home/vishnuk/go/src/github.com/GoogleCloudPlatform/heapster/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:63
/usr/local/google/home/vishnuk/go/src/github.com/GoogleCloudPlatform/heapster/Godeps/_workspace/src/github.com/GoogleCloudPlatform/kubernetes/pkg/util/util.go:54
/usr/lib/google-golang/src/runtime/asm_amd64.s:401
/usr/lib/google-golang/src/runtime/panic.go:387
/usr/lib/google-golang/src/runtime/panic.go:42`

**Comment by mvdan** [comment]
Edited the last comment to fix formatting.

@sanjana-bhat for multiline quotes, to keep newlines, use triple backquotes.

**Comment by sanjana-bhat** [comment]
Thanks @mvdan 
@afein, is there something that I'm missing for the APIs to work?

**Comment by afein** [comment]
Hey @sanjana-bhat, sorry for the delay. The internal error is actually not supposed to occur outside of unit tests, which is quite confusing. It represents a case where your CPU usage metrics are actually flowing into the heapster model backwards in time.

We are currently in the process of refactoring the underlying codebase of the APIs (#478) so this issue might only affect v0.17.0.

Can you try deploying heapster using the docker image located at `afein/heapster-model:latest`?
If your setup is still not operational with that docker image then the underlying problem would be related to your deployment environment, which we can try to dig into further.
If your setup does becomes operational with that docker image then the underlying problem will be fixed in the next heapster release.

Also, can you post the replication controller file that you are using to spawn heapster?

**Comment by sanjana-bhat** [comment]
Heapster RC:
```json
{
    "apiVersion": "v1",
    "kind": "ReplicationController",
    "metadata": {
        "labels": {
            "k8s-app": "heapster",
            "name": "heapster",
            "version": "v6"
        },
        "name": "heapster",
        "namespace": "kube-system"
    },
    "spec": {
        "replicas": 1,
        "selector": {
            "k8s-app": "heapster",
            "version": "v6"
        },
        "template": {
            "metadata": {
                "labels": {
                    "k8s-app": "heapster",
                    "version": "v6"
                }
            },
            "spec": {
                "containers": [
                    {
                        "image": "kubernetes/heapster:v0.17.0",
                        "name": "heapster",
                        "command": [
                            "/heapster",
                            "--source=kubernetes:http://{k8s-master-host}:6443?inClusterConfig=false&auth=",
                            "--sink=influxdb:http://monitoring-influxdb:8086",
                            "--use_model=true",
                            "--model_resolution=1m"
                        ],
                        "ports": [
                            {
                                "containerPort": 8082
                            }
                        ]
                    }
                ]
            }
        }
    }
}
```
I will try with the docker image located at `afein/heapster-model:latest`

**Comment by sanjana-bhat** [comment]
@afein, I still see the same errors
```
W0901 01:44:30.442023       1 impl.go:171] failed to parse ContainerMetricElement: failed to add cpu-limit metric: failed to add metric to DayStore: the provided timepoint has a timestamp in the past
W0901 01:44:30.445863       1 impl.go:171] failed to parse ContainerMetricElement: failed to calculate instantaneous CPU usage: the provided value 0 is less than the previous one 341040435488
W0901 01:44:30.446051       1 impl.go:171] failed to parse ContainerMetricElement: failed to calculate instantaneous CPU usage: the provided value 0 is less than the previous one 341183797709
W0901 01:44:30.446162       1 impl.go:171] failed to parse ContainerMetricElement: failed to calculate instantaneous CPU usage: the provided value 0 is less than the previous one 341311764352
W0901 01:44:30.446275       1 impl.go:171] failed to parse ContainerMetricElement: failed to calculate instantaneous CPU usage: the provided value 0 is less than the previous one 341445209247
E0901 01:44:30.446528       1 util.go:69] Recovered from panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
E0901 01:46:07.622115       1 kube_events.go:127] failed to store events in cache: failed to store event {{NodeReady default  %node% map[] } Node %node% status is now: NodeReady kubelet 2015-09-01 01:35:30 +0000 UTC {{ } {%node%.13ffb6bd3e5c0336  default /api/v1/namespaces/default/events/%node%.13ffb6bd3e5c0336  333599 0 0001-01-01 00:00:00 +0000 UTC 2015-09-01 02:35:30 +0000 UTC map[] map[]} {Node  %node% %node%   } NodeReady Node %node% status is now: NodeReady {kubelet %node%} 2015-09-01 01:35:29 +0000 UTC 2015-09-01 01:35:30 +0000 UTC 2}} - UID cannot be empty
```

**Comment by sanjana-bhat** [comment]
Heapster service file:
```json
{
    "apiVersion": "v1",
    "kind": "Service",
    "metadata": {
        "labels": {
            "kubernetes.io/cluster-service": "true",
            "kubernetes.io/name": "Heapster"
        },
        "name": "heapster",
        "namespace": "kube-system"
    },
    "spec": {
        "ports": [
            {
                "port": 8082,
                "targetPort": 8082
            }
        ],
        "selector": {
            "k8s-app": "heapster"
        }
    }
}
```

**Comment by afein** [comment]
There seems to be some sort of issue with the data that is being scraped from the nodes.
Could you let us know what version of kubernetes you are running through `kubectl version`?

**Comment by sanjana-bhat** [comment]
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.2003+b3bce3aa608834", GitCommit:"b3bce3aa6088345f57c9ae8c6be5802b114a181d", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.2003+b3bce3aa608834", GitCommit:"b3bce3aa6088345f57c9ae8c6be5802b114a181d", GitTreeState:"clean"}
```

**Comment by sanjana-bhat** [comment]
@afein 
I cleaned up etcd to remove all the dead nodes and I don't see the cpu related errors. Also I explicitly create kube-system namespace as that was missing in etcd. After this, only `/api/v1/model/nodes/%node%/stats/` returns me non-empty response. All the other endpoints including `/api/v1/model/metrics` return empty response.

```json
{
  "uptime": 18446744064486179580,
  "stats": {
   "cpu-limit": {
    "minute": {
     "average": 2000,
     "percentile": 2000,
     "max": 2000
    },
    "hour": {
     "average": 2000,
     "percentile": 2000,
     "max": 2000
    },
    "day": {
     "average": 2000,
     "percentile": 2000,
     "max": 2000
    }
   },
   "cpu-usage": {
    "minute": {
     "average": 255,
     "percentile": 255,
     "max": 255
    },
    "hour": {
     "average": 913,
     "percentile": 1590,
     "max": 1650
    },
    "day": {
     "average": 1085,
     "percentile": 1650,
     "max": 1650
    }
   },
   "fs-limit-dev-vda": {
    "minute": {
     "average": 26355142656,
     "percentile": 26355142656,
     "max": 26355142656
    },
    "hour": {
     "average": 26355142700,
     "percentile": 26355142700,
     "max": 26355142700
    },
    "day": {
     "average": 26355142700,
     "percentile": 26355142700,
     "max": 26355142700
    }
   },
   "fs-usage-dev-vda": {
    "minute": {
     "average": 22341485909,
     "percentile": 22341632000,
     "max": 22341632000
    },
    "hour": {
     "average": 22317888664,
     "percentile": 22339956200,
     "max": 22341632000
    },
    "day": {
     "average": 22312987970,
     "percentile": 22327245300,
     "max": 22336712704
    }
   },
   "memory-limit": {
    "minute": {
     "average": 4145524736,
     "percentile": 4145524736,
     "max": 4145524736
    },
    "hour": {
     "average": 4148166656,
     "percentile": 4148166656,
     "max": 4148166656
    },
    "day": {
     "average": 4148166656,
     "percentile": 4148166656,
     "max": 4148166656
    }
   },
   "memory-usage": {
    "minute": {
     "average": 2607667882,
     "percentile": 2607861760,
     "max": 2607861760
    },
    "hour": {
     "average": 2720761118,
     "percentile": 2864709632,
     "max": 2873098240
    },
    "day": {
     "average": 2748737126,
     "percentile": 2873098240,
     "max": 2873098240
    }
   },
   "memory-working": {
    "minute": {
     "average": 1656687274,
     "percentile": 1656778752,
     "max": 1656778752
    },
    "hour": {
     "average": 1959578828,
     "percentile": 2378170368,
     "max": 2390753280
    },
    "day": {
     "average": 2034656870,
     "percentile": 2390753280,
     "max": 2390753280
    }
   }
  }
```

**Comment by sanjana-bhat** [comment]
@afein and @vishh 
I increased the log level and noticed the model data structure is not being updated because of the following warnings "Internal Error: reached unreachable CPU Usage parsing flow" and hence no metrics seem to be added. After debugging I found out that prevRoundedStamp and roundedStamp values are the same and the following condition https://github.com/kubernetes/heapster/blob/master/model/impl.go#L541 is false most of the time. 

I use the default poll_duration and stats_resolution values whereas model_resolution is set to 2m. Any changes that I need to do to fix this?

**Comment by afein** [comment]
From my understanding, it appears that heapster is constantly reading 0 for cpu usage while parsing model data.

Can you try accessing 
`http://{master-ip}/api/v1/proxy/namespaces/kube-system/services/heapster/api/v1/metric-export` and searching for cpu/usage values that are zero?

**Comment by sanjana-bhat** [comment]
@afein, it does seem that way. But cpu/usage values are zero only for specific containers under /system.slice cgroup. But this shouldn't cause the API to return empty response at the cluster, node or namespace level right? Not all values are zero. 

May be add a condition here https://github.com/kubernetes/heapster/blob/master/model/impl.go#L530 if(ok) so that nil pointer dereference doesn't occur? 

Here is a sample response from the above API call:
```json
[
    {
        "labels": {
            "container_base_image": "",
            "container_name": "k8s_etcd.aa8dfebb_kube-dns-v8-kfmsf_kube-system_86936fe4-5207-11e5-9c3e-fa163e56b235_39cdc306",
            "host_id": "illusioninfusion",
            "hostname": "illusioninfusion"
        },
        "metrics": {
            "cpu/limit": [
                {
                    "start": "2015-09-03T18:41:39Z",
                    "end": "2015-09-03T18:41:39Z",
                    "value": 99
                }
            ],
            "cpu/usage": [
                {
                    "start": "2015-09-03T06:46:50Z",
                    "end": "2015-09-03T18:41:39Z",
                    "value": 146200165151
                }
            ],
            "memory/limit": [
                {
                    "start": "2015-09-03T18:41:39Z",
                    "end": "2015-09-03T18:41:39Z",
                    "value": 52428800
                }
            ],
            "memory/major_page_faults": [
                {
                    "start": "2015-09-03T06:46:50Z",
                    "end": "2015-09-03T18:41:39Z",
                    "value": 63
                }
            ],
            "memory/page_faults": [
                {
                    "start": "2015-09-03T06:46:50Z",
                    "end": "2015-09-03T18:41:39Z",
                    "value": 12408
                }
            ],
            "memory/usage": [
                {
                    "start": "2015-09-03T18:41:39Z",
                    "end": "2015-09-03T18:41:39Z",
                    "value": 19165184
                }
            ],
            "memory/working_set": [
                {
                    "start": "2015-09-03T18:41:39Z",
                    "end": "2015-09-03T18:41:39Z",
                    "value": 12181504
                }
            ],
            "network/rx": [
                {
                    "start": "2015-09-03T06:46:50Z",
                    "end": "2015-09-03T18:41:39Z",
                    "value": 0
                }
            ],
            "network/rx_errors": [
                {
                    "start": "2015-09-03T06:46:50Z",
                    "end": "2015-09-03T18:41:39Z",
                    "value": 0
                }
            ],
            "network/tx": [
                {
                    "start": "2015-09-03T06:46:50Z",
                    "end": "2015-09-03T18:41:39Z",
                    "value": 0
                }
            ],
            "network/tx_errors": [
                {
                    "start": "2015-09-03T06:46:50Z",
                    "end": "2015-09-03T18:41:39Z",
                    "value": 0
                }
            ],
            "uptime": [
                {
                    "start": "2015-09-03T06:46:50Z",
                    "end": "2015-09-03T18:41:39Z",
                    "value": 42900007
                }
            ]
        }
    },
    {
        "labels": {
            "container_base_image": "",
            "container_name": "/system.slice/mdmonitor.service",
            "host_id": "illusioninfusion",
            "hostname": "illusioninfusion"
        },
        "metrics": {
            "cpu/limit": [
                {
                    "start": "2015-09-03T18:41:33Z",
                    "end": "2015-09-03T18:41:33Z",
                    "value": 1000
                }
            ],
            "cpu/usage": [
                {
                    "start": "2015-09-02T18:48:42Z",
                    "end": "2015-09-03T18:41:33Z",
                    "value": 0
                }
            ],
            "uptime": [
                {
                    "start": "2015-09-02T18:48:42Z",
                    "end": "2015-09-03T18:41:33Z",
                    "value": 85988219
                }
            ]
        }
    }
]
```

**Comment by afein** [comment]
@sanjana-bhat I added such a condition on #508, which is planned to be merged shortly.

**Comment by sanjana-bhat** [comment]
@afein, I pulled in this condition in my heapster docker image and I see non-empty response for /metrics. Has /stats being removed recently? I built the docker image from the master branch.

**Comment by afein** [comment]
@sanjana-bhat yes, the /stats endpoint has been removed temporarily to facilitate code review. It will be reintroduced in a future PR and it is definitely going to be included in the next heapster release.

Is everything else fully operational?

**Comment by sanjana-bhat** [comment]
Great! Yes, everything looks okay now. Thanks!

**Comment by sanjana-bhat** [comment]
@afein, when is the next heapster release? Can I expect these changes to be a part of that?

**Comment by afein** [comment]
The /stats endpoints were merged today in master, so you should be able to access the full feature set by building the current HEAD.

I am not aware about the exact date of the next release (\cc @vishh), but any further changes until that release would most probably involve internal quality

**Comment by vishh** [comment]
We are waiting on the issues that are part of [this](
https://github.com/kubernetes/heapster/milestones/Enable%20Model%20API)
milestone to be resolved before making a new release.

**Comment by sanjana-bhat** [comment]
@afein, /stats gives average, max and 95th percentile over the past minute. Suppose time now is 23:30, /stats returns average for 23:29?

**Comment by afein** [comment]
As of now, the model is updated roughly every 2.5 * model_resolution (which defaults to 2.5 minutes).

This means that the latest data available through both /stats and /metrics is the average for the last minute that is stored, which could be either 23:28, 23:29 or 23:30. If you are interested in the exact time, you can invoke the /metrics endpoint as well

**Comment by sanjana-bhat** [comment]
I have specified model_resolution to 1 min. Is that considered or it always takes default?

**Comment by afein** [comment]
The model_resolution flag is always considered, however 1 min is also the default value for model_resolution (https://github.com/kubernetes/heapster/blob/master/heapster.go#L43).

**Comment by sanjana-bhat** [comment]
@afein and @vishh, what are the recommended resource specifications for heapster container?

**Comment by vishh** [comment]
I would suggest providing 300MB of memory and 0.2 cores for Heapster to
begin with. If you see heapster getting closer to these limits, let me
know. Disk space should not be of concern since heapster is currently
stateless.

**Comment by vishh** [comment]
I'm closing this issue. @sanjana-bhat feel free to re-open if I failed to address any concerns.

**Comment by ntquyen** [comment]
@vishh I'm using heapster 0.19.0 in k8s 1.2.0 and getting this error couple times in a few days

```
...
W0420 04:09:44.699088       1 impl.go:225] failed to parse ContainerMetricElement: failed to calculate instantaneous CPU usage: the provided value 345625445296 is less than the previous one 370196565249
W0420 04:09:44.699281       1 impl.go:225] failed to parse ContainerMetricElement: failed to calculate instantaneous CPU usage: the provided value 356329092212 is less than the previous one 370196565249
W0420 04:09:44.699440       1 impl.go:225] failed to parse ContainerMetricElement: failed to calculate instantaneous CPU usage: the provided value 359914434773 is less than the previous one 370196565249
W0420 04:09:44.699537       1 impl.go:225] failed to parse ContainerMetricElement: failed to calculate instantaneous CPU usage: the provided value 364883164555 is less than the previous one 370196565249
...
```

heapster pod yaml config:

```
...
- image: kubernetes/heapster:v0.19.0
  name: heapster
  resources:
    limits:
      memory: 300Mi
  ports:
    - name: heapster-api
      containerPort: 8082
      hostPort: 8082
  command:
    - /heapster
    - --source=kubernetes:http://api-server:8080
    - --sink=influxdb:http://influxdb-server:8086
    - --stats_resolution=10s
    - --sink_frequency=15s
...
```

heapster stop sending metrics to influxdb when this error occurred unless I restart the container. 

So please help me more clear on the problem. Is it an async problem between cadvisor and heapster?
