### ISSUE TITLE
Autoscale sink for openshift

### ISSUE THREAD

**Issue by shilpapadgaonkar** [kubernetes/heapster#502]
Hello @jimmidyson @smarterclayton 

Is an autoscale sink similar to this 

https://github.com/kubernetes/heapster/blob/master/sinks/gcmautoscaling/driver.go
 
on roadmap for openshift ?

Regards,
Shilpa

**Comment by smarterclayton** [comment]
Yes - it would be through the hawkular sync.

**Comment by smarterclayton** [comment]
@mwringe

**Comment by mwringe** [comment]
As far as I can tell, the gcmautoscaling sink is just a scaled down version of the gcm sink. Its only meant to gather the specific metrics autoscaling needs (cpu and memory) instead of all the metrics.

The Hawkular sink is already storing all the metrics coming in from Heapster, so it has access to the same cpu and memory metrics.

Is there a link to a card for autoscaling in OpenShift you can post?

**Comment by vishh** [comment]
#481 talks about providing access to data stored in different storage backends via a common API. I would like to integrate hawkular support for auto-scaling through this mechanism.

**Comment by mwringe** [comment]
>I would like to integrate hawkular support for auto-scaling through this mechanism.

Awesome :)

**Comment by shilpapadgaonkar** [comment]
@smarterclayton : Is there some documentation explaining how openshift will use hawkular to implement auto-scaling. Is this the right place --https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/autoscaling.md

**Comment by smarterclayton** [comment]
Yes, the OpenShift team members are trying to work with the autoscaling
team.  It's still in progress so unfortunately we don't have a single
document yet.

On Fri, Aug 28, 2015 at 4:26 AM, shilpapadgaonkar <notifications@github.com>
wrote:

> @smarterclayton <https://github.com/smarterclayton> : Is there some
> documentation explaining how openshift will use hawkular to implement
> auto-scaling. Is this the right place --
> https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/autoscaling.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kubernetes/heapster/issues/502#issuecomment-135661078>
> .
>



-- 
Clayton Coleman | Lead Engineer, OpenShift

**Comment by piosz** [comment]
This is obsolete. Cluster autoscaler for Kubernetes is implemented and it no longer needs signals from Heapster.

cc @mwielgus
