### ISSUE TITLE
InfluxDB: Field label doesn't exist

### ISSUE THREAD

**Issue by plamer** [kubernetes/heapster#507]
Hello,

I've managed to run Heapster with InfluxDB and Grafana on my testing kubernetes cluster but I'm still missing something - I get the cluster statistics, but not the pod's. Here is a screenshot from my dashboard: http://drive.cmailpro.net/~p.kalchev@icn.bg/protected/pwd/1fd655ce302b2e1b5427dd8faff985/Screen%20Shot%202015-08-30%20at%2011.37.56%20AM.png

Any idea what am I missing? Before switching to k8s 1.0 I was running heapster/influxdb/grafana without problems and all stats were displaying correctly.

**Comment by vishh** [comment]
The label format for `heapster` and `influxDB` has changed. Kindly take a
look at the respective pod labels and edit the Grafana graph config
appropriately. Sorry for the confusion. This was fixed upstream, but the
changes haven't been pushed to k8s v1.0.

**Comment by plamer** [comment]
Hey @vishh ,

Something like: "labels =~/k8s-app:heapster/"? In the web  Because that doesn't seem to work either.

**Comment by vishh** [comment]
Does this issue happen for cpu or memory?

**Comment by plamer** [comment]
For both, the error is the same: label doesn't exist. This is the pod:

    [root@k8s-master ~]# kubectl --namespace=kube-system describe pod monitoring-heapster-v8-c4ms9
    Name:				monitoring-heapster-v8-c4ms9
    Namespace:			kube-system
    Image(s):			gcr.io/google_containers/heapster:v0.17.0
    Node:				.../...
    Labels:				k8s-app=heapster,kubernetes.io/cluster-service=true,version=v8
    Status:				Running
    Reason:
    Message:
    IP:				10.16.2.5
    Replication Controllers:	monitoring-heapster-v8 (1/1 replicas created)
    Containers:
      heapster:
        Image:	gcr.io/google_containers/heapster:v0.17.0
        Limits:
          cpu:		100m
          memory:		300Mi
        State:		Running
          Started:		Sat, 29 Aug 2015 16:56:14 +0300
        Ready:		True
        Restart Count:	0
    Conditions:
      Type		Status
      Ready 	True
    No events.

**Comment by vishh** [comment]
Do you have access to the Influxdb UI? The UI is available on port 8083 on
the influxdb service. You might have to make that service public to use the
UI.
Once you get to the UI, can you list all the distinct labels?

**Comment by plamer** [comment]
Hm.. am I looking at the right place? I'm searching in k8s database, with the following query:
http://drive.cmailpro.net/~p.kalchev@icn.bg/protected/pwd/27a14288a5d571af65969c580ea39e/Screen%20Shot%202015-09-04%20at%206.01.58%20PM.png

Can't see "label" field?

**Comment by korczis** [comment]
Any updates? I am still experiencing same problems.

**Comment by mwielgus** [comment]
@korczis What Heapster/influxdb version?

**Comment by korczis** [comment]
Heapster 0.13, influx 0.3. I am following this tutorial
https://github.com/vishh/heapster-1/blob/master/docs/coreos.md

**Comment by piosz** [comment]
Closing as obsolete. Please try to use the latest Heapster release.
