### ISSUE TITLE
Possible race between Manager.Housekeep() and enternalSinkManager.sync()

### ISSUE THREAD

**Issue by piosz** [kubernetes/heapster#509]
After PR #315 introducing cache for external sinks is introduced there is a possible race between goroutine that scrapes data from sources and the one that populates data to sinks. If the first one is slower than the second one no data won't be actually exported and all the time I can see in logs:
```
I0902 13:56:20.605264       1 manager.go:126] starting to scrape data from sources start:2015-09-02 13:54:20.561439292 +0000 UTC end:2015-09-02 13:56:20.605254223 +0000 UTC
I0902 13:58:13.273417       1 external.go:104] no timeseries data between %v and %v2015-09-02 13:56:12.815738708 +0000 UTC 2015-09-02 13:58:13.273198203 +0000 UTC
I0902 13:58:20.933195       1 manager.go:126] starting to scrape data from sources start:2015-09-02 13:56:20.605254223 +0000 UTC end:2015-09-02 13:58:20.933185196 +0000 UTC
I0902 14:00:13.274350       1 external.go:104] no timeseries data between %v and %v2015-09-02 13:58:13.273198203 +0000 UTC 2015-09-02 14:00:13.274113237 +0000 UTC
I0902 14:00:21.254414       1 manager.go:126] starting to scrape data from sources start:2015-09-02 13:58:20.933185196 +0000 UTC end:2015-09-02 14:00:21.254404587 +0000 UTC
I0902 14:02:13.275140       1 external.go:104] no timeseries data between %v and %v2015-09-02 14:00:13.274113237 +0000 UTC 2015-09-02 14:02:13.274917438 +0000 UTC
```

A possible solution to this problem is to replace the current implementation of cache with a queue of data.

cc @vishh @fgrzadkowski @mwielgus @jszczepkowski

**Comment by mvdan** [comment]
I ran into the very same issue when adding `-race` to `go test` here: https://github.com/kubernetes/heapster/pull/504

**Comment by mvdan** [comment]
Confirmed it is fixed since the tests now pass with `-race` consistently.

**Comment by piosz** [comment]
I still can see a problem here. Let's call scraping goroutine S and populating goroutine P. Let's assume that poll_duration=1m and sink_frequency=2m.

S scrapped already data for time inteval [10:00, 10:01] and started scraping for [10:01, 10:02]. Right after P started populating data for [10:00,10:02]. It found only the first part of the data, populated them and marked [10:00, 10:02] interval as done. Right after that S provided data for [10:01, 10:02] interval which will be never exported.

It can happen also in situation when poll_duration=sink_frequency

So there is no more races in terms @mvdan mentioned but some data may be lost.

**Comment by vishh** [comment]
Good catch @piosz! The race you mention does exist today.
