### ISSUE TITLE
Unable to get grafana UI and Influx on 8086 port page not found 

### ISSUE THREAD

**Issue by Naresht-vedams** [kubernetes/heapster#519]
I have a kubernetes single node cluster in ubuntu

_Node details_ 
**kubectl get nodes**
```NAME           LABELS                               STATUS```
```172.16.2.179   kubernetes.io/hostname=172.16.2.179   Ready```

I run this `kubectl create -f deploy/kube-config/influxdb/`

**kubectl -o wide get pods**
``NAME                     READY     STATUS    RESTARTS   AGE       NODE``
``heapster-j81xk            1/1       Running   0          4m        172.16.2.179``
``infludb-grafana-ltna7    2/2       Running   0          4m        172.16.2.179``

**kubectl -o wide get services**
``NAME                  LABELS                         SELECTOR             IP(S)           PORT(S)``
``heapster      kubernetes.io/cluster-service=true,kubernetes.io/name=Heapster     k8s-app=heapster     192.168.3.142   80/TCP``
``kubernetes            component=apiserver,provider=kubernetes    <none> 192.168.3.1     443/TCP``
``monitoring-grafana    kubernetes.io/cluster-service=true,kubernetes.io/name=monitoring-grafana   name=influxGrafana   192.168.3.90    80/TCP``
``monitoring-influxdb   <none>                                  name=influxGrafana   192.168.3.229   8083/TCP``
``                                                                                                                                              8086/TCP``
# Problem:- 
I tried to find ``Grafana`` on _localhost:3000_ but no luck.    
I tried on _localhost:8086_ it displaying ``404 page not found``

# Information:-
Influxdb is running on _localhost:8083_.

On 4194 port cAdvisor is running  

How can I get grafana UI and apart from this, can I configure any thing else.

**Comment by vishh** [comment]
Can you post heapster logs? Grafana should be accessible via the service IP
(`192.168.3.90` in your case).

**Comment by Naresht-vedams** [comment]
@vishh 

# iptables -n -t nat -L
```DNAT       tcp  --  0.0.0.0/0            192.168.3.203        /* default/monitoring-grafana: */ tcp dpt:80 to:10.20.0.72:56627```

* Grafana is accessible from 172.16.2.179:56627 but for 3000 port not accessible. 
* Here I can't access private network like 192.168.3.90.

# kubectl logs heapster-66mz1
```I0905 05:02:37.712569       1 heapster.go:55] /heapster --source=kubernetes:https://kubernetes --sink=influxdb:http://monitoring-influxdb:8086```
```I0905 05:02:37.712629       1 heapster.go:56] Heapster version 0.17.0```
```I0905 05:02:37.723263       1 kube_factory.go:168] Using Kubernetes client with master "https://kubernetes" and version "v1"```
```I0905 05:02:37.723325       1 kube_factory.go:169] Using kubelet port 10255```
```E0905 05:02:57.926683       1 reflector.go:136] Failed to list *api.Node: Get https://kubernetes/api/v1/nodes: dial tcp: lookup kubernetes: no such host```
```E0905 05:02:57.926817       1 reflector.go:136] Failed to list *api.Pod: Get https://kubernetes/api/v1/pods?fieldSelector=spec.nodeName%21%3D: dial tcp: lookup kubernetes: no such host```
```E0905 05:02:57.926932       1 kube_events.go:96] Failed to load events: Get https://kubernetes/api/v1/events: dial tcp: lookup kubernetes: no such host```
```E0905 05:02:57.927004       1 reflector.go:136] Failed to list *api.Namespace: Get https://kubernetes/api/v1/namespaces: dial tcp: lookup kubernetes: no such host```
```E0905 05:03:18.016648       1 driver.go:326] Database creation failed: Post http://monitoring-influxdb:8086/db?u=root&p=root: dial tcp: lookup monitoring-influxdb: no such host. Retrying after 30 seconds```
```E0905 05:03:19.026478       1 reflector.go:136] Failed to list *api.Node: Get https://kubernetes/api/v1/nodes: dial tcp: lookup kubernetes: no such host```
```E0905 05:03:19.026555       1 reflector.go:136] Failed to list *api.Pod: Get https://kubernetes/api/v1/pods?fieldSelector=spec.nodeName%21%3D: dial tcp: lookup kubernetes: no such host```

**Comment by Naresht-vedams** [comment]
@vishh 

You said in this video https://www.youtube.com/watch?v=SZgqjMrxo3g&feature=youtu.be

* For my case it is not displaying monitoring-grafana.

  **kubectl cluster-config**
``Kubernetes master is running at http://172.16.2.179:8080``
***cat ~/.kube/./config***
``apiVersion: v1``
``clusters:``
``- cluster:``
``    insecure-skip-tls-verify: true``
  ``  server: http://172.16.2.179:8080``
 `` name: ubuntu``
``contexts:``
``- context:``
``    cluster: ubuntu``
``    user: ubuntu``
``  name: ubuntu``
``current-context: ubuntu``
``kind: Config``
``preferences: {}``
``users:``
``- name: ubuntu``
``  user:``
``    password: 6GjTCltvpoaqPgDO``
``    username: admin``

Can you explain a bit more what needs to do to get the cluster-info perfectly

**Comment by mvdan** [comment]
@Naresht-vedams edited your comments to fix formatting. For readability, use three backquotes around a multiline paste, not around every line.

**Comment by Naresht-vedams** [comment]
@vishh 

`curl http://172.16.2.179:8080/api/v1/namespaces`

for above URL  I am getting the response like this

```
{
  "kind": "NamespaceList",
  "apiVersion": "v1",
  "metadata": {
    "selfLink": "/api/v1/namespaces",
    "resourceVersion": "20840"
  },
  "items": [
    {
      "metadata": {
        "name": "default",
        "selfLink": "/api/v1/namespaces/default",
        "uid": "9246d446-5389-11e5-a511-0800272179e9",
        "resourceVersion": "5",
        "creationTimestamp": "2015-09-05T04:50:03Z"
      },
      "spec": {
        "finalizers": [
          "kubernetes"
        ]
      },
      "status": {
        "phase": "Active"
      }
    }
  ]
}
```
But in heapster logs , it is trying to connect like `https://kubernetes/api/v1/namespaces` this so it is giving error. what I have to do to fix this.

**Comment by vishh** [comment]
Have you set up kube-dns?

**Comment by Naresht-vedams** [comment]
@vishh 
Now I got it.
Thanks @vishh

**Comment by vishh** [comment]
Closing this issue.

**Comment by pakuni** [comment]
Hey Naresht / Vishh, I am having the same issue what's the fix?

**Comment by Naveen1186** [comment]
Hi Naresht / Vishh, we are also getting same problem ,heapster is getting failed .

Below are our logs , could you please let us know the fix



53:36 PME0206 10:53:36.798791       1 reflector.go:203] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:100: Failed to list *api.Node: Get https://Kubernetes.kubernetes:6443/api/v1/nodes?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:53:36 PME0206 10:53:36.800519       1 reflector.go:203] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: Get https://Kubernetes.kubernetes:6443/api/v1/namespaces?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:53:36 PME0206 10:53:36.802125       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:319: Failed to list *api.Pod: Get https://Kubernetes.kubernetes:6443/api/v1/pods?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:53:40 PMW0206 10:53:40.131358       1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces2/6/2017 6:53:49 PME0206 10:53:49.957914       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: Get https://Kubernetes.kubernetes:6443/api/v1/nodes?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:05 PME0206 10:54:05.000391       1 kubelet.go:270] No nodes received from APIserver.2/6/2017 6:54:07 PME0206 10:54:07.793478       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:327: Failed to list *api.Node: Get https://Kubernetes.kubernetes:6443/api/v1/nodes?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:07 PME0206 10:54:07.799488       1 reflector.go:203] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:100: Failed to list *api.Node: Get https://Kubernetes.kubernetes:6443/api/v1/nodes?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:07 PME0206 10:54:07.801454       1 reflector.go:203] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: Get https://Kubernetes.kubernetes:6443/api/v1/namespaces?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:07 PME0206 10:54:07.802846       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:319: Failed to list *api.Pod: Get https://Kubernetes.kubernetes:6443/api/v1/pods?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:10 PMW0206 10:54:10.130822       1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces2/6/2017 6:54:20 PME0206 10:54:20.959021       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: Get https://Kubernetes.kubernetes:6443/api/v1/nodes?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:38 PME0206 10:54:38.794490       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:327: Failed to list *api.Node: Get https://Kubernetes.kubernetes:6443/api/v1/nodes?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:38 PME0206 10:54:38.800115       1 reflector.go:203] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go:100: Failed to list *api.Node: Get https://Kubernetes.kubernetes:6443/api/v1/nodes?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:38 PME0206 10:54:38.802081       1 reflector.go:203] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: Failed to list *api.Namespace: Get https://Kubernetes.kubernetes:6443/api/v1/namespaces?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:38 PME0206 10:54:38.803496       1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:319: Failed to list *api.Pod: Get https://Kubernetes.kubernetes:6443/api/v1/pods?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:40 PMW0206 10:54:40.132858       1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces2/6/2017 6:54:51 PME0206 10:54:51.960146       1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: Failed to list *api.Node: Get https:/

**Comment by Naveen1186** [comment]
Also 
 cat ~/.kube/config    result
 

apiVersion: v1
kind: Config
clusters:
- cluster:
    api-version: v1
    server: "http://kubernetes.kubernetes.rancher.internal"
  name: "Default"
contexts:
- context:
    cluster: "Default"
  name: "Default"
current-context: "Default"
>

**Comment by DirectXMan12** [comment]
Please paste configuration and logs in a fenced code block so that they are actually readable.

**Comment by pramodshaw** [comment]
` Failed to list *api.Node: Get https://Kubernetes.kubernetes:6443/api/v1/nodes?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:53:36 PME0206 10:53:36.800519 1 reflector.go:203] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84:
 Failed to list *api.Namespace: Get https://Kubernetes.kubernetes:6443/api/v1/namespaces?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:53:36 PME0206 10:53:36.802125 1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:319: 
Failed to list *api.Pod: Get https://Kubernetes.kubernetes:6443/api/v1/pods?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:53:40 PMW0206 10:53:40.131358 1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces2/6/2017 6:53:49 PME0206 10:53:49.957914 1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339: 
Failed to list *api.Node: Get https://Kubernetes.kubernetes:6443/api/v1/nodes?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:05 PME0206 10:54:05.000391 1 kubelet.go:270] No nodes received from APIserver.2/6/2017 6:54:07 PME0206 10:54:07.793478 1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:327: 
Failed to list *api.Node: Get https://Kubernetes.kubernetes:6443/api/v1/nodes?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:07 PME0206 10:54:07.799488 1 reflector.go:203] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go
 Failed to list *api.Node: Get https://Kubernetes.kubernetes:6443/api/v1/nodes?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:07 PME0206 10:54:07.801454 1 reflector.go:203] k8s.io/heapster/metrics/processors/namespace_based_enricher.go:84: 
Failed to list *api.Namespace: Get https://Kubernetes.kubernetes:6443/api/v1/namespaces?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:07 PME0206 10:54:07.802846 1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:319: Failed to list *api.Pod: Get https://Kubernetes.kubernetes:6443/api/v1/pods?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:10 PMW0206 10:54:10.130822 1 listers.go:68] can not retrieve list of objects using index : object has no meta: object does not implement the Object interfaces2/6/2017 6:54:20 PME0206 10:54:20.959021 1 reflector.go:203] k8s.io/heapster/metrics/sources/kubelet/kubelet.go:339:
 Failed to list *api.Node: Get https://Kubernetes.kubernetes:6443/api/v1/nodes?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:38 PME0206 10:54:38.794490 1 reflector.go:203] k8s.io/heapster/metrics/heapster.go:327:
 Failed to list *api.Node: Get https://Kubernetes.kubernetes:6443/api/v1/nodes?resourceVersion=0: dial tcp: i/o timeout2/6/2017 6:54:38 PME0206 10:54:38.800115 1 reflector.go:203] k8s.io/heapster/metrics/processors/node_autoscaling_enricher.go
`

**Comment by pramodshaw** [comment]
`cat ~/.kube/config result

apiVersion: v1
kind: Config
clusters:
- cluster:
    api-version: v1
    server: "http://kubernetes.kubernetes.rancher.internal"
  name: "Default"
contexts:
- context:
    cluster: "Default"
  name: "Default"
current-context: "Default"`

**Comment by pramodshaw** [comment]
Formatted the logs

**Comment by pramodshaw** [comment]
`2017/2/14 上午6:33:49dnsmasq[1]: started, version 2.76 cachesize 10002017/2/14 上午6:33:49dnsmasq[1]: compile time options: IPv6 GNU-getopt no-DBus no-i18n no-IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth no-DNSSEC loop-detect inotify2017/2/14 上午6:33:49dnsmasq[1]: using nameserver 127.0.0.1#100532017/2/14 上午6:33:49dnsmasq[1]: read /etc/hosts - 7 addresses2017/2/14 上午6:33:50dnsmasq[1]: nameserver 127.0.0.1 refused to do a recursive query'
