### ISSUE TITLE
Pods should be stored in one place, along with their metrics and other data. 

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/heapster#520]
Right now there is cache, model storage and store inside podApi's reflector.

**Comment by vishh** [comment]
+1. In general we need a way for handling the lifecycle of entities like
pods, nodes and containers and efficiently communicating that across all
the internal modules.
The cache is meant to just be a temporary storage of data. It is not
expected to be the source for lifecycle events.

**Comment by mwielgus** [comment]
Unfortunately, the cache is used to populate the model storage so right now it is in fact a source/transmitter of pod lifecycle events.

**Comment by vishh** [comment]
Yeah. What do you think about separating out lifecycle events from the
cache? The cache can be a consumer of the lifecycle events.

**Comment by piosz** [comment]
After Heapster big refactoring effort this is no longer an issue.
