### ISSUE TITLE
Separation of model cache consumption and metric aggregation

### ISSUE THREAD

**Issue by alexmavr** [kubernetes/heapster#528]
As of now, the model processes new metrics and performs the aggregation step during the Update operation. 

This is problematic, as the same timestamp is used to track progress in both cases. This forces aggregated metrics to be calculated using only partial values of the last one resolution.

A much better approach would be to perform aggregation outside of the Update operation, using a different timestamp to track progress.

\cc @vishh @mwielgus @piosz

**Comment by jszczepkowski** [comment]
CC @jszczepkowski

**Comment by fgrzadkowski** [comment]
Done in new heapster
