### ISSUE TITLE
Define an internal Spec and Stats API in source package

### ISSUE THREAD

**Issue by piosz** [kubernetes/heapster#542]
To guard against changes in cadvisor API. Follow up https://github.com/kubernetes/heapster/pull/539#issuecomment-140020545

**Comment by piosz** [comment]
I should do it during Kubernetes "code freeze" for 1.1.
cc @mwielgus @vishh

**Comment by vishh** [comment]
This is a very useful refactoring. In addition to k8s, it will help
integrating with docker and possibly other data sources.

**Comment by piosz** [comment]
We no longer use cadvisor types internally. Closing as obsolete
