### ISSUE TITLE
Restricting metrics view to a namespace

### ISSUE THREAD

**Issue by shilpapadgaonkar** [kubernetes/heapster#564]
Hello,
I am currently running heapster(+influxdb + grafana) on openshift. I can see the clusterwide metrics in grafana and can edit the metrics in the dashboard etc. 
I want to however restrict users to be able to see the metrics only for a given namespace (from openshift point of view a user should be able to see metrics only for his project). Any pointers on if and how this can be achieved?

**Comment by shilpapadgaonkar** [comment]
@jimmidyson: Currently we are using the read-only port without auth to make heapster work on openshift. When authentication is introduced, I am guessing this should solve the problem?

I also saw this https://trello.com/c/xWFvS0xc/45-8-hawkular-metrics-security-metrics
for hawkular. Is there something similar planned for heapster?

**Comment by jimmidyson** [comment]
One for @mwringe I think.

**Comment by mwringe** [comment]
What we are doing here for Hawkular will be specific to the Hawkular sink in Heapster, so its not a generic solution for other sinks.

We separate out the metrics from each individual project and store them into separate tenants in Hawkular (https://github.com/kubernetes/heapster/pull/555). In Hawkular will then require a token to be sent with any request and it will be used to authenticate against the OpenShift server.

We need to run some more tests on it though before the Hawkular container will support this security setup.

**Comment by vishh** [comment]
To get similar behavior with InfluxDB and Grafana, we can create a DB per
namespace and let users manage access to those DBs via InfluxDB directly.
InfluxDB documentation [here](
https://influxdb.com/docs/v0.9/administration/authorization.html). In
Grafana, you'd then need to pass in DB credentials in-order to gain access
to your namespace metrics.

**Comment by shilpapadgaonkar** [comment]
@vishh 
Does heapster now support influxdb v0.9?
Could you kindly give me a hint how I can make heapster get this data into namespace specific DBs?

Thanks

**Comment by shilpapadgaonkar** [comment]
@mwringe : I would like to try out the heapster-hawkular sink for my openshift env. Could you kindly point me to some documentation link for the same?

**Comment by vishh** [comment]
#800 is out to support InfluxDB v0.9. To create multiple DBs, the InfluxDB
driver under `sinks/influxdb/driver.go` will have to create a new database
whenever it encounters a new namespace and use that database for all
metrics that belong to that namespace.
From the InfluxDB side you can create users and access policies.

On Thu, Sep 17, 2015 at 12:05 AM, shilpapadgaonkar <notifications@github.com

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
