### ISSUE TITLE
Expose cpu usage in terms of cores

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#568]
Cpu limits are exposed as milli cores, but cpu usage is in terms of nanoseconds. This makes visualizing these metrics together difficult.

**Comment by vishh** [comment]
CAdvisor is currently being updated to expose instantaneous usage.

**Comment by afein** [comment]
Finally! What is the time interval that is used in the calculation of the instantaneous CPU metric?

**Comment by vishh** [comment]
cc @mvdan

**Comment by mvdan** [comment]
See https://github.com/google/cadvisor/pull/861. They are derived from the accumulated cpu usage, so they are updated exactly as often as the accumulated cpu usage is.

**Comment by piosz** [comment]
This is fixed in new Heapster.
