### ISSUE TITLE
Certificate error

### ISSUE THREAD

**Issue by shilpapadgaonkar** [kubernetes/heapster#571]
Hello,
I was earlier able to run heapster on my openshift installation but today when I tried it again, I get an error saying  Failed to list *api.Namespace: Get https://kubernetes.default.svc.cluster.local/api/v1/namespaces: x509: certificate is valid for master4.exampletest.com, not kubernetes.default.svc.cluster.local.

@jimmidyson  
I am still following your user guide https://docs.openshift.org/latest/admin_guide/cluster_metrics.html
where my source in heapster.yaml is
"-source=kubernetes:https://kubernetes.default.svc?auth=&insecure=true&useServiceAccount=true"

**Comment by jimmidyson** [comment]
@shilpapadgaonkar The api server certificate has been created with a different FQDN, `master4.exampletest.com`. Did you do this manually or use the ansible scripts or some other way? There are a couple of SANs (alternative names) that should be added to your api server certificate to help make services that run on your cluster portable & the api server address validate successfully. These are:

```
kubernetes.default.svc
kubernetes.default.svc.cluster.local
```

You will need to regenerate your api server certificates with these SANs. IIRC you can use `oadm ca` a bit like this:

```
oadm ca create-server-cert --cert=master.server.crt --key=master.server.key --hostnames=kubernetes.default.svc,kubernetes.default.svc.cluster.local,localhost,openshift.default.svc.cluster.local,127.0.0.1
```

You can also add `master4.exampletest.com` to the `hostnames` flag if that's the public or externally resolvable address for your cluster & you will need to update the certificate/key paths appropriately.

**Comment by shilpapadgaonkar** [comment]
Thanks.

**Comment by jimmidyson** [comment]
@shilpapadgaonkar Glad that worked for you.

**Comment by lorenzvth7** [comment]
I have the same issue. I'm using OpenShift Origin (installed with ansible). I want to enable metrics using Influxdb, grafana and heapster. I'm using the same user guide.
I have this error logs in the Heapster pod.
```
ip-10-0-0-104.eu-west-1.compute.internal, not kubernetes.default.svc
E1026 10:07:10.011991       1 reflector.go:136] Failed to list *api.Namespace: Get https://kubernetes.default.svc/api/v1/namespaces: x509: certificate is valid for ec2-52-18-247-x.eu-west-1.compute.amazonaws.com, ip-10-0-0-x.eu-west-1.compute.internal, not kubernetes.default.svc
E1026 10:07:10.211997       1 reflector.go:136] Failed to list *api.Pod: Get https://kubernetes.default.svc/api/v1/pods?fieldSelector=spec.nodeName%21%3D: x509: certificate is valid for ec2-52-18-247-x.eu-west-1.compute.amazonaws.com, ip-10-0-0-x.eu-west-1.compute.internal, not kubernetes.default.svc
E1026 10:07:10.235825       1 reflector.go:136] Failed to list *api.Node: Get https://kubernetes.default.svc/api/v1/nodes: x509: certificate is valid for ec2-52-18-247-x.eu-west-1.compute.amazonaws.com,
```
So very similar and I executed your command:

```oadm ca create-server-cert --cert=master.server.crt --key=master.server.key --signer-cert=/etc/origin/master/ca.crt --signer-key=/etc/origin/master/ca.key --signer-serial=/etc/origin/master/ca.serial.txt --hostnames=kubernetes.default.svc,kubernetes.default.svc.cluster.local,localhost,openshift.default.svc.cluster.local,127.0.0.1
```
But it really messed up my OpenShift:
```
[root@ip-10-0-0-104 centos]# oc login
The connection to the server hostname:8443 was refused - did you specify the right host or port?
```
 It said I was not able to login anymore and I had to run the ansible installer again to recover. 
After the recover I had still the same error for Heapster.

**Comment by jimmidyson** [comment]
@lorenzvth7 Try adding the public hostname you're trying to connect to to the list of hostnames passed to the `--hostnames` flag. Once you've done that & restarted the API server, can you check it's running successfully before trying `oc login` again?

**Comment by lorenzvth7** [comment]
@jimmidyson I'm sorry but what do you mean with the public hostname? The domainname?: ```ec2-52-18-247-x.eu-west-1.compute.amazonaws.com```

**Comment by jimmidyson** [comment]
@lorenzvth7 Sorry - I mean whatever address you hit the API server at remotely, if that's the public hostname of the server or a different DNS that you have set up.

**Comment by lorenzvth7** [comment]
I did 
```
oadm ca create-server-cert --cert=master.server.crt --key=master.server.key --signer-cert=/etc/origin/master/ca.crt --signer-key=/etc/origin/master/ca.key --signer-serial=/etc/origin/master/ca.serial.txt --hostnames=kubernetes.default.svc,kubernetes.default.svc.cluster.local,localhost,openshift.default.svc.cluster.local,127.0.0.1,ec2-52-18-247-58.eu-west-1.compute.amazonaws.com
```
And after restarting openshift I've just the same issue.

**Comment by lorenzvth7** [comment]
The logs from the beginning:
```
 1 heapster.go:55] /heapster -source=kubernetes:https://kubernetes.default.svc?auth=&insecure=true&useServiceAccount=true -sink=influxdb:http://influxdb-monitoring:8086
I1026 11:29:18.505734       1 heapster.go:56] Heapster version 0.17.0
I1026 11:29:18.506127       1 kube_factory.go:168] Using Kubernetes client with master "https://kubernetes.default.svc" and version "v1"
I1026 11:29:18.506143       1 kube_factory.go:169] Using kubelet port 10255
I1026 11:29:18.516213       1 driver.go:376] created influxdb sink with options: {root root influxdb-monitoring:8086 k8s false}
I1026 11:29:18.537332       1 heapster.go:66] Starting heapster on port 8082
E1026 11:29:18.538358       1 reflector.go:136] Failed to list *api.Node: Get https://kubernetes.default.svc/api/v1/nodes: x509: certificate is valid for ec2-52-18-247-x.eu-west-1.compute.amazonaws.com, ip-10-0-0-104.eu-west-1.compute.internal, not kubernetes.default.svc
E1026 11:29:18.538417       1 kube_events.go:96] Failed to load events: Get https://kubernetes.default.svc/api/v1/events: x509: certificate is valid for ec2-52-18-247-x.eu-west-1.compute.amazonaws.com, ip-10-0-0-104.eu-west-1.compute.internal, not kubernetes.default.svc
```

**Comment by jimmidyson** [comment]
Did you overwrite the `master.server.crt` & `master.server.key` files wherever they are stored? Possibly in `/etc/origin/master/` looking at your logs.

**Comment by lorenzvth7** [comment]
Okay I did it a few times an I think it works now. I'm also able to login There is a new error:
```
E1026 11:39:53.383614       1 kube_events.go:96] Failed to load events: Get https://kubernetes.default.svc/api/v1/events: dial tcp: lookup kubernetes.default.svc: no such host
E1026 11:39:54.378966       1 driver.go:235] failed to write stats to influxDB - Post http://influxdb-monitoring:8086/db/k8s/series?u=root&p=root&time_precision=s: dial tcp: lookup influxdb-monitoring: no such host
```

**Comment by jimmidyson** [comment]
Have you deployed influxdb in the same namespace? Has it started properly?

**Comment by lorenzvth7** [comment]
I think so,  they are in the same openshift-project (=same namespace). The pod is running fine. I can access the influxdb container. 
```
[root@influxdb-monitoring-a86fq /]#  /etc/init.d/influxdb start    
Setting ulimit -n 65536
Starting the process influxdb [ OK ]
influxdb process was started [ OK ]
```

**Comment by jimmidyson** [comment]
What does `oc get services influxdb-monitoring` show?

**Comment by lorenzvth7** [comment]
```
[root@ip-10-0-0-104 master]# oc get services influxdb-monitoring
NAME                  CLUSTER_IP     EXTERNAL_IP   PORT(S)    SELECTOR                                         AGE
influxdb-monitoring   172.30.62.53   <none>        8086/TCP   component=influxdb-monitoring,provider=fabric8   3d
```

**Comment by lorenzvth7** [comment]
The logs are changed:
```
E1026 11:39:54.378966       1 driver.go:235] failed to write stats to influxDB - Post http://influxdb-monitoring:8086/db/k8s/series?u=root&p=root&time_precision=s: dial tcp: lookup influxdb-monitoring: no such host
E1026 11:49:24.100784       1 driver.go:235] failed to write stats to influxDB - Post http://influxdb-monitoring:8086/db/k8s/series?u=root&p=root&time_precision=s: EOF
```

The last log is several minutes ago. I think the manual start of influxdb (in the container) did the job. I'm also seeing the statistics in grafana in my web browser. So I think it's working now? Thanks!

**Comment by jimmidyson** [comment]
There should be no need to manually start influxdb though...

**Comment by lorenzvth7** [comment]
Weird, maybe I just had to wait a bit longer? Is it possible to curl to the service of influxdb? I get a 404 but I read that's normal? But sometimes I'm seeing some UI for influxdb on tutorialsites.

**Comment by vishh** [comment]
Just curious: How is DNS handled in the case of open shift? Could there be
an issue with DNS here?

**Comment by jimmidyson** [comment]
@vishh skydns is embedded in the openshift binary so instead of the DNS addon deployed as a pod it is embedded in the master.

@lorenzvth7 `404` is normal when using the API port (`8086`). InfluxDB does have a built-in console on port `8083` - if you want to use that then create another service using that as the target port & connect to the service IP (or OpenShift route if you're running in a full-on cluster).
