### ISSUE TITLE
Default memory and cpu limit to that of Node Capacity

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#581]
Current memory and cpu limits for containers are set to a random number which does not signify the logic limits applied by the kernel. We can instead default cpu and memory limits to that of the node.

cc @piosz @mwielgus

**Comment by afein** [comment]
For reference, the memory limits are currently being set to -1 and the cpu limits are being set to 99 millicores.

**Comment by vishh** [comment]
Is this in Heapster?

**Comment by mwielgus** [comment]
Can you provide more context? I don't understand how this issue is related to Heapster.

**Comment by afein** [comment]
This is defined in CAdvisor. 
Machine containers are populated here: https://github.com/google/cadvisor/blob/master/container/raw/handler.go#L168

The behavior you're describing could be handled here as well

**Comment by vishh** [comment]
@mwielgus: If limits are not set on containers, the node's capacity is the limit. So instead of defaulting memory limit to some arbitrary high value, we can set it to node capacity. Similarly for cpu, we can set it to cpu capacity. This defaulting behavior is only required if one of the sources doesn't do it automatically. For example, Cadvisor could perform this defaulting.

**Comment by mwielgus** [comment]
Obsolete.

**Comment by vishh** [comment]
Has this been fixed for real? This will affect monitoring of best effort
pods...

**Comment by piosz** [comment]
As for now we aggregate limit/request metric for node. It's no longer a machine capacity.
