### ISSUE TITLE
heapster deployment with influxdb/grafana

### ISSUE THREAD

**Issue by liuhewei** [kubernetes/heapster#586]
As a beginner, I tried deploying heapster with influxdb/grafana following [guide](https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md) and [manifests](https://github.com/kubernetes/heapster/tree/master/deploy/kube-config/influxdb). I think here might be a mistake:

`"--source=kubernetes:https://kubernetes"`
https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/influxdb/heapster-controller.json#L33

If not change, there will be errors from heapster pod:
```
kubectl logs <heapster-podname>
...
E0919 09:17:33.649401       1 reflector.go:136] Failed to list *api.Node: Get https://kubernetes/api/v1/nodes: dial tcp: lookup kubernetes: no such host
```

I wonder the reason might be the "kubernetes" service only exists under "default" namespace, so the "heapster" under "kube-system" namespace can't reach to "kubernetes" through DNS/Kube-proxy because there is no route under "kube-system". Refer to heapster standalone deployment, I changed the `--source` to :
```
"--source=kubernetes"
```
Following: https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/standalone/heapster-controller.json#L41
Then everything is fine till now.

**Comment by vishh** [comment]
That's interesting. AFAIK DNS is not restricted to namespaces yet in
Kubernetes. In kubernetes clusters, you should be able to re-use existing
deployment files under `deploy/kube-config/`.

Thanks for reporting!

**Comment by jonaz** [comment]
Also ran in to this problem source should be

```
--source=kubernetes:https://kubernetes.default
```

**Comment by vishh** [comment]
That's right. Heapster got moved into `kube-system` namespace and thats the
reason for this breakage. I will fix this right away.

**Comment by jimmidyson** [comment]
Shouldn't it be `kubernetes.default.svc`?

**Comment by vishh** [comment]
The search paths (resolv.conf) include `svc.cluster.local` and so
`kubernetes.default` should work.
