### ISSUE TITLE
Add a kafka sink

### ISSUE THREAD

**Issue by huangyuqi** [kubernetes/heapster#595]
Now, an increasing number of OPS systems have been integrating [kafka](http://kafka.apache.org/documentation.html#introduction)  to provide the functionality of a messaging system. So I want to add a **kafka sink for Heapster**. Would you kindly offer me some advice? : )

**Comment by vishh** [comment]
@huangyuqi: You seemed to closed this issue. Was that intentional?

**Comment by huangyuqi** [comment]
Sorry, @vishh , : ). I have found an existing issue about the kafka sink.: https://github.com/kubernetes/heapster/issues/172. So, i close this one.
