### ISSUE TITLE
Make heapster REST interface compatible with CIM-RS

### ISSUE THREAD

**Issue by gerritbinnenmars** [kubernetes/heapster#603]
Hello,

As mentioned in https://groups.google.com/forum/#!topic/google-containers/2utXt1WvG54
we like to use the REST API of Heapster as monitoring solution in our project github.com/inaetics/kubernetes-demo-cluster.

It would be helpful if Heapster could implement a CIM-RS server to be able to make the container data of a Kubernetes Cluster available in "standard" management tools like Open Pegasus. 
See http://www.dmtf.org/standards/cimrs for the standard

**Comment by vishh** [comment]
@gerritbinnenmars: Can you post a WIP that will demonstrate the changes required? As we discussed over email, I'd be fine with an additional API that exposes data in CIM format.

**Comment by piosz** [comment]
This issue has been inactive for a year so closing it. Please reopen if you think it's still wanted.
