### ISSUE TITLE
Make all cAdvisor REST API info available through HEAPSTER

### ISSUE THREAD

**Issue by gerritbinnenmars** [kubernetes/heapster#604]
Hello,

As mentioned in https://groups.google.com/forum/#!topic/google-containers/2utXt1WvG54
we like to use the REST API of Heapster as monitoring solution in our project github.com/inaetics/kubernetes-demo-cluster.

It would be helpful if Heapster could make all cAdvisor data available. We are especially missing the machine information that cAdvisor contains.

**Comment by vishh** [comment]
@gerritbinnenmars: Thanks for filing the issue. Is this something that you can work on?

**Comment by rohitsardesai83** [comment]
Hello @vishh , I can take this up. Do let me know if I can proceed. Thanks !

**Comment by mwielgus** [comment]
Personally, I would rather not include cAdvisor structs in Heapster api. What is exactly needed? Maybe we could expose the required data through some generic api?

**Comment by jimmidyson** [comment]
The majority of information should be available once #941 is merged - this will be in the heapster API format. Is that enough? Supported metrics shown in https://github.com/kubernetes/heapster/pull/941/files#diff-7ee408da48cb16f010268e3b72643f00R37

**Comment by gerritbinnenmars** [comment]
Hello all,

Thanks for picking this up. We would like to have the machine information like the Node structure with number of cores, the disk Info structure and the NetInfo structure of cAdvisor available. This is needed to build a custom scheduler that is based on the OSGi requirement-capability resolver.
E.g. a specific POD is only placed on machines that have a 10 Gb interface.
Hope it is more clear now.

Greetings Gerrit

**Comment by piosz** [comment]
Those informations are available in api server. It doesn't make sense to duplicate api server functionality in Heapster.
