### ISSUE TITLE
Smarter integration tests timeouts

### ISSUE THREAD

**Issue by mvdan** [kubernetes/heapster#618]
Right now we have an overall timeout of 30m on the integration tests. The timeout is sane because sometimes we have to bring up a cluster, which may take up to 5-10m, plus the tests themselves which may take up to 5m.

The problem is that if the integration tests are broken, they take 30m to fail. Since Jenkins currently only does one job at a time, this means that if a broken PR triggers a few builds, Jenkins can be down for hours. This shouldn't happen.

The timeout should start counting from the point where the cluster is ready. Then the timeout can be lowered to something like 10m, since the tests should never take more than 5m. They usually take around 2m as the model takes roughly 1m to gather up stats.

This way, Jenkins would be stuck for a third of the time it usually would.

CC @vishh

**Comment by vishh** [comment]
At times, we upgrade the test cluster version. That is now tied to the
integration tests themselves for the sake of ease. If we separate cluster
maintenance from integration testing, we can lower the timeout and also
possibly run multiple tests in parallel (each tests needs its own
namespace).

**Comment by piosz** [comment]
It seems to be not a big problem, so closing the issue
