### ISSUE TITLE
Heapster connections to InfluxDB

### ISSUE THREAD

**Issue by jordannielsen** [kubernetes/heapster#619]
I'm trying to spin up a heapster rc in our Kubernetes cluster. I have InfluxDB 0.9.4.1 running outside of Kubernetes. Each time I start the rc  I get the following error:

E0929 23:15:17.504255       1 driver.go:326] Database creation failed: Server returned (404): 404 page not found
. Retrying after 30 seconds

Any ideas?

**Comment by jordannielsen** [comment]
I am using the following options in the rc file:

          command:
            - /heapster
            - --source=kubernetes:http://IP_Address?insecure=true&inClusterConfig=false
            - --sink=influxdb:http://IP_Address:8086

**Comment by jkurz** [comment]
same issue here.

**Comment by thucatebay** [comment]
kubernetes/heapster:v0.18.1 as specified in https://github.com/kubernetes/heapster/blob/master/deploy/kube-config/influxdb/heapster-controller.yaml doesn't work with InfluxDB 0.9.4. I had to build heapster from master branch and create my own Docker image with it.

**Comment by vishh** [comment]
Sorry for the confusion. #634 should fix this issue.

**Comment by piosz** [comment]
fixed by #634
