### ISSUE TITLE
Heapster Pod ExitCode:255 status with restart loop

### ISSUE THREAD

**Issue by prateekrastogi** [kubernetes/heapster#622]
I tried to run heapster using
https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md
and changed Grafanaservice yaml to use NodePort rather than LoadBalancer. After executing kubectl command on the directory, I get following output for my pods: 
NAME                    READY     STATUS         RESTARTS   AGE
heapster-zxvi0          0/1       ExitCode:255   14         22m
infludb-grafana-frz46   2/2       Running        0          22m
kube-dns-v8-nyura       4/4       Running        0          2d
kube-dns-v8-socln       4/4       Running        2          2d
kube-dns-v8-tx505       4/4       Running        0          59m

Needless to say i am unable to access web ui.
Here is my modified grafana-service.yaml

apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-grafana
  name: monitoring-grafana
  namespace: kube-system
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    name: influxGrafana

**Comment by vishh** [comment]
I suspect heapster is being killed by the kernel because of memory limits. Can you try removing the memory limits from heapster cofiguration file?

**Comment by prateekrastogi** [comment]
Hi, I don't have any memory limit set in my config file. Also, I tried running only heapster-rc alone and it is unable to start. docker ps -a shows no trace of heapster container whatsoever. My docker version in 1.7.1, build 2c2c52b-dirty. And the cluster is running on coreos.

**Comment by vishh** [comment]
What version are you running? Can you post heapster logs? Also post the
output of `dmesg` from your host.

**Comment by prateekrastogi** [comment]
i was running 7.3.0 of coreos with k8 1.0.5. After your response I used dmesg and saw some error lines in it, so i tried upgrading the whole cluster first os and then k8, but it broke down whole setup. Then, i created a new setup with latest realeases and heapster working fine on it. Unfortunately, i was not able to log dmesg at that time, nor able to comprehend how mere upgrade broke down whole cluster setup. Thanks for your efforts anyway.
