### ISSUE TITLE
Pods are queried separately

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/heapster#637]
Each pod container is queried in a separate http request. On the other hand all container stats come in `kubelete.go/getAllContainers` but pod stats are dropped. This is likely to cause network problems on big clusters -  30 pods x 250 nodes (=> 250 qps with stats resolution 30sec) which is the target for Kubernets 1.1

**Comment by mwielgus** [comment]
cc: @fgrzadkowski @piosz @wojtek-t @gmarek

**Comment by vishh** [comment]
https://github.com/kubernetes/kubernetes/issues/12483 should solve this.

**Comment by mwielgus** [comment]
Fixed in heapster-scalability.
