### ISSUE TITLE
Heapster gets 1 sample/second from cAdvisor

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/heapster#638]
Even if the stats resolution is 30 seconds. We drop 29 samples but they consume both network(transmission) and cpu&mem (parsing).

**Comment by mwielgus** [comment]
cc: @fgrzadkowski @piosz @gmarek @wojtek-t

**Comment by mwielgus** [comment]
This, combined with #637, means that we transfer up to 60x more data than we actually need.

**Comment by vishh** [comment]
We can request for just one sample instead.

**Comment by piosz** [comment]
This will be fix by introducing Metrics API in Kubeletet https://github.com/kubernetes/kubernetes/issues/12483
