### ISSUE TITLE
Cache should store timeseries, not cadvisor.Stats and cadvisor.Spec

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/heapster#641]
Right now `cadvisor.Spec` is stored with every data set from cAdvisor. I guess the decoding should take place before storing data in the cache, not before sending them to sinks.

**Comment by mwielgus** [comment]
cc: @piosz

**Comment by vishh** [comment]
The cache is used for the API and the model, in addition to the sinks.
So switching over to timeseries might not be possible.
One option is to avoid storing the entire cadvisor object and instead choose to store only the metrics heapster can handle.

**Comment by mwielgus** [comment]
Sinks are fed with timeseries. Model storage does some processing on its own but it is mainly targeted at fighting with cumulative cpu usage. 

I think it is bad. The metrics should come from sources/cache in one common way that doesn't require any extra processing to make them usable.

**Comment by mwielgus** [comment]
I have a strong feeling that the responsibility and isolation between sources, sinks, and data-passing layer should be drawn more clearly. Sources should produce ready-to-use container metrics. Another layer should group the container data into pods, namespaces, nodes etc. Another calculate any derivative metrics that are needed (cummulative cpu -> average cpu). And the final layer: sinks and model would pass it to the external data stores and expose the data to clients.

cc: @jszczepkowski @fgrzadkowski

**Comment by afein** [comment]
Even though this is a very drastic change, I agree that it would lead to a more intuitive structure for the project and a reduced memory footprint.

Alternatively, the model could replace the cache as it already maintains a set of compressed timeseries in memory.

**Comment by vishh** [comment]
Kubelet will return pod and node metrics in the future. Except for this part I agree with the rest of your comments. 
The current state has been reached due to organic growth.

**Comment by mwielgus** [comment]
Fixed in heapster-scalability.
