### ISSUE TITLE
sources/kube_pods.go should be removed

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/heapster#643]
After thinking for a while on #637 I came to conclusion that this way of getting pods+metrics should actually not be needed. Pods are marked quite clearly in Docker ("io.kubernetes.pod.name" label that contains namespace+"/"+name). So a single query to cAdvisor/kubelet for all containers will get us metrics AND the list of pods that are running. We don't care about pods that don't have metrics (are dead, stalled, pending etc). 

Depending only on cAdvisor/kubelet output will simplify things a lot. There will be no need for api watch on pods, no extra watch cache to sync with and no separate queries for metrics.

This will also make pods.go obsolete.

**Comment by mwielgus** [comment]
cc: @vishh @piosz @jszczepkowski @fgrzadkowski

**Comment by mwielgus** [comment]
The only thing that is taken from pod - cpu/mem reservation can be added either to the api or to docker kubelet-generated labels, just like "io.kubernetes.pod.terminationGracePeriod" is right now.

**Comment by vishh** [comment]
We need to watch the API server for metadata. This approach might not work with other runtimes like rocket which can understand pods only. https://github.com/kubernetes/kubernetes/issues/12483 attempts to solve this issue. The labels added by kubelet are an implementation detail and ideally, the rest of the system should not depend on that implementation detail.

**Comment by mwielgus** [comment]
Which metadata (that are not returned by cAdvisor) are needed?

**Comment by mwielgus** [comment]
Fixed in heapster-scalability.
