### ISSUE TITLE
Get list timestap metic record fail?(by get  Heapster Metric Model API)

### ISSUE THREAD

**Issue by ttllyy** [kubernetes/heapster#646]
heapster/docs/model.md
It allows the extraction of up to 1 hour of historical data for any Container, Pod, Node or Namespace in the cluster, as well as the cluster itself.
I set -use_model=true and  -model_resolution=10s

Get
/api/v1/model/namespaces/{namespace-name}/pods/{pod-name}/metrics/{metric-name}?start=X&end=Y
 (If start is not defined, it is assumed as the zero Unix epoch time. If end is not defined, then all data later than start will be returned.)
I don't set start and end param
I think list timestamp number is  (60 x 60) /10 = 360   (1 hour of historical data)

But report 
{
  "metrics": [
   {
    "timestamp": "2015-10-09T20:14:20+08:00",
    "value": 377606144
   },
   {
    "timestamp": "2015-10-09T20:14:10+08:00",
    "value": 381681664
   },
   {
    "timestamp": "2015-10-09T20:14:00+08:00",
    "value": 381681664
   },
   {
    "timestamp": "2015-10-09T20:13:50+08:00",
    "value": 381681664
   },
   {
    "timestamp": "2015-10-09T20:13:40+08:00",
    "value": 381681664
   }
  ],
  "latestTimestamp": "2015-10-09T20:14:20+08:00"
 }

why list is not 360 record?

if i set start and end, url example is ?

**Comment by lvsha1989** [comment]
Have you sloved the problem?

**Comment by piosz** [comment]
We no longer support 1 hour of historical data. To gather it you should query your metric backend. Heapster provides only the latest values.

**Comment by DirectXMan12** [comment]
Alternatively, you can use the Heapster historical API, if your backend supports it (currently only InfluxDB, Hawkular support coming soon).
