### ISSUE TITLE
cpu usage unit is ns，How to correspond to percent？

### ISSUE THREAD

**Issue by ttllyy** [kubernetes/heapster#650]
/api/v1/model/namespaces/{namespace-name}/pods/{pod-name}/metrics/cpu-usage
Returns a set of (Timestamp, Value) pairs for the requested pod-level metric

cpu usage unit is ns，How to correspond to percent?
Every timestamp,  How much is the total time?

**Comment by vishh** [comment]
If a process were to run on one cpu continuously for a second, its usage
will be 1e+9 nanoseconds. If it ran on `n` cores continuously its usage
will n * 1e+9 nanoseconds. Does this make sense?

Percentage will be usage_in_nanoseconds / (capacity_in_absolute_cores *
1e+9).

Meanwhile we are also working on adding an utilization metric.

**Comment by piosz** [comment]
Since there was no follow up, I assume @vishh's clarification fixed the issue.

**Comment by shayeeb-ahmed** [comment]
Can u please still elaborate about the cpu metric shown in <machine-ip>:10255/stats/summary
