### ISSUE TITLE
Data race in Hawkular Sink

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#653]
GOOS=linux GOARCH=amd64 godep go test --test.short -race ./... 
?   	k8s.io/heapster	[no test files]
?   	k8s.io/heapster/api/v1	[no test files]
?   	k8s.io/heapster/api/v1/types	[no test files]
?   	k8s.io/heapster/clusters/coreos	[no test files]
?   	k8s.io/heapster/expapi/v2	[no test files]
?   	k8s.io/heapster/expapi/v2/types	[no test files]
?   	k8s.io/heapster/extpoints	[no test files]
ok  	k8s.io/heapster/integration	1.030s
ok  	k8s.io/heapster/manager	1.044s
ok  	k8s.io/heapster/model	1.413s
ok  	k8s.io/heapster/sinks	22.839s
ok  	k8s.io/heapster/sinks/api	1.023s
ok  	k8s.io/heapster/sinks/cache	19.792s
ok  	k8s.io/heapster/sinks/gcl	1.035s
?   	k8s.io/heapster/sinks/gcm	[no test files]
?   	k8s.io/heapster/sinks/gcmautoscaling	[no test files]
I1014 17:31:33.367523   24826 driver.go:491] Initialised Hawkular Sink with parameters {test-heapster http://127.0.0.1:49355?tenant=test-heapster 0xc820204000 }
I1014 17:31:33.371821   24826 driver.go:491] Initialised Hawkular Sink with parameters {test-heapster http://127.0.0.1:41084?tenant=test-heapster&labelToTenant=projectId 0xc8200f6140 }
==================
WARNING: DATA RACE
Read by goroutine 33:
  k8s.io/heapster/sinks/hawkular.TestStoreTimeseries.func1()
      /home/jenkins/workspace/project/src/k8s.io/heapster/sinks/hawkular/driver_test.go:267 +0x5c
  net/http.HandlerFunc.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1422 +0x47
  net/http/httptest.(*waitGroupHandler).ServeHTTP()
      /tmp/workdir/go/src/net/http/httptest/server.go:200 +0xfe
  net/http.serverHandler.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1862 +0x206
  net/http.(*conn).serve()
      /tmp/workdir/go/src/net/http/server.go:1361 +0x117c

Previous write by goroutine 35:
  k8s.io/heapster/sinks/hawkular.TestStoreTimeseries.func1()
      /home/jenkins/workspace/project/src/k8s.io/heapster/sinks/hawkular/driver_test.go:267 +0x75
  net/http.HandlerFunc.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1422 +0x47
  net/http/httptest.(*waitGroupHandler).ServeHTTP()
      /tmp/workdir/go/src/net/http/httptest/server.go:200 +0xfe
  net/http.serverHandler.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1862 +0x206
  net/http.(*conn).serve()
      /tmp/workdir/go/src/net/http/server.go:1361 +0x117c

Goroutine 33 (running) created at:
  net/http.(*Server).Serve()
      /tmp/workdir/go/src/net/http/server.go:1910 +0x464

Goroutine 35 (running) created at:
  net/http.(*Server).Serve()
      /tmp/workdir/go/src/net/http/server.go:1910 +0x464
==================
==================
WARNING: DATA RACE
Read by goroutine 33:
  k8s.io/heapster/sinks/hawkular.TestStoreTimeseries.func1()
      /home/jenkins/workspace/project/src/k8s.io/heapster/sinks/hawkular/driver_test.go:294 +0x859
  net/http.HandlerFunc.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1422 +0x47
  net/http/httptest.(*waitGroupHandler).ServeHTTP()
      /tmp/workdir/go/src/net/http/httptest/server.go:200 +0xfe
  net/http.serverHandler.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1862 +0x206
  net/http.(*conn).serve()
      /tmp/workdir/go/src/net/http/server.go:1361 +0x117c

Previous write by goroutine 35:
  k8s.io/heapster/sinks/hawkular.TestStoreTimeseries.func1()
      /home/jenkins/workspace/project/src/k8s.io/heapster/sinks/hawkular/driver_test.go:294 +0x950
  net/http.HandlerFunc.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1422 +0x47
  net/http/httptest.(*waitGroupHandler).ServeHTTP()
      /tmp/workdir/go/src/net/http/httptest/server.go:200 +0xfe
  net/http.serverHandler.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1862 +0x206
  net/http.(*conn).serve()
      /tmp/workdir/go/src/net/http/server.go:1361 +0x117c

Goroutine 33 (running) created at:
  net/http.(*Server).Serve()
      /tmp/workdir/go/src/net/http/server.go:1910 +0x464

Goroutine 35 (running) created at:
  net/http.(*Server).Serve()
      /tmp/workdir/go/src/net/http/server.go:1910 +0x464
==================
==================
WARNING: DATA RACE
Read by goroutine 33:
  runtime.growslice()
      /tmp/workdir/go/src/runtime/slice.go:51 +0x0
  k8s.io/heapster/sinks/hawkular.TestStoreTimeseries.func1()
      /home/jenkins/workspace/project/src/k8s.io/heapster/sinks/hawkular/driver_test.go:294 +0x8ba
  net/http.HandlerFunc.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1422 +0x47
  net/http/httptest.(*waitGroupHandler).ServeHTTP()
      /tmp/workdir/go/src/net/http/httptest/server.go:200 +0xfe
  net/http.serverHandler.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1862 +0x206
  net/http.(*conn).serve()
      /tmp/workdir/go/src/net/http/server.go:1361 +0x117c

Previous write by goroutine 35:
  k8s.io/heapster/sinks/hawkular.TestStoreTimeseries.func1()
      /home/jenkins/workspace/project/src/k8s.io/heapster/sinks/hawkular/driver_test.go:294 +0x90b
  net/http.HandlerFunc.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1422 +0x47
  net/http/httptest.(*waitGroupHandler).ServeHTTP()
      /tmp/workdir/go/src/net/http/httptest/server.go:200 +0xfe
  net/http.serverHandler.ServeHTTP()
      /tmp/workdir/go/src/net/http/server.go:1862 +0x206
  net/http.(*conn).serve()
      /tmp/workdir/go/src/net/http/server.go:1361 +0x117c

Goroutine 33 (running) created at:
  net/http.(*Server).Serve()
      /tmp/workdir/go/src/net/http/server.go:1910 +0x464

Goroutine 35 (running) created at:
  net/http.(*Server).Serve()
      /tmp/workdir/go/src/net/http/server.go:1910 +0x464
==================
I1014 17:31:33.380695   24826 driver.go:491] Initialised Hawkular Sink with parameters {heapster http://127.0.0.1:54291?user=tester&pass=hidden 0xc820166500 }
I1014 17:31:33.383568   24826 driver.go:491] Initialised Hawkular Sink with parameters {heapster http://127.0.0.1:39903?filter=label(namespace_id:^$)&filter=label(container_name:^[/system.slice/|/user.slice].*)&filter=name(remove*) 0xc820166640 }
PASS
Found 3 data race(s)
FAIL	k8s.io/heapster/sinks/hawkular	1.050s
ok  	k8s.io/heapster/sinks/influxdb	1.027s
ok  	k8s.io/heapster/sources	1.042s
?   	k8s.io/heapster/sources/api	[no test files]
ok  	k8s.io/heapster/sources/datasource	1.049s
ok  	k8s.io/heapster/sources/nodes	1.031s
ok  	k8s.io/heapster/store	1.018s
ok  	k8s.io/heapster/store/daystore	1.019s
ok  	k8s.io/heapster/store/statstore	1.035s
?   	k8s.io/heapster/third_party/window	[no test files]
?   	k8s.io/heapster/util	[no test files]
?   	k8s.io/heapster/util/gce	[no test files]
ok  	k8s.io/heapster/util/gcstore	1.016s
?   	k8s.io/heapster/validate	[no test files]
?   	k8s.io/heapster/version	[no test files]
godep: go exit status 1

cc @jimmidyson @burmanm 

This is breaking HEAD.

**Comment by jimmidyson** [comment]
@mwringe @burmanm Can you look at this please? Needs to be fixed for opensihft heapster release too.

**Comment by burmanm** [comment]
Okay, it is theoretical data race in a test (if the test would be run in a multithreaded way and the same instance of httptest-server would be used) as the method used inside the goroutine does "++" operator to an outside variable.. This can't be triggered by the test itself as it does not spawn more threads. I'll fix it.

**Comment by jimmidyson** [comment]
@burmanm Is this closed now?

**Comment by burmanm** [comment]
Yep.
