### ISSUE TITLE
panic in sources.(*kubeNodeMetrics).updateStats

### ISSUE THREAD

**Issue by ravilr** [kubernetes/heapster#658]
heapster custom build from commit rev 20f9a2eac6f64d305a71d3c392ee9209c2e65e91
kubernetes : v1.0.5

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x68 pc=0x50a016]

goroutine 570 [running]:
k8s.io/heapster/sources.(*kubeNodeMetrics).updateStats(0xc2080e4a80, 0xc20831d5f0, 0x2f, 0xc2085fc300, 0xe, 0xc2087fe1f0, 0xe, 0xc20831a030, 0x2f, 0x5dc0, ...)
	/var/builds/workspace/46403-v3-component/BUILD_CONTAINER/docker/label/DOCKER-HIGH/app_root/tmp/go/src/k8s.io/heapster/sources/kube_nodes.go:86 +0xc06
k8s.io/heapster/sources.func·002(0xc20831d5f0, 0x2f, 0xc2085fc300, 0xe, 0xc2087fe1f0, 0xe, 0xc20831a030, 0x2f, 0x5dc0, 0xba87cf000)
	/var/builds/workspace/46403-v3-component/BUILD_CONTAINER/docker/label/DOCKER-HIGH/app_root/tmp/go/src/k8s.io/heapster/sources/kube_nodes.go:103 +0x10a
created by k8s.io/heapster/sources.(*kubeNodeMetrics).getNodesInfo
	/var/builds/workspace/46403-v3-component/BUILD_CONTAINER/docker/label/DOCKER-HIGH/app_root/tmp/go/src/k8s.io/heapster/sources/kube_nodes.go:111 +0x4a3

https://github.com/kubernetes/heapster/blob/20f9a2eac6f64d305a71d3c392ee9209c2e65e91/sources/kube_nodes.go#L86
i have a few nodes in the cluster in NotReady status (kubelet down).

**Comment by vishh** [comment]
cc @mwielgus @piosz

**Comment by ravilr** [comment]
I tried to debug this more. what i found out was, one of the node in the cluster was returning empty stats for rawContainerstats call  http://kubelet:10255/stats/container/

**Comment by piosz** [comment]
cc @gmarek

**Comment by vishh** [comment]
Thanks for debugging @ravilr! 
1. heapster should handle this situation gracefully and not panic.
2. We should investigate why kubelet is not exporting stats. This can happen is cAdvisor initialization fails. Can you check your kubelet logs @ravilr?

**Comment by ravilr** [comment]
@vishh, i remember checking the kubelet cadvisor port 4914 directly and it was showing stats at that time. the kubelet logs are rotated now, will check next time this issue recurs.
