### ISSUE TITLE
InfluxDB database 'k8s' is empty

### ISSUE THREAD

**Issue by flyer5200** [kubernetes/heapster#661]
I am deploy a standlone InfluxDB v0.9.4.1, heapster 0.18.2, kubernetes v1.1.0

I try run a command by heapster,

[root@iZ94orq2kz1Z ~]# /usr/local/bin/heapster --source="kubernetes:http://10.116.92.1:8080?inClusterConfig=false" --sink=influxdb:http://10.45.176.243:8086
I1020 16:38:22.346787   17492 heapster.go:61] /usr/local/bin/heapster --source=kubernetes:http://10.116.92.1:8080?inClusterConfig=false --sink=influxdb:http://10.45.176.243:8086
I1020 16:38:22.346875   17492 heapster.go:62] Heapster version 0.18.0
I1020 16:38:22.347061   17492 kube_factory.go:168] Using Kubernetes client with master "http://10.116.92.1:8080" and version "v1"
I1020 16:38:22.347100   17492 kube_factory.go:169] Using kubelet port 10255
I1020 16:38:22.348599   17492 driver.go:316] created influxdb sink with options: {root root 10.45.176.243:8086 k8s false}
I1020 16:38:22.419181   17492 driver.go:245] Created database "k8s" on influxDB server at "10.45.176.243:8086"
I1020 16:38:22.424520   17492 heapster.go:72] Starting heapster on port 8082

But the influxdb database 'k8s' is empty, why?

**Comment by remy-phelipot** [comment]
I have the same problem with the kubernetes endpoint configured in unsecure mode. Here is the configuration for the replication controllers:

Grafana/InfluxDB
``` yaml
apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: 2015-10-22T08:42:33Z
  generation: 1
  labels:
    name: influxGrafana
  name: infludb-grafana
  namespace: kube-system
  resourceVersion: "2249"
  selfLink: /api/v1/namespaces/kube-system/replicationcontrollers/infludb-grafana
  uid: d6ab1f6e-7898-11e5-8753-0016c2000115
spec:
  replicas: 1
  selector:
    name: influxGrafana
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: influxGrafana
    spec:
      containers:
      - image: kubernetes/heapster_influxdb:v0.4
        imagePullPolicy: IfNotPresent
        name: influxdb
        ports:
        - containerPort: 8083
          hostPort: 8083
          protocol: TCP
        - containerPort: 8086
          hostPort: 8086
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
      - image: grafana/grafana:2.1.0
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        volumeMounts:
        - mountPath: /var/lib/grafana
          name: grafana-store
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - emptyDir: {}
        name: grafana-store
status:
  observedGeneration: 1
  replicas: 1
```

Heapster
``` yaml
apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: 2015-10-22T08:42:33Z
  generation: 1
  labels:
    k8s-app: heapster
    name: heapster
    version: v6
  name: heapster
  namespace: kube-system
  resourceVersion: "2250"
  selfLink: /api/v1/namespaces/kube-system/replicationcontrollers/heapster
  uid: d6a5d2ee-7898-11e5-8753-0016c2000115
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - command:
        - /heapster
        - --source=kubernetes:http://212.xxx.xx.21:8888?insecure=true&auth=&inClusterConfig=false
        - --sink=influxdb:http://monitoring-influxdb.kube-system.xxx.xxxx.net:8086
        image: kubernetes/heapster:v0.16.0
        imagePullPolicy: IfNotPresent
        name: heapster
        resources: {}
        terminationMessagePath: /dev/termination-log
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status:
  observedGeneration: 1
  replicas: 1
```

Here are the logs:

```
I1022 08:42:39.879044       1 heapster.go:52] /heapster --source=kubernetes:http://212.xxx.xx.21:8888?insecure=true&auth=&inClusterConfig=false --sink=influxdb:http://monitoring-influxdb.kube-system.xxx.xx.net:8086
I1022 08:42:39.879092       1 heapster.go:53] Heapster version 0.16.0
I1022 08:42:39.879187       1 kube_factory.go:169] Using Kubernetes client with master "http://212.xxx.xx.21:8888" and version "v1"
I1022 08:42:39.879199       1 kube_factory.go:170] Using kubelet port 10255
E1022 08:42:40.062408       1 driver.go:322] Database creation failed: Post http://monitoring-influxdb.kube-system.xxxx.net:8086/db?u=root&p=root: read tcp 10.10.10.213:8086: connection reset by peer. Retrying after 30 seconds
I1022 08:43:10.288550       1 driver.go:297] Created database "k8s" on influxdb
I1022 08:43:10.288603       1 driver.go:376] created influxdb sink with options: {root root monitoring-influxdb.kube-system.xxxxxx.net:8086 k8s false}
I1022 08:43:10.289937       1 heapster.go:64] Starting heapster on port 8082
```

```
[10/22/15 08:42:41] [INFO] Loading configuration file /config/config.toml

+---------------------------------------------+
|  _____        __ _            _____  ____   |
| |_   _|      / _| |          |  __ \|  _ \  |
|   | |  _ __ | |_| |_   ___  _| |  | | |_) | |
|   | | | '_ \|  _| | | | \ \/ / |  | |  _ <  |
|  _| |_| | | | | | | |_| |>  <| |__| | |_) | |
| |_____|_| |_|_| |_|\__,_/_/\_\_____/|____/  |
+---------------------------------------------+
```

The InfluxDB contains an empty 'k8s' table.

**Comment by vishh** [comment]
I suspect that heapster is not able to collect metrics from the nodes. Can
you run heapster with an extra flag? Add the following line to the
`command` section in heapster controller
 `- --vmodule=*=3`

With this option, heapster logs should provide more useful information.

**Comment by remy-phelipot** [comment]
I've "solved" this issue by using the canary version of heapster and I can't go back to the previous version.. I'm sorry vishh.

**Comment by Alpanakabra** [comment]
@remy-phelipot  i face the same problem my k8s is empty . can you share the link or share more info on what did you change?

**Comment by Rastusik** [comment]
I'm having the same issue in my local k8s cluster, any suggestions? Grafana and InfluxDB are configured as NodePort.

When I test the connection to my database from grafana, I'm getting a green status, that the connection is ok, but when I run the same request in curl, I get this output:

{"results":[{"error":"database not found: k8s"}]}

**Comment by vishh** [comment]
cc @piosz @mwielgus

**Comment by Rastusik** [comment]
I managed to solve the problem, but I needed to create the database manuall from the container

**Comment by Rastusik** [comment]
turns out the real problem was something with kube-dns and some secret (maybe a bug - kubernetes/kubernetes#23111). After fixing this according to the guide from the referenced issue, the problem wasn't there anymore.

**Comment by piosz** [comment]
Thanks @Rastusik for the update. Closing the issue.
