### ISSUE TITLE
run heaster with Pod Errors & Node Errors, don't write data to influxdb

### ISSUE THREAD

**Issue by JunejaTung** [kubernetes/heapster#674]
## run heapster with cmd
docker run  -p 8082:8082 docker.io/kubernetes/heapster --source=kubernetes:http://172.27.8.210:8080?inClusterConfig=false&auth=””&useServiceAccount=false --sink=influxdb:http://172.27.8.109:8086
[root@wlan-cloudserver31 wlanuser]# 
eAccount=false --sink=influxdb:http://172.27.8.109:8086:8082 docker.io/kubernetes/heapster --source=kubernetes:http://172.27.8.210:8080?inClusterConfig=false&auth=””&useServic 
[1] 60632
[2] 60633
bash: --sink=influxdb:http://172.27.8.109:8086: No such file or directory
[2]+  Done                    auth=””
[root@wlan-cloudserver31 wlanuser]# Usage of loopback devices is strongly discouraged for production use. Either use `--storage-opt dm.thinpooldev` or use `--storage-opt dm.no_warn_on_loop_devices=true` to suppress this warning.
I1024 11:16:14.672580       1 heapster.go:55] /heapster --source=kubernetes:http://172.27.8.210:8080?inClusterConfig=false
I1024 11:16:14.673423       1 heapster.go:56] Heapster version 0.18.2
I1024 11:16:14.673832       1 kube_factory.go:169] Using Kubernetes client with master "http://172.27.8.210:8080" and version "v1"
I1024 11:16:14.673859       1 kube_factory.go:170] Using kubelet port 10255
I1024 11:16:14.682032       1 heapster.go:66] Starting heapster on port 8082
E1024 11:16:20.086757       1 kube.go:86] Skipping host wlan-cloudserver34 since looking up its IP failed - lookup wlan-cloudserver34: no such host
E1024 11:16:20.086760       1 kube.go:86] Skipping host wlan-cloudserver35 since looking up its IP failed - lookup wlan-cloudserver35: no such host
E1024 11:16:20.091360       1 kube.go:86] Skipping host wlan-cloudserver35 since looking up its IP failed - lookup wlan-cloudserver35: no such host
E1024 11:16:20.091703       1 kube.go:86] Skipping host wlan-cloudserver32 since looking up its IP failed - lookup wlan-cloudserver32: no such host
E1024 11:16:20.092085       1 kube.go:86] Skipping host wlan-cloudserver32 since looking up its IP failed - lookup wlan-cloudserver32: no such host
E1024 11:16:20.093824       1 kube.go:86] Skipping host wlan-cloudserver33 since looking up its IP failed - lookup wlan-cloudserver33: no such host
E1024 11:16:20.094239       1 kube.go:86] Skipping host wlan-cloudserver33 since looking up its IP failed - lookup wlan-cloudserver33: no such host
E1024 11:16:20.096410       1 kube.go:86] Skipping host wlan-cloudserver34 since looking up its IP failed - lookup wlan-cloudserver34: no such host
E1024 11:16:25.004851       1 kube.go:86] Skipping host wlan-cloudserver34 since looking up its IP failed - lookup wlan-cloudserver34: no such host
E1024 11:16:25.004852       1 kube.go:86] Skipping host wlan-cloudserver32 since looking up its IP failed - lookup wlan-cloudserver32: no such host
E1024 11:16:25.006846       1 kube.go:86] Skipping host wlan-cloudserver35 since looking up its IP failed - lookup wlan-cloudserver35: no such host
E1024 11:16:25.006860       1 kube.go:86] Skipping host wlan-cloudserver33 since looking up its IP failed - lookup wlan-cloudserver33: no such host
E1024 11:16:25.008594       1 kube.go:86] Skipping host wlan-cloudserver32 since looking up its IP failed - lookup wlan-cloudserver32: no such host
E1024 11:16:25.008723       1 kube.go:86] Skipping host wlan-cloudserver34 since looking up its IP failed - lookup wlan-cloudserver34: no such host
E1024 11:16:25.010908       1 kube.go:86] Skipping host wlan-cloudserver33 since looking up its IP failed - lookup wlan-cloudserver33: no such host
E1024 11:16:25.010907       1 kube.go:86] Skipping host wlan-cloudserver35 since looking up its IP failed - lookup wlan-cloudserver35: no such host
^C
[root@wlan-cloudserver31 wlanuser]# E1024 11:16:30.009168       1 kube.go:86] Skipping host wlan-cloudserver34 since looking up its IP failed - lookup wlan-cloudserver34: no such host
E1024 11:16:30.009170       1 kube.go:86] Skipping host wlan-cloudserver32 since looking up its IP failed - lookup wlan-cloudserver32: no such host
E1024 11:16:30.011022       1 kube.go:86] Skipping host wlan-cloudserver35 since looking up its IP failed - lookup wlan-cloudserver35: no such host
E1024 11:16:30.011038       1 kube.go:86] Skipping host wlan-cloudserver33 since looking up its IP failed - lookup wlan-cloudserver33: no such host
E1024 11:16:30.012377       1 kube.go:86] Skipping host wlan-cloudserver32 since looking up its IP failed - lookup wlan-cloudserver32: no such host
E1024 11:16:30.012382       1 kube.go:86] Skipping host wlan-cloudserver34 since looking up its IP failed - lookup wlan-cloudserver34: no such host
E1024 11:16:30.014075       1 kube.go:86] Skipping host wlan-cloudserver35 since looking up its IP failed - lookup wlan-cloudserver35: no such host
E1024 11:16:30.014303       1 kube.go:86] Skipping host wlan-cloudserver33 since looking up its IP failed - lookup wlan-cloudserver33: no such host

## http://172.27.8.210:8082/validate/
when i access heapster:8082 there are some errors tips: 
Heapster Version: 0.18.2

Source type: kube-pod-metrics
	Pod Errors: map[{name:jenkins-master-xongc id:4455aeed-7a2b-11e5-8c76-fa163e77e286 ip:172.27.8.212}:24 {name:portal-master-82yce id:bbf6da3b-7a28-11e5-8c76-fa163e77e286 ip:172.27.8.212}:24]

Source type: Kube Node Metrics
Kubernetes Nodes plugin: 
	Healthy Nodes:
	Node Errors: map[wlan-cloudserver32:48 wlan-cloudserver33:48 wlan-cloudserver34:48 wlan-cloudserver35:48]

Source type: kube-events
External Sinks
	Exported metrics:
		uptime: Number of milliseconds since the container was started
		cpu/usage: Cumulative CPU usage on all cores
		cpu/limit: CPU hard limit in millicores.
		cpu/request: CPU request (the guaranteed amount of resources) in millicores. This metric is Kubernetes specific.
		memory/usage: Total memory usage
		memory/working_set: Total working set usage. Working set is the memory being used and not easily dropped by the kernel
		memory/limit: Memory hard limit in bytes.
		memory/request: Memory request (the guaranteed amount of resources) in bytes. This metric is Kubernetes specific.
		memory/page_faults: Number of page faults
		memory/major_page_faults: Number of major page faults
		network/rx: Cumulative number of bytes received over the network
		network/rx_errors: Cumulative number of errors while receiving over the network
		network/tx: Cumulative number of bytes sent over the network
		network/tx_errors: Cumulative number of errors while sending over the network
		filesystem/usage: Total number of bytes consumed on a filesystem
		filesystem/limit: The total size of filesystem in bytes
	Exported labels:
		hostname: Hostname where the container ran
		host_id: Identifier specific to a host. Set by cloud provider or user
		container_name: User-provided name of the container or full container name for system containers
		container_base_image: User-defined image name that is run inside the container
		pod_name: The name of the pod
		pod_id: The unique ID of the pod
		pod_namespace: The namespace of the pod
		namespace_id: The UID of namespace of the pod
		labels: Comma-separated list of user-provided labels
		resource_id: Identifier(s) specific to a metric
	External Sinks:

## kubectl version 
[root@wlan-cloudserver31 kubernetes]# kubectl version
Client Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.1909+280b66c9012c21", GitCommit:"b9a88a7d0e357be2174011dd2b127038c6ea8929", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.1909+280b66c9012c21", GitCommit:"b9a88a7d0e357be2174011dd2b127038c6ea8929", GitTreeState:"clean"}

## nodes
[root@wlan-cloudserver31 kubernetes]# kubectl get nodes
NAME                 LABELS                                      STATUS
wlan-cloudserver32   kubernetes.io/hostname=wlan-cloudserver32   Ready
wlan-cloudserver33   kubernetes.io/hostname=wlan-cloudserver33   Ready
wlan-cloudserver34   kubernetes.io/hostname=wlan-cloudserver34   Ready
wlan-cloudserver35   kubernetes.io/hostname=wlan-cloudserver35   NotReady

## list series 
when i 'list series' on influxdb:8083, results: 
Server returned error: error parsing query: found list, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 1
Unable to fetch list of databases.

what's wrong with my heapster? thanks

**Comment by JunejaTung** [comment]
when i got run with ./heapster --source=kubernetes:http://172.27.8.210:8080?inClusterConfig=false&auth=””&useServiceAccount=false --sink=influxdb:http://172.27.8.109:8086?user=root&pw=root&db=k8s
it run ok .

**Comment by vishh** [comment]
* You need to run kube-dns addon.
* We recommend setting up service accounts as part of kube cluster setup.

**Comment by vishh** [comment]
Kindly re-open this issue if the documentation under `docs/source-configuration.md` does not help you resolve your current issues :)

**Comment by JunejaTung** [comment]
@vishh thanks for your help, i run heapster in standalone type (make the heapster source code, adn ./heapster ...), then the doubt hasn't encounter!
