### ISSUE TITLE
lookup monitoring-influxdb: no such host, not found with , 500 can't access influxdb service

### ISSUE THREAD

**Issue by JunejaTung** [kubernetes/heapster#675]
## run heapster in deploy/kube-config/influxdb
the heapster have to restart!
[root@wlan-cloudserver31 opt]# kubectl get pods --all-namespaces=true
NAMESPACE     NAME                     READY     STATUS    RESTARTS   AGE
default       jenkins-master-xongc     1/1       Running   0          2d
default       portal-master-82yce      1/1       Running   0          2d
default       portal-slave-helec       1/1       Running   0          2h
kube-system   heapster-qwuma           1/1       Running   4          4m
kube-system   influxdb-grafana-a960j   2/2       Running   0          4m
[root@wlan-cloudserver31 opt]# kubectl cluster-info 
Kubernetes master is running at http://localhost:8080
Heapster is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/heapster
monitoring-grafana is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana
monitoring-influxdb is running at http://localhost:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb
[root@wlan-cloudserver31 opt]# 

## heapster start errors log
can't find host : monitoring-influxdb ! 
[root@wlan-cloudserver34 opt]# docker logs 54eb1dd90335
I1026 11:10:46.197658       1 heapster.go:60] /heapster --source=kubernetes:https://172.27.8.210:8080?inClusterConfig=false&useServiceAccount=false --sink=influxdb:http://monitoring-influxdb:8086
I1026 11:10:46.198138       1 heapster.go:61] Heapster version 0.18.0
I1026 11:10:46.198479       1 kube_factory.go:168] Using Kubernetes client with master "https://172.27.8.210:8080" and version "v1"
I1026 11:10:46.198491       1 kube_factory.go:169] Using kubelet port 10255
F1026 11:11:06.228878       1 heapster.go:67] failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp: lookup monitoring-influxdb: no such host
[root@wlan-cloudserver34 opt]#

## not found with access services monitoring-grafana & monitoring-influxdb
when i access  http://Master-IP:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-influxdb ,then returns:
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "no endpoints available for \"monitoring-influxdb\"",
  "code": 500
}
monitoring-granafa , then web returns:
Error: 'dial tcp 172.17.76.7:3000: no route to host'
Trying to reach: 'http://172.17.76.7:3000/'

## other info
#iptables -n -t nat -L
Chain KUBE-PORTALS-CONTAINER (1 references)
target     prot opt source               destination         
REDIRECT   tcp  --  0.0.0.0/0            10.254.0.1           /* default/kubernetes: */ tcp dpt:443 redir ports 41651
REDIRECT   tcp  --  0.0.0.0/0            10.254.173.124       /* default/portal-master: */ tcp dpt:6379 redir ports 49906
REDIRECT   tcp  --  0.0.0.0/0            10.254.98.56         /* default/maintain-master: */ tcp dpt:6379 redir ports 44546
REDIRECT   tcp  --  0.0.0.0/0            10.254.217.179       /* default/portal-slave: */ tcp dpt:6379 redir ports 48370
REDIRECT   tcp  --  0.0.0.0/0            10.254.153.176       /* kube-system/monitoring-grafana: */ tcp dpt:3000 redir ports 40908
REDIRECT   tcp  --  0.0.0.0/0            10.254.179.183       /* kube-system/heapster: */ tcp dpt:8082 redir ports 60679
REDIRECT   tcp  --  0.0.0.0/0            10.254.9.117         /* kube-system/monitoring-influxdb:http */ tcp dpt:8083 redir ports 34619
REDIRECT   tcp  --  0.0.0.0/0            10.254.9.117         /* kube-system/monitoring-influxdb:api */ tcp dpt:8086 redir ports 50330

Chain KUBE-PORTALS-HOST (1 references)
target     prot opt source               destination         
DNAT       tcp  --  0.0.0.0/0            10.254.0.1           /* default/kubernetes: */ tcp dpt:443 to:172.27.8.211:41651
DNAT       tcp  --  0.0.0.0/0            10.254.173.124       /* default/portal-master: */ tcp dpt:6379 to:172.27.8.211:49906
DNAT       tcp  --  0.0.0.0/0            10.254.98.56         /* default/maintain-master: */ tcp dpt:6379 to:172.27.8.211:44546
DNAT       tcp  --  0.0.0.0/0            10.254.217.179       /* default/portal-slave: */ tcp dpt:6379 to:172.27.8.211:48370
DNAT       tcp  --  0.0.0.0/0            10.254.153.176       /* kube-system/monitoring-grafana: */ tcp dpt:3000 to:172.27.8.211:40908
DNAT       tcp  --  0.0.0.0/0            10.254.1

[root@wlan-cloudserver31 heapster]# kubectl version
Client Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.1909+280b66c9012c21", GitCommit:"b9a88a7d0e357be2174011dd2b127038c6ea8929", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1+", GitVersion:"v1.1.0-alpha.0.1909+280b66c9012c21", GitCommit:"b9a88a7d0e357be2174011dd2b127038c6ea8929", GitTreeState:"clean"}
[root@wlan-cloudserver31 heapster]# more deploy/kube-config/influxdb-test/heapster-controller.yaml 
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    name: heapster
    version: v6
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - name: heapster
        image: kubernetes/heapster:canary
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:https://172.27.8.210:8080?inClusterConfig=false&useServiceAccount=false
        - --sink=influxdb:http://monitoring-influxdb:8086
[root@wlan-cloudserver31 heapster]# 

what's wrong with my heapster? services heapster have to restart because can't find monitoring-influxdb host, and services influxdb & granafa has started but i can't access them ..

**Comment by thucatebay** [comment]
From your list of pods, it looks like skydns  wasn't there. You'll need to enable the DNS add-on to access InfluxDB service via ```monitoring-influxdb```.

**Comment by vishh** [comment]
Yeah. kube-dns addon needs to be run. If you choose to not run that, you
will have to pass the IP of monitoring-influxdb service to heapster.

**Comment by JunejaTung** [comment]
@vishh @thucatebay  I'm sorry ，i can't find any documention for kube-dns，how to start kube-dns？

**Comment by thucatebay** [comment]
@JunejaTung https://github.com/kubernetes/kubernetes/tree/release-1.1/cluster/addons/dns.

**Comment by JunejaTung** [comment]
@thucatebay  thanks, i had try to lauch kube-dns, encounter many questions no luck. then i try to pass the ips to all services for refer, then all pods and services (heapster , influxdb , granafa) run normal. i will try to resolve other troubles such as grafana web returns no figures, inlfuxdb no data .

**Comment by JunejaTung** [comment]
@vishh  now i can access web ui of influxdb and grafana services through  config NodePort in yaml file, when i ' kubectl create  -f  heapster-controller.yaml ' , the heapster have to restart for underly error logs, i pass clusterIP to ‘--sink=influxdb:http//’ option, but the heapster didn't use the pass ip but another localhost, how can i resolve this new trouble? heapster version is canary .
[root@wlan-cloudserver32 home]# docker logs cd50b5b3e7b4
I1028 07:58:33.024362       1 heapster.go:60] /heapster --source=kubernetes:http://172.27.8.210:8080?inClusterConfig=false&useServiceAccount=false --sink=influxdb:http:///10.254.248.100:8086
I1028 07:58:33.024555       1 heapster.go:61] Heapster version 0.18.0
I1028 07:58:33.024840       1 kube_factory.go:168] Using Kubernetes client with master "http://172.27.8.210:8080" and version "v1"
I1028 07:58:33.024861       1 kube_factory.go:169] Using kubelet port 10255
F1028 07:58:33.028741       1 heapster.go:67] failed to ping InfluxDB server at "localhost:8086" - Get http://localhost:8086/ping: dial tcp 127.0.0.1:8086: connection refused
[root@wlan-cloudserver32 home]# 

[root@wlan-cloudserver31 influxdb-test]# kubectl get services --all-namespaces 
NAMESPACE     NAME                  LABELS                                                                      SELECTOR               IP(S)            PORT(S)
default       kubernetes            component=apiserver,provider=kubernetes                                     <none>                 10.254.0.1       443/TCP
default       maintain-master       name=maintain-master                                                        name=maintain-master   10.254.98.56     6379/TCP
default       portal-master         name=portal-master                                                          name=portal-master     10.254.173.124   6379/TCP
default       portal-slave          name=portal-slave                                                           name=portal-slave      10.254.217.179   6379/TCP
kube-system   heapster              kubernetes.io/cluster-service=true,kubernetes.io/name=Heapster              k8s-app=heapster       10.254.99.54     8082/TCP
kube-system   monitoring-grafana    kubernetes.io/cluster-service=true,kubernetes.io/name=monitoring-grafana    name=influxGrafana     10.254.205.99    3000/TCP
kube-system   monitoring-influxdb   kubernetes.io/cluster-service=true,kubernetes.io/name=monitoring-influxdb   name=influxGrafana     10.254.248.100   8083/TCP
                                                                                                                                                        8086/TCP

**Comment by JunejaTung** [comment]
@vishh  sorry, for my clerical errors in `--sink=influxdb:http:///....` option in `heapster-controller.yaml` ,  more a char `/`. then entry that  strange question: `F1028 07:58:33.028741       1 heapster.go:67] failed to ping InfluxDB server at "localhost:8086" - Get http://localhost:8086/ping: dial tcp 127.0.0.1:8086: connection refused`
