### ISSUE TITLE
Container view often empty

### ISSUE THREAD

**Issue by tsn77130** [kubernetes/heapster#688]
Hi,

I've set up grafana & influxdb with pods from "master/cluster/addons/cluster-monitoring/influxdb", pods are alive.

Problem is that Kubernetes view is OK (see all nodes & cluster graphes), but the Containers view is empty most of time. 
I say most of time, because I've already seen all of my pods listed normally hre inthis view after refleshing. But a reflresh later, I had only some of containers, or most of time noting ( see capture below)

$ kubectl get po --namespace=kube-system
NAME                                      READY     STATUS    RESTARTS   AGE
heapster-v10-xgqhg                        1/1       Running   0          2h
kube-apiserver-149.202.163.141            1/1       Running   2          22d
kube-controller-manager-149.202.163.141   1/1       Running   2          22d
kube-dns-v9-5iv6f                         4/4       Running   27         21d
kube-podmaster-149.202.163.141            2/2       Running   4          22d
kube-proxy-149.202.163.141                1/1       Running   2          22d
kube-proxy-149.202.163.142                1/1       Running   1          22d
kube-proxy-149.202.163.143                1/1       Running   1          2d
kube-proxy-149.202.174.88                 1/1       Running   1          21d
kube-scheduler-149.202.163.141            1/1       Running   2          22d
kube-ui-v3-vo3tn                          1/1       Running   3          9d
kubedash-87pui                            1/1       Running   1          3d
monitoring-influxdb-grafana-v2-vamvb      2/2       Running   0          2h

![containers](https://cloud.githubusercontent.com/assets/8789835/10964581/50b5f2bc-83a8-11e5-99f2-bdb362792988.png)

**Comment by tsn77130** [comment]
result when I'm lucky

![containers_ok](https://cloud.githubusercontent.com/assets/8789835/10964862/eacb89b0-83a9-11e5-89cd-affc01b5885d.png)

**Comment by vishh** [comment]
This is an issue with the kubernetes api server. Can you try accessing
grafana directly, without the api-server proxy? The configuration files
should contain information that will guide you to skip the proxy.

**Comment by tsn77130** [comment]
Hi vishh, thanks for answer.
I'm already using public IP to access grafana

**Comment by vishh** [comment]
In that case, @thucatebay might be able to help you.

**Comment by thucatebay** [comment]
It seems that Grafana wasn't able to get the list of containers from time to time. Any errors in Grafana log?

**Comment by tsn77130** [comment]
No, nothing apperas with kubectl logs monitoring-influxdb-grafana-v2-vamvb grafana --namespace=kube-system

**Comment by thucatebay** [comment]
If you're just starting out on using Heapster, I'd recommend using the [latest]( https://github.com/kubernetes/heapster/tree/master/deploy/kube-config/influxdb), which leverages InfluxDB 0.9.

In the version that you use, the query to get all containers looks like this:

```
select distinct(container_name) from \"uptime_ms_cumulative\" where pod_name =~ /$pod/ and \"pod_namespace\" =~ /$namespace/ and time > now() - 1m
```

You'll find it in the dashboard settings panel under the Templating section. You can change the time internal to say 30m. 

I have a pending task to update it to use the time filter instead of hardcoding.

**Comment by maklemenz** [comment]
I've experienced the same problem was just about to report it.

Basically the query grafana used to get a list of all pods nearly always returned an empty array. I fixed that by using a larger timefilter at the end of each query and creating an own container based on the official one just adding the fixed container-dashboard. 

I used dockerhub for my tests. To test the image just replace the *heapster_grafana* container in the rc with *maklemenz/heapster_grafana:latest*

As @thucatebay has a pending task to make this configurable I probably shouldn't make a pull request with just another hardcoded value.

**Comment by tsn77130** [comment]
Hi, 
@thucatebay , thanks for your reply.
I just have recreated services, rc & pods, and indeed it works great with 0.5 vertsion of influxDB.

It is a little confusing, because I used kubernetes documentation for install monitoring, and it refers to another github location , with 0.4 version in (see https://github.com/kubernetes/kubernetes/tree/master/cluster/addons/cluster-monitoring/influxdb )

Maybe it would be beneficial to group sources to avoid confusion

**Comment by suchisubhra** [comment]
i have couple of issues...we have our own  name spaces.. It doesn't show up in  namespace list.
Also kube-system pod show nothing.. 

I just  downloaded and deployed heapster..

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
