### ISSUE TITLE
Expose disk io metrics

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#690]
Disk IO metrics are useful to identify disk bandwidth hogging application. Since containers typically share a local disk, these metrics will be very useful.

**Comment by mwielgus** [comment]
Good idea. I will take a look.

**Comment by HardikDR** [comment]
Any update on this ??

**Comment by andyxning** [comment]
@vishh @mwielgus 

I am now working on adding disk io stats metrics to Heapster. Did you have any thought about this? For example, which metrics should be collected and the metric names.

I  prefer to add both `read` and `write` bytes per second metric separately. With this original data, we can also get the aggregated bytes per second including both `read` and `write`.

**Comment by andyxning** [comment]
Close this as disk io has been added to heapster with legacy source.

/close
