### ISSUE TITLE
Create a plugin-like mechanism for sinks

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/heapster#692]
At this moment we have a bunch of sinks contributed by the community. I guess none of the core Heapster developers will have time to actively test all of the fancy sinks with the newest release of Kafka, Riemann, Bosun, or some yet another shiny time series database. 

I think we have to draw a line between what is fully supported/tested, what is bundled with the default release and what is a best effort add-on/plugin.

cc: @piosz @vishh @jszczepkowski @fgrzadkowski

**Comment by piosz** [comment]
cc @bgrant0607 @davidopp

**Comment by mwielgus** [comment]
related to: #665

**Comment by vishh** [comment]
Yeah. The best we can do for now is document what we test against.
Setting up integration tests for some of the sinks like kafka and riemann isn't that difficult. We can create a heapster pod with these sinks, re-configure heapster sinks from e2e tests, and then run the necessary sink validation logic.
We can also encourage the community to add e2e tests for those sinks, if they happen to use those sinks in production.

**Comment by mwielgus** [comment]
Postponed until after 1.2

**Comment by piosz** [comment]
closing as obsolete
