### ISSUE TITLE
Fails to start for GCM

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/heapster#694]
I am getting the following error while deploying to a kubernetes cluster running in google cloud.  

kubectl create -f deploy/kube-config/google/

I am on the master ... should I try a release?

Error from kubectl logs

flag provided but not defined: -poll_duration
Usage of /heapster:
  -allowed_users="": comma-separated list of allowed users
  -alsologtostderr=false: log to standard error as well as files
  -cache_duration=4m0s: The total duration of the historical data that will be cached by heapster.
  -listen_ip="": IP to listen on, defaults to all IPs
  -log_backtrace_at=:0: when logging hits line file:N, emit a stack trace
  -log_dir="": If non-empty, write log files in this directory
  -logtostderr=false: log to standard error instead of files
  -max_procs=0: max number of CPUs that can be used simultaneously. Less than 1 for default (number of cores)
  -model_frequency=2m25s: Frequency at which model will be updated. Applies only if use_model is true
  -model_resolution=1m0s: The resolution of the timeseries stored in the model. Applies only if use_model is true
  -port=8082: port to listen to
  -sink=[]: external sink(s) that receive data
  -sink_frequency=10s: Frequency at which data will be pushed to sinks
  -source=[]: source(s) to watch
  -stats_resolution=5s: The resolution at which heapster will retain stats.
  -stderrthreshold=0: logs at or above this threshold go to stderr
  -tls_cert="": file containing TLS certificate
  -tls_client_ca="": file containing TLS client CA for client cert validation
  -tls_key="": file containing TLS key
  -use_model=true: When true, the internal model representation will be used
  -v=0: log level for V logs
  -vmodule=: comma-separated list of pattern=N settings for file-filtered logging

**Comment by vishh** [comment]
cc @piosz
