### ISSUE TITLE
Fails to start with GCM

### ISSUE THREAD

**Issue by chrislovecnm** [kubernetes/heapster#702]
So this is continuing https://github.com/kubernetes/heapster/issues/694

Now the pod keeps restarting, with very little logging information.  All I have now is:

W1110 14:48:19.665252   12536 cmd.go:149] log is DEPRECATED and will be removed in a future version. Use logs instead.
I1110 21:48:19.802383       1 heapster.go:61] /heapster --source=kubernetes:https://kubernetes.default --sink=gcm --sink=gcl --stats_resolution=1m
I1110 21:48:19.802509       1 heapster.go:62] Heapster version 0.18.0
F1110 21:48:19.802525       1 heapster.go:64] stats resolution '60000000000' is not less than model resolution '60000000000'
                                                                                                                            
I am see multiple restarts of the 
Image:		kubernetes/heapster:canary 
on the heapster pod

**Comment by vishh** [comment]
cc @piosz

**Comment by piosz** [comment]
Thanks for reporting @chrislovecnm. You can decrease stats_resolution to 30s. I'll create a fix.

**Comment by chrislovecnm** [comment]
That is great!  Maybe the docs should be a bit more clear??

**Comment by chrislovecnm** [comment]
Another error:

Let me know what else you need

kubectl logs heapster-j9w02 --namespace=kube-system
I1112 18:06:02.054151       1 heapster.go:61] /heapster --source=kubernetes:https://kubernetes.default --sink=gcm --sink=gcl --stats_resolution=30s
I1112 18:06:02.054215       1 heapster.go:62] Heapster version 0.18.0
I1112 18:06:02.054659       1 kube_factory.go:172] Using Kubernetes client with master "https://kubernetes.default" and version "v1"
I1112 18:06:02.054669       1 kube_factory.go:173] Using kubelet port 10255
I1112 18:06:02.069390       1 driver.go:113] created GCM sink
I1112 18:06:02.070631       1 driver.go:242] Project ID for GCL sink is: "decent-slice-104819"
I1112 18:06:02.070647       1 driver.go:262] creating GCL sink
E1112 18:06:02.070654       1 manager.go:257] encountered following errors while setting up sinks - Current instance does not have the expected scope ("https://www.googleapis.com/auth/monitoring"). Actual scopes: https://www.googleapis.com/auth/compute
https://www.googleapis.com/auth/devstorage.read_only
https://www.googleapis.com/auth/logging.write
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x703ff7]

**Comment by vishh** [comment]
AFAIK, GCE does not allow updating scopes (permissions to Google Cloud
APIs) dynamically. When you create nodes on GCE, you need to add the
monitoring scope. If you had setup the cluster using the kubernetes scripts
(kube-up.sh), then the monitoring scope should have been added by default.

To get around this, you will have to add new nodes with the `monitoring`
scope enabled, and then delete the old nodes.

**Comment by chrislovecnm** [comment]
Nooooooooooooooo .... Have time setup with Google to discuss.  Arg
