### ISSUE TITLE
Consider using OAuth to communicate with Google Cloud Sinks

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#709]
Currently, heapster requires `monitoring` and `logging` scopes to be set to read-write on all nodes. This requirement is not explicit, and often users end up hitting this road-block after setting up their VMs. 
Heapster currently supports dynamic sink updates. We can let users add Google Cloud sinks (GCM and GCL) dynamically and in that process complete the login sequence that will let heapster access Google Cloud APIs. To make this process simple, we can busybox the heapster binary to be run as a client utility that will let users add or remove sinks easily.

For example,
`$ heapster add-sinks gcm <heapster_url>`
This command can then post a login URL that lets heapster server authenticate with Google Cloud Monitoring API and then register the sink.

cc @mwielgus @piosz 
#702

**Comment by piosz** [comment]
closing as obsolete
