### ISSUE TITLE
Update documentation for Heapster on CoreOS

### ISSUE THREAD

**Issue by oli-g** [kubernetes/heapster#710]
Hi! I'm evaluating Heapster as a monitoring solution for a CoreOS cluster. I followed [this guide](https://github.com/kubernetes/heapster/blob/master/docs/coreos.md), and I was able to view this crippled dashboard:

![screenshot 2015-11-13 17 43 38](https://cloud.githubusercontent.com/assets/440821/11151558/1ce29f76-8a2e-11e5-830a-eb57553e3719.png)

That guide above mentions old versions of the components: 
- `kubernetes/heapster_influxdb:v0.3`
- `kubernetes/heapster:v0.13.0`
- `kubernetes/heapster_grafana:v0.7`

In order to try to fix the visualization issues, I tried with `kubernetes/heapster_grafana:v2.1.1`, but the resulting dashboard is completely broken:

![screenshot 2015-11-13 14 40 12](https://cloud.githubusercontent.com/assets/440821/11147305/496161b8-8a15-11e5-853e-6da74b9ac8e2.png)

So my questions is: is it possible to have a working setup on CoreOS, using more recent versions of those software components? Even with the old versions you're mentioning in the guide, I cannot have a fully functional monitoring dashboard.

**Comment by tyler274** [comment]
would appreciate this as well

**Comment by vishh** [comment]
Can you try with the latest versions of all the components?
Heapster is v0.19.0, InfluxDB v0.6 and Grafana v2.6.0

**Comment by binarybana** [comment]
These version numbers did indeed fix things for me (although 0.19.1 heapster also fixed the race between heapster and influxdb). Thanks!

**Comment by ntquyen** [comment]
CoreOS support is currently suspended. https://github.com/kubernetes/heapster/issues/115#issuecomment-195324116

**Comment by piosz** [comment]
Closing as obsolete
