### ISSUE TITLE
Race in deployment of heapster vs. influxdb

### ISSUE THREAD

**Issue by chrisleck** [kubernetes/heapster#711]
Instructions here point to starting up all services/RCs simultaneously: https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md.

If heapster comes up before influxdb is ready, I see the following error in the heapster logs:
E1117 00:54:03.431077       1 manager.go:257] encountered following errors while setting up sinks - failed to ping InfluxDB server at "monitoring-influxdb:8086" - Get http://monitoring-influxdb:8086/ping: dial tcp: lookup monitoring-influxdb: no such host

And influxdb never gets the 'k8s' database added.

If I manually order the startup of these containers, everything works properly.

**Comment by vishh** [comment]
What version of heapster are you using? Heapster will retry connecting to
InfluxDB until it can succeed.

**Comment by chrisleck** [comment]
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    name: heapster
    version: v6
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - name: heapster
        image: kubernetes/heapster:canary
        imagePullPolicy: Always
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://monitoring-influxdb:8086

**Comment by vishh** [comment]
@piosz @mwielgus Can one of you try out the HEAD configs and see if we are able to repro this issue?

**Comment by mwielgus** [comment]
I will take a look.

**Comment by perhapszzy** [comment]
And there's a similar problem: 

Heapster will not work correctly if the influxdb pod restart.

**Comment by vishh** [comment]
This issue has been fixed on HEAD. The next release of heapster should be
resilient to backend failures.

**Comment by chrisleck** [comment]
Cool!  When is the next release of heapster happening?

**Comment by piosz** [comment]
@vishh could you please link PR with fix? I can't find any.

**Comment by vishh** [comment]
https://github.com/kubernetes/heapster/blob/master/sinks/influxdb/driver.go#L230

**Comment by mwielgus** [comment]
Fixed with #780. 
The fix is available in release v0.19.1.
