### ISSUE TITLE
/api/v1/model/namespaces/ response file not found

### ISSUE THREAD

**Issue by SidneyAn** [kubernetes/heapster#713]
I am running heapster standalone and I get non-empty response when I using the following endpoint http://{master-ip}/api/v1/model/metrics/. But when I try the endpoint http://{master-ip}/api/v1/model/namespaces/ , it returns file not found.

I use the binary file and the following parameters "--source="cadvisor:external?cadvisorPort=8080"","--use_model=true","-stats_resolution==1s","-model_resolution=2s", "-model_frequency=3s". Any help here is really appreciated.

**Comment by afein** [comment]
The namespaces endpoint refers to Kubernetes namespaces. If you are not running heapster within a Kubernetes cluster then this endpoint is not enabled. 

In standalone mode, you should be able to view your containers on a per-node basis under /api/v1/model/nodes/{node-name}/freecontainers

**Comment by SidneyAn** [comment]
I retry it within a Kubernetes cluster. I run heapster standalone in a minion node and I change the cadvisorPort to 4194, which is the port provided by kubelet. But the namespaces endpoint still returns file not found.
My test containers are running under the default namespace. Is there any problem with it?

**Comment by huangyuqi** [comment]
@SidneyAn , 
>  I run heapster standalone in a minion node and I change the cadvisorPort to 4194

If you want to get the response of something  about kubernetes cluster, you need  config the `source` to `kubernetes`,like this: ` --source=kubernetes:http://9.91.18.135:8080` or ` --source=kubernetes:http://kubernetes`(If you run the heapster in a `POD`)
>  run heapster standalone in a minion node

In this mode, you can just get the metrics from the cadvisor, and not perceive the resource about `kubernetes`, such as `namespace`, `pod` and so on.

**Comment by SidneyAn** [comment]
@huangyuqi  get it. Thanks a lot!

**Comment by biswars** [comment]
@huangyuqi , I am getting the same error while trying to access the container metrics.
Using /api/v1/model/namespaces/default/pods/{pod-name}/containers to access the containers but getting 404 error. Containers are not listed.

Note: The set up is running in kubernetes cluster with version "heapster-v1.1.0.beta1" and I am able to get node and pod level metrics successfully. Only Container level metrics fails.

Any special flags to be set to enable container level metrics ?

**Comment by huangyuqi** [comment]
@biswars the source of heapster you config is kubernetes, right?   And all apis can not work normally?

**Comment by biswars** [comment]
@huangyuqi yes, the source of heapster is kubernetes. In fact, I am using the heapster-controller.yaml as present in the kubernetes repo (one of the previous versions) [https://github.com/kubernetes/kubernetes/blob/0dcd49d5844b40327a39e1b91197b1a822ffd580/cluster/addons/cluster-monitoring/influxdb/heapster-controller.yaml](url)

While referring to [https://github.com/kubernetes/heapster/blob/master/docs/model.md](url), I tried getting the metrics using Rest API and Cluster-level Metrics, Pod and Node-level Metrics work. However, Container-level Metrics does not work.

Example:
/api/v1/model/namespaces/kube-system/pods returns
[
  "heapster-v1.1.0.beta1-3062717326-3u7h4",
  "monitoring-influxdb-grafana-v3-ukr6v",
  "kube-dns-v11-p6jiq"
 ]

/api/v1/model/namespaces/kube-system/pods/kube-dns-v11-p6jiq/metrics returns the available metrics

But, /api/v1/model/namespaces/kube-system/pods/kube-dns-v11-p6jiq/containers returns 404 error.

**Comment by huangyuqi** [comment]
@biswars I got reason of this issue

+ the version of heapster in the deployment file you use is "1.1.0", it is a refactor version; And the `model.md` maybe not update.
+ So, i go to check the code of heapster api, i found the api `/api/v1/model/namespaces/{namespace-name}/pods/{pod-name}/containers/` has been removed. Maybe a omission.  You can refer the file https://github.com/kubernetes/heapster/blob/master/metrics/api/v1/model_handlers.go#L49-L217

This issue is a bug certainly, in my opinion. Would you bring a new issue to community, copy this comment to there and at me? I am pleasure to fix this.

**Comment by DirectXMan12** [comment]
model is no longer supported, and this issue is stale, closing
