### ISSUE TITLE
Asking for built-in network graphs in grafana dashboard

### ISSUE THREAD

**Issue by ntquyen** [kubernetes/heapster#720]
First of all, thank you very much for including grafana dashboard. It saved me a lot of time learning influxdb queries and building grafana graphs. I think it would be even nicer if there are also network graphs included :-)

**Comment by antoineco** [comment]
I'm working on it as part of #824, however Network metrics are not yet available for containers (see #368)

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
