### ISSUE TITLE
Add new label for the Node name

### ISSUE THREAD

**Issue by mwringe** [kubernetes/heapster#731]
We should add support for a new label for the name of the node. This should correspond to the metadata.name element of the node.

Currently the closest thing we have is "host_id" but this corresponds to using a deprecated 'ExternalID' (https://github.com/kubernetes/kubernetes/blob/release-1.0/pkg/api/v1/types.go#L1256) which is probably not something we should continue to use.

**Comment by mwringe** [comment]
I already have a patch getting ready for this, the bigger issue is that heapster broke compatibility with OpenShift about a month ago (which I also have a patch almost ready to commit, I just need to update the tests). 

How does one get added as someone who can take tasks?

**Comment by vishh** [comment]
@mwringe: I have added you to the `kubernetes` github org. Issues and PRs can be assigned to you now.

**Comment by piosz** [comment]
We do have a label https://github.com/kubernetes/heapster/blob/master/sinks/api/supported_labels.go#L45 which is usually set to node name https://github.com/kubernetes/heapster/blob/master/sources/nodes/kube.go#L71

**Comment by mwringe** [comment]
The hostname is only set to the node name if the hostname is empty. Which I don't think should be the case in most situations.

There is also the host_id which corresponds to the external id of the node. If the system doesn't overwrite the external id, then it should default to the node name. The external id is also deprecated and probably not something we should continue to rely on (https://github.com/kubernetes/kubernetes/blob/release-1.0/pkg/api/v1/types.go#L1256)

The problem is that in both the case of the hostname and host_id, its non deterministic that you will ever get back the node name.

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
