### ISSUE TITLE
Support connecting to kubelet endpoints using hostname

### ISSUE THREAD

**Issue by mwringe** [kubernetes/heapster#732]
Currently we connect to the kubelet endpoints using the ip address instead of the hostname.

This can cause problems when dealing with tls and certificates where the certificate may contain the hostname but not the ip address.

This means connecting via the hostname will result in the certificate being valid, while connecting directly via the ipaddress is not.

It would be nice to be able to have a flag to specify that we would prefer to connect to a kubelet over its hostname instead of ip address to resolve this type of issue.

**Comment by ncdc** [comment]
@jszczepkowski @piosz @mwielgus

**Comment by piosz** [comment]
When do you need it? Should this be fixed in the HEAD right now or can we do it once we will refactor Heapster (late Dec/early Jan).

**Comment by ncdc** [comment]
I'm guessing this can wait for the refactor, but let's get at least 1 of @smarterclayton @liggitt @deads2k @mwringe @sdodson to weigh in.

**Comment by liggitt** [comment]
Are we sure we always have DNS resolution of hostnames to nodes?

**Comment by ncdc** [comment]
@liggitt if not, using the proposed flag to indicate using the IP address would suffice, wouldn't it?

**Comment by mwringe** [comment]
There are a lot of people running into the problem where they cannot connect to the kubelet endpoints due to this. OpenShift should soon have the ability to update the certificates when performing an update, so it may be less of an issue when new releases.

**Comment by sdodson** [comment]
I defer to @mwringe on priority here. But yeah basically folks who have upgraded from Origin 1.0 / OSE 3.0 to Origin 1.1 / OSE 3.1 will have trouble with this.

**Comment by DirectXMan12** [comment]
Don't think this is still an issue.  closing.
