### ISSUE TITLE
Regression: OpenShift secure connections

### ISSUE THREAD

**Issue by mwringe** [kubernetes/heapster#746]
There was a commit about a month ago (https://github.com/kubernetes/heapster/commit/063ce38deb63d1d66629a3811ef508a49860b08d) which breaks compatibility with OpenShift.

Specifically it removes the ability to connect to OpenShift in a secure manner.

The problem is that it is using the kubernetes v1.1.0 build, where the security implementation is in the v1.2.0 builds.

We need to update our godeps to use kubernetes v1.2.0

**Comment by vishh** [comment]
AFAIK, v0.18.2 should not have this issue. v0.18.2 is what has been bundled
with kubernetes v1.1.

**Comment by vishh** [comment]
It might be helpful to setup an e2e test against all releases and master
and post the results to github. I can help setup such an e2e.

**Comment by mwringe** [comment]
v0.18.2 is almost 2 months ago and is out of date with our needs. We did get a bunch of the commits we required into the release-0.18.0 branch, but no release has happened yet which contains those commits. Even if a release were to happen for 0.18.0 we would still need to go in and back port a commit or two.

I almost have a PR which will bring master up to the latest v1.2.0 alpha, if that makes sense for the master branch.

**Comment by vishh** [comment]
Ok. We can cut a v0.18.3 if the PRs you care about are already merged into
`release-0.18` branch. It is just an option.

**Comment by jimmidyson** [comment]
Yes it seems we should just be able to cut a release from the `release-0.18.0` branch as @vishh said unless there's something we're missing @mwringe?

**Comment by mwringe** [comment]
Yeah, getting a proper release from the release-0.18.0 branch would be the best solution :)

We probably want to backport a few commits from master in there, and to get the commits from https://github.com/kubernetes/heapster/issues/731 in there

Updating the heapster master to the v1.2.0 alphas is probably also a good idea

**Comment by jimmidyson** [comment]
:+1: to updating master to 1.2.0 alphas

**Comment by mwringe** [comment]
The patch I have is not that complex, other than updating the godeps to the newer 1.2.0 alphas, there is just some minor changes which need to be made.

**Comment by jimmidyson** [comment]
I agree with @vishh that we need e2e against multiple versions now, including master so we can track version compatibility as much as anything else.

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
