### ISSUE TITLE
Errors logged at info level

### ISSUE THREAD

**Issue by phemmer** [kubernetes/heapster#757]
I was trying to track down why heapster wasn't gathering any stats, but the logs weren't proving much help, only:

    E1202 20:04:54.955140       1 model_handlers.go:620] unable to get pod list metric: the model is not populated yet

After increasing the logging level, I started seeing other errors such as:

```
I1202 20:04:52.247233       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.220:10255/stats/default/firebirds-xjhq2/656abaa4-9855-11e5-98be-0e3733bda1bf/firebirds - Get http://10.0.0.220:10255/stats/default/firebirds-xjhq2/656abaa4-9855-11e5-98be-0e3733bda1bf/firebirds: dial tcp 10.0.0.220:10255: connection timed out
I1202 20:04:52.247244       1 kube_pods.go:110] failed to get stats for container "firebirds" in pod "default"/"firebirds-xjhq2"
I1202 20:04:52.247264       1 kube_nodes.go:59] Failed to get container stats from Kubelet on node "ip-10-0-0-217.ec2.internal"
```

As these are error messages, I think they should be logged at the error level, so that you don't have to adjust the log level on the daemon to see them.

**Comment by vishh** [comment]
SGTM. This issue shows up very frequently these days, that it warrants
raising the logging level by default.
Do you have some spare cycles to post a PR?

**Comment by phemmer** [comment]
Perhaps. I'm sure it's a trivial change. Will take a look.
