### ISSUE TITLE
Hawkular Sink: Support trusting specific certificate

### ISSUE THREAD

**Issue by mwringe** [kubernetes/heapster#771]
Currently we are running into an issue where Heapster connects to Hawkular Metrics via its service hostname (eg 'hawkular-metrics') but a user provided certificate may not contain 'hawkular-metrics' as part of the certificate's san.

In this situation the connection will be refused.

We already pass the certificate used by Hawkular Metrics to the Hawkular Sink, and we should just trust this certificate for connections to the 'hawkular-metrics' hostname, regardless if the certificate actually contains 'hawkular-metrics'.

**Comment by jimmidyson** [comment]
Adding that is an option sounds ok, but should not be the default: if users have gone to the trouble of configuring TLS then we should adhere to proper TLS handshake/certificate validation.

**Comment by mwringe** [comment]
It wont be by default. The user would have to explicitly configure the sink to trust very specific certificates.

Looking at the current options, we don't actually pass the server certificate but the CA certificate. As part of this we will need to add a new option to specify the server certificate to trust.

**Comment by jimmidyson** [comment]
Passing a server certificate seems odd. If you have a CA then you should give the CA certificate. If you are using self-signed server certificates then that also acts as the CA for the server certificate (their one & the same thing) so we don't need to add an option for specifying a server certificate.

Even so, the only way to trust a badly issued certificate (e.g. one that has a hostname that isn't the same as the actual hostname used to connect to the service) is to disable TLS verification completely: it's pretty worthless anyway in this case. That is already supported.

I'm not sure anything needs to be done here.

**Comment by DirectXMan12** [comment]
please reopen if you plan on working on this
