### ISSUE TITLE
Can't send data to influxdb using master

### ISSUE THREAD

**Issue by rvrignaud** [kubernetes/heapster#775]
I'm running GKE cluster (1.1.2). I'm trying to send heapster data to influxdb (0.9.4). I tried to build master branch but I'm having some errors.

```
1209 18:40:19.093749       1 driver.go:189] failed to write stats to influxDB - unable to parse '...': bad timestamp
```

Heapster is launched with `/heapster --source=kubernetes:"" --sink=influxdb:http://influxdb:8086 --sink_frequency=30s`

Am I doing something wrong ?

**Comment by vishh** [comment]
That error is returned by InfluxDB. We have tested HEAD against InfluxDB v0.9.4 and it used to work in the past. 
We are in the process of releasing a new version of heapster with InfluxDB v0.9 support. 
cc @mwielgus: We should test v0.19.0 with the InfluxDB v0.9.4 before officially releasing it.

**Comment by rvrignaud** [comment]
Just for the record, I've been running Heapster (commit d500aa975889f6ba2c2093b2bd518e17266c42fd) successfully for a while. Since my cluster got upgraded to 1.1.2 I have this kind of error with the d500aa version:
```
E1210 11:22:08.390460       8 external.go:87] failed to sync data to sinks - encountered the following errors: unable to parse '...': missing fields
```

This is why I tried to upgrade heapster version to master without luck (see first comment).
I can send privately full logs if needed.

**Comment by vishh** [comment]
Heapster from HEAD supports InfluxDB v0.9 only. Are you running InfluxDB
v0.8?

**Comment by rvrignaud** [comment]
As I said I'm running Influxdb 0.9.4.1. Heapster d500aa975889f6ba2c2093b2bd518e17266c42fd has successfully sent data for a while when I was running GKE 1.0.7.

**Comment by vishh** [comment]
Thanks for clarifying. I'm trying the new release v0.19.0 now.

**Comment by rvrignaud** [comment]
Hi @vishh. Did you reproduce ?

**Comment by rvrignaud** [comment]
I still have same problem (bad timestamp error) with heapster 0.19.1

**Comment by vishh** [comment]
I have been running heapster v0.19.0 with InfluxDB v0.9.6 successfully for
the last few days.
I'm using the configs from HEAD.

**Comment by rvrignaud** [comment]
Is there anything I can provide to help you debug ?

**Comment by vishh** [comment]
Setting heapster logging level to `--vmodule=*=4` will be very helpful.

**Comment by rvrignaud** [comment]
@vishh I sent you the log file with vmodule=*=4 privately as it's very complicated to remove sensible parts on this huge file.

**Comment by antoineco** [comment]
@rvrignaud I have a similar issue with a group of pods, can you check the :point_up: referenced issue and see if we have a pattern in common? If suspect it has to do with a `lifecycle:` block but I could be completely wrong.

**Comment by rvrignaud** [comment]
@antoineco Thank you very much. Removing all lifecycle definitions, fixed indeed the heapster problem.
@vish did you get anything from the logs I sent you ? Do you reproduce when adding lifecycle fields ?

**Comment by piosz** [comment]
Closing as obsolete
