### ISSUE TITLE
some  issues come with 'time synchronization'

### ISSUE THREAD

**Issue by huangyuqi** [kubernetes/heapster#802]
Sometimes, in our production environment, the timestamp of the cluster nodes are nonsynchronous for some reasons(such as NTP server do not work i.e).
For this reason, heapster can not get the metrics in two kinds of scene, as follows:

+ timestamp of heapster is **sooner** than other nodes

  if **TimeSpan > cache_duration**,  all the metrics data will be set to `tooOld`,and be discarded.

```
func (rc *realCache) isTooOld(lastUpdated time.Time) bool {
	if time.Now().Sub(lastUpdated) >= rc.bufferDuration {
		return true
	}
	return false
}
```
+ timestamp of heapster is **later** than other nodes

   AFAIK, heapster calls kubelet's api to get metrics data, such as:

```golang
// Get stats for all non-Kubernetes containers.
func (self *kubeletSource) GetAllRawContainers(host Host, start, end time.Time) ([]api.Container, error) {
        ...
	url := fmt.Sprintf("%s://%s:%d/stats/container/", scheme, host.IP, host.Port)
	return self.getAllContainers(url, start, end)
}

func (self *kubeletSource) getAllContainers(url string, start, end time.Time) ([]api.Container, error) {
	// Request data from all subcontainers.
	request := statsRequest{
		ContainerName: "/",
		Start:         start,
		End:           end,
		Subcontainers: true,
	}
	body, err := json.Marshal(request)
        ...
	req, err := http.NewRequest("POST", url, bytes.NewBuffer(body))
        ...
```
Because the `start` is later than the kubelet's timestamp, and if **TimeSpan > cache_duration** , 
the response of `POST` request above will be empty. The reason is that, the kubelet does not hold the ageing metrics data.
```
func (rm *realManager) Housekeep() {
	for {
		start := rm.lastSync
		end := start.Add(rm.resolution)
		...
		}
	}
}
```

Generally, users often spend much time to resolve issues deriving from this reason.
**So, should we add a logic in heapster to check the timestamp synchronous or not in the init process? And give a tips for users.**

**Comment by vishh** [comment]
Yeah. Perhaps we can enhance the `debugging.md` doc with this information?

**Comment by huangyuqi** [comment]
Yes, I agree with you @vishh , enhancing the docs is a practicable way, i will add this tips. 
But I think it's not a forcing method ^_^.
Maybe, In my opinion, let the heapster to check in the init process is more better, if the timestamp is nonsynchronous, it will return a warning or an error to users. 
BTW, all these come from usability of heapster, it's assistant .So what's your opinion about add this to heapster?

**Comment by vishh** [comment]
Sure post a PR. We can discuss the specifics over the PR.
