### ISSUE TITLE
Push user labels for pods and containers as separate tags in InfluxDB

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#807]
As of now we serialize all the user defined labels into a single tag in InfluxDB. 
This was done to meet the number of lables limitation in GCM.
We should make this schema storage dependent.

**Comment by chaen** [comment]
Just to say that I would definitely love to be able to have my labels stored as separate tag in InfluxDB ! :-) so +1000 !

**Comment by bartebor** [comment]
A year has passed...
I also would really like to have some labels stored as tags in influxdb. We could pick the labels via flag(s) to keep this flexible.
Maintainers, could you state your opinion on this issue? Are you willing to accept PR if it becomes available?

**Comment by DirectXMan12** [comment]
Yes, I would accept a PR to do this.
