### ISSUE TITLE
[Grafana] Container metrics aggregated across namespaces and pods

### ISSUE THREAD

**Issue by antoineco** [kubernetes/heapster#817]
(Containers dashboard)
Container metrics are aggregated across namespaces and pods even when a namespace and/or pod is selected via Grafana's drop-down menus.

Let's say I have a container `web` running in both namespaces `ns1` and `ns2`, in 2 different pods `pod1` and `pod2`. The metrics I see for the container `web` in pod `pod1` running in namespace `ns1` is the aggregation of both `web` containers running in both aforementioned namespaces.

**Comment by mwielgus** [comment]
LGTM
