### ISSUE TITLE
 Run Heapster on a Kubernetes cluster with InfluxDB:  failed to get stats for container "hello" in pod "default"/"hello-world"

### ISSUE THREAD

**Issue by Fei-Guang** [kubernetes/heapster#820]
$source ${KUBE_ROOT}/cluster/ubuntu/config-default.sh

$kubectl create -f deploy/kube-config/influxdb/
service "monitoring-grafana" created
replicationcontroller "heapster" created
service "heapster" created
replicationcontroller "influxdb-grafana" created
service "monitoring-influxdb" created

$ kubectl logs heapster-ll34y  --namespace=kube-system

I1223 01:40:10.666821       1 heapster.go:61] /heapster --source=kubernetes:https://kubernetes.default --sink=influxdb:http://monitoring-influxdb:8086
I1223 01:40:10.666943       1 heapster.go:62] Heapster version 0.19.1
I1223 01:40:10.668758       1 kube_factory.go:172] Using Kubernetes client with master "https://kubernetes.default" and version "v1"
I1223 01:40:10.668798       1 kube_factory.go:173] Using kubelet port 10255
I1223 01:40:10.693724       1 driver.go:351] created influxdb sink with options: {root root monitoring-influxdb:8086 k8s false}
I1223 01:40:10.773177       1 driver.go:272] Created database "k8s" on influxDB server at "monitoring-influxdb:8086"
I1223 01:40:10.777331       1 heapster.go:72] Starting heapster on port 8082
E1223 01:40:15.018363       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:40:15.018396       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:40:20.072006       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:40:20.072094       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:40:25.022254       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:40:25.022317       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:40:30.020519       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:40:30.020553       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:40:35.018795       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:40:35.018855       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:40:40.033585       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:40:40.033693       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:40:45.014130       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:40:45.014204       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:40:50.064095       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:40:50.065104       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:40:55.017329       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:40:55.017350       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:41:00.021505       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:41:00.023014       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:41:05.015772       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:41:05.016693       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:41:10.017381       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:41:10.017508       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:41:15.010812       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:41:15.010914       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:41:20.019273       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:41:20.019331       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:41:25.017475       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:41:25.017609       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:41:30.016801       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:41:30.017041       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:41:35.014202       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:41:35.014287       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:41:40.012590       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:41:40.012686       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:41:45.023101       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:41:45.023418       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:41:50.011450       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:41:50.011617       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:41:55.019194       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:41:55.019417       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:42:00.014253       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:42:00.014276       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:42:05.019330       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:42:05.019432       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:42:10.021359       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:42:10.021388       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:42:15.016257       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:42:15.016401       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:42:20.025086       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:42:20.025278       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:42:25.011700       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:42:25.011721       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:42:30.010230       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:42:30.010350       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:42:35.073396       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:42:35.073422       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:42:40.014557       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:42:40.014725       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"
E1223 01:42:45.011833       1 kubelet.go:96] failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"
E1223 01:42:45.011962       1 kube_pods.go:110] failed to get stats for container "hello" in pod "default"/"hello-world"

**Comment by huangyuqi** [comment]
This log shows that, heapster can not get the metrics from kubelet (Cadvisor). So, In my opinion, there may be two ways to check first,

+ You can request the URL `http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello` manually, with command `curl` or `wget` to check stats of kubelet. This is the RESTapi of Cadvisor,.

+ Run `docker ps` to check the container exists or not.

**Comment by Fei-Guang** [comment]
ubuntu@k8s:~$ sudo netstat -ntp |grep 10255
sudo: unable to resolve host k8s
tcp6       0      0 10.0.0.12:10255         172.16.70.5:60664       ESTABLISHED 30150/kubelet
tcp6       0      0 10.0.0.12:10255         172.16.70.5:60651       ESTABLISHED 30150/kubelet

**Comment by huangyuqi** [comment]
Can you get the container after running `docker ps` ?

**Comment by Fei-Guang** [comment]
ubuntu@k8s:~$ docker ps --format={{.Image}}
kubernetes/heapster:canary
kubernetes/heapster_grafana:v2.5.0
kubernetes/heapster_influxdb:v0.6
gcr.io/google_containers/pause:0.8.0
gcr.io/google_containers/pause:0.8.0
nginx
gcr.io/google_containers/pause:0.8.0
gcr.io/google_samples/gb-frontend:v3
gcr.io/google_samples/gb-redisslave:v1
gcr.io/google_containers/pause:0.8.0
gcr.io/google_containers/pause:0.8.0

**Comment by huangyuqi** [comment]
Because you got the error log `failed to get stats from kubelet url: http://10.0.0.12:10255/stats/default/hello-world/e8c46f4f-a54b-11e5-85d5-fa163ea22a7a/hello - request failed - "404 Not Found", response: "no matching container\n"`  
So ,i want to know the container `hello` exists or not in your kubernetes nodes. Would you check again? 
AFAIK, if containers are deleted by some reason(delete by RC, update, or crash), heapster's still holds the container information in its cache during the `cache_duration`, and you will also get this error information until heapster execute `runGc` to delete

**Comment by vishh** [comment]
The pod and/or container is mostly not running on the kubelet.

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
