### ISSUE TITLE
Add status information to Heapster

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/heapster#826]
**In heapster-scalability**

Use prometheus client library (https://github.com/prometheus/client_golang) to instrument the code so that the following information is exposed on a http endpoint:

* time of the last metrics scrape
* histogram of Kubelet/source response times
* number of scraped nodes and containers
* time spent in scrape (single run, not cumulative)
* time spent in processors (single run, not cumulative)
* time spent in exporting data to sinks (single run, not cumulative)
* number of http model api requests
* number of other http requests

cc: @piosz @huangyuqi

**Comment by huangyuqi** [comment]
thanks, @mwielgus , I will work on this interesting issues.

**Comment by mwielgus** [comment]
Fixed by @huangyuqi .
