### ISSUE TITLE
`TLS handshake error` on heapster and `malformed HTTP response` on kubedash

### ISSUE THREAD

**Issue by jtblin** [kubernetes/heapster#831]
I've setup heapster in a kubernetes cluster following the docs here. I have influxdb and grafana working fine but there are continuous errors in heapster logs, errors in kubedash when it tries to talk to heapster and no data making it through kubedash or grafana.

heapster logs:
```
I1229 11:37:11.475886       1 heapster.go:61] /heapster --source=kubernetes:https://kubernetes.default --sink=influxdb:http://monitoring-influxdb.kube-system:8086 --tls_client_ca=/etc/kubernetes/ssl/ca.pem --tls_key=/etc/kubernetes/ssl/worker-key.pem --tls_cert=/etc/kubernetes/ssl/worker.pem
I1229 11:37:11.475933       1 heapster.go:62] Heapster version 0.19.1
I1229 11:37:11.476475       1 kube_factory.go:172] Using Kubernetes client with master "https://kubernetes.default" and version "v1"
I1229 11:37:11.476495       1 kube_factory.go:173] Using kubelet port 10255
I1229 11:37:11.515172       1 driver.go:351] created influxdb sink with options: {root root monitoring-influxdb.kube-system:8086 k8s false}
I1229 11:37:11.526634       1 driver.go:272] Created database "k8s" on influxDB server at "monitoring-influxdb.kube-system:8086"
I1229 11:37:11.532369       1 heapster.go:72] Starting heapster on port 8082
2015/12/29 11:37:30 http: TLS handshake error from 10.244.92.13:37416: tls: first record does not look like a TLS handshake
2015/12/29 11:37:30 http: TLS handshake error from 10.244.92.13:37418: tls: first record does not look like a TLS handshake
2015/12/29 11:37:30 http: TLS handshake error from 10.244.92.13:37420: tls: first record does not look like a TLS handshake
...
```

I have no idea what ip `10.244.92.13` is. It doesn't look like any of the master / nodes neither skydns cidr. This error keeps going forever. If I attach to the container I can curl influxdb, kubernetes, kubelets, etc.

In kubedash logs, I see the following: `E1229 11:38:00.871823       1 handlers.go:57] unable to GET http://heapster/api/v1/model/stats - Get http://heapster/api/v1/model/stats: malformed HTTP response "\x15\x03\x01\x00\x02\x02"`. If I curl the url above from a container, I cannot get any valid response:

```
<:/usr/share/grafana# curl -vvv -i http://heapster/api/v1/model/stats        
* About to connect() to heapster port 80 (#0)
*   Trying 10.100.0.37...
* connected
* Connected to heapster (10.100.0.37) port 80 (#0)
> GET /api/v1/model/stats HTTP/1.1
> User-Agent: curl/7.26.0
> Host: heapster
> Accept: */*
> 
* additional stuff not fine transfer.c:1037: 0 0
* Increasing bytecount by 7 from hbuflen

* nread <= 0, server closed connection, bailing
* Connection #0 to host heapster left intact
* Closing connection #0
```

The rc for heapster is as-follow:

```yaml
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    k8s-app: heapster
    name: heapster
    version: v6
  name: heapster
  namespace: kube-system
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v6
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v6
    spec:
      containers:
      - name: heapster
        image: kubernetes/heapster:0.19.1
        volumeMounts:
          - name: ssl-certs
            mountPath: /etc/kubernetes/ssl
        command:
        - /heapster
        - --source=kubernetes:https://kubernetes.default
        - --sink=influxdb:http://monitoring-influxdb.kube-system:8086
        - --tls_client_ca=/etc/kubernetes/ssl/ca.pem
        - --tls_key=/etc/kubernetes/ssl/worker-key.pem
        - --tls_cert=/etc/kubernetes/ssl/worker.pem
      volumes:
        - name: ssl-certs
          hostPath:
            path: /etc/kubernetes/ssl
```

Running `curl --cert /etc/kubernetes/ssl/worker.pem --key /etc/kubernetes/ssl/worker-key.pem --cacert /etc/kubernetes/ssl/ca.pem https://kubernetes.default` from heapster container works fine.

Thanks for your help.

**Comment by vishh** [comment]
cc @jimmidyson

**Comment by jimmidyson** [comment]
The `--tls_*` flags are used to configure Heapster serving TLS, not connecting to a secured Kubernetes endpoint - with your current configuration you would need to `curl https://heapster/...`

To connect using TLS please take a look at https://github.com/kubernetes/heapster/blob/master/docs/source-configuration.md#kubernetes:

> Heapster requires an authentication token to connect with the apiserver securely. By default, Heapster will use the inClusterConfig system to configure the secure connection. This requires kubernetes version v1.0.3 or higher and a couple extra kubernetes configuration steps. Firstly, for your apiserver you must create a SSL certificate pair with a SAN that includes the ClusterIP of the kubernetes service. Look here for an example of how to properly generate certs. Secondly, you need to pass the ca.crt that you generated to the --root-ca-file option of the controller-manager. This will distribute the root CA to /var/run/secrets/kubernetes.io/serviceaccount/ of all pods. If you are using ABAC authorization (as opposed to AllowAll which is the default), you will also need to give the system:serviceaccount:<namespace-of-heapster>:default readonly access to the cluster (look here for more info).

**Comment by jimmidyson** [comment]
I'm going to close this now as I've just tested & it works for me. @jtblin - feel free to reopen if you still have problems or queries.

**Comment by jtblin** [comment]
Thanks @jimmidyson for the detailed info. I'm on leave so cannot verify but that looks like it should solve my problems.
