### ISSUE TITLE
Heapster falls behind and cadvisor returns no stats

### ISSUE THREAD

**Issue by moomou** [kubernetes/heapster#843]
This might be related to https://github.com/kubernetes/heapster/issues/684 but just want to summarize the issue I encountered in case it helps others.

I am running heapster in production with 19 k8s nodes where each runs about 20-30 pods. I noticed that heapster would start fine and write data to influxdb for the first 5 minutes or so but it it inexplicably stop writing data.

After a lot of digging and turning on verbose logging, I noticed from these [log lines](https://github.com/kubernetes/heapster/blob/master/manager/manager.go#L162-L175) that scraping takes nontrivial amount of time (30sec on average and worst case 1min+). After a few collection cycles, heapster would fall behind and try to 'catch up' by asking cadvisor for data in the "past" (approx. 2 minute behind in my case). This is using the default `stat_resolution` of 5 second. But in these cases, cadvisor would return empty stats. What I am not sure if whether cadvisor is expected to return stats in the past but it always return stats a few seconds from the present.

My current work around is to bump the `stat_resolution` to 5 minute. Doing this is not great, but at least heapster doesn't fall behind and get empty data. 

If there are better suggestions or improvements, I would be happy to hear them!

Setup
heapster: 6d2d9d9a8d41fd7979df9a37e72c572c6bbf8f67
kubernetes: 1.1.3
influxdb: 0.9.6

**Comment by huangyuqi** [comment]
please refer https://github.com/kubernetes/heapster/issues/802

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
