### ISSUE TITLE
Heapster not authorized to query kubernetes stats endpoint in an OpenShift cluster - 403 Forbidden using system:anonymous

### ISSUE THREAD

**Issue by cboggs** [kubernetes/heapster#860]
I'm trying to run a standalone Heapster pod in my OpenShift cluster that can query kubernetes and ship those stats out to Riemann, but `openshift/origin-metrics-heapster:latest` uses Heapster 0.18.0 which does not include the Riemann sink. I see that there is indeed a Riemann sink in Heapster 0.19.0, but plugging that version into the heapster image (just modifying the dockerfile used for the openshift/origin- image) isn't working out so well.

The pod deploys and Heapster runs, but fails to query any kubernetes nodes with messages such as this:

```
E0105 16:44:00.161918       1 kube_pods.go:110] failed to get stats for container "fluentd-elasticsearch" in pod "logging"/"logging-fluentd-1-5br5g"
E0105 16:44:00.161945       1 kubelet.go:96] failed to get stats from kubelet url: https://10.32.43.11:10250/stats/logging/logging-fluentd-1-6yarw/65f6b4e7-b2b2-11e5-9d3c-005056b45736/fluentd-elasticsearch - request failed - "403 Forbidden", response: "Forbidden (user=system:anonymous, verb=get, namespace=, resource=nodes/stats)"
```

It appears that Heapster is trying to auth as `system:anonymous` despite my best efforts to force it to do otherwise.

Running with the provided 0.18.0 image works fine and auths successfully, and can write out to InfluxDB without issue.

There's a good chance that I'm not understanding how the auth should work with 0.19.0, but I'm not sure exactly where to look next. I've tried everything I can think of to force Heapster to attempt to query Kubernetes with the system acccount that I created for it (`heapster:heapster`) which works fine with 0.18.0, but no luck.

Any suggestions are greatly appreciated!

**Comment by vishh** [comment]
cc @jimmidyson

**Comment by jimmidyson** [comment]
cc @mwringe :)

**Comment by mwringe** [comment]
It could be related to https://github.com/kubernetes/heapster/pull/749

Heapster broke compatibility with OpenShift when it refactored some of its dependencies and for some reason the PR to get it back running have not yet been accepted.

**Comment by cboggs** [comment]
Excellent! Thanks so much for the update. Certainly seems related to the PR mentioned, happy to wait until that's merged and released. In the meantime I can get by with using cadvisor as my source (it's hack week, so a less-than-ideal fix is totally fine for a while).

I'll monitor that PR and update here if my issue goes away when it's released.

Thanks again!

**Comment by ivanthelad** [comment]
@cboggs I was able to get rieman sink working on OSE 3.1 by rebuilding the origin heapster-base  and heapster images based on the following commit id. https://github.com/kubernetes/heapster/commit/c7910881b1a5acde8fe7b1e8b93e6d1b828f6d0c
See, https://github.com/ivanthelad/origin-metrics/blob/master/heapster-base/Dockerfile#L30

and then building the 'heapster' image  https://github.com/ivanthelad/origin-metrics/tree/master/heapster
You will then need to edit the heapster RC accordingly to reference the new image. 

It is a bit of  a hack but you did mention its hack week

**Comment by cboggs** [comment]
@ivanthelad, did you get it to work with Kubernetes as the source?

The Riemann sink has actually been working quite nicely, it's just been the source side that I'm struggling with. :-)

**Comment by mwringe** [comment]
@cboggs do you mean what to use for the `--source` option?

The standalone Heapster configuration file we uses this https://github.com/openshift/origin-metrics/blob/master/deployer/templates/heapster-standalone.yaml#L71

See also https://github.com/openshift/origin-metrics#deploying-only-heapster

**Comment by cboggs** [comment]
@mwringe, sorry to have stalled out on this one - planning and meetings, meetings and planning, blah.

That said, I've run back into this particular issue, even with the sha that you provided in PR #749. At one point I'd managed to make it work, but we've since blown away our test OpenShift environment and I can't seem to get the same version to work with auth'd kubernetes endpoints anymore (same behavior as mentioned in this issue's initial post).

I tried to build from `mwringe:update-1.2.0`, but I'm running into all sorts of pain in getting `godep get k8s.io/kubernetes` and `godep get k8s.io/heapster` to successfully complete.

Any ideas? We're soon to be at a point where missing the Kubernetes metadata for our container metrics is going to be very painful, happy to tackle whatever suggestions you might have. :-)

**Comment by mwringe** [comment]
Do you know what problems you are running into with performing your builds? Godeps can be interesting to deal with.

I just tried out these steps and it built:

export GOPATH=/tmp/heapster
mkdir -p $GOPATH/src/k8s.io/
cd $GOPATH/src/k8s.io/
git clone https://github.com/mwringe/heapster
cd heapster
git checkout update-1.2.0
make

At this point I don't know what to do about trying to get https://github.com/kubernetes/heapster/pull/749 merged in any faster. They are already even using the same 1.2.0 alpha in the heapster-scalability branch.

**Comment by cboggs** [comment]
Interesting. I'll try those steps, though they look awfully familiar - then again, it's been more than a few sleeps since I tried. I'll give it another go.

I also recall trying to build from the head of `heapster-scalability`, but no love there either.

Thanks for the input! Will loop back around after I give it a shot tonight or tomorrow.

**Comment by mwringe** [comment]
If you run into issues building, please let us know what the command used and what the error message is. We might be able to help debug the build problem.

I am almost tempted to start carrying the patch in the OpenShift metric images for Heapster, just so we can get something up and running again on OpenShift which is a bit newer. But I would really prefer to get the patch properly merged.

**Comment by cboggs** [comment]
@mwringe, it worked! Had to add steps to install godep in my container, but it worked this time. I haven't a clue what I did wrong before, but that's fine, I have a reproducible build now, thanks!

I think it's working with Kubernetes appropriately at this point, but I'm getting flooded with 404's for containers that never managed to spin up inside the pending pods that kubernetes sees. Need to figure out how to quiet that down, and verify that my metrics are shipping as I expected, but I think I'm in a good spot. Thanks for your help!

**Comment by mwringe** [comment]
> Had to add steps to install godep

Ah, you need to add $GOPATH/bin to $PATH for godeps to automatically be available. I just created an issue for this (https://github.com/kubernetes/heapster/issues/906). Since its being installed as part of the build, we should configure it to be actually used by the build.

> but I'm getting flooded with 404's for containers that never managed to spin up inside the pending pods that kubernetes sees.

From the Heapster logs or from somewhere else? How verbose the Heapster logs are can be configured, and when its configured to be verbose it can be very verbose.

**Comment by cboggs** [comment]
Yea the godep path issue was an easy fix, I had just forgotten it at first. No biggie.

The 404's are in the heapster log. I've tried various flags to quiet it down, but no dice yet. Eventually just piped everything to /dev/null in the wrapper script for now, though that's clearly not a viable solution long-term.

I believe the flags I've tried are `-stderrthreshold=10` and `-alsologtostderr=false`, but to no avail.

**Comment by mwringe** [comment]
Ah, ok, I am seeing those as well. It looks like its throwing an error when its trying to fetch metrics for containers which are no longer running

**Comment by cboggs** [comment]
Yea it's really not a big problem in itself, just ends up filling up my docker volume on whatever host happens to be hosting heapster at the time. Would be down for a better fix than piping to /dev/null, that's for sure. :-)

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
