### ISSUE TITLE
Expose heapster internal metrics to sinks

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#863]
The internal metrics that were added recently (#874) should be exposed to the sinks as well, to facilitate monitoring heapster as well.

cc @huangyuqi

**Comment by jimmidyson** [comment]
There is no #874?

**Comment by jimmidyson** [comment]
Ah you mean #847. So the metrics added in #847 & enhanced in #861 could be useful to external sinks as custom metrics.

**Comment by huangyuqi** [comment]
Yes, I agree. Do we need add the runtime profiling data to sinks at the same time?

**Comment by jimmidyson** [comment]
#861 instrumented the sink export data so you can track how long exploring to each individual sink took.

**Comment by huangyuqi** [comment]
thanks so much, @jimmidyson ,  i will study this and take the exporting today.

**Comment by mwielgus** [comment]
Well not really. I don't want to create another path for metrics to go within Heapster. So this should be rather handled by defining the Prometheus internal metrics as Custom Metrics and use the upcoming mechanism to export custom metrics from Kubelet. The same applies to storing internal metrics of other Kubernetes components, like scheduler.

**Comment by jimmidyson** [comment]
@mwielgus :+1:

**Comment by fgrzadkowski** [comment]
We don't want to do this for now.
