### ISSUE TITLE
heapster start step

### ISSUE THREAD

**Issue by Toplife** [kubernetes/heapster#873]
Hi all,
How to start heapster in k8s cluster and access UI link?
Thanks.

**Comment by huangyuqi** [comment]
Maybe, you can get more details in this doc:
https://github.com/kubernetes/heapster/blob/master/docs/influxdb.md

**Comment by Toplife** [comment]
yes,
I have flow this document to setup.
but look like can not working...
May be need I print some log to here.

**Comment by bh016088** [comment]
One thing that is not mentioned at all in the "getting started guide" is configuring sources:
https://github.com/kubernetes/heapster/blob/master/docs/source-configuration.md#kubernetes

The documentation of this thing needs some serious help.

**Comment by jimmidyson** [comment]
@bh016088 Thanks for offering! PRs always appreciated.
