### ISSUE TITLE
For scalability branch: strange ContainerInfo triggers panic

### ISSUE THREAD

**Issue by huangyuqi** [kubernetes/heapster#884]
In my experimental environment, I changed the clock between some nodes(includes heapster) to nonsynchronous , i got a panic.

Then i take a debug, found that: 
when call function `getAllContainers`:
https://github.com/kubernetes/heapster/blob/heapster-scalability/metrics/sources/kubelet/kubelet_client.go#L118
```
func (self *KubeletClient) getAllContainers(url string, start, end time.Time) ([]cadvisor.ContainerInfo, error) {
	// Request data from all subcontainers.
	request := statsRequest{
		ContainerName: "/",
		NumStats:      1,
		Start:         start,
		End:           end,
		Subcontainers: true,
	}
	...
```

the respone of container info does not contains any `stat`, like this:

```
{
"/": {
"name": "/"
"subcontainers": [...6]-
"spec": {...}-
}-
"/0410ffb12de5b16669727cb8d30dd64c7d065b21859d6e235916e2d9d0b13409": {
...
```

So, the panic will occur  in funciton `decodeMetrics`, when get `c.Stats[0]`
https://github.com/kubernetes/heapster/blob/heapster-scalability/metrics/sources/kubelet/kubelet.go#L146

```
	for _, metric := range StandardMetrics {
		if metric.HasValue(&c.Spec) {
			cMetrics.MetricValues[metric.Name] = metric.GetValue(&c.Spec, c.Stats[0])
		}
	}
```
I will take a PR to fix this. 
And i want to mention the clock synchronization once more ^_^ https://github.com/kubernetes/heapster/pull/814
@mwielgus

**Comment by fgrzadkowski** [comment]
We don't panic anymore. Fixed
