### ISSUE TITLE
Run Heapster on a Kubernetes cluster with InfluxDB: Only 2-3 records of a metric for a container

### ISSUE THREAD

**Issue by dehongw** [kubernetes/heapster#893]
We setup an environment for K8S and use Heapster monitoring the cluster. We wan to use API to retrieve performance metrics. It's no problem to get values for a metric at node level. For example, with URL /api/v1/model/nodes/{nodeip}/metrics/cpu-usage/, we got about 60 records,it's last one hour data. But when try to get value for a metrics at container level,It always return 2 records only. 

For example, with URL /api/v1/model/namespaces/kube-system/pods/{pod-name}/metrics/cpu-usage/, we got response as below.

{
  "metrics": [
   {
    "timestamp": "2016-01-18T11:32:00+08:00",
    "value": 9
   },
   {
    "timestamp": "2016-01-18T11:31:00+08:00",
    "value": 30
   }
  ],
  "latestTimestamp": "2016-01-18T11:32:00+08:00"
 }

Is this a bug? How to get last one hour data for a metric at container level?

**Comment by DImuthuUpe** [comment]
I'm also getting the same output

**Comment by fgrzadkowski** [comment]
@bryk

**Comment by fgrzadkowski** [comment]
We are about to release new version of heapster (0.20) which will solve this problem.

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
