### ISSUE TITLE
Endpoint access issue

### ISSUE THREAD

**Issue by shilpapadgaonkar** [kubernetes/heapster#894]
Hello,
I am not able to access the grafana endpoint http://public-master-ip:8080/api/v1/proxy/namespaces/kube-system/services/monitoring-grafana/.

I have checked that the pods are running fine
# oc get pods --all-namespaces=true

kube-system   monitoring-influxdb-grafana-v2-scrfs                         2/2       Running   0          4d
# oc describe pod monitoring-influxdb-grafana-v2-scrfs  --namespace=kube-system

[root@master kubernetes]# kubectl describe pods monitoring-influxdb-grafana-v2-scrfs --namespace=kube-system
Name:                           monitoring-influxdb-grafana-v2-scrfs
Namespace:                      kube-system
Image(s):                       gcr.io/google_containers/heapster_influxdb:v0.4,gcr.io/google_containers/heapster_graf                                                 ana:v2.1.1
Node:                           kube-node-01.xxx.xxx/172.30.15.39
Labels:                         k8s-app=influxGrafana,kubernetes.io/cluster-service=true,version=v2
Status:                         Running
Reason:
Message:
IP:                             172.16.58.3
Replication Controllers:        monitoring-influxdb-grafana-v2 (1/1 replicas created)
Containers:
  influxdb:
    Image:      gcr.io/google_containers/heapster_influxdb:v0.4
    Limits:
      cpu:              100m
      memory:           200Mi
    State:              Running
      Started:          Tue, 19 Jan 2016 10:33:36 +0000
    Ready:              True
    Restart Count:      0
  grafana:
    Image:      gcr.io/google_containers/heapster_grafana:v2.1.1
    Limits:
      cpu:              100m
      memory:           100Mi
    State:              Running
      Started:          Tue, 19 Jan 2016 10:33:41 +0000
    Ready:              True
    Restart Count:      0
Conditions:
  Type          Status
  Ready         True
No events.

---
# kubectl get services --all-namespaces

kube-system   monitoring-grafana      kubernetes.io/cluster-service=true,kubernetes.io/name=Grafana                                       k8s-app=influxGrafana           10.254.210.70    80/TCP
kube-system   monitoring-influxdb     kubernetes.io/cluster-service=true,kubernetes.io/name=InfluxDB                                      k8s-app=influxGrafana           10.254.146.187   8083/TCP
                                                                                                                                                                                           8086/TCP

Thanks,
Shilpa

**Comment by fgrzadkowski** [comment]
How this can be reproduced?

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
