### ISSUE TITLE
Fix modified Godep dependencies

### ISSUE THREAD

**Issue by mwringe** [kubernetes/heapster#899]
Heapster currently has modified files in its Godeps/_workspace directory.

This means its a hassle to use `godeps restore` to populate the checkout and build without using godeps.

All the changes are to modify the path of the imports. For example, see these two files:

https://github.com/kubernetes/heapster/blob/master/Godeps/_workspace/src/github.com/coreos/etcd/client/auth_role.go#L23
https://github.com/coreos/etcd/blob/319b77b0513deb7a4528f7d8f421ba38bc4e9dd8/client/auth_role.go#L23

If we need to modify any files in the _workspace directory then we should be forking those projects and apply the patch there instead of hiding modified files under _workspace. Or use some other mechanism to patch these files during the build.

As it currently stands, the Godeps.json does not give an accurate depiction of the actual code used, and makes it confusing to track and update dependencies when needed.

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
