### ISSUE TITLE
installed godep not used by default for the build

### ISSUE THREAD

**Issue by mwringe** [kubernetes/heapster#906]
Currently as part of the Makefile we install godeps (https://github.com/kubernetes/heapster/blob/master/Makefile#L11), but this is not automatically added to the path, so its not used without manual configuration.

If we are installing godeps as part of the build, we should be using this version for the build

**Comment by vishh** [comment]
Shouldn't this be handled as part of golang setup? If required, we can
reference all binaries relative to $GOPATH.

**Comment by mwringe** [comment]
Its not part of the go install as far as I can tell: https://golang.org/doc/install
And its not something that the system installed go does on RHEL or Fedora systems either.

**Comment by DirectXMan12** [comment]
if you're working in a GOPATH, sane practice is to have the GOPATH's `bin` directory on your path.
