### ISSUE TITLE
Switch kubelet metrics source to /stats/summary API

### ISSUE THREAD

**Issue by timstclair** [kubernetes/heapster#907]
Heapster should try to use the new `/stats/summary` API provided by the kubelet when it's available. The new API is preferable because:
- It hides implementation details (e.g. does Container-Pod mapping)
- It sends less data over the wire
- It will include volume & FS information not previously available

The switch must be backwards compatible to support older kubelets.

**Comment by fgrzadkowski** [comment]
@timstclair - Tim, thanks for adding this new API! Since we are almost at the code freeze for 1.2 I think we won' be able to work on this for this release. I think we should come back to this once we are done with 1.2.

Btw - does the new API export custom metrics?

@dchen1107 @mwielgus @piosz

**Comment by timstclair** [comment]
I know this is coming in hot, but if the Kubelet side does land it would be awesome to get this in. I'm volunteering to do all the work on this, as I know you're all overloaded right now (and it's so late!).

@vishh is adding custom metrics to the API.

**Comment by mwielgus** [comment]
You can start adding the new API as a separate source (leaving the existing one intact). If all elements are in (including the code that picks the right api based on kubelet version and CM) and we still have time to redo the tests then we will definitely consider using the new source in K8S 1.2.

**Comment by timstclair** [comment]
Sounds good. I've already mostly implemented this as an alternate path in
the existing kubelet source, since there's a lot of overlap with the
previous methods. I'll probably send a WIP PR out later today, so if you
still think it would be better to refactor it as a separate source after
that, let me know.

**Comment by mwielgus** [comment]
Yes, please make it completely separate.
