### ISSUE TITLE
[heapster-scalability] 'No node info in pod' crashes Heapster

### ISSUE THREAD

**Issue by mwringe** [kubernetes/heapster#911]
When Heapster tries to access a pod which is not currently running, it will not receive information about that pod. Currently with the heapster-scalability branch this will cause the Heapster container to crash:
>F0128 18:33:35.546050       1 manager.go:135] Error in processor: No node info in pod namespace:test-1454000850/pod:metrics-deployer-436wu: map[labels:component:deployer,metrics-infra:deployer,provider:openshift namespace_id:a323cf1e-c5e1-11e5-a5bc-3c970e88a56f type:pod namespace_name:test-1454000850 pod_namespace:test-1454000850 pod_name:metrics-deployer-436wu pod_id:423a890c-c5ed-11e5-a5bc-3c970e88a56f]

`oc get pods metrics-deployer-436wu`
> NAME                     READY     STATUS      RESTARTS   AGE
metrics-deployer-436wu   0/1       Completed   0          6m

In the `master` branch this looks to cause 404 errors to be logged, but the Heapster instance will continue to run properly.

**Comment by mwringe** [comment]
Is there anyway I could get this assigned to me?

**Comment by jimmidyson** [comment]
@mwringe It doesn't need to be assigned for you to work on it & provide a PR :)

**Comment by mwielgus** [comment]
Does #922 fix the problem?

**Comment by jimmidyson** [comment]
It should do. Sorry I didn't mark it as fixed in the PR.

**Comment by mwringe** [comment]
Can we please re-open this issue?

#922 just adds a check to get around the issue and is not addressing the main problem.

There are a few things happening here and it has to do with how we handle metrics coming in from /stats endpoint and how we handle metrics which are not available under /stats.

For metrics which we get from the /stats endpoint, we go through and add the hostname label to them (https://github.com/kubernetes/heapster/blob/heapster-scalability/metrics/sources/kubelet/kubelet.go#L94)

But, we also get the list of pods from the cluster. If any of those pods are not currently accounted for in the list of metrics, then we try and add them: https://github.com/kubernetes/heapster/blob/heapster-scalability/metrics/processors/pod_based_enricher.go#L56

The issue is we are forgetting to add the hostname attribute here. So all that we need to do is to add `core.LabelNodename.Key: pod.Spec.NodeName,` and then this issue goes away (at least for completed containers, I suspect it would be the same for the other scenarios mentioned in #922). At the very least we should be logging a warning in #922 and not logging this situations as info level.

I would have submitted a PR to add in the nodename to the pods coming in from the pods list and not /stats, but I am unclear why exactly we are trying to add these types of pods (https://github.com/kubernetes/heapster/blob/heapster-scalability/metrics/processors/pod_based_enricher.go#L56)

I would have assumed that since there are no metrics for these pods, that we would have just ignored these pods instead of trying to add them back in.

Anyone know why we are trying to add metric-less pods?

**Comment by jimmidyson** [comment]
I do agree it would make more sense to only keep stats for pods we have stats for & ignore pods we don't have stats for. I assume the idea was to have an in-memory representation of every pod in the cluster but that is a bit wasteful.

Thoughts @mwielgus?
