### ISSUE TITLE
[heapster-scalability] Lots of "missing metadata for container" errors in the logs

### ISSUE THREAD

**Issue by mwringe** [kubernetes/heapster#912]
When running on OpenShift with the heapster-scalability branch, there are a lot of error messages in the logs about missing metadata for the system level metrics. These are the metrics which are not coming from a container or pod, but from the system itself.

Eg:
> kubelet.go:132] Missing metadata for container /system.slice/libvirtd.service. Got: map[]
kubelet.go:132] Missing metadata for container /system.slice/run-user-42-gvfs.mount. Got: map[]
kubelet.go:132] Missing metadata for container /system.slice/systemd-logind.service. Got: map[]
kubelet.go:132] Missing metadata for container /system.slice/gdm.service. Got: map[]

**Comment by jimmidyson** [comment]
The problem here is this bit of code - https://github.com/kubernetes/heapster/blob/heapster-scalability/metrics/sources/kubelet/cadvisor_utils.go#L23-L41. It doesn't take into account systemd based distros systems or indeed nested cgroups.

**Comment by jimmidyson** [comment]
System containers are now properly identified.
