### ISSUE TITLE
Add a REST endpoint to expose resource usage at various levels

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#92]
Since heapster aggregates data across all nodes and containers, it can and probably should expose resource usage data aggregated at various levels,
1. container,
2. Pod,
3. Service/Controller,
4. labels 
Instantaneous metrics will be useful for UI purposes and derives metrics (mean, 90%ile, max, etc) will be useful for end users.

**Comment by piosz** [comment]
Obsolete.
