### ISSUE TITLE
Heapster containers are being killed 

### ISSUE THREAD

**Issue by ichekrygin** [kubernetes/heapster#925]
It seems that after 10 min or so, k8s kills heapster pods and removes rc.

```
FIRSTSEEN                         LASTSEEN                          COUNT     NAME           KIND                    SUBOBJECT   REASON             SOURCE                      MESSAGE
Mon, 01 Feb 2016 15:34:03 -0800   Mon, 01 Feb 2016 15:34:03 -0800   1         heapster-v10   ReplicationController               SuccessfulCreate   {replication-controller }   Created pod: heapster-v10-9djcs
Mon, 01 Feb 2016 15:34:03 -0800   Mon, 01 Feb 2016 15:34:03 -0800   1         heapster-v10-9djcs   Pod                 Scheduled   {scheduler }   Successfully assigned heapster-v10-9djcs to ip-10-72-9-107.us-west-2.compute.internal
Mon, 01 Feb 2016 15:34:03 -0800   Mon, 01 Feb 2016 15:34:03 -0800   1         heapster-v10-9djcs   Pod       implicitly required container POD   Pulled    {kubelet ip-10-72-9-107.us-west-2.compute.internal}   Container image "gcr.io/google_containers/pause:0.8.0" already present on machine
Mon, 01 Feb 2016 15:34:03 -0800   Mon, 01 Feb 2016 15:34:03 -0800   1         heapster-v10-9djcs   Pod       implicitly required container POD   Created   {kubelet ip-10-72-9-107.us-west-2.compute.internal}   Created with docker id d71af43c5d13
Mon, 01 Feb 2016 15:34:03 -0800   Mon, 01 Feb 2016 15:34:03 -0800   1         heapster-v10-9djcs   Pod       implicitly required container POD   Started   {kubelet ip-10-72-9-107.us-west-2.compute.internal}   Started with docker id d71af43c5d13
Mon, 01 Feb 2016 15:34:03 -0800   Mon, 01 Feb 2016 15:34:03 -0800   1         heapster-v10-9djcs   Pod       spec.containers{heapster}   Pulled    {kubelet ip-10-72-9-107.us-west-2.compute.internal}   Container image "gcr.io/google_containers/heapster:v0.18.2" already present on machine
Mon, 01 Feb 2016 15:34:03 -0800   Mon, 01 Feb 2016 15:34:03 -0800   1         heapster-v10-9djcs   Pod       spec.containers{heapster}   Created   {kubelet ip-10-72-9-107.us-west-2.compute.internal}   Created with docker id 0ad4599f1a95
Mon, 01 Feb 2016 15:34:03 -0800   Mon, 01 Feb 2016 15:34:03 -0800   1         heapster-v10-9djcs   Pod       spec.containers{heapster}   Started   {kubelet ip-10-72-9-107.us-west-2.compute.internal}   Started with docker id 0ad4599f1a95
Mon, 01 Feb 2016 15:41:01 -0800   Mon, 01 Feb 2016 15:41:01 -0800   1         heapster-v10-9djcs   Pod       spec.containers{heapster}   Killing   {kubelet ip-10-72-9-107.us-west-2.compute.internal}   Killing with docker id 0ad4599f1a95
Mon, 01 Feb 2016 15:41:01 -0800   Mon, 01 Feb 2016 15:41:01 -0800   1         heapster-v10-9djcs   Pod       implicitly required container POD   Killing   {kubelet ip-10-72-9-107.us-west-2.compute.internal}   Killing with docker id d71af43c5d13
```

Heapster container logs does not show any errors.

**Comment by gravis** [comment]
I have the same issue with os 1.1.3
Only heapster pod is being deleted, no error in the logs, just:
`Killing container with docker id 97b2aa607729: Need to kill pod.`
in the events.

**Comment by ichekrygin** [comment]
Update: this issue is most likely due to "corrupted" heapster-controller.yaml during `kube up`. Which resulted in installation where heapster-controller.yaml was entirely missing on kube master under: `/etc/kubernetes/addons/cluster-monitoring/influxdb/`. They way I understand it k8s is using salt to keep installed kube-system components in check. Since heapster-controller.yaml was originally missing, adding it after the fact violated the state captured in salt, hence the controller was deleted.

I stood up new cluster with "corrected" heapster-controller.yaml and heapster pod is running as expected.

**Comment by gravis** [comment]
Ok, I'll wait for the image openshift/origin-metrics-deployer to be updated and will try again then.
Thanks!

**Comment by mwringe** [comment]
@gravis How exactly does this relate to origin-metrics? This doesn't sound like the issue with the yaml file would apply to origin-metrics. Could you please open a new issue for the issue you are seeing when running with the origin-metrics components (https://github.com/openshift/origin-metrics/issues)?

**Comment by mwringe** [comment]
@gravis its not mixing up projects and if you have specific questions or issues about Heapster, then please file them here :) The origin-metrics project does things a bit differently in terms of deployment and if you hare having problems deploying components than its likely the fault of origin-metrics and not related to Heapster directly.

**Comment by ichekrygin** [comment]
This is no longer an issue after hipster controller was fixed. Also, this does not repro in 1.2.x.
Closing.
