### ISSUE TITLE
[QUESTION]autoscaler can not work normal by heapster.

### ISSUE THREAD

**Issue by vklonghml** [kubernetes/heapster#939]
Description of problem:
 when i create two autoscalers in cluster environment, one is php-apache which created through http://kubernetes.io/v1.1/docs/user-guide/horizontal-pod-autoscaling/README.html, the other is 
dockerhttpd, here is the result:

kubectl get hpa --all-namespaces -o wide
NAMESPACE   NAME           REFERENCE                                  TARGET    CURRENT     MINPODS   MAXPODS   AGE
default     autos          ReplicationController/autos/scale          10%       waiting   1         3         44s
default     php-apache-2   ReplicationController/php-apache-2/scale   50%       466%        1         10        13h

here comes the problems, 
1.the CURRENT of autos(dockerhttpd) is waiting while the php-apache-2 shows the cpu percent.
2.when i stop load, the percent of php-apache-2 is always 466%.

my environment is below:
1.kubenetes version
Client Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"1", GitVersion:"v1.1.7", GitCommit:"e4e6878293a339e4087dae684647c9e53f1cf9f0", GitTreeState:"clean"}

2.heapster version
gcr.io/google_containers/heapster:v0.18.2
heapster in use is created from  kubernetes/cluster/gce/coreos/kube-manifests/addons/cluster-monitoring/influxdb/(master version),  when the heapster runs, it could connect to influxdb and kubelet, kube-api, and the logs show normal too.

but how this problem comes out, does anybody know this situation? Thanks.

**Comment by piosz** [comment]
This should be fixed in the new Heapster 1.0.0 released in Kubernetes 1.2.
