### ISSUE TITLE
Container Dash not populating

### ISSUE THREAD

**Issue by bh016088** [kubernetes/heapster#943]
I just set up heapster/grafana/influxdb on my on-premise Centos7 Kube cluster.  Kube v1.1.4, Heapster v0.18.2 (even though I specify 'latest' in the controller).

I set it up to use a service account and kubernetes api as the source.

When I pull up grafana I see two built in dashboards, Kubernetes Cluster and Containers.  I see data in the Kubernetes Cluster dashboard but when I pull up the container dashboard I get:

Dashboard init failed
Template variables could not be initialized: InfluxDB Error: <br/>Field pod_namespace doesn't exist in series uptime_ms_cumulative

Am I doing something wrong?

**Comment by moserke** [comment]
Have verified that this is a docker 1.10.x issue.  Don't have a resolution to date, but went back to the beta channel of coreos.

**Comment by bh016088** [comment]
This occurred on Docker 1.8.x when I tried it.  I recently upgraded to 1.9.  I will test.

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
