### ISSUE TITLE
Release a version with OpenTSDB support

### ISSUE THREAD

**Issue by llarsson** [kubernetes/heapster#955]
I would love to see a release, complete with container image, that includes OpenTSDB support, now that it's present in the master branch. Alternatively, I would appreciate an estimate on when we could expect it, in case we need to go ahead and make unofficial builds and images in the mean time.

**Comment by jimmidyson** [comment]
Rather than unofficial builds/images, we'd love contributions for that to heapster itself if you're up for that?

**Comment by llarsson** [comment]
I am unclear about how I would go about making a build that gets pushed out through the official channels.

The code for OpenTSDB is there (not mine), there are no bug reports against it as far as I can see, and it's just not made available in any of the official images.

**Comment by mwielgus** [comment]
Heapster v0.20.0 (currently we have an alpha release candidate) will have OpenTSDB enabled.

**Comment by harryge00** [comment]
Is there an official docker image about OpenTSDB?

**Comment by piosz** [comment]
Heapster in versions 1.0, 1.1, 1.2 support OpenTSDB. [Here](https://github.com/kubernetes/heapster/blob/master/docs/sink-configuration.md#opentsdb) you can find an info how to configure the sink. Providing image to with OpenTSDB itself is our of the scope of Heapster project.
