### ISSUE TITLE
Debug k8s gce autoscaling suite

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/heapster#958]
It is failing despite gcm sink with autoscaling enabled.

**Comment by mwielgus** [comment]
cc: @piosz

**Comment by piosz** [comment]
from logs
```
E0210 20:19:52.372961       1 factory.go:65] Failed to create sink: Post https://www.googleapis.com/cloudmonitoring/v2beta2/projects/k8s-jnks-e2e-gce-autoscalin
g/metricDescriptors?alt=json: oauth2/google: can't get a token from the metadata service; not running on GCE
```

**Comment by piosz** [comment]
To fix the problem we should add waiting for token right after it's created https://github.com/kubernetes/heapster/blob/heapster-scalability/metrics/sinks/gcm/gcm.go#L239

I'll create the fix tomorrow.
