### ISSUE TITLE
[heapster-scalability] certificate based authentication broken

### ISSUE THREAD

**Issue by mwringe** [kubernetes/heapster#967]
It looks like certificate authentication was broken when this commit was put into place: https://github.com/kubernetes/heapster/commit/8ad5353a3dd6dc00eeb24eb4da778e566d26178c

As it stands right now its not possible to use client based authentication to secure the heapster endpoints.

**Comment by fgrzadkowski** [comment]
Fixed in #968

Please let us know if this is still the problem.
