### ISSUE TITLE
Heapster Internal Error 500

### ISSUE THREAD

**Issue by tommyknows** [kubernetes/heapster#973]
Hi,
I have a working baremetal Kubernetes Cluster on top of CoreOS. When deploying heapster, I had to change the datasource in Grafana from _http://monitoring-grafana:8086_ to _http://localhost:8086_ to get the InfluxDB Database working.
Now I see stats for the Kubernetes Dashboard, but none for the Container-Dashboard.
I tried to start debugging and found out that Heapster has many internal error - 500:

``` shell
kubectl logs heapster-715ro --namespace=kube-system
E0215 13:07:35.007517       1 kube_pods.go:110] failed to get stats for container "kube2sky" in pod "kube-system"/"kube-dns-v10-81ok3"
E0215 13:07:35.008109       1 kubelet.go:102] failed to get stats from kubelet url: http://192.168.1.43:10255/stats/kube-system/kube-dns-v10-81ok3/ca0b5a5f-cfef-11e5-afdf-00215aee6ec8/skydns - request failed - "500 Internal Server Error", response: "Internal Error: unable to find Docker container \"90e880bf010c4659877507d076868026e64ca7f9bf036646a136dfee3510686d\"\n"
E0215 13:07:35.008123       1 kube_pods.go:110] failed to get stats for container "skydns" in pod "kube-system"/"kube-dns-v10-81ok3"
E0215 13:07:35.008728       1 kubelet.go:102] failed to get stats from kubelet url: http://192.168.1.43:10255/stats/kube-system/kube-dns-v10-81ok3/ca0b5a5f-cfef-11e5-afdf-00215aee6ec8/healthz - request failed - "500 Internal Server Error", response: "Internal Error: unable to find Docker container \"e22530edcd6e9d3601ca157a76d9510af0b632f25aaaa349a75ff7f20bb3d32c\"\n"
```

However, all the containers are running; for example:

``` shell
docker ps --no-trunc | grep '90e880bf010c4659877507d076868026e64ca7f9bf036646a136dfee3510686d'
90e880bf010c4659877507d076868026e64ca7f9bf036646a136dfee3510686d   gcr.io/google_containers/skydns:2015-10-13-8c72f8c   "/skydns -machines=http://127.0.0.1:4001 -addr=0.0.0.0:53 -ns-rotate=false -domain=domain.local"                                                                                                                      16 hours ago        Up 16 hours                                                      k8s_skydns.cf571477_kube-dns-v10-81ok3_kube-system_ca0b5a5f-cfef-11e5-afdf-00215aee6ec8_74947c81
```

I'm running Kubernetes v1.1.2

**Comment by theobolo** [comment]
Same issue here
Kubernetes v 1.1.7

**Comment by fgrzadkowski** [comment]
It seems that there are two separate issues:
* It seems that DNS is not working in your cluster. This means that you'll not be able to use addresses like `http://monitoring-grafana:8086`
* Internal error in kubelet is somewhat separate story, but please report it in kubernetes/kubernetes and cross reference this issue.

**Comment by ramonrue** [comment]
My DNS is working, when I start a busybox in the kube-system Namespace and execute a nslookup monitoring-grafana, I get the correct IP address of the server. I can curl to that IP and get a WebSite back...

**Comment by fgrzadkowski** [comment]
Assigning to @mwielgus for further debugging.

**Comment by ZhuPeng** [comment]
Encounter same issue with kubernetes building from master HEAD source(commit id: 7ee8dde1e3afc9fc68616c54833f96d6391e0b22)

**Comment by Morriz** [comment]
I have the same issue (tested with 1.1.2 all the way up to 1.2.0-alpha.8). Could it be networking contraints that prevent it? Or would we see 404s then?

**Comment by ZhuPeng** [comment]
The problem was same with this issue https://github.com/kubernetes/kubernetes/issues/18868.

**Comment by tommyknows** [comment]
Ok, that explains the error 500s, but the DNS-problem still persists, right?

**Comment by zjx-immersion** [comment]
I also have the same issue which in 1.1.8 and docker 1.10.2

**Comment by Morriz** [comment]
I found that my issues were related to firewalling, so I advise to check all routes...
