### ISSUE TITLE
Downsampling k8s cluster data

### ISSUE THREAD

**Issue by tsn77130** [kubernetes/heapster#978]
Hi all,

I've set up heapster / grafana / influxdb on my kubernetes cluster, and it works well.

Problem I have is that it generates a lot of data, and so size of DB is growing quickly (~1GB / day)
I saw on influxdb docs that we can downsample data with Retention Policies & Continuous Queries, with for example full data on last 24 hours, and sample data for long time (like RRDs ).

Is that a simple way to enable this on k8s cluster ?

thomas

**Comment by fgrzadkowski** [comment]
@tsn77130 What exactly do you mean? Would it be a change in Heapster or just a configuration change in Influxdb?

**Comment by tsn77130** [comment]
I was thinking a way to enable this change in influxdb configuration

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue
