### ISSUE TITLE
Suggestion: use InfluxDB continuous queries

### ISSUE THREAD

**Issue by arkadijs** [kubernetes/heapster#98]
In real life scenarios the performance of Grafana dashboard is abysmal and metrics are plain wrong when graphs are built on top of `stats` table directly. I suggest to use continuous queries.

Why wrong? Imagine a single Docker container with the same name deployed on different machines. There will be multiple rows from different machines, thus `derivative(cpu_cumulative_usage)` will return random values because there is no `group by hostname`.
Continuous queries also allows to slice the metric across more than one dimension, thus side-stepping Grafana limitations.

https://github.com/arkadijs/heapster/blob/master/sinks/influxdb.go#L298

Note that `group by time(10s)` must be twice as large as -poll_duration (5s in my fork), else InfluxDB won't see lagged data. AFAIK, this is going to change in InfluxDB 0.9.

Also, I don't know you plans for disk-io stats, but filesystem stats greatly multiplies the volume of data as they are added as separate rows per filesystem. Consider writing them on lower cadence. Or aggregating (which is not an entirely correct approach) across the filesystems and pushing into the same record.

**Comment by vishh** [comment]
@arkadijs: Why is `group by hostname` not possible? I thought it can be combined with a `where container_name=<blah>` clause in Grafana. 

With diskio and filesystems I was thinking of separating them into separate series. Does that approach sound good?

**Comment by arkadijs** [comment]
An example.
There are two kinds of containers: user apps and infra. I want to show a stacked graph of infra containers accross the cluster. What do I do?

    select container_name, derivative(cpu_cumulative_usage) as cpu_usage 
      from stats where container_name =~ '^infra-'
      group by time(10s), container_name

Doesn't work.
`derivative()` if operating on non-related values that comes from different machines.

    select container_name, derivative(cpu_cumulative_usage) as cpu_usage 
      from stats where container_name =~ '^infra-'
      group by time(10s), container_name, hostname

If Gafana would have a support for that - ie. grouping by more than 1 non-time column - which it doesn't suport with InfluxDB, that would give me a line per machine.
Thus I need a two-stage process. A continuous query:

    select container_name, derivative(cpu_cumulative_usage) as cpu_usage
      from stats where container_name =~ '^infra-'
      group by time(10s), container_name, hostname into cpu_stats_infra

then:

    select container_name, sum(cpu_usage)
      from cpu_stats_infra where $timeFilter
      group by time($interval), container_name order asc

in Grafana.
Similar pattern repeats over and over again, hitting the limitations of InfluxDB query language and Grafana.

Anyway, graphing from stats is really slow. Testing is done on m3.large AWS instances, timeseries data fits in InfluxDB memory cache. InfluxDB 0.8.8.

> With diskio and filesystems I was thinking of separating them into separate series. Does that approach sound good?

Yes. Please think about separating as much as possible into different series. Maybe even a series table per container (name) / pod, eliminating a repetitive scans over `stats`. I don't know if InfluxDB would be able to cleanup that effectively, which is probably could, but InfluxDB can join series into single data set - `select * from /.*/`, thus providing performance and/or aggregated data when required.

IIRC, InfluxDB 0.9 will be better by storing columns as integers to refer to unique values, but that won't solve the performance problem in general.

**Comment by vishh** [comment]
Thanks for explaining! I see the problem now. We personally don't have
experience using InfluxDB in production and so feedback from users is much
appreciated.

I was thinking of going for a series per metric, but a series per container
sounds to be better.

I will try and work on this soon. Until then, feel free to post PRs to
enhance the InfluxDB backend.

**Comment by pires** [comment]
@arkadijs excellent analysis. Will keep an eye on this issue.

**Comment by jimmidyson** [comment]
As detailed above, separating into separate series is the first step. Series name should include namespace as well so that we can perhaps provide some kind of authorisation based on series names. Separating out also will let us do clean up more easily on historic stats, say as namespaces/projects are deleted.

Continuous queries are also going to be critical, not just for the performance reasons detailed above, but for tend analysis, etc. over long periods of time where you don't want to keep the individual metrics.

**Comment by piosz** [comment]
Obsolete.
