### ISSUE TITLE
[heapster-scalability] Convert missing rate metrics from cumulatives

### ISSUE THREAD

**Issue by mwielgus** [kubernetes/heapster#984]
https://github.com/kubernetes/heapster/blob/master/sinks/gcm/rate_metrics.go

**Comment by mwielgus** [comment]
@piosz Only cpu is converted, plus the code is prone for map size overflow. 
https://github.com/kubernetes/heapster/blob/heapster-scalability/metrics/sources/kubelet/kubelet.go#L218

**Comment by piosz** [comment]
fixed in #985
