### ISSUE TITLE
%d is not substituted 

### ISSUE THREAD

**Issue by git001** [kubernetes/heapster#989]
Hi.

I have the following in my logs in version 0.20.0-alpha7.

I0218 13:09:08.645330       1 influxdb.go:145] Exported %d data to influxDB in %s4046 193.84419ms

I have found 2 lines where this output is.

heapster]$ egrep -r 'data to influxDB' *
events/sinks/influxdb/influxdb.go:      glog.V(4).Info("Exported %d data to influxDB in %s", len(dataPoints), end.Sub(start))
metrics/sinks/influxdb/influxdb.go:     glog.V(4).Info("Exported %d data to influxDB in %s", len(dataPoints), end.Sub(start))

**Comment by mwielgus** [comment]
Yep should be Infof instead of Info. Will fix it in a minute.

**Comment by mwielgus** [comment]
Fixed.
