### ISSUE TITLE
Consider dropping uptime from storage

### ISSUE THREAD

**Issue by timstclair** [kubernetes/heapster#993]
Since CreateTime was added to the MetricSet in https://github.com/kubernetes/heapster/pull/985/files, it now seems redundant to store an Uptime metric. Consider removing it to save storage costs.

/cc @mwielgus

**Comment by DirectXMan12** [comment]
this is quite old.  please re-open if you are still experiencing the issue

**Comment by DirectXMan12** [comment]
feel free to reopen if someone wants to work on this.  Trying to prune open issues as noticed by the bot to stuff that we're actually likely to work on.
