### ISSUE TITLE
Export new disk metrics via `/metric-export` endpoint.

### ISSUE THREAD

**Issue by vishh** [kubernetes/heapster#994]
The newly exposed disk usage metrics are required for GKE monitoring. `/metric-export` and `/metric-export-schema` REST endpoints should include pod volumes usage data and container's logs and write layer usage data, if available.

Essentially, [`LabeledMetrics`](https://github.com/kubernetes/heapster/blob/heapster-scalability/metrics/core/metrics.go#L66) should also be exported. 

This will let us expose disk usage for pods and containers in GKE.

cc @timstclair @mwielgus

**Comment by fgrzadkowski** [comment]
P2 as it's not a blocker for 1.2

**Comment by dchen1107** [comment]
@fgrzadkowski disk account is blocker 1.2.

**Comment by fgrzadkowski** [comment]
@dchen1107 I didn't know that. Thanks for noticing this. Bumping up priority and reassigning to @timstclair as it seems he owns this now.

**Comment by vishh** [comment]
I started putting together a patch for this issue. I'm yet to test it. I can own this issue.
