### ISSUE TITLE
Double entry in influxdb

### ISSUE THREAD

**Issue by git001** [kubernetes/heapster#996]
Hi.

we use the following components.

InfluxDB starting, version 0.10.0, branch 0.10.0, commit b8bb32ecad9808ef00219e7d2469514890a0987a, built 2016-02-04T17:06:04.850564
Go version go1.4.3, GOMAXPROCS set to 4
Heapster version 0.20.0-alpha7

Heapster sends 2 different entries at the same time.
Is this a expected behavior?

oc rsh influxdb-0-10-2-x9qdg
bash-4.2$ influx
> use k8s
> select time,value from "cpu/usage" where pod_name ='influxdb-0-10-1-k5kou'
...
1455877380000000000     2.269334708401e+12
1455877380000000000     2.269263703749e+12
1455877440000000000     2.329301421515e+12
1455877440000000000     2.329230379448e+12
1455877500000000000     2.38931343909e+12
1455877500000000000     2.389242138467e+12
###

Heapster runs with following options.

###
        - /heapster
        - -source=kubernetes:https://kubernetes.default?useServiceAccount=true&kubeletHttps=true&kubeletPort=10250
        - -sink=influxdb:http://influxdb-0-10:8086
        - -logtostderr=true
        - -alsologtostderr
        - -allowed_users=system:serviceaccount:cw-metrics:heapster,aleks,cw-metrics-signer@2016-02-18
        - -tls_cert=/secrets/heapster.cert
        - -tls_client_ca=/secrets/heapster.client-ca
        - -tls_key=/secrets/heapster.key
        - -metric_resolution=60s
#######

we have also running heapster without ' -metric_resolution=60s' but there was also 2 entries in the db.

**Comment by mwielgus** [comment]
I guess that the first entry is for pod and the second is for the container. Please add container_name to the query to check.

**Comment by git001** [comment]
cool yes you are right.

thanks.
